Repository kubeflow/manifests, pull requests merged in 2019-09, with the labels that each got.

#337 Adds keycloak-gatekeeper as OIDC Authenticator
  dex-auth/README.md
  dex-auth/keycloak-gatekeeper/base/config-map.yaml
  dex-auth/keycloak-gatekeeper/base/deployment.yaml
  dex-auth/keycloak-gatekeeper/base/kustomization.yaml
  dex-auth/keycloak-gatekeeper/base/namespace.yaml
  dex-auth/keycloak-gatekeeper/base/params.env
  dex-auth/keycloak-gatekeeper/base/params.yaml
  dex-auth/keycloak-gatekeeper/base/service.yaml
  dex-auth/keycloak-gatekeeper/base/virtualservice.yaml
  tests/keycloak-gatekeeper-base_test.go
Labels: approved, cla: yes, lgtm, size/XL

#340 Delete gcp-credentials-patch.yaml
  gcp/iap-ingress/overlays/gcp-credentials/deployment.yaml
  gcp/iap-ingress/overlays/gcp-credentials/gcp-credentials-patch.yaml
  gcp/iap-ingress/overlays/gcp-credentials/kustomization.yaml
  gcp/iap-ingress/overlays/gcp-credentials/stateful-set.yaml
  tests/iap-ingress-overlays-gcp-credentials_test.go
Labels: approved, cla: yes, lgtm, size/M

#344 Restricting controller access with Gatekeeper
  gatekeeper/README.md
  gatekeeper/constraint-template.yaml
  gatekeeper/ns-required-annotations.yaml
Labels: approved, cla: yes, lgtm, size/L

#346 allow websocket redirect
  gcp/basic-auth-ingress/base/istio-mapping-svc.yaml
  tests/basic-auth-ingress-base_test.go
  tests/basic-auth-ingress-overlays-certmanager_test.go
  tests/basic-auth-ingress-overlays-gcp-credentials_test.go
  tests/basic-auth-ingress-overlays-managed-cert_test.go
Labels: approved, cla: yes, lgtm, size/S

#349 Delete the JupyterHub kustomize manifest.
  jupyter/jupyter/base/application.yaml
  jupyter/jupyter/base/config-map.yaml
  jupyter/jupyter/base/kustomization.yaml
  jupyter/jupyter/base/params.env
  jupyter/jupyter/base/params.yaml
  jupyter/jupyter/base/role-binding.yaml
  jupyter/jupyter/base/role.yaml
  jupyter/jupyter/base/service-account.yaml
  jupyter/jupyter/base/service.yaml
  jupyter/jupyter/base/stateful-set.yaml
  jupyter/jupyter/overlays/minikube/kustomization.yaml
  jupyter/jupyter/overlays/minikube/params.env
  jupyter/jupyter/overlays/minikube/persistent-volume-claim.yaml
  jupyter/jupyter/overlays/minikube/persistent-volume.yaml
  jupyter/jupyter/overlays/minikube/stateful-set.yaml
  tests/jupyter-base_test.go
  tests/jupyter-overlays-minikube_test.go
Labels: approved, cla: yes, lgtm, size/XXL

#350 Fix v0.6-branch presubmits; use v0.6-branch of kubeflow/kubeflow
  tests/scripts/run-tests.sh
  tests/workflows/components/kfctl_go_test.jsonnet
  tests/workflows/components/workflows.libsonnet
Labels: approved, cla: yes, lgtm, size/S

#347 allow websocket redirect (#346)
  gcp/basic-auth-ingress/base/istio-mapping-svc.yaml
  tests/basic-auth-ingress-base_test.go
Labels: approved, cla: yes, lgtm, size/XS

#323 Updates Istio to 1.2.5 release
  istio/istio-crds/base/crds.yaml
  istio/istio-crds/base/kustomization.yaml
  istio/istio-install/base/istio-noauth.yaml
  istio/istio-install/base/kustomization.yaml
  istio/istio-install/base/params.env
  istio/istio-install/base/params.yaml
  tests/expected-outputs/base-istio-install-istio-noauth.yaml
  tests/istio-crds-base_test.go
  tests/istio-install-base_test.go
Labels: approved, cla: yes, lgtm, size/XXL

#357 Revert "Updates Istio to 1.2.5 release"
  istio/istio-crds/base/crds.yaml
  istio/istio-crds/base/kustomization.yaml
  istio/istio-install/base/istio-noauth.yaml
  istio/istio-install/base/kustomization.yaml
  istio/istio-install/base/params.env
  istio/istio-install/base/params.yaml
  tests/expected-outputs/base-istio-install-istio-noauth.yaml
  tests/istio-crds-base_test.go
  tests/istio-install-base_test.go
Labels: approved, cla: yes, lgtm, size/XXL

#354 GCP KfDef should pull deployment manager configs from kubeflow/manifests
  kfdef/kfctl_gcp_basic_auth.yaml
  kfdef/kfctl_gcp_iap.yaml
  prow_config.yaml
  tests/workflows/components/kfctl_go_test.jsonnet
Labels: approved, cla: yes, lgtm, size/S

#358 fix for backtick escape error
  hack/gen-test-target.sh
  hack/gen-test-targets.sh
  tests/Makefile
  tests/basic-auth-ingress-overlays-certmanager_test.go
  tests/basic-auth-ingress-overlays-gcp-credentials_test.go
  tests/basic-auth-ingress-overlays-managed-cert_test.go
  tests/cloud-endpoints-overlays-gcp-credentials_test.go
  tests/iap-ingress-base_test.go
  tests/iap-ingress-overlays-certmanager_test.go
  tests/iap-ingress-overlays-gcp-credentials_test.go
  tests/iap-ingress-overlays-managed-cert_test.go
  tests/istio-ingress-overlays-cognito_test.go
  tests/istio-ingress-overlays-oidc_test.go
  tests/istio-install-base_test.go
  tests/keycloak-gatekeeper-base_test.go
  tests/metadata-base_test.go
  tests/metadata-overlays-application_test.go
  tests/metadata-overlays-istio_test.go
  tests/seldon-core-operator-base_test.go
  tests/seldon-core-operator-overlays-application_test.go
Labels: approved, cla: yes, lgtm, size/XXL

#355 Ambassador fix to work with kustomize3
  common/ambassador/base/deployment.yaml
  common/ambassador/base/kustomization.yaml
  common/ambassador/base/service-account.yaml
  common/ambassador/base/service.yaml
  tests/ambassador-base_test.go
Labels: approved, cla: yes, lgtm, size/S

#364 Notebook beta changes
  jupyter/notebook-controller/base/crd.yaml
  jupyter/notebook-controller/base/kustomization.yaml
  tests/notebook-controller-base_test.go
  tests/notebook-controller-overlays-application_test.go
  tests/notebook-controller-overlays-istio_test.go
Labels: approved, cla: yes, lgtm, size/M

#359 Added visualization server deployment and service yaml
  pipeline/pipeline-visualization-service/base/deployment.yaml
  pipeline/pipeline-visualization-service/base/kustomization.yaml
  pipeline/pipeline-visualization-service/base/service.yaml
  tests/pipeline-visualization-service-base_test.go
Labels: approved, cla: yes, lgtm, size/L

#174 Add a spark operator
  spark/spark-operator/base/Kube-descriptor.yaml
  spark/spark-operator/base/cr-clusterrole.yaml
  spark/spark-operator/base/crb.yaml
  spark/spark-operator/base/crd-cleanup-job.yaml
  spark/spark-operator/base/deploy.yaml
  spark/spark-operator/base/kustomization.yaml
  spark/spark-operator/base/operator-sa.yaml
  spark/spark-operator/base/spark-sa.yaml
  spark/spark-operator/overlays/application/application.yaml
  spark/spark-operator/overlays/application/kustomization.yaml
  tests/spark-operator-base_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#381 Fixes gcp headers in IAP config
  kfdef/kfctl_gcp_iap.yaml
Labels: approved, cla: yes, lgtm, size/S

#382 Upgrade to Kubernetes 1.14 for GCP deployments.
  gcp/deployment_manager_configs/cluster-kubeflow.yaml
Labels: approved, cla: yes, lgtm, size/XS

#383 kfdef: generic: revert #376
  kfdef/generic/istio/istio-noauth.yaml
Labels: approved, cla: yes, lgtm, size/M

#379 KFDef specs should no longer be checking out the kubeflow repo.
  kfdef/kfctl_aws_cognito.yaml
  kfdef/kfctl_existing_arrikto.yaml
  kfdef/kfctl_k8s_istio.yaml
Labels: approved, cla: yes, lgtm, size/XS

#368 parameterize gateway selector
  istio/istio/base/kf-istio-resources.yaml
  istio/istio/base/kustomization.yaml
  istio/istio/base/params.env
  istio/istio/base/params.yaml
  tests/istio-base_test.go
Labels: approved, cla: yes, lgtm, size/S

#370 metadata: Updating metadata component to use mlmd-grpc server
  metadata/base/kustomization.yaml
  metadata/base/metadata-deployment.yaml
  metadata/base/metadata-envoy-deployment.yaml
  metadata/base/metadata-envoy-service.yaml
  metadata/base/metadata-service.yaml
  tests/metadata-base_test.go
  tests/metadata-overlays-application_test.go
  tests/metadata-overlays-istio_test.go
Labels: approved, cla: yes, lgtm, size/L

#390 Enable workload identity in our KFDef specs.
  kfdef/kfctl_gcp_basic_auth.yaml
  kfdef/kfctl_gcp_iap.yaml
Labels: approved, cla: yes, lgtm, size/S

#380 kfctl anthos config
  kfdef/kfctl_anthos.yaml
Labels: approved, cla: yes, lgtm, size/L

#394 Update operator images to latest
  pytorch-job/pytorch-operator/base/deployment.yaml
  tests/pytorch-operator-base_test.go
  tests/pytorch-operator-overlays-application_test.go
  tests/tf-job-operator-base_test.go
  tests/tf-job-operator-overlays-application_test.go
  tests/tf-job-operator-overlays-istio_test.go
  tf-training/tf-job-operator/base/deployment.yaml
Labels: approved, cla: yes, lgtm, size/S

#389 Separate TFJob CRDs into a different kustomize package
  kfdef/kfctl_anthos.yaml
  kfdef/kfctl_aws.yaml
  kfdef/kfctl_aws_cognito.yaml
  kfdef/kfctl_existing_arrikto.yaml
  kfdef/kfctl_gcp_basic_auth.yaml
  kfdef/kfctl_gcp_iap.yaml
  kfdef/kfctl_k8s_istio.yaml
  tests/tf-job-crds-base_test.go
  tests/tf-job-operator-base_test.go
  tests/tf-job-operator-overlays-application_test.go
  tests/tf-job-operator-overlays-istio_test.go
  tf-training/tf-job-crds/base/crd.yaml
  tf-training/tf-job-crds/base/kustomization.yaml
  tf-training/tf-job-operator/base/kustomization.yaml
Labels: approved, cla: yes, lgtm, size/L

#397 Update operator images
  pytorch-job/pytorch-operator/base/kustomization.yaml
  tests/pytorch-operator-base_test.go
  tests/pytorch-operator-overlays-application_test.go
  tests/tf-job-operator-base_test.go
  tests/tf-job-operator-overlays-application_test.go
  tests/tf-job-operator-overlays-istio_test.go
  tf-training/tf-job-operator/base/deployment.yaml
  tf-training/tf-job-operator/base/kustomization.yaml
Labels: approved, cla: yes, lgtm, size/M
