Repository kubeflow/manifests, pull requests merged in 2019-11, with the labels that each got.

#596 Remove the tfjob tests.
  tests/workflows/components/kubeflow_workflow.libsonnet
Labels: approved, cla: yes, lgtm, size/M

#598 Automated cherry pick of #596: Remove the tfjob tests. Cherry pick of #596 on v0.7-branch. #596: Remove the tfjob tests.
  tests/workflows/components/kubeflow_workflow.libsonnet
Labels: approved, cla: yes, lgtm, size/M

#600 kfdef: existing_arrikto: rename to kfctl_istio_dex
  kfdef/kfctl_istio_dex.yaml
Labels: approved, cla: yes, lgtm, size/XS

#597 fix basic-auth role binding ns
  gcp/basic-auth-ingress/base/cluster-role-binding.yaml
  gcp/basic-auth-ingress/base/params.yaml
  tests/basic-auth-ingress-base_test.go
  tests/basic-auth-ingress-overlays-application_test.go
  tests/basic-auth-ingress-overlays-certmanager_test.go
  tests/basic-auth-ingress-overlays-gcp-credentials_test.go
  tests/basic-auth-ingress-overlays-managed-cert_test.go
Labels: approved, cla: yes, lgtm, size/M

#413 Istio 1.3.1 kustomize manifests
  istio-1-3-1/istio-crds-1-3-1/base/crd.yaml
  istio-1-3-1/istio-crds-1-3-1/base/kustomization.yaml
  istio-1-3-1/istio-install-1-3-1/base/attribute-manifest.yaml
  istio-1-3-1/istio-install-1-3-1/base/cluster-role-binding.yaml
  istio-1-3-1/istio-install-1-3-1/base/cluster-role.yaml
  istio-1-3-1/istio-install-1-3-1/base/config-map.yaml
  istio-1-3-1/istio-install-1-3-1/base/daemon-set.yaml
  istio-1-3-1/istio-install-1-3-1/base/deployment.yaml
  istio-1-3-1/istio-install-1-3-1/base/handler.yaml
  istio-1-3-1/istio-install-1-3-1/base/horizontal-pod-autoscaler.yaml
  istio-1-3-1/istio-install-1-3-1/base/instance.yaml
  istio-1-3-1/istio-install-1-3-1/base/job.yaml
  istio-1-3-1/istio-install-1-3-1/base/kustomization.yaml
  istio-1-3-1/istio-install-1-3-1/base/mutating-webhook-configuration.yaml
  istio-1-3-1/istio-install-1-3-1/base/namespace.yaml
  istio-1-3-1/istio-install-1-3-1/base/params.env
  istio-1-3-1/istio-install-1-3-1/base/params.yaml
  istio-1-3-1/istio-install-1-3-1/base/pod-disruption-budget.yaml
  istio-1-3-1/istio-install-1-3-1/base/role-binding.yaml
  istio-1-3-1/istio-install-1-3-1/base/role.yaml
  istio-1-3-1/istio-install-1-3-1/base/rule.yaml
  istio-1-3-1/istio-install-1-3-1/base/service-account.yaml
  istio-1-3-1/istio-install-1-3-1/base/service-role-binding.yaml
  istio-1-3-1/istio-install-1-3-1/base/service-role.yaml
  istio-1-3-1/istio-install-1-3-1/base/service.yaml
  tests/istio-crds-1-3-1-base_test.go
  tests/istio-crds-base_test.go
  tests/istio-install-1-3-1-base_test.go
  tests/istio-install-base_test.go
Labels: approved, cla: yes, lgtm, size/XXL

#601 fix basic-auth role binding ns (#597)
  gcp/basic-auth-ingress/base/cluster-role-binding.yaml
  gcp/basic-auth-ingress/base/params.yaml
  tests/basic-auth-ingress-base_test.go
  tests/basic-auth-ingress-overlays-application_test.go
  tests/basic-auth-ingress-overlays-certmanager_test.go
  tests/basic-auth-ingress-overlays-gcp-credentials_test.go
  tests/basic-auth-ingress-overlays-managed-cert_test.go
Labels: approved, cla: yes, lgtm, size/M

#594 Fix ml-pipeline-ui doesn't have gcp permission bug
  kfdef/kfctl_gcp_basic_auth.yaml
  kfdef/kfctl_gcp_iap.yaml
  pipeline/pipelines-ui/overlays/gcp/deployment.yaml
  pipeline/pipelines-ui/overlays/gcp/kustomization.yaml
  tests/iap-ingress-base_test.go
  tests/iap-ingress-overlays-application_test.go
  tests/iap-ingress-overlays-certmanager_test.go
  tests/iap-ingress-overlays-gcp-credentials_test.go
  tests/iap-ingress-overlays-managed-cert_test.go
  tests/istio-ingress-overlays-cognito_test.go
  tests/istio-ingress-overlays-oidc_test.go
  tests/istio-overlays-https-gateway_test.go
  tests/pipelines-ui-overlays-gcp_test.go
  tests/profiles-base_test.go
  tests/profiles-overlays-application_test.go
  tests/profiles-overlays-debug_test.go
  tests/profiles-overlays-devices_test.go
  tests/profiles-overlays-istio_test.go
  tests/profiles-overlays-test_test.go
Labels: approved, cla: yes, lgtm, size/L

#602 Cherrypick "Fix ml-pipeline-ui doesn't have gcp permission bug" (#594)
  kfdef/kfctl_gcp_basic_auth.0.7.0.yaml
  kfdef/kfctl_gcp_iap.0.7.0.yaml
  pipeline/pipelines-ui/overlays/gcp/deployment.yaml
  pipeline/pipelines-ui/overlays/gcp/kustomization.yaml
  tests/basic-auth-ingress-base_test.go
  tests/basic-auth-ingress-overlays-application_test.go
  tests/basic-auth-ingress-overlays-certmanager_test.go
  tests/basic-auth-ingress-overlays-gcp-credentials_test.go
  tests/basic-auth-ingress-overlays-managed-cert_test.go
  tests/istio-ingress-overlays-cognito_test.go
  tests/istio-ingress-overlays-oidc_test.go
  tests/mxnet-operator-overlays-application_test.go
  tests/notebook-controller-overlays-istio_test.go
  tests/pipelines-ui-overlays-gcp_test.go
  tests/profiles-base_test.go
  tests/profiles-overlays-application_test.go
  tests/profiles-overlays-debug_test.go
  tests/profiles-overlays-devices_test.go
  tests/profiles-overlays-istio_test.go
  tests/profiles-overlays-test_test.go
Labels: approved, cla: yes, lgtm, size/L

#606 Automated cherry pick of #605: update metadata tag to v0.1.10
  metadata/base/kustomization.yaml
  metadata/base/metadata-deployment.yaml
  tests/metadata-base_test.go
  tests/metadata-overlays-application_test.go
  tests/metadata-overlays-istio_test.go
Labels: approved, cla: yes, lgtm, size/S

#605 Update metadata tag to v0.1.10
  metadata/base/kustomization.yaml
  metadata/base/metadata-deployment.yaml
  tests/metadata-base_test.go
  tests/metadata-overlays-application_test.go
  tests/metadata-overlays-istio_test.go
Labels: approved, cla: yes, lgtm, size/S

#581 Cherry-pick #223 to v0.7-branch: Fix and update Kubebench manifests
  kubebench/base/cluster-role-binding.yaml
  kubebench/base/cluster-role.yaml
  kubebench/base/config-map.yaml
  kubebench/base/crd.yaml
  kubebench/base/deployment.yaml
  kubebench/base/kustomization.yaml
  kubebench/base/service-account.yaml
  tests/kubebench-base_test.go
  tests/kubebench-overlays-application_test.go
  tests/kubebench-overlays-istio_test.go
Labels: approved, cla: yes, lgtm, size/L

#603 Create OWNERS for Istio 1.3.1
  istio-1-3-1/OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#608 Add katib crd application to kfdef files
  kfdef/kfctl_anthos.yaml
  kfdef/kfctl_aws.yaml
  kfdef/kfctl_aws_cognito.yaml
  kfdef/kfctl_gcp_basic_auth.yaml
  kfdef/kfctl_gcp_iap.yaml
  kfdef/kfctl_istio_dex.yaml
  kfdef/kfctl_k8s_istio.yaml
Labels: approved, cla: yes, lgtm, size/S

#611 Automated cherry pick of #610: Reduce metadata
  metadata/base/metadata-deployment.yaml
  tests/metadata-base_test.go
  tests/metadata-overlays-application_test.go
  tests/metadata-overlays-istio_test.go
Labels: approved, cla: yes, lgtm, size/S

#610 Reduce metadata #replicas
  metadata/base/metadata-deployment.yaml
  tests/metadata-base_test.go
  tests/metadata-overlays-application_test.go
  tests/metadata-overlays-istio_test.go
Labels: approved, cla: yes, lgtm, size/S

#609 Add katib application cr to kfdef (v0.7-branch)
  kfdef/kfctl_anthos.0.7.0.yaml
  kfdef/kfctl_aws.0.7.0.yaml
  kfdef/kfctl_aws_cognito.0.7.0.yaml
  kfdef/kfctl_existing_arrikto.0.7.0.yaml
  kfdef/kfctl_gcp_basic_auth.0.7.0.yaml
  kfdef/kfctl_gcp_iap.0.7.0.yaml
  kfdef/kfctl_k8s_istio.0.7.0.yaml
Labels: approved, cla: yes, lgtm, size/S

#614 Remove the E2E test to unblock presubmits
  prow_config.yaml
  tests/workflows/components/kfctl_go_test.jsonnet
  tests/workflows/components/kubeflow_workflow.libsonnet
  tests/workflows/components/params.libsonnet
Labels: approved, cla: yes, lgtm, size/XXL

#623 kfserving inferenceservice CRD cannot work in pipeline
  pipeline/pipelines-runner/base/cluster-role.yaml
  tests/pipelines-runner-base_test.go
  tests/pipelines-runner-overlays-application_test.go
Labels: approved, cla: yes, lgtm, size/XS

#624 metadata: Stadardizing metadata db configs
  metadata/base/kustomization.yaml
  metadata/base/metadata-db-configmap.yaml
  metadata/base/metadata-db-deployment.yaml
  metadata/base/metadata-db-secret.yaml
  metadata/base/metadata-deployment.yaml
  tests/metadata-base_test.go
  tests/metadata-overlays-application_test.go
  tests/metadata-overlays-istio_test.go
Labels: approved, cla: yes, lgtm, size/L

#621 Add metadata application overlay to kfdef
  kfdef/kfctl_anthos.yaml
  kfdef/kfctl_aws.yaml
  kfdef/kfctl_aws_cognito.yaml
  kfdef/kfctl_gcp_basic_auth.yaml
  kfdef/kfctl_gcp_iap.yaml
  kfdef/kfctl_istio_dex.yaml
  kfdef/kfctl_k8s_istio.yaml
Labels: approved, cla: yes, lgtm, size/XS

#626 Update metadata images to use MLMD 0.15.1
  metadata/base/kustomization.yaml
  metadata/base/metadata-deployment.yaml
  tests/metadata-base_test.go
  tests/metadata-overlays-application_test.go
  tests/metadata-overlays-istio_test.go
Labels: approved, cla: yes, lgtm, size/M

#628 Automated cherry pick of #614: Remove the E2E test.
  prow_config.yaml
  tests/workflows/components/kfctl_go_test.jsonnet
  tests/workflows/components/kubeflow_workflow.libsonnet
  tests/workflows/components/params.libsonnet
Labels: approved, cla: yes, lgtm, size/XXL

#627 Automated cherry pick of #624: metadata: Stadardizing metadata db configs #626: update metadata to use MLMD 0.15.1 on v0.7-branch
  metadata/base/kustomization.yaml
  metadata/base/metadata-db-configmap.yaml
  metadata/base/metadata-db-deployment.yaml
  metadata/base/metadata-db-secret.yaml
  metadata/base/metadata-deployment.yaml
  tests/metadata-base_test.go
  tests/metadata-overlays-application_test.go
  tests/metadata-overlays-istio_test.go
Labels: approved, cla: yes, lgtm, size/L
