Repository kubeflow/manifests, pull requests merged in 2019-07, with the labels that each got.

#139 adds kfctl E2E test
  .gitignore
  prow_config.yaml
  tests/workflows/components/kfctl_go_test.jsonnet
  tests/workflows/components/kubeflow_workflow.libsonnet
  tests/workflows/components/params.libsonnet
  tests/workflows/components/util.libsonnet
Labels: approved, lgtm, size/XXL

#198 Update argo artifact repo secret name
  argo/base/params.env
  tests/argo-base_test.go
  tests/argo-overlays-istio_test.go
Labels: approved, lgtm, size/S

#199 update KFP UI role to launch tensorboard
  pipeline/pipelines-ui/base/role.yaml
  tests/pipelines-ui-base_test.go
  tests/pipelines-ui-overlays-istio_test.go
Labels: approved, lgtm, size/M

#192 update image for v0.6.0
  katib-v1alpha2/katib-controller/base/kustomization.yaml
  katib-v1alpha2/katib-manager/base/kustomization.yaml
  katib-v1alpha2/katib-ui/base/kustomization.yaml
  katib-v1alpha2/metrics-collector/base/kustomization.yaml
  katib-v1alpha2/suggestion/base/kustomization.yaml
  pytorch-job/pytorch-operator/base/kustomization.yaml
  tests/katib-controller-base_test.go
  tests/katib-manager-base_test.go
  tests/katib-ui-base_test.go
  tests/katib-ui-overlays-istio_test.go
  tests/metrics-collector-base_test.go
  tests/pytorch-operator-base_test.go
  tests/pytorch-operator-overlays-application_test.go
  tests/seldon-core-operator-base_test.go
  tests/seldon-core-operator-overlays-application_test.go
  tests/suggestion-base_test.go
  tests/tf-job-operator-base_test.go
  tests/tf-job-operator-overlays-application_test.go
  tests/tf-job-operator-overlays-istio_test.go
  tf-training/tf-job-operator/base/deployment.yaml
Labels: approved, lgtm, size/XXL

#201 jupyter-web-app: Update the image for PodDefaults
  jupyter/jupyter-web-app/base/kustomization.yaml
  tests/jupyter-web-app-base_test.go
  tests/jupyter-web-app-overlays-application_test.go
  tests/jupyter-web-app-overlays-istio_test.go
Labels: approved, lgtm, size/XS

#202 Fix volumeClaimTemplate for Seldon
  gcp/prometheus/base/kustomization.yaml
  seldon/seldon-core-operator/base/statefulset.yaml
  tests/iap-ingress-base_test.go
  tests/minio-base_test.go
  tests/minio-overlays-minioPd_test.go
  tests/mysql-base_test.go
  tests/mysql-overlays-mysqlPd_test.go
  tests/pipelines-ui-overlays-istio_test.go
  tests/profiles-base_test.go
  tests/profiles-overlays-debug_test.go
  tests/profiles-overlays-devices_test.go
  tests/profiles-overlays-istio_test.go
  tests/prometheus-base_test.go
  tests/seldon-core-operator-base_test.go
  tests/seldon-core-operator-overlays-application_test.go
Labels: approved, lgtm, size/M

#203 github: add PR template
  .github/pull_request_template.md
Labels: approved, lgtm, size/S

#204 fix basic auth
  common/ambassador/base/deployment.yaml
  common/ambassador/base/kustomization.yaml
  common/ambassador/base/service-account.yaml
  common/ambassador/base/service.yaml
  gcp/basic-auth-ingress/base/certificate.yaml
  gcp/basic-auth-ingress/base/istio-mapping-svc.yaml
  gcp/basic-auth-ingress/base/kustomization.yaml
  gcp/basic-auth-ingress/base/params.yaml
  tests/ambassador-base_test.go
  tests/basic-auth-ingress-base_test.go
  tests/iap-ingress-base_test.go
  tests/minio-base_test.go
  tests/minio-overlays-minioPd_test.go
  tests/mysql-base_test.go
  tests/mysql-overlays-mysqlPd_test.go
  tests/profiles-base_test.go
  tests/profiles-overlays-debug_test.go
  tests/profiles-overlays-devices_test.go
  tests/profiles-overlays-istio_test.go
  tests/workflows/app.yaml
  tests/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/L

#206 Sync06
  .github/pull_request_template.md
  common/ambassador/base/deployment.yaml
  common/ambassador/base/kustomization.yaml
  common/ambassador/base/service-account.yaml
  common/ambassador/base/service.yaml
  gcp/basic-auth-ingress/base/certificate.yaml
  gcp/basic-auth-ingress/base/istio-mapping-svc.yaml
  gcp/basic-auth-ingress/base/kustomization.yaml
  gcp/basic-auth-ingress/base/params.yaml
  tests/ambassador-base_test.go
  tests/basic-auth-ingress-base_test.go
  tests/iap-ingress-base_test.go
  tests/minio-base_test.go
  tests/minio-overlays-minioPd_test.go
  tests/mysql-base_test.go
  tests/mysql-overlays-mysqlPd_test.go
  tests/profiles-base_test.go
  tests/profiles-overlays-debug_test.go
  tests/profiles-overlays-devices_test.go
  tests/profiles-overlays-istio_test.go
  tests/workflows/app.yaml
  tests/workflows/components/workflows.libsonnet
Labels: size/L

#209 make ClusterRbacConfig configurable
  istio/istio/base/kf-istio-resources.yaml
  istio/istio/base/kustomization.yaml
  istio/istio/base/params.env
  istio/istio/base/params.yaml
  tests/istio-base_test.go
Labels: approved, lgtm, size/M

#212 remove istio from gcp
  gcp/istio-crds/base/crds.yaml
  gcp/istio-crds/base/kustomization.yaml
  gcp/istio-install/base/istio-noauth.yaml
  gcp/istio-install/base/kustomization.yaml
  gcp/istio/base/README.md
  gcp/istio/base/kf-istio-resources.yaml
  gcp/istio/base/kustomization.yaml
Labels: approved, lgtm, size/XXL

#213 sync v0.6 to master head
  gcp/istio/base/kustomization.yaml
  istio/istio-crds/base/crds.yaml
  istio/istio-crds/base/kustomization.yaml
  istio/istio-install/base/istio-noauth.yaml
  istio/istio-install/base/kustomization.yaml
  istio/istio/base/README.md
  istio/istio/base/kf-istio-resources.yaml
  istio/istio/base/kustomization.yaml
  istio/istio/base/params.env
  istio/istio/base/params.yaml
  tests/istio-base_test.go
  tests/istio-crds-base_test.go
  tests/prometheus-base_test.go
Labels: approved, lgtm, size/M

#214 update jupyter web app image
  jupyter/jupyter-web-app/base/kustomization.yaml
  tests/jupyter-web-app-base_test.go
  tests/jupyter-web-app-overlays-application_test.go
  tests/jupyter-web-app-overlays-istio_test.go
Labels: approved, lgtm, size/XS

#215 Add myself to manifests OWNERS file
  OWNERS
Labels: approved, lgtm, size/XS

#218 Add metadata OWNERS
  metadata/OWNERS
Labels: approved, lgtm, size/XS

#224 Fix tfjob application CR name
  tests/tf-job-operator-overlays-application_test.go
  tf-training/tf-job-operator/overlays/application/application.yaml
Labels: approved, lgtm, size/XS

#219 envoy-config: fix port name in setup_backend.sh
  gcp/iap-ingress/base/config-map.yaml
  tests/iap-ingress-base_test.go
Labels: approved, lgtm, ok-to-test, size/XS

#225 Add katib application CR
  katib-v1alpha2/katib-controller/overlays/application/application.yaml
  katib-v1alpha2/katib-controller/overlays/application/kustomization.yaml
  katib-v1alpha2/katib-db/overlays/application/application.yaml
  katib-v1alpha2/katib-db/overlays/application/kustomization.yaml
  katib-v1alpha2/katib-manager/overlays/application/application.yaml
  katib-v1alpha2/katib-manager/overlays/application/kustomization.yaml
  katib-v1alpha2/katib-ui/overlays/application/application.yaml
  katib-v1alpha2/katib-ui/overlays/application/kustomization.yaml
  katib-v1alpha2/metrics-collector/overlays/application/application.yaml
  katib-v1alpha2/metrics-collector/overlays/application/kustomization.yaml
  katib-v1alpha2/suggestion/overlays/application/application.yaml
  katib-v1alpha2/suggestion/overlays/application/kustomization.yaml
  tests/katib-controller-overlays-application_test.go
  tests/katib-db-overlays-application_test.go
  tests/katib-manager-overlays-application_test.go
  tests/katib-ui-overlays-application_test.go
  tests/metrics-collector-overlays-application_test.go
  tests/suggestion-overlays-application_test.go
Labels: approved, lgtm, size/XXL

#210 Bump metadata version.
  metadata/base/metadata-deployment.yaml
  tests/iap-ingress-base_test.go
  tests/istio-base_test.go
  tests/metadata-base_test.go
  tests/metadata-overlays-istio_test.go
  tests/minio-base_test.go
  tests/minio-overlays-minioPd_test.go
  tests/mysql-base_test.go
  tests/mysql-overlays-mysqlPd_test.go
  tests/profiles-base_test.go
  tests/profiles-overlays-debug_test.go
  tests/profiles-overlays-devices_test.go
  tests/profiles-overlays-istio_test.go
  tests/prometheus-base_test.go
Labels: approved, lgtm, size/M

#239 Update metadata backend version nubmer
  metadata/base/metadata-deployment.yaml
  tests/metadata-base_test.go
Labels: approved, lgtm, size/XS

#240 add istio namespace for cloud endpoint
  gcp/basic-auth-ingress/base/cloud-endpoint.yaml
  gcp/basic-auth-ingress/base/kustomization.yaml
  gcp/basic-auth-ingress/base/params.env
  gcp/basic-auth-ingress/base/params.yaml
  tests/basic-auth-ingress-base_test.go
  tests/iap-ingress-base_test.go
  tests/istio-base_test.go
  tests/minio-base_test.go
  tests/minio-overlays-minioPd_test.go
  tests/mysql-base_test.go
  tests/mysql-overlays-mysqlPd_test.go
  tests/profiles-base_test.go
  tests/profiles-overlays-debug_test.go
  tests/profiles-overlays-devices_test.go
  tests/profiles-overlays-istio_test.go
Labels: approved, lgtm, size/M

#242 Cherry-pick #240 add istio namespace for cloud endpoint
  gcp/basic-auth-ingress/base/cloud-endpoint.yaml
  gcp/basic-auth-ingress/base/kustomization.yaml
  gcp/basic-auth-ingress/base/params.env
  gcp/basic-auth-ingress/base/params.yaml
  tests/basic-auth-ingress-base_test.go
Labels: approved, lgtm, size/S

#244 cherry pick #243 patch appName to endpoint
  gcp/basic-auth-ingress/base/cloud-endpoint.yaml
  gcp/basic-auth-ingress/base/kustomization.yaml
  gcp/basic-auth-ingress/base/params.env
  gcp/basic-auth-ingress/base/params.yaml
  tests/basic-auth-ingress-base_test.go
Labels: approved, lgtm, size/S

#247 Fix manifest for cloud-endpoint
  gcp/cloud-endpoints/base/cluster-role.yaml
  tests/cloud-endpoints-base_test.go
Labels: approved, lgtm, size/XS
