Repository kubeflow/manifests, pull requests merged in 2019-04, with the labels that each got.

#12 add katib
  OWNERS
  katib/v1alpha1/base/katib-db-pvc.yaml
  katib/v1alpha1/base/katib-ui-deployment.yaml
  katib/v1alpha1/base/katib-ui-rbac.yaml
  katib/v1alpha1/base/katib-ui-service.yaml
  katib/v1alpha1/base/kustomization.yaml
  katib/v1alpha1/base/metrics-collector-rbac.yaml
  katib/v1alpha1/base/metrics-collector-template-configmap.yaml
  katib/v1alpha1/base/studyjob-controller-deployment.yaml
  katib/v1alpha1/base/studyjob-crd.yaml
  katib/v1alpha1/base/studyjob-rbac.yaml
  katib/v1alpha1/base/studyjob-service.yaml
  katib/v1alpha1/base/suggestion-bayesianoptimization-deployment.yaml
  katib/v1alpha1/base/suggestion-bayesianoptimization-service.yaml
  katib/v1alpha1/base/suggestion-grid-deployment.yaml
  katib/v1alpha1/base/suggestion-grid-service.yaml
  katib/v1alpha1/base/suggestion-hyperband-deployment.yaml
  katib/v1alpha1/base/suggestion-hyperband-service.yaml
  katib/v1alpha1/base/suggestion-nasrl-deployment.yaml
  katib/v1alpha1/base/suggestion-nasrl-service.yaml
  katib/v1alpha1/base/suggestion-random-deployment.yaml
  katib/v1alpha1/base/suggestion-random-service.yaml
  katib/v1alpha1/base/vizier-core-deployment.yaml
  katib/v1alpha1/base/vizier-core-rbac.yaml
  katib/v1alpha1/base/vizier-core-rest-deployment.yaml
  katib/v1alpha1/base/vizier-core-rest-service.yaml
  katib/v1alpha1/base/vizier-core-service.yaml
  katib/v1alpha1/base/vizier-db-deployment.yaml
  katib/v1alpha1/base/vizier-db-secret.yaml
  katib/v1alpha1/base/vizier-db-service.yaml
  katib/v1alpha1/base/worker-template.yaml
  kustomization.yaml
Labels: approved, lgtm, size/XL

#15 add centraldashboard
  README.md
  centraldashboard/base/deployment.yaml
  centraldashboard/base/kustomization.yaml
  centraldashboard/base/role.yaml
  centraldashboard/base/rolebinding.yaml
  centraldashboard/base/service.yaml
  centraldashboard/base/serviceaccount.yaml
  centraldashboard/overlay/add_service_annotation.yaml
  centraldashboard/overlay/kustomization.yaml
  kustomization.yaml
Labels: approved, lgtm, size/L

#16 Add ServiceAccount to Katib-ui deploy
  katib/v1alpha1/base/katib-ui-deployment.yaml
Labels: approved, lgtm, size/XS

#14 Add pipelines manifests
  argo/base/argo-ui-deployment.yaml
  argo/base/argo-wfc-deployment.yaml
  pipelines/api-service/base/deployment.yaml
  pipelines/api-service/base/kustomization.yaml
  pipelines/api-service/base/role-binding.yaml
  pipelines/api-service/base/role.yaml
  pipelines/api-service/base/sa.yaml
  pipelines/api-service/base/service.yaml
  pipelines/kustomization.yaml
  pipelines/minio/base/deployment.yaml
  pipelines/minio/base/kustomization.yaml
  pipelines/minio/base/secret.yaml
  pipelines/minio/base/service.yaml
  pipelines/mysql/base/deployment.yaml
  pipelines/mysql/base/kustomization.yaml
  pipelines/mysql/base/service.yaml
  pipelines/persistent-agent/base/clusterrole-binding.yaml
  pipelines/persistent-agent/base/clusterrole.yaml
  pipelines/persistent-agent/base/deployment.yaml
  pipelines/persistent-agent/base/kustomization.yaml
  pipelines/persistent-agent/base/sa.yaml
  pipelines/pipelines-runner/base/clusterrole-binding.yaml
  pipelines/pipelines-runner/base/clusterrole.yaml
  pipelines/pipelines-runner/base/kustomization.yaml
  pipelines/pipelines-runner/base/sa.yaml
  pipelines/pipelines-ui/base/deployment.yaml
  pipelines/pipelines-ui/base/kustomization.yaml
  pipelines/pipelines-ui/base/role-binding.yaml
  pipelines/pipelines-ui/base/role.yaml
  pipelines/pipelines-ui/base/sa.yaml
  pipelines/pipelines-ui/base/service.yaml
  pipelines/pipelines-viewer/base/clusterrole-binding.yaml
  pipelines/pipelines-viewer/base/clusterrole.yaml
  pipelines/pipelines-viewer/base/deployment.yaml
  pipelines/pipelines-viewer/base/kustomization.yaml
  pipelines/pipelines-viewer/base/resources.yaml
  pipelines/pipelines-viewer/base/sa.yaml
  pipelines/pipelines-viewer/base/service.yaml
  pipelines/scheduledworkflow/base/deployment.yaml
  pipelines/scheduledworkflow/base/kustomization.yaml
  pipelines/scheduledworkflow/base/resources.yaml
  pipelines/scheduledworkflow/base/role-binding.yaml
  pipelines/scheduledworkflow/base/role.yaml
  pipelines/scheduledworkflow/base/sa.yaml
Labels: approved, lgtm, size/XL

#17 add profiles
  kustomization.yaml
  profiles/base/README.md
  profiles/base/clusterrolebinding.yaml
  profiles/base/crd.yaml
  profiles/base/deployment.yaml
  profiles/base/kustomization.yaml
  profiles/base/role.yaml
  profiles/base/rolebinding.yaml
  profiles/base/serivce.yaml
  profiles/base/serviceaccount.yaml
Labels: approved, lgtm, size/L

#25 add katib
  README.md
  katib/base/katib-db-pvc.yaml
  katib/base/katib-ui-deployment.yaml
  katib/base/katib-ui-rbac.yaml
  katib/base/katib-ui-service.yaml
  katib/base/kustomization.yaml
  katib/base/metrics-collector-rbac.yaml
  katib/base/metrics-collector-template-configmap.yaml
  katib/base/studyjob-controller-deployment.yaml
  katib/base/studyjob-crd.yaml
  katib/base/studyjob-rbac.yaml
  katib/base/studyjob-service.yaml
  katib/base/suggestion-bayesianoptimization-deployment.yaml
  katib/base/suggestion-bayesianoptimization-service.yaml
  katib/base/suggestion-grid-deployment.yaml
  katib/base/suggestion-grid-service.yaml
  katib/base/suggestion-hyperband-deployment.yaml
  katib/base/suggestion-hyperband-service.yaml
  katib/base/suggestion-nasrl-deployment.yaml
  katib/base/suggestion-nasrl-service.yaml
  katib/base/suggestion-random-deployment.yaml
  katib/base/suggestion-random-service.yaml
  katib/base/vizier-core-deployment.yaml
  katib/base/vizier-core-rbac.yaml
  katib/base/vizier-core-rest-deployment.yaml
  katib/base/vizier-core-rest-service.yaml
  katib/base/vizier-core-service.yaml
  katib/base/vizier-db-deployment.yaml
  katib/base/vizier-db-secret.yaml
  katib/base/vizier-db-service.yaml
  katib/base/worker-template.yaml
Labels: approved, lgtm, size/XL

#28 adds modeldb kustomize manifest
  modeldb/base/artifact-store-deployment.yaml
  modeldb/base/artifact-store-service.yaml
  modeldb/base/backend-deployment.yaml
  modeldb/base/backend-proxy-service.yaml
  modeldb/base/backend-service.yaml
  modeldb/base/configmap.yaml
  modeldb/base/kustomization.yaml
  modeldb/base/mysql-backend-deployment.yaml
  modeldb/base/mysql-service.yaml
  modeldb/base/persistent-volume-claim.yaml
  modeldb/base/proxy-deployment.yaml
  modeldb/base/secret.yaml
  modeldb/base/webapp-deplyment.yaml
  modeldb/base/webapp-service.yaml
Labels: approved, lgtm, size/L

#29 fixes to profiles
  README.md
  profiles/base/cluster-role-binding.yaml
  profiles/base/clusterrolebinding.yaml
  profiles/base/crd.yaml
  profiles/base/deployment.yaml
  profiles/base/kustomization.yaml
  profiles/base/role-binding.yaml
  profiles/base/role.yaml
  profiles/base/rolebinding.yaml
  profiles/base/serivce.yaml
  profiles/base/service-account.yaml
  profiles/base/service.yaml
  profiles/base/serviceaccount.yaml
Labels: approved, lgtm, size/L

#35 kfctl generate failed with kustomize
  pipeline/kustomization.yaml
  pipeline/pipelines-ui/base/kustomization.yaml
  pipeline/pipelines-ui/base/service.yaml
  pipeline/pipelines-viewer/base/kustomization.yaml
  pipeline/pipelines-viewer/base/service.yaml
Labels: approved, lgtm, size/XS
