Repository kubeflow/manifests, pull requests merged in 2019-12, with the labels that each got.

#634 adding self to owner file
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#622 Add storage overlays for IBM NFS
  istio/oidc-authservice/overlays/ibm-storage-config/deployment.yaml
  istio/oidc-authservice/overlays/ibm-storage-config/kustomization.yaml
  katib/katib-controller/overlays/ibm-storage-config/katib-db-deployment.yaml
  katib/katib-controller/overlays/ibm-storage-config/kustomization.yaml
  metadata/overlays/ibm-storage-config/kustomization.yaml
  tests/katib-controller-overlays-ibm-storage-config_test.go
  tests/metadata-overlays-ibm-storage-config_test.go
  tests/oidc-authservice-overlays-ibm-storage-config_test.go
Labels: approved, cla: yes, lgtm, size/XXL

#630 Add a GitHub action to auto add/remove issues to Needs Triage Project
  .github/workflows/triage_issues.yaml
Labels: approved, cla: yes, lgtm, size/S

#620 Upgrades Istio in kfctl_istio_dex kfdef
  kfdef/kfctl_istio_dex.yaml
Labels: approved, cla: yes, lgtm, size/M

#635 Update kfdef versions to v0.7.0
  kfdef/kfctl_anthos.0.7.0.yaml
  kfdef/kfctl_aws.0.7.0.yaml
  kfdef/kfctl_aws_cognito.0.7.0.yaml
  kfdef/kfctl_gcp_basic_auth.0.7.0.yaml
  kfdef/kfctl_gcp_iap.0.7.0.yaml
  kfdef/kfctl_k8s_istio.0.7.0.yaml
Labels: approved, cla: yes, lgtm, size/S

#633 istio: oidc-authservice: add readiness probe and update image
  istio/oidc-authservice/base/deployment.yaml
  istio/oidc-authservice/base/kustomization.yaml
  tests/basic-auth-ingress-base_test.go
  tests/basic-auth-ingress-overlays-application_test.go
  tests/basic-auth-ingress-overlays-certmanager_test.go
  tests/basic-auth-ingress-overlays-gcp-credentials_test.go
  tests/basic-auth-ingress-overlays-managed-cert_test.go
  tests/istio-crds-base_test.go
  tests/istio-install-base_test.go
  tests/metadata-base_test.go
  tests/metadata-overlays-application_test.go
  tests/metadata-overlays-ibm-storage-config_test.go
  tests/metadata-overlays-istio_test.go
  tests/oidc-authservice-base_test.go
  tests/oidc-authservice-overlays-application_test.go
  tests/oidc-authservice-overlays-ibm-storage-config_test.go
Labels: approved, cla: yes, lgtm, size/L

#631 moving kfserving to 0.2.2
  kfserving/kfserving-crds/base/crd.yaml
  kfserving/kfserving-install/base/cluster-role.yaml
  kfserving/kfserving-install/base/config-map.yaml
  kfserving/kfserving-install/base/kustomization.yaml
  kfserving/kfserving-install/base/statefulset.yaml
  tests/kfserving-crds-base_test.go
  tests/kfserving-crds-overlays-application_test.go
  tests/kfserving-install-base_test.go
  tests/kfserving-install-overlays-application_test.go
Labels: approved, cla: yes, lgtm, size/XL

#645 kfdef 0.7.0 pin commit
  kfdef/kfctl_anthos.0.7.0.yaml
  kfdef/kfctl_aws.0.7.0.yaml
  kfdef/kfctl_aws_cognito.0.7.0.yaml
  kfdef/kfctl_existing_arrikto.0.7.0.yaml
  kfdef/kfctl_gcp_basic_auth.0.7.0.yaml
  kfdef/kfctl_gcp_iap.0.7.0.yaml
  kfdef/kfctl_k8s_istio.0.7.0.yaml
Labels: approved, cla: yes, lgtm, size/S

#650 Automated cherry pick of #631: moving kfserving to 0.2.2 Cherry pick of #631 on v0.7-branch. #631: moving kfserving to 0.2.2
  kfserving/kfserving-crds/base/crd.yaml
  kfserving/kfserving-install/base/cluster-role.yaml
  kfserving/kfserving-install/base/config-map.yaml
  kfserving/kfserving-install/base/kustomization.yaml
  kfserving/kfserving-install/base/statefulset.yaml
  tests/kfserving-crds-base_test.go
  tests/kfserving-crds-overlays-application_test.go
  tests/kfserving-install-base_test.go
  tests/kfserving-install-overlays-application_test.go
Labels: approved, cla: yes, lgtm, size/XL

#649 Automated cherry pick of #646: update profile image Cherry pick of #646 on v0.7-branch. #646: update profile image
  profiles/base/kustomization.yaml
  tests/profiles-base_test.go
  tests/profiles-overlays-application_test.go
  tests/profiles-overlays-debug_test.go
  tests/profiles-overlays-devices_test.go
  tests/profiles-overlays-istio_test.go
  tests/profiles-overlays-test_test.go
Labels: approved, cla: yes, lgtm, size/M

#656 Kfdef 0.7.1
  kfdef/kfctl_anthos.0.7.1.yaml
  kfdef/kfctl_aws.0.7.1.yaml
  kfdef/kfctl_aws_cognito.0.7.1.yaml
  kfdef/kfctl_existing_arrikto.0.7.1.yaml
  kfdef/kfctl_gcp_basic_auth.0.7.1.yaml
  kfdef/kfctl_gcp_iap.0.7.1.yaml
  kfdef/kfctl_k8s_istio.0.7.1.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#658 Add upgrade spec for v0.7.0 to v0.7.1
  kfdef/kfctl_upgrade_gcp_iap_0.7.1.yaml
Labels: approved, cla: yes, lgtm, size/S

#660 Trigger kfctl e2e tests on kubeflow/manifests
  prow_config.yaml
Labels: approved, cla: yes, lgtm, size/S

#639 Automated cherry pick of #633: istio: oidc-authservice: add readiness probe and update Cherry pick of #633 on v0.7-branch. #633: istio: oidc-authservice: add readiness probe and update
  istio/oidc-authservice/base/deployment.yaml
  istio/oidc-authservice/base/kustomization.yaml
  tests/metadata-base_test.go
  tests/metadata-overlays-application_test.go
  tests/metadata-overlays-istio_test.go
  tests/oidc-authservice-base_test.go
  tests/oidc-authservice-overlays-application_test.go
Labels: approved, cla: yes, lgtm, size/L

#641 Allow nb-controller get/list/watch/create events
  jupyter/jupyter-web-app/base/cluster-role.yaml
  jupyter/notebook-controller/base/cluster-role.yaml
  tests/jupyter-web-app-base_test.go
  tests/jupyter-web-app-overlays-application_test.go
  tests/jupyter-web-app-overlays-istio_test.go
  tests/notebook-controller-base_test.go
  tests/notebook-controller-overlays-application_test.go
  tests/notebook-controller-overlays-istio_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#678 add owners file for jupyter
  jupyter/OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#681 Create OWNERS for kfdef folder
  kfdef/OWNERS
Labels: approved, cla: yes, lgtm, size/S

#655 Add permissions to JWA for SubjectAccessReviews
  jupyter/jupyter-web-app/base/cluster-role.yaml
  tests/jupyter-jupyter-web-app-base_test.go
  tests/jupyter-jupyter-web-app-overlays-application_test.go
  tests/jupyter-jupyter-web-app-overlays-istio_test.go
Labels: approved, cla: yes, lgtm, size/S

#682 update notebook controller image
  jupyter/notebook-controller/base/kustomization.yaml
  tests/jupyter-notebook-controller-base_test.go
  tests/jupyter-notebook-controller-overlays-application_test.go
  tests/jupyter-notebook-controller-overlays-istio_test.go
Labels: approved, cla: yes, lgtm, size/XS

#684 update apiVersion kfdef
  kfdef/kfctl_anthos.yaml
  kfdef/kfctl_aws.yaml
  kfdef/kfctl_aws_cognito.yaml
  kfdef/kfctl_gcp_basic_auth.yaml
  kfdef/kfctl_gcp_iap.yaml
  kfdef/kfctl_istio_dex.yaml
  kfdef/kfctl_k8s_istio.yaml
Labels: approved, cla: yes, lgtm, size/S

#617 Automated cherry pick of #549: kfdef: existing_arrikto: add cert-manager Cherry pick of #549 on v0.7-branch. #549: kfdef: existing_arrikto: add cert-manager
  admission-webhook/webhook/overlays/cert-manager/certificate.yaml
  admission-webhook/webhook/overlays/cert-manager/deployment.yaml
  admission-webhook/webhook/overlays/cert-manager/kustomization.yaml
  admission-webhook/webhook/overlays/cert-manager/mutating-webhook-configuration.yaml
  admission-webhook/webhook/overlays/cert-manager/params.env
  admission-webhook/webhook/overlays/cert-manager/params.yaml
  tests/webhook-overlays-cert-manager_test.go
Labels: approved, cla: yes, lgtm, size/L
