Repository kubeflow/manifests, pull requests merged in 2019-10, with the labels that each got.

#403 Seldon 0.4.1
  seldon/Makefile
  seldon/seldon-core-operator/base/Kube-descriptor.yaml
  seldon/seldon-core-operator/base/seldon-config-cm.yaml
  seldon/seldon-core-operator/base/seldon-manager-sa.yaml
  seldon/seldon-core-operator/base/seldon-operator-controller-manager-service-svc.yaml
  seldon/seldon-core-operator/base/seldon-operator-controller-manager-statefulset.yaml
  seldon/seldon-core-operator/base/seldon-operator-manager-role-clusterrole.yaml
  seldon/seldon-core-operator/base/seldon-operator-manager-rolebinding-crb.yaml
  seldon/seldon-core-operator/base/seldondeployments.machinelearning.seldon.io-crd.yaml
  seldon/seldon-core-operator/base/webhook-server-service-svc.yaml
  seldon/values.yaml
  tests/seldon-core-operator-base_test.go
  tests/seldon-core-operator-overlays-application_test.go
Labels: approved, cla: yes, lgtm, size/M

#401 Add new updated Jupyter notebook images
  jupyter/jupyter-web-app/base/config-map.yaml
  tests/jupyter-web-app-base_test.go
  tests/jupyter-web-app-overlays-application_test.go
Labels: approved, cla: yes, lgtm, size/M

#424 Metadata fix
  metadata/base/kustomization.yaml
  metadata/base/metadata-envoy-deployment.yaml
  metadata/overlays/istio/virtual-service-metadata-grpc.yaml
  tests/metadata-base_test.go
  tests/metadata-overlays-application_test.go
  tests/metadata-overlays-istio_test.go
Labels: approved, cla: yes, lgtm, size/M

#406 Katib v1alpha3 manifests
  katib/katib-controller/base/katib-configmap.yaml
  katib/katib-controller/base/katib-controller-deployment.yaml
  katib/katib-controller/base/katib-controller-rbac.yaml
  katib/katib-controller/base/katib-controller-secret.yaml
  katib/katib-controller/base/katib-controller-service.yaml
  katib/katib-controller/base/katib-db-deployment.yaml
  katib/katib-controller/base/katib-db-pvc.yaml
  katib/katib-controller/base/katib-db-secret.yaml
  katib/katib-controller/base/katib-db-service.yaml
  katib/katib-controller/base/katib-manager-deployment.yaml
  katib/katib-controller/base/katib-manager-rest-deployment.yaml
  katib/katib-controller/base/katib-manager-rest-service.yaml
  katib/katib-controller/base/katib-manager-service.yaml
  katib/katib-controller/base/katib-ui-deployment.yaml
  katib/katib-controller/base/katib-ui-rbac.yaml
  katib/katib-controller/base/katib-ui-service.yaml
  katib/katib-controller/base/kustomization.yaml
  katib/katib-controller/base/params.env
  katib/katib-controller/base/params.yaml
  katib/katib-controller/base/trial-template-configmap.yaml
  katib/katib-controller/overlays/application/application.yaml
  katib/katib-controller/overlays/application/kustomization.yaml
  katib/katib-controller/overlays/istio/katib-ui-virtual-service.yaml
  katib/katib-controller/overlays/istio/kustomization.yaml
  katib/katib-controller/overlays/istio/params.yaml
  katib/katib-crds/base/experiment-crd.yaml
  katib/katib-crds/base/kustomization.yaml
  katib/katib-crds/base/suggestion-crd.yaml
  katib/katib-crds/base/trial-crd.yaml
  kfdef/kfctl_anthos.yaml
  kfdef/kfctl_aws.yaml
  kfdef/kfctl_aws_cognito.yaml
  kfdef/kfctl_existing_arrikto.yaml
  kfdef/kfctl_gcp_basic_auth.yaml
  kfdef/kfctl_gcp_iap.yaml
  kfdef/kfctl_k8s_istio.yaml
  tests/katib-v3-controller-base_test.go
  tests/katib-v3-controller-overlays-application_test.go
  tests/katib-v3-controller-overlays-istio_test.go
  tests/katib-v3-crds-base_test.go
Labels: approved, cla: yes, lgtm, size/XXL

#432 Removing tf-job dashboard from deployment
  tests/tf-job-crds-base_test.go
  tests/tf-job-operator-base_test.go
  tests/tf-job-operator-overlays-application_test.go
  tests/tf-job-operator-overlays-istio_test.go
  tf-training/tf-job-crds/base/crd.yaml
  tf-training/tf-job-operator/base/cluster-role-binding.yaml
  tf-training/tf-job-operator/base/cluster-role.yaml
  tf-training/tf-job-operator/base/config-map.yaml
  tf-training/tf-job-operator/base/deployment.yaml
  tf-training/tf-job-operator/base/kustomization.yaml
  tf-training/tf-job-operator/base/params.env
  tf-training/tf-job-operator/base/params.yaml
  tf-training/tf-job-operator/base/service.yaml
  tf-training/tf-job-operator/overlays/application/application.yaml
  tf-training/tf-job-operator/overlays/istio/kustomization.yaml
  tf-training/tf-job-operator/overlays/istio/params.yaml
  tf-training/tf-job-operator/overlays/istio/virtual-service.yaml
Labels: approved, cla: yes, lgtm, size/XL

#433 Remove istio overlay in tf-job-operator
  kfdef/kfctl_anthos.yaml
  kfdef/kfctl_aws.yaml
  kfdef/kfctl_aws_cognito.yaml
  kfdef/kfctl_existing_arrikto.yaml
  kfdef/kfctl_gcp_basic_auth.yaml
  kfdef/kfctl_gcp_iap.yaml
  kfdef/kfctl_k8s_istio.yaml
Labels: approved, cla: yes, lgtm, size/XS

#434 Reorder katib manifests
  kfdef/kfctl_anthos.yaml
  kfdef/kfctl_aws.yaml
  kfdef/kfctl_aws_cognito.yaml
  kfdef/kfctl_existing_arrikto.yaml
  kfdef/kfctl_gcp_basic_auth.yaml
  kfdef/kfctl_gcp_iap.yaml
  kfdef/kfctl_k8s_istio.yaml
Labels: approved, cla: yes, lgtm, size/L

#404 kfdef: existing_arrikto: remove metacontroller application
  kfdef/kfctl_existing_arrikto.yaml
Labels: approved, cla: yes, lgtm, size/XS

#437 Fix presubmits; pythonpath needs to include kubeflow/kubeflow/py
  tests/workflows/components/kfctl_go_test.jsonnet
Labels: approved, cla: yes, lgtm, size/XS

#430 Restore Metadata fix (#424)
  metadata/base/kustomization.yaml
  metadata/base/metadata-envoy-deployment.yaml
  metadata/overlays/istio/kustomization.yaml
  metadata/overlays/istio/virtual-service-metadata-grpc.yaml
  tests/metadata-base_test.go
  tests/metadata-overlays-application_test.go
  tests/metadata-overlays-istio_test.go
Labels: approved, cla: yes, lgtm, size/M

#438 Revert Rollback of Add new updated Jupyter notebook images (#401)
  jupyter/jupyter-web-app/base/config-map.yaml
  tests/jupyter-web-app-base_test.go
  tests/jupyter-web-app-overlays-application_test.go
Labels: approved, cla: yes, lgtm, size/M

#393 K8s ClusterRoles for: TFJobs, PyTorchJobs, Notebooks, PodDefaults, Profiles
  admission-webhook/webhook/base/cluster-role.yaml
  jupyter/notebook-controller/base/cluster-role.yaml
  pytorch-job/pytorch-operator/base/cluster-role.yaml
  tests/notebook-controller-base_test.go
  tests/notebook-controller-overlays-application_test.go
  tests/notebook-controller-overlays-istio_test.go
  tests/pytorch-operator-base_test.go
  tests/pytorch-operator-overlays-application_test.go
  tests/tf-job-operator-base_test.go
  tests/tf-job-operator-overlays-application_test.go
  tests/webhook-base_test.go
  tf-training/tf-job-operator/base/cluster-role.yaml
Labels: approved, cla: yes, lgtm, size/XL

#431 Removing unnecessary configs from Pytorch operator
  pytorch-job/pytorch-job-crds/base/crd.yaml
  pytorch-job/pytorch-operator/base/cluster-role.yaml
  pytorch-job/pytorch-operator/base/config-map.yaml
  pytorch-job/pytorch-operator/base/deployment.yaml
  pytorch-job/pytorch-operator/base/kustomization.yaml
  tests/pytorch-job-crds-base_test.go
  tests/pytorch-operator-base_test.go
  tests/pytorch-operator-overlays-application_test.go
  tests/tf-job-operator-base_test.go
  tests/tf-job-operator-overlays-application_test.go
  tests/workflows/components/kubeflow_workflow.libsonnet
  tf-training/tf-job-operator/base/cluster-role.yaml
Labels: approved, cla: yes, lgtm, size/L

#392 Update pipelines manifest to ship 0.1.31
  kfdef/kfctl_aws.yaml
  kfdef/kfctl_aws_cognito.yaml
  kfdef/kfctl_existing_arrikto.yaml
  kfdef/kfctl_gcp_basic_auth.yaml
  kfdef/kfctl_gcp_iap.yaml
  kfdef/kfctl_k8s_istio.yaml
  pipeline/api-service/base/config-map.yaml
  pipeline/api-service/base/deployment.yaml
  pipeline/api-service/base/kustomization.yaml
  pipeline/persistent-agent/base/deployment.yaml
  pipeline/persistent-agent/base/kustomization.yaml
  pipeline/pipeline-visualization-service/base/kustomization.yaml
  pipeline/pipelines-ui/base/deployment.yaml
  pipeline/pipelines-ui/base/kustomization.yaml
  pipeline/pipelines-viewer/base/deployment.yaml
  pipeline/pipelines-viewer/base/kustomization.yaml
  pipeline/scheduledworkflow/base/deployment.yaml
  pipeline/scheduledworkflow/base/kustomization.yaml
  tests/api-service-base_test.go
  tests/persistent-agent-base_test.go
  tests/pipeline-visualization-service-base_test.go
  tests/pipelines-ui-base_test.go
  tests/pipelines-ui-overlays-istio_test.go
  tests/pipelines-viewer-base_test.go
  tests/scheduledworkflow-base_test.go
Labels: approved, cla: yes, lgtm, size/L

#446 add instance label to jupyter-web-app, selector to Application
  jupyter/jupyter-web-app/overlays/application/application.yaml
  jupyter/jupyter-web-app/overlays/application/kustomization.yaml
  tests/aws-alb-ingress-controller-base_test.go
  tests/aws-alb-ingress-controller-overlays-vpc_test.go
  tests/aws-efs-csi-driver-base_test.go
  tests/aws-fsx-csi-driver-base_test.go
  tests/basic-auth-ingress-overlays-certmanager_test.go
  tests/basic-auth-ingress-overlays-gcp-credentials_test.go
  tests/basic-auth-ingress-overlays-managed-cert_test.go
  tests/centraldashboard-base_test.go
  tests/centraldashboard-overlays-application_test.go
  tests/centraldashboard-overlays-istio_test.go
  tests/cloud-endpoints-overlays-gcp-credentials_test.go
  tests/fluentd-cloud-watch-base_test.go
  tests/iap-ingress-base_test.go
  tests/iap-ingress-overlays-certmanager_test.go
  tests/iap-ingress-overlays-gcp-credentials_test.go
  tests/iap-ingress-overlays-managed-cert_test.go
  tests/istio-base_test.go
  tests/istio-ingress-base_test.go
  tests/istio-ingress-overlays-cognito_test.go
  tests/istio-ingress-overlays-oidc_test.go
  tests/jupyter-web-app-base_test.go
  tests/jupyter-web-app-overlays-application_test.go
  tests/jupyter-web-app-overlays-istio_test.go
  tests/metadata-base_test.go
  tests/metadata-overlays-application_test.go
  tests/metadata-overlays-istio_test.go
  tests/minio-base_test.go
  tests/minio-overlays-minioPd_test.go
  tests/mxnet-operator-base_test.go
  tests/mxnet-operator-overlays-application_test.go
  tests/mysql-base_test.go
  tests/mysql-overlays-mysqlPd_test.go
  tests/profiles-base_test.go
  tests/profiles-overlays-debug_test.go
  tests/profiles-overlays-devices_test.go
  tests/profiles-overlays-istio_test.go
  tests/prometheus-base_test.go
  tests/seldon-core-operator-base_test.go
  tests/seldon-core-operator-overlays-application_test.go
Labels: approved, cla: yes, lgtm, size/L

#443 Update the notebook-controller image.
  jupyter/notebook-controller/base/kustomization.yaml
  tests/notebook-controller-base_test.go
  tests/notebook-controller-overlays-application_test.go
  tests/notebook-controller-overlays-istio_test.go
  tests/scripts/run-tests.sh
Labels: approved, cla: yes, lgtm, size/S

#453 add application overlay for admission-webhook/{webhook,bootstrap}
  admission-webhook/bootstrap/overlays/application/application.yaml
  admission-webhook/bootstrap/overlays/application/kustomization.yaml
  admission-webhook/webhook/overlays/application/application.yaml
  admission-webhook/webhook/overlays/application/kustomization.yaml
  kfdef/kfctl_anthos.yaml
  kfdef/kfctl_aws.yaml
  kfdef/kfctl_aws_cognito.yaml
  kfdef/kfctl_existing_arrikto.yaml
  kfdef/kfctl_gcp_basic_auth.yaml
  kfdef/kfctl_gcp_iap.yaml
  kfdef/kfctl_k8s_istio.yaml
  tests/aws-alb-ingress-controller-base_test.go
  tests/aws-alb-ingress-controller-overlays-vpc_test.go
  tests/aws-efs-csi-driver-base_test.go
  tests/aws-fsx-csi-driver-base_test.go
  tests/basic-auth-ingress-overlays-managed-cert_test.go
  tests/bootstrap-overlays-application_test.go
  tests/centraldashboard-base_test.go
  tests/centraldashboard-overlays-application_test.go
  tests/centraldashboard-overlays-istio_test.go
  tests/fluentd-cloud-watch-base_test.go
  tests/iap-ingress-base_test.go
  tests/iap-ingress-overlays-certmanager_test.go
  tests/iap-ingress-overlays-gcp-credentials_test.go
  tests/iap-ingress-overlays-managed-cert_test.go
  tests/istio-base_test.go
  tests/istio-ingress-base_test.go
  tests/istio-ingress-overlays-cognito_test.go
  tests/istio-ingress-overlays-oidc_test.go
  tests/jupyter-web-app-base_test.go
  tests/jupyter-web-app-overlays-application_test.go
  tests/jupyter-web-app-overlays-istio_test.go
  tests/minio-base_test.go
  tests/minio-overlays-minioPd_test.go
  tests/mxnet-operator-base_test.go
  tests/mxnet-operator-overlays-application_test.go
  tests/mysql-base_test.go
  tests/mysql-overlays-mysqlPd_test.go
  tests/profiles-base_test.go
  tests/profiles-overlays-debug_test.go
  tests/profiles-overlays-devices_test.go
  tests/profiles-overlays-istio_test.go
  tests/prometheus-base_test.go
  tests/webhook-overlays-application_test.go
Labels: approved, cla: yes, lgtm, size/XXL

#455 add argo application overlay
  argo/overlays/application/application.yaml
  argo/overlays/application/kustomization.yaml
  kfdef/kfctl_anthos.yaml
  kfdef/kfctl_aws.yaml
  kfdef/kfctl_aws_cognito.yaml
  kfdef/kfctl_existing_arrikto.yaml
  kfdef/kfctl_gcp_basic_auth.yaml
  kfdef/kfctl_gcp_iap.yaml
  kfdef/kfctl_k8s_istio.yaml
  tests/argo-overlays-application_test.go
Labels: approved, cla: yes, lgtm, size/XL

#465 add kubebench application overlay
  kubebench/overlays/application/application.yaml
  kubebench/overlays/application/kustomization.yaml
  tests/kubebench-overlays-application_test.go
Labels: approved, cla: yes, lgtm, size/L

#461 Update kfserving manifests to 0.2.0
  kfserving/kfserving-crds/base/crd.yaml
  kfserving/kfserving-install/base/cluster-role-binding.yaml
  kfserving/kfserving-install/base/cluster-role.yaml
  kfserving/kfserving-install/base/config-map.yaml
  kfserving/kfserving-install/base/kustomization.yaml
  kfserving/kfserving-install/base/statefulset.yaml
  kfserving/kfserving-install/overlays/application/application.yaml
  tests/kfserving-crds-base_test.go
  tests/kfserving-install-base_test.go
  tests/kfserving-install-overlays-application_test.go
Labels: approved, cla: yes, lgtm, size/XXL

#478 Update the centraldashboard image to a newly built image.
  common/centraldashboard/base/kustomization.yaml
  tests/centraldashboard-base_test.go
  tests/centraldashboard-overlays-application_test.go
  tests/centraldashboard-overlays-istio_test.go
Labels: approved, cla: yes, lgtm, size/S

#448 Restores Kubeflow based ClusterRoles for Katib in its newer manifests
  katib/katib-controller/base/katib-controller-rbac.yaml
  tests/katib-controller-base_test.go
  tests/katib-controller-overlays-application_test.go
  tests/katib-controller-overlays-istio_test.go
Labels: approved, cla: yes, lgtm, size/L

#457 Minor changes to Katib manifests
  katib/katib-controller/base/katib-manager-deployment.yaml
  katib/katib-crds/base/trial-crd.yaml
  tests/katib-controller-base_test.go
  tests/katib-controller-overlays-application_test.go
  tests/katib-controller-overlays-istio_test.go
  tests/katib-crds-base_test.go
Labels: approved, cla: yes, lgtm, size/S

#473 add application overlays for gcp
  gcp/cloud-endpoints/overlays/application/application.yaml
  gcp/cloud-endpoints/overlays/application/kustomization.yaml
  gcp/gpu-driver/overlays/application/application.yaml
  gcp/gpu-driver/overlays/application/kustomization.yaml
  gcp/iap-ingress/overlays/application/application.yaml
  gcp/iap-ingress/overlays/application/kustomization.yaml
  gcp/prometheus/overlays/application/application.yaml
  gcp/prometheus/overlays/application/kustomization.yaml
  kfdef/kfctl_gcp_basic_auth.yaml
  kfdef/kfctl_gcp_iap.yaml
  tests/cloud-endpoints-overlays-application_test.go
  tests/gpu-driver-overlays-application_test.go
  tests/iap-ingress-overlays-application_test.go
  tests/prometheus-overlays-application_test.go
Labels: approved, cla: yes, lgtm, size/XXL

#470 add application overlays for pipeline
  istio/istio-install/base/istio-noauth.yaml
  kfdef/kfctl_anthos.yaml
  kfdef/kfctl_aws.yaml
  kfdef/kfctl_aws_cognito.yaml
  kfdef/kfctl_existing_arrikto.yaml
  kfdef/kfctl_gcp_basic_auth.yaml
  kfdef/kfctl_gcp_iap.yaml
  kfdef/kfctl_k8s_istio.yaml
  pipeline/api-service/overlays/application/application.yaml
  pipeline/api-service/overlays/application/kustomization.yaml
  pipeline/minio/overlays/application/application.yaml
  pipeline/minio/overlays/application/kustomization.yaml
  pipeline/mysql/overlays/application/application.yaml
  pipeline/mysql/overlays/application/kustomization.yaml
  pipeline/persistent-agent/overlays/application/application.yaml
  pipeline/persistent-agent/overlays/application/kustomization.yaml
  pipeline/pipeline-visualization-service/overlays/application/application.yaml
  pipeline/pipeline-visualization-service/overlays/application/kustomization.yaml
  pipeline/pipelines-runner/overlays/application/application.yaml
  pipeline/pipelines-runner/overlays/application/kustomization.yaml
  pipeline/pipelines-ui/overlays/application/application.yaml
  pipeline/pipelines-ui/overlays/application/kustomization.yaml
  pipeline/pipelines-viewer/overlays/application/application.yaml
  pipeline/pipelines-viewer/overlays/application/kustomization.yaml
  pipeline/scheduledworkflow/overlays/application/application.yaml
  pipeline/scheduledworkflow/overlays/application/kustomization.yaml
  tests/api-service-overlays-application_test.go
  tests/istio-install-base_test.go
  tests/kfserving-crds-base_test.go
  tests/kfserving-crds-overlays-application_test.go
  tests/minio-overlays-application_test.go
  tests/mysql-overlays-application_test.go
  tests/persistent-agent-overlays-application_test.go
  tests/pipeline-visualization-service-overlays-application_test.go
  tests/pipelines-runner-overlays-application_test.go
  tests/pipelines-ui-overlays-application_test.go
  tests/pipelines-viewer-overlays-application_test.go
  tests/scheduledworkflow-overlays-application_test.go
Labels: approved, cla: yes, lgtm, size/XXL

#492 Add application overlays for profiles
  kfdef/kfctl_anthos.yaml
  kfdef/kfctl_aws.yaml
  kfdef/kfctl_aws_cognito.yaml
  kfdef/kfctl_existing_arrikto.yaml
  kfdef/kfctl_gcp_basic_auth.yaml
  kfdef/kfctl_gcp_iap.yaml
  kfdef/kfctl_k8s_istio.yaml
  profiles/overlays/application/application.yaml
  profiles/overlays/application/kustomization.yaml
  tests/profiles-overlays-application_test.go
Labels: approved, cla: yes, lgtm, size/L

#503 Adding Katib db liveness check
  katib/katib-controller/base/katib-db-deployment.yaml
  katib/katib-controller/base/kustomization.yaml
  tests/katib-controller-base_test.go
  tests/katib-controller-overlays-application_test.go
  tests/katib-controller-overlays-istio_test.go
Labels: approved, cla: yes, lgtm, size/M

#462 Replaces null values at ClusterRoles with [] - for kubectl CLI compatibility
  admission-webhook/webhook/base/cluster-role.yaml
  jupyter/notebook-controller/base/cluster-role.yaml
  kfserving/kfserving-install/base/cluster-role.yaml
  kubeflow-roles/base/cluster-roles.yaml
  pipeline/pipelines-viewer/base/cluster-role.yaml
  pipeline/scheduledworkflow/base/cluster-role.yaml
  pytorch-job/pytorch-operator/base/cluster-role.yaml
  tests/kfserving-install-base_test.go
  tests/kfserving-install-overlays-application_test.go
  tests/kubeflow-roles-base_test.go
  tests/notebook-controller-base_test.go
  tests/notebook-controller-overlays-application_test.go
  tests/notebook-controller-overlays-istio_test.go
  tests/pipelines-viewer-base_test.go
  tests/pytorch-operator-base_test.go
  tests/pytorch-operator-overlays-application_test.go
  tests/scheduledworkflow-base_test.go
  tests/tf-job-operator-base_test.go
  tests/tf-job-operator-overlays-application_test.go
  tests/webhook-base_test.go
  tests/webhook-overlays-application_test.go
  tf-training/tf-job-operator/base/cluster-role.yaml
Labels: approved, cla: yes, lgtm, size/M

#500 Fix kfseving clusterrole's API group
  kfserving/kfserving-install/base/cluster-role.yaml
  tests/kfserving-install-base_test.go
  tests/kfserving-install-overlays-application_test.go
Labels: approved, cla: yes, lgtm, size/S

#505 Fix broken presubmit tests
  tests/pipelines-viewer-overlays-application_test.go
  tests/scheduledworkflow-overlays-application_test.go
Labels: approved, cla: yes, lgtm, size/XS

#460 update centraldashboard version, instance tags
  common/centraldashboard/overlays/application/application.yaml
  common/centraldashboard/overlays/application/kustomization.yaml
  kfdef/kfctl_anthos.yaml
  kfdef/kfctl_existing_arrikto.yaml
  kfdef/kfctl_gcp_basic_auth.yaml
  kfdef/kfctl_gcp_iap.yaml
  kfdef/kfctl_k8s_istio.yaml
  tests/centraldashboard-overlays-application_test.go
Labels: approved, cla: yes, lgtm, size/L

#466 Only generate what's changed. Add option to generate overlays/application
  hack/gen-test-targets.sh
Labels: approved, cla: yes, lgtm, size/L

#498 Workaround workload identity bug and fix node autoprovisioning.
  gcp/deployment_manager_configs/cluster-kubeflow.yaml
  gcp/deployment_manager_configs/cluster.jinja
Labels: approved, cla: yes, lgtm, size/XS

#490 Updates KfDefs with kubeflow-roles
  kfdef/kfctl_anthos.yaml
  kfdef/kfctl_aws.yaml
  kfdef/kfctl_aws_cognito.yaml
  kfdef/kfctl_existing_arrikto.yaml
  kfdef/kfctl_gcp_basic_auth.yaml
  kfdef/kfctl_gcp_iap.yaml
  kfdef/kfctl_k8s_istio.yaml
Labels: approved, cla: yes, lgtm, size/M

#497 Update jupyter notebooks image tags
  jupyter/jupyter-web-app/base/config-map.yaml
  tests/jupyter-web-app-base_test.go
  tests/jupyter-web-app-overlays-application_test.go
Labels: approved, cla: yes, lgtm, size/S

#491 update jwt excluded_paths
  gcp/iap-ingress/base/policy.yaml
  tests/iap-ingress-base_test.go
  tests/iap-ingress-overlays-application_test.go
  tests/iap-ingress-overlays-certmanager_test.go
  tests/iap-ingress-overlays-gcp-credentials_test.go
  tests/iap-ingress-overlays-managed-cert_test.go
Labels: approved, cla: yes, lgtm, size/S

#519 kfdef: existing_arrikto: specify package manager
  kfdef/kfctl_existing_arrikto.yaml
Labels: approved, cla: yes, lgtm, size/XS

#468 add gcp basic-auth-ingress application overlay
  gcp/basic-auth-ingress/overlays/application/application.yaml
  gcp/basic-auth-ingress/overlays/application/kustomization.yaml
  kfdef/kfctl_gcp_basic_auth.yaml
  tests/basic-auth-ingress-overlays-application_test.go
Labels: approved, cla: yes, lgtm, size/XL

#496 document istio workaround for 'Internal error occurred: failed calling admission webhook "pilot.validation.istio.io"'
  istio/istio-install/base/istio-noauth.yaml
  tests/istio-install-base_test.go
Labels: approved, cla: yes, lgtm, size/XS

#515 generate fixes and improvements
  hack/gen-test-target.sh
  hack/gen-test-targets.sh
  tests/Makefile
Labels: approved, cla: yes, lgtm, size/L

#494 add application overlay for spartakus
  common/spartakus/overlays/application/application.yaml
  common/spartakus/overlays/application/kustomization.yaml
  kfdef/kfctl_anthos.yaml
  kfdef/kfctl_aws.yaml
  kfdef/kfctl_aws_cognito.yaml
  kfdef/kfctl_existing_arrikto.yaml
  kfdef/kfctl_gcp_basic_auth.yaml
  kfdef/kfctl_gcp_iap.yaml
  kfdef/kfctl_k8s_istio.yaml
  tests/aws-alb-ingress-controller-overlays-application_test.go
  tests/aws-alb-ingress-controller-overlays-vpc_test.go
  tests/nvidia-device-plugin-overlays-application_test.go
  tests/spartakus-overlays-application_test.go
Labels: approved, cla: yes, lgtm, size/XL

#451 Add application overlay for notebook-controller
  jupyter/notebook-controller/overlays/application/application.yaml
  jupyter/notebook-controller/overlays/application/kustomization.yaml
  tests/notebook-controller-overlays-application_test.go
Labels: approved, cla: yes, lgtm, size/L

#530 fix backend list name collision
  gcp/iap-ingress/base/config-map.yaml
  tests/api-service-overlays-application_test.go
  tests/aws-alb-ingress-controller-base_test.go
  tests/aws-alb-ingress-controller-overlays-application_test.go
  tests/aws-alb-ingress-controller-overlays-vpc_test.go
  tests/aws-efs-csi-driver-base_test.go
  tests/aws-fsx-csi-driver-base_test.go
  tests/centraldashboard-overlays-application_test.go
  tests/cloud-endpoints-overlays-application_test.go
  tests/fluentd-cloud-watch-base_test.go
  tests/gpu-driver-overlays-application_test.go
  tests/iap-ingress-base_test.go
  tests/iap-ingress-overlays-application_test.go
  tests/iap-ingress-overlays-certmanager_test.go
  tests/iap-ingress-overlays-gcp-credentials_test.go
  tests/iap-ingress-overlays-managed-cert_test.go
  tests/istio-base_test.go
  tests/istio-ingress-base_test.go
  tests/istio-ingress-overlays-cognito_test.go
  tests/istio-ingress-overlays-oidc_test.go
  tests/istio-install-base_test.go
  tests/jupyter-web-app-base_test.go
  tests/jupyter-web-app-overlays-application_test.go
  tests/jupyter-web-app-overlays-istio_test.go
  tests/kfserving-crds-base_test.go
  tests/kfserving-crds-overlays-application_test.go
  tests/kfserving-install-overlays-application_test.go
  tests/knative-serving-crds-base_test.go
  tests/knative-serving-crds-overlays-application_test.go
  tests/knative-serving-install-base_test.go
  tests/knative-serving-install-overlays-application_test.go
  tests/kubebench-overlays-application_test.go
  tests/minio-base_test.go
  tests/minio-overlays-application_test.go
  tests/minio-overlays-minioPd_test.go
  tests/mxnet-operator-base_test.go
  tests/mxnet-operator-overlays-application_test.go
  tests/mysql-base_test.go
  tests/mysql-overlays-application_test.go
  tests/mysql-overlays-mysqlPd_test.go
  tests/notebook-controller-overlays-application_test.go
  tests/nvidia-device-plugin-overlays-application_test.go
  tests/persistent-agent-overlays-application_test.go
  tests/pipeline-visualization-service-overlays-application_test.go
  tests/pipelines-runner-overlays-application_test.go
  tests/pipelines-ui-overlays-application_test.go
  tests/pipelines-viewer-overlays-application_test.go
  tests/profiles-base_test.go
  tests/profiles-overlays-application_test.go
  tests/profiles-overlays-debug_test.go
  tests/profiles-overlays-devices_test.go
  tests/profiles-overlays-istio_test.go
  tests/prometheus-base_test.go
  tests/prometheus-overlays-application_test.go
  tests/pytorch-job-crds-overlays-application_test.go
  tests/pytorch-operator-overlays-application_test.go
  tests/scheduledworkflow-overlays-application_test.go
  tests/spartakus-overlays-application_test.go
  tests/webhook-base_test.go
  tests/webhook-overlays-application_test.go
Labels: approved, cla: yes, lgtm, size/XXL

#531 Metadata add readiness probe & reduce replicas#
  metadata/base/metadata-deployment.yaml
  tests/metadata-base_test.go
  tests/metadata-overlays-application_test.go
  tests/metadata-overlays-istio_test.go
Labels: approved, cla: yes, lgtm, size/M

#534 Update labels to v0.7.0
  admission-webhook/bootstrap/overlays/application/application.yaml
  admission-webhook/bootstrap/overlays/application/kustomization.yaml
  admission-webhook/webhook/overlays/application/application.yaml
  admission-webhook/webhook/overlays/application/kustomization.yaml
  application/application/overlays/application/application.yaml
  application/application/overlays/application/kustomization.yaml
  aws/aws-alb-ingress-controller/overlays/application/application.yaml
  aws/aws-alb-ingress-controller/overlays/application/kustomization.yaml
  hack/update-instance-labels.sh
  jupyter/jupyter-web-app/overlays/application/application.yaml
  jupyter/jupyter-web-app/overlays/application/kustomization.yaml
  metadata/overlays/application/application.yaml
  metadata/overlays/application/kustomization.yaml
  mxnet-job/mxnet-operator/overlays/application/application.yaml
  mxnet-job/mxnet-operator/overlays/application/kustomization.yaml
  seldon/seldon-core-operator/overlays/application/kustomization.yaml
  spark/spark-operator/overlays/application/application.yaml
  spark/spark-operator/overlays/application/kustomization.yaml
  tektoncd/tektoncd-dashboard/overlays/application/kustomization.yaml
  tektoncd/tektoncd-install/overlays/application/kustomization.yaml
  tests/application-overlays-application_test.go
  tests/aws-alb-ingress-controller-overlays-application_test.go
  tests/bootstrap-overlays-application_test.go
  tests/jupyter-web-app-overlays-application_test.go
  tests/metadata-overlays-application_test.go
  tests/mxnet-operator-overlays-application_test.go
  tests/seldon-core-operator-overlays-application_test.go
  tests/spark-operator-overlays-application_test.go
  tests/tektoncd-dashboard-overlays-application_test.go
  tests/tektoncd-install-overlays-application_test.go
  tests/webhook-overlays-application_test.go
Labels: approved, cla: yes, lgtm, size/L

#516 Remove katib-manager-rest
  katib/katib-controller/base/katib-manager-rest-deployment.yaml
  katib/katib-controller/base/katib-manager-rest-service.yaml
  katib/katib-controller/base/kustomization.yaml
  tests/katib-controller-base_test.go
  tests/katib-controller-overlays-application_test.go
  tests/katib-controller-overlays-istio_test.go
Labels: approved, cla: yes, lgtm, size/L

#532 go generates invalid tests for platform configs
  hack/gen-test-targets.sh
Labels: approved, cla: yes, lgtm, size/M

#535 Update operator images to 0.7tag
  pytorch-job/pytorch-operator/base/kustomization.yaml
  tests/pytorch-operator-base_test.go
  tests/pytorch-operator-overlays-application_test.go
  tests/tf-job-operator-base_test.go
  tests/tf-job-operator-overlays-application_test.go
  tf-training/tf-job-operator/base/kustomization.yaml
Labels: approved, cla: yes, lgtm, size/S

#493 update profile config to v1beta1
  default-install/base/kustomization.yaml
  default-install/base/params.env
  default-install/base/params.yaml
  default-install/base/profile-instance.yaml
  kfdef/kfctl_gcp_basic_auth.yaml
  kfdef/kfctl_gcp_iap.yaml
  profiles/base/crd.yaml
  profiles/base/deployment.yaml
  profiles/base/kustomization.yaml
  profiles/base/params.env
  profiles/base/params.yaml
  profiles/base/role-binding.yaml
  profiles/base/role.yaml
  profiles/base/service-account.yaml
  tests/default-install-base_test.go
  tests/profiles-base_test.go
  tests/profiles-overlays-application_test.go
  tests/profiles-overlays-debug_test.go
  tests/profiles-overlays-devices_test.go
  tests/profiles-overlays-istio_test.go
Labels: approved, cla: yes, lgtm, size/XXL

#499 [3945] Configurable Istio Gateway for Notebook Controller
  jupyter/notebook-controller/base/kustomization.yaml
  jupyter/notebook-controller/base/params.env
  jupyter/notebook-controller/overlays/istio/deployment.yaml
  jupyter/notebook-controller/overlays/istio/params.env
  tests/notebook-controller-base_test.go
  tests/notebook-controller-overlays-application_test.go
  tests/notebook-controller-overlays-istio_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#541 kubeflow on GCP: create empty GPU pool by default
  gcp/deployment_manager_configs/cluster-kubeflow.yaml
  tests/profiles-overlays-test_test.go
Labels: approved, cla: yes, lgtm, size/L

#523 update instance label for metadata
  application/application/overlays/application/application.yaml
  application/application/overlays/application/kustomization.yaml
  hack/gen-test-targets.sh
  metadata/overlays/application/application.yaml
  metadata/overlays/application/kustomization.yaml
  mxnet-job/mxnet-operator/overlays/application/application.yaml
  mxnet-job/mxnet-operator/overlays/application/kustomization.yaml
  pytorch-job/pytorch-operator/overlays/application/kustomization.yaml
  seldon/seldon-core-operator/overlays/application/kustomization.yaml
  spark/spark-operator/overlays/application/application.yaml
  spark/spark-operator/overlays/application/kustomization.yaml
  tektoncd/tektoncd-dashboard/overlays/application/kustomization.yaml
  tektoncd/tektoncd-install/overlays/application/kustomization.yaml
  tests/application-overlays-application_test.go
  tests/basic-auth-ingress-overlays-application_test.go
  tests/metadata-overlays-application_test.go
  tests/mxnet-operator-overlays-application_test.go
  tests/pytorch-operator-overlays-application_test.go
  tests/seldon-core-operator-overlays-application_test.go
  tests/spark-operator-overlays-application_test.go
  tests/tektoncd-dashboard-overlays-application_test.go
  tests/tektoncd-install-overlays-application_test.go
Labels: approved, cla: yes, lgtm, size/L

#545 Update manifest repos and versions for v0.7
  kfdef/kfctl_anthos.yaml
  kfdef/kfctl_aws.yaml
  kfdef/kfctl_aws_cognito.yaml
  kfdef/kfctl_existing_arrikto.yaml
  kfdef/kfctl_gcp_basic_auth.yaml
  kfdef/kfctl_gcp_iap.yaml
  kfdef/kfctl_k8s_istio.yaml
Labels: approved, cla: yes, lgtm, size/M

#514 Fix alibi explainer configmap
  kfserving/kfserving-install/base/config-map.yaml
  tests/kfserving-install-base_test.go
  tests/kfserving-install-overlays-application_test.go
Labels: approved, cla: yes, lgtm, size/M

#551 Periodically update the JWT policy for IAP.
  gcp/iap-ingress/base/config-map.yaml
  tests/iap-ingress-base_test.go
  tests/iap-ingress-overlays-application_test.go
  tests/iap-ingress-overlays-certmanager_test.go
  tests/iap-ingress-overlays-gcp-credentials_test.go
  tests/iap-ingress-overlays-managed-cert_test.go
Labels: approved, cla: yes, lgtm, size/L

#542 Migrate KfDef to v1beta1
  kfdef/kfctl_gcp_basic_auth.yaml
  kfdef/kfctl_gcp_iap.yaml
  kfdef/kfctl_k8s_istio.yaml
Labels: approved, cla: yes, lgtm, size/L

#552 Automated cherry pick of #551: Periodically update the JWT policy for IAP. Cherry pick of #551 on v0.7-branch. #551: Periodically update the JWT policy for IAP.
  gcp/iap-ingress/base/config-map.yaml
  tests/iap-ingress-base_test.go
  tests/iap-ingress-overlays-application_test.go
  tests/iap-ingress-overlays-certmanager_test.go
  tests/iap-ingress-overlays-gcp-credentials_test.go
  tests/iap-ingress-overlays-managed-cert_test.go
Labels: approved, cla: yes, lgtm, size/L

#555 Update KFServing ONNX version
  kfserving/kfserving-install/base/config-map.yaml
  tests/kfserving-install-base_test.go
  tests/kfserving-install-overlays-application_test.go
Labels: approved, cla: yes, lgtm, size/S

#556 Cherry pick kfdef v1beta1 for gcp
  kfdef/kfctl_gcp_basic_auth.0.7.0.yaml
  kfdef/kfctl_gcp_iap.0.7.0.yaml
  kfdef/kfctl_k8s_istio.0.7.0.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#559 Remove not versioned kfdef from release
  kfdef/kfctl_gcp_basic_auth.yaml
  kfdef/kfctl_gcp_iap.yaml
  kfdef/kfctl_k8s_istio.yaml
  prow_config.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#549 existing_arrikto: add cert-manager
  admission-webhook/webhook/overlays/cert-manager/certificate.yaml
  admission-webhook/webhook/overlays/cert-manager/deployment.yaml
  admission-webhook/webhook/overlays/cert-manager/kustomization.yaml
  admission-webhook/webhook/overlays/cert-manager/mutating-webhook-configuration.yaml
  admission-webhook/webhook/overlays/cert-manager/params.env
  admission-webhook/webhook/overlays/cert-manager/params.yaml
  kfdef/kfctl_existing_arrikto.yaml
  tests/webhook-overlays-cert-manager_test.go
Labels: approved, cla: yes, lgtm, size/XL

#553 Migrate Kfdef to v1beta1
  kfdef/kfctl_anthos.yaml
  kfdef/kfctl_aws.yaml
  kfdef/kfctl_aws_cognito.yaml
  kfdef/kfctl_existing_arrikto.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#518 Add application name for seldon and mpi-operator
  kfdef/kfctl_aws.yaml
  kfdef/kfctl_aws_cognito.yaml
Labels: approved, cla: yes, lgtm, size/XS

#569 Sync configmap changes from kfserving repo
  kfserving/kfserving-install/base/config-map.yaml
  tests/kfserving-install-base_test.go
  tests/kfserving-install-overlays-application_test.go
Labels: approved, cla: yes, lgtm, size/M

#567 [aws] Clean up istio gateway and virtual services.
  aws/istio-ingress/base/ingress.yaml
  aws/istio-ingress/base/istio-gateway.yaml
  aws/istio-ingress/base/istio-policy.yaml
  aws/istio-ingress/base/istio-virutal-service.yaml
  aws/istio-ingress/base/kustomization.yaml
  aws/istio-ingress/overlays/cognito/ingress.yaml
  aws/istio-ingress/overlays/oidc/ingress.yaml
  tests/istio-ingress-base_test.go
  tests/istio-ingress-overlays-cognito_test.go
  tests/istio-ingress-overlays-oidc_test.go
Labels: approved, cla: yes, lgtm, size/L

#572 Cherry pick #518 #567 to v0.7-branch
  aws/istio-ingress/base/ingress.yaml
  aws/istio-ingress/base/istio-gateway.yaml
  aws/istio-ingress/base/istio-policy.yaml
  aws/istio-ingress/base/istio-virutal-service.yaml
  aws/istio-ingress/base/kustomization.yaml
  aws/istio-ingress/overlays/cognito/ingress.yaml
  aws/istio-ingress/overlays/oidc/ingress.yaml
  kfdef/kfctl_aws.0.7.0.yaml
  kfdef/kfctl_aws_cognito.0.7.0.yaml
  tests/istio-ingress-base_test.go
  tests/istio-ingress-overlays-cognito_test.go
  tests/istio-ingress-overlays-oidc_test.go
Labels: approved, cla: yes, lgtm, size/L

#571 kfdef: existing_arrikto: add v0.7.0 config
  kfdef/kfctl_existing_arrikto.0.7.0.yaml
Labels: approved, cla: yes, lgtm, size/XS

#574 update profile API
  profiles/base/crd.yaml
  profiles/base/kustomization.yaml
  tests/profiles-base_test.go
  tests/profiles-overlays-application_test.go
  tests/profiles-overlays-debug_test.go
  tests/profiles-overlays-devices_test.go
  tests/profiles-overlays-istio_test.go
  tests/profiles-overlays-test_test.go
Labels: approved, cla: yes, lgtm, size/M

#573 reset backend name
  gcp/iap-ingress/base/config-map.yaml
  tests/iap-ingress-base_test.go
  tests/iap-ingress-overlays-application_test.go
  tests/iap-ingress-overlays-certmanager_test.go
  tests/iap-ingress-overlays-gcp-credentials_test.go
  tests/iap-ingress-overlays-managed-cert_test.go
Labels: approved, cla: yes, lgtm, size/M

#570 Update centraldashboard image to fix issue with 2 profiles being created by registration
  common/centraldashboard/base/deployment.yaml
  common/centraldashboard/base/kustomization.yaml
  tests/centraldashboard-base_test.go
  tests/centraldashboard-overlays-application_test.go
  tests/centraldashboard-overlays-istio_test.go
Labels: approved, cla: yes, lgtm, size/S

#562 Configures Istio Gateway to serve through port 443 for HTTPS
  istio/istio/overlays/https-gateway/kf-istio-resources.yaml
  istio/istio/overlays/https-gateway/kustomization.yaml
  istio/istio/overlays/https-gateway/params.env
  istio/istio/overlays/https-gateway/params.yaml
  tests/istio-overlays-https-gateway_test.go
Labels: approved, cla: yes, lgtm, size/L

#575 Automated cherry pick of #570: Update centraldashboard image to fix issue with 2 profiles Cherry pick of #570 on v0.7-branch. #570: Update centraldashboard image to fix issue with 2 profiles
  common/centraldashboard/base/deployment.yaml
  common/centraldashboard/base/kustomization.yaml
  tests/centraldashboard-base_test.go
  tests/centraldashboard-overlays-application_test.go
  tests/centraldashboard-overlays-istio_test.go
Labels: approved, cla: yes, lgtm, size/S

#362 Adds self sigining cert to dex-ingress
  istio/ingressgateway-self-signed-cert/base/certificate.yaml
  istio/ingressgateway-self-signed-cert/base/kustomization.yaml
  istio/ingressgateway-self-signed-cert/base/params.env
  istio/ingressgateway-self-signed-cert/base/params.yaml
  tests/ingressgateway-self-signed-cert-base_test.go
Labels: approved, cla: yes, lgtm, size/L

#577 Unpin from GKE 1.14.6-gke.2; 1.14.6 is no longer a valid master.
  gcp/deployment_manager_configs/cluster-kubeflow.yaml
Labels: approved, cla: yes, lgtm, size/XS

#576 Fix KFServing preventing notebook (and other pods) form starting.
  gcp/deployment_manager_configs/cluster-kubeflow.yaml
  kfserving/kfserving-install/base/kustomization.yaml
  kfserving/kfserving-install/base/statefulset.yaml
  tests/kfserving-install-base_test.go
  tests/kfserving-install-overlays-application_test.go
Labels: approved, cla: yes, lgtm, size/S

#578 update profile API (#574)
  profiles/base/crd.yaml
  profiles/base/kustomization.yaml
  tests/profiles-base_test.go
  tests/profiles-overlays-application_test.go
  tests/profiles-overlays-debug_test.go
  tests/profiles-overlays-devices_test.go
  tests/profiles-overlays-istio_test.go
  tests/profiles-overlays-test_test.go
Labels: approved, cla: yes, lgtm, size/S

#223 Fix and update Kubebench manifests
  kubebench/base/cluster-role-binding.yaml
  kubebench/base/cluster-role.yaml
  kubebench/base/config-map.yaml
  kubebench/base/crd.yaml
  kubebench/base/deployment.yaml
  kubebench/base/kustomization.yaml
  kubebench/base/service-account.yaml
  tests/kubebench-base_test.go
  tests/kubebench-overlays-application_test.go
  tests/kubebench-overlays-istio_test.go
Labels: approved, cla: yes, lgtm, size/L

#580 [0.7] chore: Use v0.7.0 in Katib
  katib/katib-controller/base/katib-configmap.yaml
  katib/katib-controller/base/kustomization.yaml
  tests/katib-controller-base_test.go
  tests/katib-controller-overlays-application_test.go
  tests/katib-controller-overlays-istio_test.go
Labels: approved, cla: yes, lgtm, size/M

#582 [chore] Cherry-pick #580 to v0.7-branch
  katib/katib-controller/base/katib-configmap.yaml
  katib/katib-controller/base/kustomization.yaml
  tests/katib-controller-base_test.go
  tests/katib-controller-overlays-application_test.go
  tests/katib-controller-overlays-istio_test.go
Labels: approved, cla: yes, lgtm, size/M

#586 Update deployments to use `apps/v1` api version
  metadata/base/metadata-envoy-deployment.yaml
  tests/metadata-base_test.go
  tests/metadata-overlays-application_test.go
  tests/metadata-overlays-istio_test.go
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#584 Fix multiple overlays as title
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#588 Automated cherry pick of #586: Update deployments to use `apps/v1` api version on v0.7-branch.
  metadata/base/metadata-envoy-deployment.yaml
  tests/metadata-base_test.go
  tests/metadata-overlays-application_test.go
  tests/metadata-overlays-istio_test.go
Labels: approved, cla: yes, lgtm, size/XS

#589 update central dashboard image
  common/centraldashboard/base/kustomization.yaml
  tests/centraldashboard-base_test.go
  tests/centraldashboard-overlays-application_test.go
  tests/centraldashboard-overlays-istio_test.go
Labels: approved, cla: yes, lgtm, size/XS

#590 Automated cherry pick of #589: update central dashboard image for kubeflow/kubeflow#4415
  common/centraldashboard/base/kustomization.yaml
  tests/centraldashboard-base_test.go
  tests/centraldashboard-overlays-application_test.go
  tests/centraldashboard-overlays-istio_test.go
Labels: approved, cla: yes, lgtm, size/XS

#583 Add self to appropriate OWNERS files
  OWNERS
  cert-manager/OWNERS
  dex-auth/OWNERS
  istio/OWNERS
  kubeflow-roles/OWNERS
Labels: approved, cla: yes, lgtm, size/S
