Repository kubeflow/manifests, pull requests merged in 2019-06, with the labels that each got.

#107 Add config for MySQL used by metadata service
  metadata/base/kustomization.yaml
  metadata/base/metadata-db-deployment.yaml
  metadata/base/metadata-db-pvc.yaml
  metadata/base/metadata-db-secret.yaml
  metadata/base/metadata-db-service.yaml
  metadata/base/metadata-deployment.yaml
  tests/metadata-base_test.go
Labels: approved, lgtm, size/L

#67 add application-controller and application overlays (disabled by default)
  application/base/application.yaml
  application/base/cluster-role-binding.yaml
  application/base/cluster-role.yaml
  application/base/crd.yaml
  application/base/kustomization.yaml
  application/base/service-account.yaml
  application/base/service.yaml
  application/base/stateful-set.yaml
  application/overlays/debug/kustomization.yaml
  application/overlays/debug/params.env
  application/overlays/debug/params.yaml
  application/overlays/debug/stateful-set.yaml
  hack/gen-test-targets.sh
  hack/kustomize/plugin/kfdef.apps.kubeflow.org/v1alpha1/KfDef
  jupyter/jupyter-web-app/overlays/application/application.yaml
  jupyter/jupyter-web-app/overlays/application/kustomization.yaml
  metacontroller/base/crd.yaml
  plugins/kustomize/plugin/kfdef.apps.kubeflow.org/v1alpha1/KfDef
  tests/Makefile
  tests/application-base_test.go
  tests/application-overlays-debug_test.go
  tests/jupyter-web-app-overlays-application_test.go
  tests/metacontroller-base_test.go
Labels: approved, lgtm, size/XXL

#89 Validate generated yamls prior to adding automated validation tests
  admission-webhook/bootstrap/base/params.yaml
  admission-webhook/bootstrap/base/stateful-set.yaml
  gcp/basic-auth-ingress/base/stateful-set.yaml
  jupyter/jupyter/base/stateful-set.yaml
  jupyter/jupyter/overlays/minikube/stateful-set.yaml
  kubebench/base/deployment.yaml
  tests/basic-auth-ingress-base_test.go
  tests/bootstrap-base_test.go
  tests/jupyter-base_test.go
  tests/jupyter-overlays-minikube_test.go
  tests/kubebench-base_test.go
Labels: approved, lgtm, size/M

#108 Update Argo version to v2.3.0
  argo/base/deployment.yaml
  argo/base/kustomization.yaml
  argo/base/params.env
  tests/argo-base_test.go
Labels: approved, lgtm, size/S

#110 Add Prometheus annotations and port configurations to tf-training kus…
  tests/tf-job-operator-base_test.go
  tf-training/tf-job-operator/base/deployment.yaml
  tf-training/tf-job-operator/base/service.yaml
Labels: approved, lgtm, size/M

#114 Update kubebench for v1alpha2
  kubebench/base/config-map.yaml
  kubebench/base/deployment.yaml
  kubebench/base/kustomization.yaml
  kubebench/base/role-binding.yaml
  kubebench/base/role.yaml
  kubebench/base/service-account.yaml
  kubebench/base/service.yaml
  kubebench/base/workflow.yaml
  tests/kubebench-base_test.go
  tests/kubebench-overlays-istio_test.go
Labels: approved, lgtm, size/XXL

#125 Adding monitoring config to manifests
  pytorch-job/pytorch-job-crds/base/crd.yaml
  pytorch-job/pytorch-operator/base/deployment.yaml
  pytorch-job/pytorch-operator/base/kustomization.yaml
  pytorch-job/pytorch-operator/base/service.yaml
  tests/pytorch-job-crds-base_test.go
  tests/pytorch-operator-base_test.go
Labels: approved, lgtm, size/M

#128 Reorganize katib v1alpha1 packages
  katib-v1alpha1/katib-ui/base/katib-ui-deployment.yaml
  katib-v1alpha1/katib-ui/base/katib-ui-rbac.yaml
  katib-v1alpha1/katib-ui/base/katib-ui-service.yaml
  katib-v1alpha1/katib-ui/base/kustomization.yaml
  katib-v1alpha1/katib-ui/base/params.env
  katib-v1alpha1/katib-ui/overlays/istio/katib-ui-virtual-service.yaml
  katib-v1alpha1/katib-ui/overlays/istio/kustomization.yaml
  katib-v1alpha1/katib-ui/overlays/istio/params.yaml
  katib-v1alpha1/metrics-collector/base/kustomization.yaml
  katib-v1alpha1/metrics-collector/base/metrics-collector-rbac.yaml
  katib-v1alpha1/metrics-collector/base/metrics-collector-template-configmap.yaml
  katib-v1alpha1/studyjob/base/kustomization.yaml
  katib-v1alpha1/studyjob/base/studyjob-controller-deployment.yaml
  katib-v1alpha1/studyjob/base/studyjob-crd.yaml
  katib-v1alpha1/studyjob/base/studyjob-rbac.yaml
  katib-v1alpha1/studyjob/base/studyjob-service.yaml
  katib-v1alpha1/studyjob/base/studyjob-worker-template.yaml
  katib-v1alpha1/suggestion/base/kustomization.yaml
  katib-v1alpha1/suggestion/base/suggestion-bayesianoptimization-deployment.yaml
  katib-v1alpha1/suggestion/base/suggestion-bayesianoptimization-service.yaml
  katib-v1alpha1/suggestion/base/suggestion-grid-deployment.yaml
  katib-v1alpha1/suggestion/base/suggestion-grid-service.yaml
  katib-v1alpha1/suggestion/base/suggestion-hyperband-deployment.yaml
  katib-v1alpha1/suggestion/base/suggestion-hyperband-service.yaml
  katib-v1alpha1/suggestion/base/suggestion-nasrl-deployment.yaml
  katib-v1alpha1/suggestion/base/suggestion-nasrl-service.yaml
  katib-v1alpha1/suggestion/base/suggestion-random-deployment.yaml
  katib-v1alpha1/suggestion/base/suggestion-random-service.yaml
  katib-v1alpha1/vizier-core/base/kustomization.yaml
  katib-v1alpha1/vizier-core/base/vizier-core-deployment.yaml
  katib-v1alpha1/vizier-core/base/vizier-core-rbac.yaml
  katib-v1alpha1/vizier-core/base/vizier-core-rest-deployment.yaml
  katib-v1alpha1/vizier-core/base/vizier-core-rest-service.yaml
  katib-v1alpha1/vizier-core/base/vizier-core-service.yaml
  katib-v1alpha1/vizier-db/base/kustomization.yaml
  katib-v1alpha1/vizier-db/base/vizier-db-deployment.yaml
  katib-v1alpha1/vizier-db/base/vizier-db-pvc.yaml
  katib-v1alpha1/vizier-db/base/vizier-db-secret.yaml
  katib-v1alpha1/vizier-db/base/vizier-db-service.yaml
  katib/base/kustomization.yaml
  tests/katib-base_test.go
  tests/katib-overlays-istio_test.go
  tests/katib-v1alpha1-metrics-collector-base_test.go
  tests/katib-v1alpha1-studyjob-base_test.go
  tests/katib-v1alpha1-suggestion-base_test.go
  tests/katib-v1alpha1-ui-base_test.go
  tests/katib-v1alpha1-ui-overlays-istio_test.go
  tests/katib-v1alpha1-vizier-core-base_test.go
  tests/katib-v1alpha1-vizier-db-base_test.go
Labels: approved, lgtm, size/XXL

#129 Fix error in ingress component
  gcp/iap-ingress/base/cloud-endpoint.yaml
  gcp/iap-ingress/base/config-map.yaml
  gcp/iap-ingress/base/kustomization.yaml
  gcp/iap-ingress/base/params.env
  tests/iap-ingress-base_test.go
Labels: approved, lgtm, size/M

#134 Remove admission-webhook/bootstrap hard-coded selector
  admission-webhook/bootstrap/base/stateful-set.yaml
  tests/bootstrap-base_test.go
  tests/katib-ui-base_test.go
  tests/katib-ui-overlays-istio_test.go
  tests/metrics-collector-base_test.go
  tests/studyjob-base_test.go
  tests/suggestion-base_test.go
  tests/vizier-core-base_test.go
  tests/vizier-db-base_test.go
Labels: approved, lgtm, size/M

#131 Katib v1alpha2 kustomize package
  katib-v1alpha2/katib-controller/base/experiment-crd.yaml
  katib-v1alpha2/katib-controller/base/katib-controller-deployment.yaml
  katib-v1alpha2/katib-controller/base/katib-controller-rbac.yaml
  katib-v1alpha2/katib-controller/base/katib-controller-secret.yaml
  katib-v1alpha2/katib-controller/base/katib-controller-service.yaml
  katib-v1alpha2/katib-controller/base/kustomization.yaml
  katib-v1alpha2/katib-controller/base/trial-crd.yaml
  katib-v1alpha2/katib-controller/base/trial-template.yaml
  katib-v1alpha2/katib-db/base/katib-db-deployment.yaml
  katib-v1alpha2/katib-db/base/katib-db-pvc.yaml
  katib-v1alpha2/katib-db/base/katib-db-secret.yaml
  katib-v1alpha2/katib-db/base/katib-db-service.yaml
  katib-v1alpha2/katib-db/base/kustomization.yaml
  katib-v1alpha2/katib-manager/base/katib-manager-deployment.yaml
  katib-v1alpha2/katib-manager/base/katib-manager-rest-deployment.yaml
  katib-v1alpha2/katib-manager/base/katib-manager-rest-service.yaml
  katib-v1alpha2/katib-manager/base/katib-manager-service.yaml
  katib-v1alpha2/katib-manager/base/kustomization.yaml
  katib-v1alpha2/katib-ui/base/katib-ui-deployment.yaml
  katib-v1alpha2/katib-ui/base/katib-ui-rbac.yaml
  katib-v1alpha2/katib-ui/base/katib-ui-service.yaml
  katib-v1alpha2/katib-ui/base/kustomization.yaml
  katib-v1alpha2/katib-ui/base/params.env
  katib-v1alpha2/katib-ui/base/params.yaml
  katib-v1alpha2/katib-ui/overlays/istio/katib-ui-virtual-service.yaml
  katib-v1alpha2/katib-ui/overlays/istio/kustomization.yaml
  katib-v1alpha2/katib-ui/overlays/istio/params.yaml
  katib-v1alpha2/metrics-collector/base/kustomization.yaml
  katib-v1alpha2/metrics-collector/base/metrics-collector-rbac.yaml
  katib-v1alpha2/metrics-collector/base/metrics-collector-template-configmap.yaml
  katib-v1alpha2/suggestion/base/kustomization.yaml
  katib-v1alpha2/suggestion/base/suggestion-bayesianoptimization-deployment.yaml
  katib-v1alpha2/suggestion/base/suggestion-bayesianoptimization-service.yaml
  katib-v1alpha2/suggestion/base/suggestion-grid-deployment.yaml
  katib-v1alpha2/suggestion/base/suggestion-grid-service.yaml
  katib-v1alpha2/suggestion/base/suggestion-hyperband-deployment.yaml
  katib-v1alpha2/suggestion/base/suggestion-hyperband-service.yaml
  katib-v1alpha2/suggestion/base/suggestion-nasrl-deployment.yaml
  katib-v1alpha2/suggestion/base/suggestion-nasrl-service.yaml
  katib-v1alpha2/suggestion/base/suggestion-random-deployment.yaml
  katib-v1alpha2/suggestion/base/suggestion-random-service.yaml
  tests/katib-v1alpha2-controller-base_test.go
  tests/katib-v1alpha2-db-base_test.go
  tests/katib-v1alpha2-manager-base_test.go
  tests/katib-v1alpha2-metrics-collector-base_test.go
  tests/katib-v1alpha2-suggestion-base_test.go
  tests/katib-v1alpha2-ui-base_test.go
  tests/katib-v1alpha2-ui-overlays-istio_test.go
Labels: approved, lgtm, size/XXL

#141 fix jwt validation
  gcp/iap-ingress/base/policy.yaml
  tests/iap-ingress-base_test.go
Labels: approved, lgtm, size/XS

#148 fix for master on generate error
  pipeline/minio/base/kustomization.yaml
  pipeline/minio/overlays/minioPd/kustomization.yaml
  pipeline/minio/overlays/minioPd/persistent-volume-claim.yaml
  pipeline/mysql/base/kustomization.yaml
  pipeline/mysql/overlays/mysqlPd/kustomization.yaml
  pipeline/mysql/overlays/mysqlPd/persistent-volume-claim.yaml
  tests/minio-base_test.go
  tests/minio-overlays-minioPd_test.go
  tests/mysql-base_test.go
  tests/mysql-overlays-mysqlPd_test.go
  tests/notebook-controller-overlays-application_test.go
Labels: approved, lgtm, size/L

#149 add kfam API to manifests
  profiles/base/deployment.yaml
  profiles/base/kustomization.yaml
  profiles/base/params.env
  profiles/base/params.yaml
  profiles/base/service.yaml
  profiles/overlays/istio/kustomization.yaml
  profiles/overlays/istio/params.yaml
  profiles/overlays/istio/virtual-service.yaml
  tests/profiles-base_test.go
  tests/profiles-overlays-debug_test.go
  tests/profiles-overlays-devices_test.go
  tests/scripts/run-tests.sh
Labels: approved, lgtm, size/L

#154 quick fix
  profiles/base/kustomization.yaml
  profiles/overlays/istio/kustomization.yaml
Labels: approved, lgtm, size/XS

#150 Partial Revert "Remove admission-webhook/bootstrap hard-coded selector"
  tests/katib-v1alpha1-metrics-collector-base_test.go
  tests/katib-v1alpha1-studyjob-base_test.go
  tests/katib-v1alpha1-suggestion-base_test.go
  tests/katib-v1alpha1-ui-base_test.go
  tests/katib-v1alpha1-ui-overlays-istio_test.go
  tests/katib-v1alpha1-vizier-core-base_test.go
  tests/katib-v1alpha1-vizier-db-base_test.go
Labels: approved, lgtm, size/M

#155 fix istio virtual service mismatch
  jupyter/jupyter-web-app/overlays/istio/virtual-service.yaml
  pipeline/pipelines-ui/overlays/istio/virtual-service.yaml
  tests/jupyter-web-app-overlays-istio_test.go
  tests/pipelines-ui-overlays-istio_test.go
Labels: approved, lgtm, size/XS

#142 TFJob application CR
  tests/tf-job-operator-overlays-application_test.go
  tf-training/tf-job-operator/overlays/application/application.yaml
  tf-training/tf-job-operator/overlays/application/kustomization.yaml
Labels: approved, lgtm, size/XL

#156 Prof crd mismatch
  profiles/base/crd.yaml
  profiles/base/deployment.yaml
  tests/profiles-base_test.go
  tests/profiles-overlays-debug_test.go
  tests/profiles-overlays-devices_test.go
Labels: approved, lgtm, size/M

#157 update jupyter webapp image
  jupyter/jupyter-web-app/base/kustomization.yaml
  tests/jupyter-web-app-base_test.go
  tests/jupyter-web-app-overlays-application_test.go
  tests/jupyter-web-app-overlays-istio_test.go
Labels: approved, lgtm, size/XS

#158 sync manifests with ksonnet config
  admission-webhook/webhook/base/deployment.yaml
  admission-webhook/webhook/base/kustomization.yaml
  common/basic-auth/base/gatekeeper-deployment.yaml
  common/basic-auth/base/kflogin-deployment.yaml
  gcp/istio/base/kf-istio-resources.yaml
  jupyter/jupyter-web-app/base/service-account.yaml
  jupyter/notebook-controller/base/deployment.yaml
  tests/basic-auth-base_test.go
  tests/basic-auth-overlays-istio_test.go
  tests/istio-base_test.go
  tests/jupyter-web-app-base_test.go
  tests/jupyter-web-app-overlays-application_test.go
  tests/jupyter-web-app-overlays-istio_test.go
  tests/notebook-controller-base_test.go
  tests/notebook-controller-overlays-application_test.go
  tests/notebook-controller-overlays-istio_test.go
  tests/webhook-base_test.go
Labels: approved, lgtm, size/M

#159 Include cluster role configs for Central Dashboard
  common/centraldashboard/base/kustomization.yaml
  tests/centraldashboard-base_test.go
  tests/centraldashboard-overlays-istio_test.go
Labels: approved, lgtm, size/M

#161 Pointing to the metadata-db service in kubeflow namespace
  metadata/base/metadata-deployment.yaml
  tests/metadata-base_test.go
Labels: approved, lgtm, size/S

#160 OWNERS: add yanniszark
  OWNERS
Labels: approved, lgtm, size/XS

#163 jupyter-web-app: Update the manifests
  jupyter/jupyter-web-app/base/config-map.yaml
  tests/jupyter-web-app-base_test.go
  tests/jupyter-web-app-overlays-application_test.go
  tests/jupyter-web-app-overlays-istio_test.go
Labels: approved, lgtm, size/XL

#165 Update jupyter web-app image
  jupyter/jupyter-web-app/base/kustomization.yaml
  tests/jupyter-web-app-base_test.go
  tests/jupyter-web-app-overlays-application_test.go
  tests/jupyter-web-app-overlays-istio_test.go
Labels: approved, lgtm, size/XS

#162 update profile image
  profiles/base/kustomization.yaml
  tests/iap-ingress-base_test.go
  tests/minio-base_test.go
  tests/minio-overlays-minioPd_test.go
  tests/mysql-base_test.go
  tests/mysql-overlays-mysqlPd_test.go
  tests/profiles-base_test.go
  tests/profiles-overlays-debug_test.go
  tests/profiles-overlays-devices_test.go
  tests/profiles-overlays-istio_test.go
Labels: approved, lgtm, size/M

#170 Notebook controller fix
  jupyter/notebook-controller/base/kustomization.yaml
  pipeline/pipelines-viewer/base/kustomization.yaml
  pipeline/pipelines-viewer/base/params.env
  pipeline/pipelines-viewer/base/params.yaml
  tests/iap-ingress-base_test.go
  tests/minio-base_test.go
  tests/minio-overlays-minioPd_test.go
  tests/mysql-base_test.go
  tests/mysql-overlays-mysqlPd_test.go
  tests/notebook-controller-base_test.go
  tests/notebook-controller-overlays-application_test.go
  tests/notebook-controller-overlays-istio_test.go
  tests/pipelines-viewer-base_test.go
  tests/profiles-base_test.go
  tests/profiles-overlays-debug_test.go
  tests/profiles-overlays-devices_test.go
  tests/profiles-overlays-istio_test.go
Labels: approved, lgtm, size/M

#168 Update metadata image to v0.1.5
  metadata/base/metadata-deployment.yaml
  metadata/base/metadata-service.yaml
  tests/metadata-base_test.go
Labels: approved, lgtm, size/M

#175 jupyter-web-app: Update the image tag
  jupyter/jupyter-web-app/base/kustomization.yaml
  tests/jupyter-web-app-base_test.go
  tests/jupyter-web-app-overlays-application_test.go
  tests/jupyter-web-app-overlays-istio_test.go
  tests/metadata-base_test.go
Labels: approved, lgtm, size/S

#166 update central dashboard
  common/centraldashboard/base/kustomization.yaml
  tests/centraldashboard-base_test.go
  tests/centraldashboard-overlays-istio_test.go
Labels: approved, area/front-end, lgtm, size/XS

#182 add centraldashboard application
  common/centraldashboard/overlays/application/application.yaml
  common/centraldashboard/overlays/application/kustomization.yaml
  tests/centraldashboard-overlays-application_test.go
Labels: approved, lgtm, size/L

#185 add IronPan to the approver list
  OWNERS
Labels: approved, lgtm, size/XS

#36 add seldon
  seldon/README.md
  seldon/seldon-core-operator/base/clusterrole.yaml
  seldon/seldon-core-operator/base/crd.yaml
  seldon/seldon-core-operator/base/kustomization.yaml
  seldon/seldon-core-operator/base/rolebinding.yaml
  seldon/seldon-core-operator/base/secret.yaml
  seldon/seldon-core-operator/base/service-account.yaml
  seldon/seldon-core-operator/base/service.yaml
  seldon/seldon-core-operator/base/statefulset.yaml
  seldon/seldon-core-operator/overlays/application/application.yaml
  seldon/seldon-core-operator/overlays/application/kustomization.yaml
  seldon/values.yaml
Labels: approved, lgtm, size/XXL

#184 Update KFP manifests to use v0.1.23
  pipeline/api-service/base/deployment.yaml
  pipeline/api-service/base/kustomization.yaml
  pipeline/persistent-agent/base/deployment.yaml
  pipeline/persistent-agent/base/kustomization.yaml
  pipeline/pipelines-ui/base/deployment.yaml
  pipeline/pipelines-ui/base/kustomization.yaml
  pipeline/pipelines-viewer/base/deployment.yaml
  pipeline/pipelines-viewer/base/kustomization.yaml
  pipeline/scheduledworkflow/base/deployment.yaml
  pipeline/scheduledworkflow/base/kustomization.yaml
  tests/api-service-base_test.go
  tests/persistent-agent-base_test.go
  tests/pipelines-ui-base_test.go
  tests/pipelines-ui-overlays-istio_test.go
  tests/pipelines-viewer-base_test.go
  tests/scheduledworkflow-base_test.go
Labels: approved, lgtm, size/M

#187 add prometheus monitoring components
  gcp/prometheus/base/kustomization.yaml
  gcp/prometheus/base/params.env
  gcp/prometheus/base/params.yaml
  gcp/prometheus/base/prometheus.yaml
  tests/iap-ingress-base_test.go
  tests/minio-base_test.go
  tests/minio-overlays-minioPd_test.go
  tests/mysql-base_test.go
  tests/mysql-overlays-mysqlPd_test.go
  tests/profiles-base_test.go
  tests/profiles-overlays-debug_test.go
  tests/profiles-overlays-devices_test.go
  tests/profiles-overlays-istio_test.go
  tests/prometheus-base_test.go
Labels: approved, lgtm, size/XL

#186 Update pipeline-runner permissions
  pipeline/pipelines-runner/base/cluster-role.yaml
  tests/pipelines-runner-base_test.go
Labels: approved, lgtm, size/S
