Repository kubeflow/manifests, pull requests merged in 2019-08, with the labels that each got.

#249 Fix presubmit
  prow_config.yaml
  tests/workflows/components/kfctl_go_test.jsonnet
  tests/workflows/components/params.libsonnet
Labels: approved, lgtm, size/XS

#250 Fix Pytorch operator application
  pytorch-job/pytorch-operator/overlays/application/application.yaml
  pytorch-job/pytorch-operator/overlays/application/kustomization.yaml
  tests/pytorch-operator-overlays-application_test.go
Labels: approved, lgtm, size/M

#254 add missing selector to metadata-deployment
  metadata/base/metadata-deployment.yaml
  tests/metadata-base_test.go
  tests/metadata-overlays-istio_test.go
Labels: approved, lgtm, needs-ok-to-test, size/XS

#257 fix routing under basic auth mode
  gcp/basic-auth-ingress/base/kustomization.yaml
  tests/basic-auth-ingress-base_test.go
  tests/basic-auth-ingress-overlays-gcp-credentials_test.go
Labels: approved, lgtm, size/M

#248 Kustomize package for mpi-operator (v1alpha1)
  mpi-job/mpi-operator/base/cluster-role-binding.yaml
  mpi-job/mpi-operator/base/cluster-role.yaml
  mpi-job/mpi-operator/base/crd.yaml
  mpi-job/mpi-operator/base/deployment.yaml
  mpi-job/mpi-operator/base/kustomization.yaml
  mpi-job/mpi-operator/base/params.env
  mpi-job/mpi-operator/base/service-account.yaml
  mpi-job/mpi-operator/overlays/application/application.yaml
  mpi-job/mpi-operator/overlays/application/kustomization.yaml
  tests/mpi-operator-base_test.go
  tests/mpi-operator-overlays-application_test.go
Labels: approved, lgtm, size/XL

#258 Add zhenghuiwang to OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#262 Cp062
  gcp/basic-auth-ingress/base/kustomization.yaml
  tests/basic-auth-ingress-base_test.go
  tests/metadata-base_test.go
  tests/metadata-overlays-istio_test.go
Labels: approved, lgtm, size/M

#263 update centraldashboard image
  common/centraldashboard/base/kustomization.yaml
  tests/centraldashboard-base_test.go
  tests/centraldashboard-overlays-application_test.go
  tests/centraldashboard-overlays-istio_test.go
Labels: approved, lgtm, size/XS

#265 update centraldashboard image (#263)
  common/centraldashboard/base/kustomization.yaml
  tests/centraldashboard-base_test.go
  tests/centraldashboard-overlays-application_test.go
  tests/centraldashboard-overlays-istio_test.go
Labels: approved, lgtm, size/XS

#269 Update image to 9419d4d
  jupyter/jupyter-web-app/base/kustomization.yaml
  tests/aws-alb-ingress-controller-base_test.go
  tests/aws-alb-ingress-controller-overlays-vpc_test.go
  tests/aws-efs-csi-driver-base_test.go
  tests/aws-fsx-csi-driver-base_test.go
  tests/basic-auth-ingress-overlays-gcp-credentials_test.go
  tests/cloud-endpoints-overlays-gcp-credentials_test.go
  tests/fluentd-cloud-watch-base_test.go
  tests/iap-ingress-base_test.go
  tests/iap-ingress-overlays-certmanager_test.go
  tests/iap-ingress-overlays-gcp-credentials_test.go
  tests/iap-ingress-overlays-managed-cert_test.go
  tests/istio-ingress-base_test.go
  tests/istio-ingress-overlays-cognito_test.go
  tests/istio-ingress-overlays-oidc_test.go
  tests/jupyter-web-app-base_test.go
  tests/jupyter-web-app-overlays-application_test.go
  tests/jupyter-web-app-overlays-istio_test.go
  tests/minio-base_test.go
  tests/minio-overlays-minioPd_test.go
  tests/mysql-base_test.go
  tests/mysql-overlays-mysqlPd_test.go
  tests/nvidia-device-plugin-base_test.go
  tests/profiles-base_test.go
  tests/profiles-overlays-debug_test.go
  tests/profiles-overlays-devices_test.go
  tests/profiles-overlays-istio_test.go
  tests/prometheus-base_test.go
Labels: approved, lgtm, size/L

#278 Fix gcp credential
  gcp/basic-auth-ingress/overlays/gcp-credentials/kustomization.yaml
  gcp/cloud-endpoints/overlays/gcp-credentials/kustomization.yaml
  gcp/iap-ingress/overlays/gcp-credentials/kustomization.yaml
  tests/basic-auth-ingress-overlays-gcp-credentials_test.go
  tests/cloud-endpoints-overlays-gcp-credentials_test.go
  tests/iap-ingress-base_test.go
  tests/iap-ingress-overlays-certmanager_test.go
  tests/iap-ingress-overlays-gcp-credentials_test.go
  tests/iap-ingress-overlays-managed-cert_test.go
Labels: approved, lgtm, size/M

#259 Add containerRuntimeExecutor field for other argo executors
  argo/base/config-map.yaml
  argo/base/kustomization.yaml
  argo/base/params.env
  tests/argo-base_test.go
  tests/argo-overlays-istio_test.go
Labels: approved, lgtm, ok-to-test, size/S

#261 add selector for application controller StatefulSet
  application/application/base/stateful-set.yaml
  tests/application-base_test.go
  tests/application-overlays-application_test.go
  tests/application-overlays-debug_test.go
Labels: approved, lgtm, ok-to-test, size/S

#280 Automated cherry pick of #269: Update image to 9419d4d Cherry pick of #269 on v0.6-branch. #269: Update image to 9419d4d
  jupyter/jupyter-web-app/base/kustomization.yaml
  tests/jupyter-web-app-base_test.go
  tests/jupyter-web-app-overlays-application_test.go
  tests/jupyter-web-app-overlays-istio_test.go
Labels: approved, cla: yes, lgtm, size/XS

#195 Kubeflow On-Premise Authentication and Authorization Prototype
  common/dex-auth/README.md
  common/dex-auth/dex-authenticator/base/config-map.yaml
  common/dex-auth/dex-authenticator/base/deployment.yaml
  common/dex-auth/dex-authenticator/base/kustomization.yaml
  common/dex-auth/dex-authenticator/base/namespace.yaml
  common/dex-auth/dex-authenticator/base/params.env
  common/dex-auth/dex-authenticator/base/params.yaml
  common/dex-auth/dex-authenticator/base/service.yaml
  common/dex-auth/dex-crds/base/config-map.yaml
  common/dex-auth/dex-crds/base/crds.yaml
  common/dex-auth/dex-crds/base/deployment.yaml
  common/dex-auth/dex-crds/base/kustomization.yaml
  common/dex-auth/dex-crds/base/namespace.yaml
  common/dex-auth/dex-crds/base/params.env
  common/dex-auth/dex-crds/base/params.yaml
  common/dex-auth/dex-crds/base/service.yaml
  common/dex-auth/dex-crds/overlays/ldap/config-map.yaml
  common/dex-auth/dex-crds/overlays/ldap/deployment.yaml
  common/dex-auth/dex-crds/overlays/ldap/kustomization.yaml
  common/dex-auth/dex-crds/overlays/ldap/params.env
  common/dex-auth/dex-crds/overlays/ldap/params.yaml
  common/dex-auth/dex-ldap/base/deployment.yaml
  common/dex-auth/dex-ldap/base/kustomization.yaml
  common/dex-auth/dex-ldap/base/namespace.yaml
  common/dex-auth/dex-ldap/base/service.yaml
  docs/dex-auth/assets/auth-istio.png
  docs/dex-auth/assets/ldap_tree.png
  docs/dex-auth/assets/user_settings_ldap.png
  docs/dex-auth/examples/README.md
  docs/dex-auth/examples/apply_example.sh
  docs/dex-auth/examples/authentication/Istio/base/kustomization.yaml
  docs/dex-auth/examples/authentication/Istio/base/params.env
  docs/dex-auth/examples/authentication/Istio/base/params.yaml
  docs/dex-auth/examples/authentication/Istio/base/policy.yaml
  docs/dex-auth/examples/authorization/Istio/cluster_rbac_config.yaml
  docs/dex-auth/examples/authorization/Istio/ml_pipeline_service_role.yaml
  docs/dex-auth/examples/authorization/Istio/ml_pipeline_service_role_binding.yaml
  docs/dex-auth/examples/authorization/Kubernetes/cluster_read_all_cluster_role.yaml
  docs/dex-auth/examples/authorization/Kubernetes/cluster_read_all_cluster_role_binding.yaml
  docs/dex-auth/examples/authorization/Kubernetes/cluster_write_all_cluster_role.yaml
  docs/dex-auth/examples/authorization/Kubernetes/cluster_write_all_cluster_role_binding.yaml
  docs/dex-auth/examples/authorization/Kubernetes/secrets_write_all_cluster_role.yaml
  docs/dex-auth/examples/authorization/Kubernetes/secrets_write_all_cluster_role_binding.yaml
  docs/dex-auth/examples/gencert.sh
  hack/gen-test-target.sh
  tests/dex-authenticator-base_test.go
  tests/dex-crds-base_test.go
  tests/dex-crds-overlays-ldap_test.go
  tests/dex-ldap-base_test.go
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XXL

#255 Add metadata application CR
  metadata/overlays/application/application.yaml
  metadata/overlays/application/kustomization.yaml
  tests/metadata-overlays-application_test.go
Labels: approved, cla: yes, lgtm, size/L

#268 Adding manifests for kfserving
  kfserving/kfserving-crds/base/crd.yaml
  kfserving/kfserving-crds/base/kustomization.yaml
  kfserving/kfserving-install/base/cluster-role-binding.yaml
  kfserving/kfserving-install/base/cluster-role.yaml
  kfserving/kfserving-install/base/config-map.yaml
  kfserving/kfserving-install/base/kustomization.yaml
  kfserving/kfserving-install/base/params.env
  kfserving/kfserving-install/base/params.yaml
  kfserving/kfserving-install/base/secret.yaml
  kfserving/kfserving-install/base/service.yaml
  kfserving/kfserving-install/base/statefulset.yaml
  kfserving/kfserving-install/overlays/application/application.yaml
  kfserving/kfserving-install/overlays/application/kustomization.yaml
  knative/knative-serving-crds/base/crd.yaml
  knative/knative-serving-crds/base/kustomization.yaml
  knative/knative-serving-install/base/apiservice.yaml
  knative/knative-serving-install/base/cluster-role-binding.yaml
  knative/knative-serving-install/base/cluster-role.yaml
  knative/knative-serving-install/base/config-map.yaml
  knative/knative-serving-install/base/deployment.yaml
  knative/knative-serving-install/base/gateway.yaml
  knative/knative-serving-install/base/hpa.yaml
  knative/knative-serving-install/base/image.yaml
  knative/knative-serving-install/base/kustomization.yaml
  knative/knative-serving-install/base/namespace.yaml
  knative/knative-serving-install/base/role-binding.yaml
  knative/knative-serving-install/base/service-account.yaml
  knative/knative-serving-install/base/service-role-binding.yaml
  knative/knative-serving-install/base/service-role.yaml
  knative/knative-serving-install/base/service.yaml
  tests/aws-alb-ingress-controller-base_test.go
  tests/aws-alb-ingress-controller-overlays-vpc_test.go
  tests/aws-efs-csi-driver-base_test.go
  tests/aws-fsx-csi-driver-base_test.go
  tests/dex-crds-overlays-ldap_test.go
  tests/fluentd-cloud-watch-base_test.go
  tests/istio-ingress-base_test.go
  tests/istio-ingress-overlays-cognito_test.go
  tests/istio-ingress-overlays-oidc_test.go
  tests/kfserving-crds-base_test.go
  tests/kfserving-install-base_test.go
  tests/kfserving-install-overlays-application_test.go
  tests/knative-serving-crds-base_test.go
  tests/knative-serving-install-base_test.go
  tests/minio-base_test.go
  tests/minio-overlays-minioPd_test.go
  tests/mysql-base_test.go
  tests/mysql-overlays-mysqlPd_test.go
  tests/nvidia-device-plugin-base_test.go
  tests/profiles-base_test.go
  tests/profiles-overlays-debug_test.go
  tests/profiles-overlays-devices_test.go
  tests/profiles-overlays-istio_test.go
  tests/prometheus-base_test.go
Labels: approved, cla: yes, lgtm, size/XXL

#287 Moves Dex Auth to top level folder
  dex-auth/README.md
  dex-auth/dex-authenticator/base/config-map.yaml
  dex-auth/dex-authenticator/base/deployment.yaml
  dex-auth/dex-authenticator/base/kustomization.yaml
  dex-auth/dex-authenticator/base/namespace.yaml
  dex-auth/dex-authenticator/base/params.env
  dex-auth/dex-authenticator/base/params.yaml
  dex-auth/dex-authenticator/base/service.yaml
  dex-auth/dex-crds/base/config-map.yaml
  dex-auth/dex-crds/base/crds.yaml
  dex-auth/dex-crds/base/deployment.yaml
  dex-auth/dex-crds/base/kustomization.yaml
  dex-auth/dex-crds/base/namespace.yaml
  dex-auth/dex-crds/base/params.env
  dex-auth/dex-crds/base/params.yaml
  dex-auth/dex-crds/base/service.yaml
  dex-auth/dex-crds/overlays/ldap/config-map.yaml
  dex-auth/dex-crds/overlays/ldap/deployment.yaml
  dex-auth/dex-crds/overlays/ldap/kustomization.yaml
  dex-auth/dex-crds/overlays/ldap/params.env
  dex-auth/dex-crds/overlays/ldap/params.yaml
  dex-auth/dex-ldap/base/deployment.yaml
  dex-auth/dex-ldap/base/kustomization.yaml
  dex-auth/dex-ldap/base/namespace.yaml
  dex-auth/dex-ldap/base/service.yaml
  tests/dex-authenticator-base_test.go
  tests/dex-crds-base_test.go
  tests/dex-crds-overlays-ldap_test.go
  tests/dex-ldap-base_test.go
Labels: approved, cla: yes, lgtm, size/M

#282 CentralDashboard Image for kubeflow/kubeflow#3933
  common/centraldashboard/base/kustomization.yaml
  tests/centraldashboard-base_test.go
  tests/centraldashboard-overlays-application_test.go
  tests/centraldashboard-overlays-istio_test.go
Labels: approved, area/front-end, cla: yes, lgtm, priority/p1, size/XS

#294 Automated cherry pick of #282: CentralDashboard image made for Cherry pick of #282 on v0.6-branch. #282: CentralDashboard image made for
  common/centraldashboard/base/kustomization.yaml
  tests/centraldashboard-base_test.go
  tests/centraldashboard-overlays-application_test.go
  tests/centraldashboard-overlays-istio_test.go
Labels: approved, cla: yes, lgtm, size/XS

#274 parameterize userid header and prefix
  common/centraldashboard/base/deployment.yaml
  common/centraldashboard/base/kustomization.yaml
  common/centraldashboard/base/params.env
  common/centraldashboard/base/params.yaml
  jupyter/jupyter-web-app/base/deployment.yaml
  jupyter/jupyter-web-app/base/kustomization.yaml
  jupyter/jupyter-web-app/base/params.env
  jupyter/jupyter-web-app/base/params.yaml
  profiles/base/deployment.yaml
  profiles/base/kustomization.yaml
  profiles/base/params.env
  profiles/base/params.yaml
  tests/basic-auth-ingress-overlays-gcp-credentials_test.go
  tests/basic-auth-ingress-overlays-managed-cert_test.go
  tests/centraldashboard-base_test.go
  tests/centraldashboard-overlays-application_test.go
  tests/centraldashboard-overlays-istio_test.go
  tests/cloud-endpoints-overlays-gcp-credentials_test.go
  tests/iap-ingress-base_test.go
  tests/iap-ingress-overlays-certmanager_test.go
  tests/iap-ingress-overlays-gcp-credentials_test.go
  tests/iap-ingress-overlays-managed-cert_test.go
  tests/jupyter-web-app-base_test.go
  tests/jupyter-web-app-overlays-application_test.go
  tests/jupyter-web-app-overlays-istio_test.go
  tests/profiles-base_test.go
  tests/profiles-overlays-debug_test.go
  tests/profiles-overlays-devices_test.go
  tests/profiles-overlays-istio_test.go
Labels: approved, cla: yes, lgtm, size/L

#297 fix central dashboard version
  application/application/overlays/application/application.yaml
Labels: approved, cla: yes, lgtm, size/XS

#298 [CentralDashboard v2] Added env_var for KFAM Server address
  common/centraldashboard/base/deployment.yaml
  tests/centraldashboard-base_test.go
  tests/centraldashboard-overlays-application_test.go
  tests/centraldashboard-overlays-istio_test.go
Labels: approved, area/front-end, cla: yes, lgtm, priority/p0, size/XS

#299 adds make generate to the test workflow
  tests/scripts/run-tests.sh
  tests/workflows/components/workflows.libsonnet
Labels: approved, cla: yes, lgtm, size/S

#301 [CentralDashboard v2] Post kubeflow/kubeflow#3980 changes now in the release
  common/centraldashboard/base/kustomization.yaml
  tests/centraldashboard-base_test.go
  tests/centraldashboard-overlays-application_test.go
  tests/centraldashboard-overlays-istio_test.go
Labels: approved, area/front-end, cla: yes, lgtm, priority/p1, size/XS

#303 Automated cherry pick of #301: Post kubeflow/kubeflow#3980 changes now in the release Cherry pick of #301 on v0.6-branch. #301: Post kubeflow/kubeflow#3980 changes now in the release
  common/centraldashboard/base/kustomization.yaml
  tests/centraldashboard-base_test.go
  tests/centraldashboard-overlays-application_test.go
  tests/centraldashboard-overlays-istio_test.go
Labels: cla: yes, lgtm, size/XS

#302 Automated cherry pick of #298: Added an environment variable to central dash to target Cherry pick of #298 on v0.6-branch. #298: Added an environment variable to central dash to target
  common/centraldashboard/base/deployment.yaml
  tests/centraldashboard-base_test.go
  tests/centraldashboard-overlays-application_test.go
  tests/centraldashboard-overlays-istio_test.go
Labels: cla: yes, lgtm, size/S

#273 Update Seldon Manifest for 0.4 Release of Seldon
  seldon/Makefile
  seldon/README.md
  seldon/seldon-core-operator/base/Kube-descriptor.yaml
  seldon/seldon-core-operator/base/kustomization.yaml
  seldon/seldon-core-operator/base/seldon-config-cm.yaml
  seldon/seldon-core-operator/base/seldon-manager-sa.yaml
  seldon/seldon-core-operator/base/seldon-operator-controller-manager-service-svc.yaml
  seldon/seldon-core-operator/base/seldon-operator-controller-manager-statefulset.yaml
  seldon/seldon-core-operator/base/seldon-operator-manager-role-clusterrole.yaml
  seldon/seldon-core-operator/base/seldon-operator-manager-rolebinding-crb.yaml
  seldon/seldon-core-operator/base/seldon-operator-webhook-server-secret-secret.yaml
  seldon/seldon-core-operator/base/seldondeployments.machinelearning.seldon.io-crd.yaml
  seldon/seldon-core-operator/base/service-account.yaml
  seldon/seldon-core-operator/base/webhook-server-service-svc.yaml
  seldon/values.yaml
  tests/seldon-core-operator-base_test.go
  tests/seldon-core-operator-overlays-application_test.go
Labels: approved, cla: yes, lgtm, size/XXL

#307 Bump the application versions to v0.6.2 on the v0.6-branch.
  common/centraldashboard/overlays/application/application.yaml
  jupyter/jupyter-web-app/overlays/application/application.yaml
  jupyter/notebook-controller/overlays/application/application.yaml
Labels: approved, cla: yes, lgtm, size/XS

#305 Automated cherry pick of #274: central dashboard: parameterize userid-{header, prefix} Cherry pick of #274 on v0.6-branch. #274: central dashboard: parameterize userid-{header, prefix}
  common/centraldashboard/base/kustomization.yaml
  common/centraldashboard/base/params.env
  common/centraldashboard/base/params.yaml
  jupyter/jupyter-web-app/base/deployment.yaml
  jupyter/jupyter-web-app/base/kustomization.yaml
  jupyter/jupyter-web-app/base/params.env
  jupyter/jupyter-web-app/base/params.yaml
  profiles/base/deployment.yaml
  profiles/base/kustomization.yaml
  profiles/base/params.env
  profiles/base/params.yaml
  tests/centraldashboard-base_test.go
  tests/centraldashboard-overlays-application_test.go
  tests/centraldashboard-overlays-istio_test.go
  tests/jupyter-web-app-base_test.go
  tests/jupyter-web-app-overlays-application_test.go
  tests/jupyter-web-app-overlays-istio_test.go
  tests/profiles-base_test.go
  tests/profiles-overlays-debug_test.go
  tests/profiles-overlays-devices_test.go
  tests/profiles-overlays-istio_test.go
Labels: approved, cla: yes, lgtm, size/L

#311 apply PR #310 to v0.6 branch, and fix a bunch of tests
  common/centraldashboard/base/kustomization.yaml
  tests/application-overlays-application_test.go
  tests/centraldashboard-base_test.go
  tests/centraldashboard-overlays-application_test.go
  tests/centraldashboard-overlays-istio_test.go
  tests/jupyter-web-app-base_test.go
  tests/jupyter-web-app-overlays-application_test.go
  tests/jupyter-web-app-overlays-istio_test.go
  tests/notebook-controller-overlays-application_test.go
  tests/profiles-base_test.go
  tests/profiles-overlays-debug_test.go
  tests/profiles-overlays-devices_test.go
  tests/profiles-overlays-istio_test.go
Labels: approved, cla: yes, lgtm, size/M

#312 Revert "Update Seldon Manifest for 0.4 Release of Seldon (#273)"
  seldon/Makefile
  seldon/README.md
  seldon/seldon-core-operator/base/Kube-descriptor.yaml
  seldon/seldon-core-operator/base/clusterrole.yaml
  seldon/seldon-core-operator/base/crd.yaml
  seldon/seldon-core-operator/base/kustomization.yaml
  seldon/seldon-core-operator/base/rolebinding.yaml
  seldon/seldon-core-operator/base/secret.yaml
  seldon/seldon-core-operator/base/seldon-config-cm.yaml
  seldon/seldon-core-operator/base/seldon-manager-sa.yaml
  seldon/seldon-core-operator/base/service-account.yaml
  seldon/seldon-core-operator/base/service.yaml
  seldon/seldon-core-operator/base/statefulset.yaml
  seldon/seldon-core-operator/base/webhook-server-service-svc.yaml
  seldon/values.yaml
  tests/seldon-core-operator-base_test.go
  tests/seldon-core-operator-overlays-application_test.go
Labels: approved, cla: yes, lgtm, size/XXL

#320 [auto PR] Update the jupyter-web-app image to 9419d4d7
  jupyter/jupyter-web-app/base/kustomization.yaml
  tests/aws-alb-ingress-controller-base_test.go
  tests/aws-alb-ingress-controller-overlays-vpc_test.go
  tests/aws-efs-csi-driver-base_test.go
  tests/aws-fsx-csi-driver-base_test.go
  tests/fluentd-cloud-watch-base_test.go
  tests/istio-ingress-base_test.go
  tests/istio-ingress-overlays-cognito_test.go
  tests/istio-ingress-overlays-oidc_test.go
  tests/jupyter-web-app-base_test.go
  tests/jupyter-web-app-overlays-application_test.go
  tests/jupyter-web-app-overlays-istio_test.go
  tests/minio-base_test.go
  tests/minio-overlays-minioPd_test.go
  tests/mysql-base_test.go
  tests/mysql-overlays-mysqlPd_test.go
  tests/nvidia-device-plugin-base_test.go
  tests/profiles-base_test.go
  tests/profiles-overlays-debug_test.go
  tests/profiles-overlays-devices_test.go
  tests/profiles-overlays-istio_test.go
  tests/prometheus-base_test.go
Labels: approved, cla: yes, lgtm, size/L

#310 [Central-Dashboard v2] Stable Release - Version and Profile-Server fixes
  common/centraldashboard/base/kustomization.yaml
  tests/centraldashboard-base_test.go
  tests/centraldashboard-overlays-application_test.go
  tests/centraldashboard-overlays-istio_test.go
Labels: approved, area/front-end, cla: yes, lgtm, priority/p1, size/XS
