Repository kubeflow/manifests, pull requests merged in 2019-05, with the labels that each got.

#32 Add kustomize config for kubeflow/metadata
  metadata/base/kustomization.yaml
  metadata/base/metadata-deployment.yaml
  metadata/base/metadata-service.yaml
Labels: approved, lgtm, size/M

#45 add gabrielwen to manifests OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#43 Pipeline UI ISTIO manifests
  pipeline/pipelines-ui/base/kustomization.yaml
  pipeline/pipelines-ui/base/params.env
  pipeline/pipelines-ui/base/params.yaml
  pipeline/pipelines-ui/base/virtual-service.yaml
  pipeline/pipelines-viewer/base/kustomization.yaml
  pipeline/pipelines-viewer/base/params.env
  pipeline/pipelines-viewer/base/params.yaml
  pipeline/pipelines-viewer/base/virtual-service.yaml
Labels: approved, lgtm, size/M

#38 Argo ISTIO config
  argo/base/kustomization.yaml
  argo/base/params.env
  argo/base/params.yaml
  argo/base/virtual-service.yaml
Labels: approved, lgtm, size/M

#39 Jupyter ISTIO manifest
  jupyter/jupyter-web-app/base/kustomization.yaml
  jupyter/jupyter-web-app/base/params.env
  jupyter/jupyter-web-app/base/params.yaml
  jupyter/jupyter-web-app/base/virtual-service.yaml
Labels: approved, lgtm, size/M

#40 Katib UI ISTIO
  katib/base/katib-ui-virtual-service.yaml
  katib/base/kustomization.yaml
  katib/base/params.env
  katib/base/params.yaml
Labels: approved, lgtm, size/M

#46 finish ISTIO configs.
  common/centraldashboard/base/kustomization.yaml
  common/centraldashboard/base/params.env
  common/centraldashboard/base/params.yaml
  common/centraldashboard/base/virtual-service.yaml
  kubebench/base/kustomization.yaml
  kubebench/base/params.env
  kubebench/base/params.yaml
  kubebench/base/virtual-service.yaml
  tensorboard/base/kustomization.yaml
  tensorboard/base/params.env
  tensorboard/base/params.yaml
  tensorboard/base/virtual-service.yaml
  tf-training/tf-job-operator/base/kustomization.yaml
  tf-training/tf-job-operator/base/params.env
  tf-training/tf-job-operator/base/params.yaml
  tf-training/tf-job-operator/base/virtual-service.yaml
Labels: approved, lgtm, size/L

#31 Support for multiple overlays
  profiles/base/crd.yaml
  profiles/base/deployment.yaml
  profiles/base/kustomization.yaml
  profiles/base/role.yaml
  profiles/overlays/debug/deployment.yaml
  profiles/overlays/debug/kustomization.yaml
  profiles/overlays/debug/params.env
  profiles/overlays/debug/params.yaml
  profiles/overlays/devices/deployment.yaml
  profiles/overlays/devices/kustomization.yaml
Labels: approved, lgtm, size/L

#41 adds basic-auth
  common/basic-auth/base/gatekeeper-deployment.yaml
  common/basic-auth/base/gatekeeper-service.yaml
  common/basic-auth/base/kflogin-deployment.yaml
  common/basic-auth/base/kflogin-service.yaml
  common/basic-auth/base/kflogin-virtual-service.yaml
  common/basic-auth/base/kustomization.yaml
  common/basic-auth/base/params.env
  common/basic-auth/base/params.yaml
Labels: approved, lgtm, size/L

#63 Set up prow for manifests
  prow_config.yaml
  tests/scripts/run-tests.sh
  tests/workflows/app.yaml
  tests/workflows/components/params.libsonnet
  tests/workflows/components/workflows.jsonnet
  tests/workflows/components/workflows.libsonnet
  tests/workflows/environments/base.libsonnet
  tests/workflows/environments/releasing/main.jsonnet
  tests/workflows/environments/releasing/params.libsonnet
  tests/workflows/lib/v1.7.0/k.libsonnet
  tests/workflows/lib/v1.7.0/k8s.libsonnet
  tests/workflows/lib/v1.7.0/swagger.json
Labels: approved, lgtm, size/XXL

#64 Add myself to OWNERS per Kam's request
  OWNERS
Labels: approved, lgtm, size/XS

#58 basic-auth-ingress is missing from gcp
  common/basic-auth/base/gatekeeper-deployment.yaml
  common/basic-auth/base/gatekeeper-service.yaml
  common/basic-auth/base/kflogin-deployment.yaml
  common/basic-auth/base/kflogin-service.yaml
  common/basic-auth/base/kflogin-virtual-service.yaml
  common/basic-auth/base/kustomization.yaml
  common/basic-auth/base/params.env
  common/basic-auth/base/params.yaml
  gcp/basic-auth-ingress/overlays/gcp/certificate.yaml
  gcp/basic-auth-ingress/overlays/gcp/cloud-endpoint.yaml
  gcp/basic-auth-ingress/overlays/gcp/cluster-role-binding.yaml
  gcp/basic-auth-ingress/overlays/gcp/cluster-role.yaml
  gcp/basic-auth-ingress/overlays/gcp/config-map.yaml
  gcp/basic-auth-ingress/overlays/gcp/deployment.yaml
  gcp/basic-auth-ingress/overlays/gcp/ingress.yaml
  gcp/basic-auth-ingress/overlays/gcp/job.yaml
  gcp/basic-auth-ingress/overlays/gcp/kustomization.yaml
  gcp/basic-auth-ingress/overlays/gcp/params.env
  gcp/basic-auth-ingress/overlays/gcp/params.yaml
  gcp/basic-auth-ingress/overlays/gcp/service-account.yaml
  gcp/basic-auth-ingress/overlays/gcp/service.yaml
  gcp/basic-auth-ingress/overlays/gcp/stateful-set.yaml
Labels: approved, lgtm, size/L

#65 enable test
  tests/scripts/run-tests.sh
Labels: approved, lgtm, size/XS

#62 move gcp components from overlays/gcp to base
  cert-manager/base/cluster-role-binding.yaml
  cert-manager/base/cluster-role.yaml
  cert-manager/base/crd.yaml
  cert-manager/base/deployment.yaml
  cert-manager/base/kustomization.yaml
  cert-manager/base/params.env
  cert-manager/base/params.yaml
  cert-manager/base/service-account.yaml
  gcp/cloud-endpoints/base/cluster-role-binding.yaml
  gcp/cloud-endpoints/base/cluster-role.yaml
  gcp/cloud-endpoints/base/composite-controller.yaml
  gcp/cloud-endpoints/base/crd.yaml
  gcp/cloud-endpoints/base/deployment.yaml
  gcp/cloud-endpoints/base/kustomization.yaml
  gcp/cloud-endpoints/base/params.env
  gcp/cloud-endpoints/base/params.yaml
  gcp/cloud-endpoints/base/service-account.yaml
  gcp/cloud-endpoints/base/service.yaml
  gcp/gcp-credentials-admission-webhook/base/cluster-role-binding.yaml
  gcp/gcp-credentials-admission-webhook/base/cluster-role.yaml
  gcp/gcp-credentials-admission-webhook/base/config-map.yaml
  gcp/gcp-credentials-admission-webhook/base/deployment.yaml
  gcp/gcp-credentials-admission-webhook/base/kustomization.yaml
  gcp/gcp-credentials-admission-webhook/base/mutating-webhook-configuration.yaml
  gcp/gcp-credentials-admission-webhook/base/params.env
  gcp/gcp-credentials-admission-webhook/base/params.yaml
  gcp/gcp-credentials-admission-webhook/base/service-account.yaml
  gcp/gcp-credentials-admission-webhook/base/service.yaml
  gcp/gcp-credentials-admission-webhook/base/stateful-set.yaml
  gcp/gpu-driver/base/daemon-set.yaml
  gcp/gpu-driver/base/kustomization.yaml
  gcp/iap-ingress/base/backend-config.yaml
  gcp/iap-ingress/base/certificate.yaml
  gcp/iap-ingress/base/cloud-endpoint.yaml
  gcp/iap-ingress/base/cluster-role-binding.yaml
  gcp/iap-ingress/base/cluster-role.yaml
  gcp/iap-ingress/base/config-map.yaml
  gcp/iap-ingress/base/deployment.yaml
  gcp/iap-ingress/base/ingress.yaml
  gcp/iap-ingress/base/job.yaml
  gcp/iap-ingress/base/kustomization.yaml
  gcp/iap-ingress/base/service-account.yaml
  gcp/iap-ingress/base/service.yaml
  gcp/iap-ingress/base/stateful-set.yaml
Labels: approved, lgtm, size/XS

#69 JWT policy for IAP ingress
  gcp/iap-ingress/base/jwt-policy.yaml
  gcp/iap-ingress/base/kustomization.yaml
Labels: approved, lgtm, size/S

#72 jupyter_test.go and profiles_test.go are replacing overlays and causing errors in run-tests
  gcp/gcp-credentials-admission-webhook/base/config-map.yaml
  hack/gen-test-target.sh
  hack/gen-test-targets.sh
  hack/utils.sh
  tests/Makefile
Labels: approved, lgtm, size/M

#73 jupyter-web-app requires access to storageclasses resources
  jupyter/jupyter-web-app/base/cluster-role.yaml
Labels: approved, lgtm, size/XS

#56 define naming and best practices for kustomize manifests
  README.md
  common/ambassador/base/deployment-ambassador-patch.yaml
  common/ambassador/base/kustomization.yaml
  docs/KustomizeBestPractices.md
  profiles/base/kustomization.yaml
Labels: approved, lgtm, size/L

#68 Fix typo of jupyter yaml
  jupyter/jupyter/base/stateful-set.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#78 Notebook controller requires rbac to create istio virtualservices
  jupyter/notebook-controller/base/cluster-role.yaml
Labels: approved, lgtm, size/XS

#80 Update tf-operator to v1
  tf-training/tf-job-operator/base/crd.yaml
  tf-training/tf-job-operator/base/deployment.yaml
Labels: approved, lgtm, size/S

#79 Extend the test harness to incorporate parameters and negative testing
  docs/TestFramework.md
  gcp/basic-auth-ingress/base/certificate.yaml
  gcp/basic-auth-ingress/base/cloud-endpoint.yaml
  gcp/basic-auth-ingress/base/cluster-role-binding.yaml
  gcp/basic-auth-ingress/base/cluster-role.yaml
  gcp/basic-auth-ingress/base/config-map.yaml
  gcp/basic-auth-ingress/base/deployment.yaml
  gcp/basic-auth-ingress/base/ingress.yaml
  gcp/basic-auth-ingress/base/job.yaml
  gcp/basic-auth-ingress/base/kustomization.yaml
  gcp/basic-auth-ingress/base/params.env
  gcp/basic-auth-ingress/base/params.yaml
  gcp/basic-auth-ingress/base/service-account.yaml
  gcp/basic-auth-ingress/base/service.yaml
  gcp/basic-auth-ingress/base/stateful-set.yaml
  hack/gen-test-target.sh
  hack/gen-test-targets.sh
  hack/kustomize/plugin/kfdef.apps.kubeflow.org/v1alpha1/KfDef
  hack/utils.sh
  profiles/overlays/debug/params.yaml
  profiles/overlays/test/app_test.yaml
  profiles/overlays/test/kustomization.yaml
  tests/Makefile
  tests/kusttestharness_test.go
  tests/scripts/run-tests.sh
Labels: approved, lgtm, size/L

#82 test_harness: checkin the generated golang tests #81
  hack/gen-test-target.sh
  hack/gen-test-targets.sh
  tests/ambassador-base_test.go
  tests/api-service-base_test.go
  tests/application-base_test.go
  tests/argo-base_test.go
  tests/basic-auth-base_test.go
  tests/basic-auth-ingress-base_test.go
  tests/bootstrap-base_test.go
  tests/centraldashboard-base_test.go
  tests/cert-manager-base_test.go
  tests/cloud-endpoints-base_test.go
  tests/gpu-driver-base_test.go
  tests/iap-ingress-base_test.go
  tests/jupyter-base_test.go
  tests/jupyter-overlays-minikube_test.go
  tests/jupyter-web-app-base_test.go
  tests/katib-base_test.go
  tests/kubebench-base_test.go
  tests/metacontroller-base_test.go
  tests/metadata-base_test.go
  tests/minio-base_test.go
  tests/modeldb-base_test.go
  tests/mysql-base_test.go
  tests/notebook-controller-base_test.go
  tests/persistent-agent-base_test.go
  tests/pipelines-runner-base_test.go
  tests/pipelines-ui-base_test.go
  tests/pipelines-viewer-base_test.go
  tests/profiles-base_test.go
  tests/profiles-overlays-debug_test.go
  tests/profiles-overlays-devices_test.go
  tests/pytorch-operator-base_test.go
  tests/scheduledworkflow-base_test.go
  tests/spartakus-base_test.go
  tests/tensorboard-base_test.go
  tests/tf-job-operator-base_test.go
  tests/webhook-base_test.go
Labels: approved, lgtm, size/XXL

#70 Fix ClusterRole in Jupyter Notebook controller
  jupyter/notebook-controller/base/cluster-role.yaml
Labels: approved, lgtm, size/XS

#77 iap-ingress is missing parameters used in ksonnet
  gcp/basic-auth-ingress/base/certificate.yaml
  gcp/basic-auth-ingress/base/cloud-endpoint.yaml
  gcp/iap-ingress/base/backend-config.yaml
  gcp/iap-ingress/base/certificate.yaml
  gcp/iap-ingress/base/cloud-endpoint.yaml
  gcp/iap-ingress/base/cluster-role.yaml
  gcp/iap-ingress/base/config-map.yaml
  gcp/iap-ingress/base/deployment.yaml
  gcp/iap-ingress/base/ingress.yaml
  gcp/iap-ingress/base/job.yaml
  gcp/iap-ingress/base/kustomization.yaml
  gcp/iap-ingress/base/params.env
  gcp/iap-ingress/base/params.yaml
  gcp/iap-ingress/base/policy.yaml
  gcp/iap-ingress/base/service-account.yaml
  gcp/iap-ingress/base/service.yaml
  gcp/iap-ingress/base/stateful-set.yaml
  tests/basic-auth-ingress-base_test.go
  tests/iap-ingress-base_test.go
Labels: approved, lgtm, size/XXL

#88 Fix notebook-controller-base_test.go after ClusterRole was fixed for Jupyter notebook controller
  tests/notebook-controller-base_test.go
Labels: approved, lgtm, size/XS

#90 Add go fmt to Makefile
  tests/Makefile
  tests/ambassador-base_test.go
  tests/api-service-base_test.go
  tests/application-base_test.go
  tests/argo-base_test.go
  tests/basic-auth-base_test.go
  tests/basic-auth-ingress-base_test.go
  tests/bootstrap-base_test.go
  tests/centraldashboard-base_test.go
  tests/cert-manager-base_test.go
  tests/cloud-endpoints-base_test.go
  tests/gpu-driver-base_test.go
  tests/iap-ingress-base_test.go
  tests/jupyter-base_test.go
  tests/jupyter-overlays-minikube_test.go
  tests/jupyter-web-app-base_test.go
  tests/katib-base_test.go
  tests/kubebench-base_test.go
  tests/metacontroller-base_test.go
  tests/metadata-base_test.go
  tests/minio-base_test.go
  tests/modeldb-base_test.go
  tests/mysql-base_test.go
  tests/notebook-controller-base_test.go
  tests/persistent-agent-base_test.go
  tests/pipelines-runner-base_test.go
  tests/pipelines-ui-base_test.go
  tests/pipelines-viewer-base_test.go
  tests/profiles-base_test.go
  tests/profiles-overlays-debug_test.go
  tests/profiles-overlays-devices_test.go
  tests/pytorch-operator-base_test.go
  tests/scheduledworkflow-base_test.go
  tests/spartakus-base_test.go
  tests/tensorboard-base_test.go
  tests/tf-job-operator-base_test.go
  tests/webhook-base_test.go
Labels: approved, lgtm, size/XXL

#91 fixes to iap_ingress and pipeline, regenerated tests
  gcp/iap-ingress/base/stateful-set.yaml
  pipeline/api-service/base/deployment.yaml
  pipeline/api-service/base/kustomization.yaml
  tests/api-service-base_test.go
  tests/iap-ingress-base_test.go
  tests/minio-base_test.go
  tests/minio-overlays-minioPd_test.go
  tests/mysql-overlays-mysqlPd_test.go
Labels: approved, lgtm, size/L

#93 Fix tf-job-operator manifest
  tests/tf-job-operator-base_test.go
  tf-training/tf-job-operator/base/crd.yaml
Labels: approved, lgtm, size/S

#95 Fix pipeline UI namespace
  pipeline/pipelines-ui/base/kustomization.yaml
  pipeline/pipelines-ui/base/service.yaml
  tests/pipelines-ui-base_test.go
Labels: approved, lgtm, size/S

#76 Change the Role verbs of a Profile user to prevent the user from getting a Profile
  profiles/base/crd.yaml
  profiles/base/role-binding.yaml
  profiles/base/role.yaml
  profiles/base/service-account.yaml
  tests/profiles-base_test.go
  tests/profiles-overlays-debug_test.go
  tests/profiles-overlays-devices_test.go
Labels: approved, lgtm, size/M

#103 Fix admin-gcp-sa secretName
  gcp/cloud-endpoints/base/params.env
  gcp/iap-ingress/base/certificate.yaml
  gcp/iap-ingress/base/deployment.yaml
  gcp/iap-ingress/base/job.yaml
  gcp/iap-ingress/base/kustomization.yaml
  gcp/iap-ingress/base/params.env
  tests/cloud-endpoints-base_test.go
  tests/iap-ingress-base_test.go
Labels: approved, lgtm, size/M

#104 Fix pipeline storage PVC overlay manifests
  pipeline/minio/overlays/minioPd/kustomization.yaml
  pipeline/minio/overlays/minioPd/params.env
  pipeline/minio/overlays/minioPd/params.yaml
  pipeline/minio/overlays/minioPd/persistent-volume-claim.yaml
  pipeline/minio/overlays/minioPd/persistent-volume.yaml
  pipeline/mysql/base/deployment.yaml
  pipeline/mysql/base/kustomization.yaml
  pipeline/mysql/base/params.env
  pipeline/mysql/base/params.yaml
  pipeline/mysql/overlays/mysqlPd/kustomization.yaml
  pipeline/mysql/overlays/mysqlPd/params.env
  pipeline/mysql/overlays/mysqlPd/params.yaml
  pipeline/mysql/overlays/mysqlPd/persistent-volume-claim.yaml
  pipeline/mysql/overlays/mysqlPd/persistent-volume.yaml
  tests/minio-overlays-minioPd_test.go
  tests/mysql-base_test.go
  tests/mysql-overlays-mysqlPd_test.go
Labels: approved, lgtm, size/L

#106 Fix Pipeline namings
  pipeline/api-service/base/deployment.yaml
  pipeline/api-service/base/kustomization.yaml
  pipeline/api-service/base/role-binding.yaml
  pipeline/api-service/base/role.yaml
  pipeline/api-service/base/service-account.yaml
  pipeline/api-service/base/service.yaml
  pipeline/minio/base/deployment.yaml
  pipeline/minio/base/kustomization.yaml
  pipeline/minio/base/secret.yaml
  pipeline/minio/base/service.yaml
  pipeline/mysql/base/deployment.yaml
  pipeline/mysql/base/kustomization.yaml
  pipeline/mysql/base/service.yaml
  pipeline/persistent-agent/base/clusterrole-binding.yaml
  pipeline/persistent-agent/base/clusterrole.yaml
  pipeline/persistent-agent/base/deployment.yaml
  pipeline/persistent-agent/base/kustomization.yaml
  pipeline/persistent-agent/base/service-account.yaml
  pipeline/pipelines-runner/base/cluster-role-binding.yaml
  pipeline/pipelines-runner/base/cluster-role.yaml
  pipeline/pipelines-runner/base/kustomization.yaml
  pipeline/pipelines-runner/base/service-account.yaml
  pipeline/pipelines-ui/base/deployment.yaml
  pipeline/pipelines-ui/base/kustomization.yaml
  pipeline/pipelines-ui/base/role-binding.yaml
  pipeline/pipelines-ui/base/role.yaml
  pipeline/pipelines-ui/base/service-account.yaml
  pipeline/pipelines-ui/base/service.yaml
  pipeline/pipelines-ui/base/virtual-service.yaml
  pipeline/pipelines-viewer/base/cluster-role-binding.yaml
  pipeline/pipelines-viewer/base/cluster-role.yaml
  pipeline/pipelines-viewer/base/deployment.yaml
  pipeline/pipelines-viewer/base/kustomization.yaml
  pipeline/pipelines-viewer/base/service-account.yaml
  pipeline/pipelines-viewer/base/service.yaml
  pipeline/pipelines-viewer/base/virtual-service.yaml
  pipeline/scheduledworkflow/base/deployment.yaml
  pipeline/scheduledworkflow/base/kustomization.yaml
  pipeline/scheduledworkflow/base/role-binding.yaml
  pipeline/scheduledworkflow/base/role.yaml
  pipeline/scheduledworkflow/base/service-account.yaml
  tests/api-service-base_test.go
  tests/minio-base_test.go
  tests/minio-overlays-minioPd_test.go
  tests/mysql-base_test.go
  tests/mysql-overlays-mysqlPd_test.go
  tests/persistent-agent-base_test.go
  tests/pipelines-runner-base_test.go
  tests/pipelines-ui-base_test.go
  tests/pipelines-viewer-base_test.go
  tests/scheduledworkflow-base_test.go
Labels: approved, lgtm, size/L

#105 added Jupyter application resources
  jupyter/jupyter-web-app/base/application.yaml
  jupyter/jupyter-web-app/base/kustomization.yaml
  jupyter/jupyter/base/application.yaml
  jupyter/jupyter/base/kustomization.yaml
  jupyter/notebook-controller/base/application.yaml
  jupyter/notebook-controller/base/kustomization.yaml
  tests/jupyter-base_test.go
  tests/jupyter-overlays-minikube_test.go
  tests/jupyter-web-app-base_test.go
  tests/notebook-controller-base_test.go
Labels: approved, lgtm, size/L
