Repository kubeflow/manifests, pull requests merged in 2020-05, with the labels that each got.

#1143 Revert #949 in v1.0-branch completely (follow up of #1111)
  istio/kfserving-gateway/base/deployment.yaml
  istio/kfserving-gateway/base/horizontal-pod-autoscaler.yaml
  istio/kfserving-gateway/base/kustomization.yaml
  istio/kfserving-gateway/base/service.yaml
  kfserving/kfserving-install/base/config-map.yaml
  knative/knative-serving-install/base/config-map.yaml
  knative/knative-serving-install/base/gateway.yaml
  tests/istio-kfserving-gateway-base_test.go
  tests/kfserving-kfserving-install-base_test.go
  tests/kfserving-kfserving-install-overlays-application_test.go
  tests/knative-knative-serving-install-base_test.go
  tests/knative-knative-serving-install-overlays-application_test.go
Labels: approved, cla: yes, lgtm, size/XL

#1150 Add OWNERS file to Katib manifests
  katib/OWNERS
  katib/katib-controller/overlays/application/application.yaml
  katib/katib-crds/overlays/application/application.yaml
  tests/tests/legacy_kustomizations/katib-controller/test_data/expected/app.k8s.io_v1beta1_application_katib-controller.yaml
  tests/tests/legacy_kustomizations/katib-crds/test_data/expected/app.k8s.io_v1beta1_application_katib-crds.yaml
Labels: approved, cla: yes, lgtm, size/S

#1144 Create an updated style/best practices guide for kustomize packages.
  README.md
  docs/KustomizeBestPractices.md
Labels: approved, cla: yes, lgtm, size/L

#1153 Add kubeflow namespace resource to enable istio injection
  kfdef/kfctl_gcp_iap.yaml
  kfdef/source/master/kfctl_gcp_iap.yaml
  namespaces/base/kustomization.yaml
  namespaces/base/namespaces.yaml
Labels: approved, cla: yes, lgtm, size/S

#1137 Patch for knative istio probe issue #6962
  istio/kfserving-gateway/base/deployment.yaml
  istio/kfserving-gateway/base/horizontal-pod-autoscaler.yaml
  istio/kfserving-gateway/base/kustomization.yaml
  istio/kfserving-gateway/base/service.yaml
  kfdef/kfctl_aws.yaml
  kfdef/kfctl_aws_cognito.yaml
  kfdef/kfctl_gcp_basic_auth.yaml
  kfdef/kfctl_gcp_iap.yaml
  kfdef/kfctl_ibm.yaml
  kfdef/kfctl_k8s_istio.yaml
  kfdef/source/master/kfctl_aws.yaml
  kfdef/source/master/kfctl_aws_cognito.yaml
  kfdef/source/master/kfctl_gcp_basic_auth.yaml
  kfdef/source/master/kfctl_gcp_iap.yaml
  kfdef/source/master/kfctl_ibm.yaml
  kfdef/source/master/kfctl_k8s_istio.yaml
  kfserving/kfserving-install/base/config-map.yaml
  knative/knative-serving-install/base/config-map.yaml
  knative/knative-serving-install/base/deployment.yaml
  knative/knative-serving-install/base/gateway.yaml
  tests/tests/legacy_kustomizations/kfserving-install/test_data/expected/~g_v1_configmap_inferenceservice-config.yaml
  tests/tests/legacy_kustomizations/knative-install/test_data/expected/apps_v1_deployment_networking-istio.yaml
  tests/tests/legacy_kustomizations/knative-install/test_data/expected/networking.istio.io_v1alpha3_gateway_knative-ingress-gateway.yaml
  tests/tests/legacy_kustomizations/knative-install/test_data/expected/~g_v1_configmap_config-istio.yaml
Labels: approved, cla: yes, lgtm, size/L

#1114 Fix the link to run_e2e_workflow.py script
  prow_config.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1155 Add support for AWS JupyterNotebook Image
  jupyter/jupyter-web-app/overlays/aws/kustomization.yaml
  jupyter/jupyter-web-app/overlays/aws/spawner_ui_config.yaml
  kfdef/kfctl_aws.yaml
  kfdef/kfctl_aws_cognito.yaml
  kfdef/source/master/kfctl_aws.yaml
  kfdef/source/master/kfctl_aws_cognito.yaml
Labels: approved, cla: yes, lgtm, size/L

#1170 Correct MPIJob CRD's apiVersion
  mpi-job/mpi-operator/base/crd.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1172 Use stable release channel for the GKE management cluster.
  gcp/v2/management/cluster/cluster.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1177 remove initializers from deployment.
  spark/spark-operator/base/deploy.yaml
  tests/tests/legacy_kustomizations/spark-operator/test_data/expected/apps_v1_deployment_spark-operatorsparkoperator.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1176 Update README.md with broken link.
  kubeflow-roles/README.md
Labels: approved, cla: yes, lgtm, size/XS

#1175 CRDs should not have status field.
  application/application-crds/base/crd.yaml
  aws/aws-istio-authz-adaptor/overlays/application/application.yaml
  aws/nvidia-device-plugin/overlays/application/application.yaml
  cert-manager/cert-manager-crds/base/crd.yaml
  jupyter/notebook-controller/base/crd.yaml
  kfserving/kfserving-crds/base/crd.yaml
  profiles/base/crd.yaml
  spark/spark-operator/base/scheduledsparkapplications.sparkoperator.k8s.io-crd.yaml
  spark/spark-operator/base/sparkapplications.sparkoperator.k8s.io-crd.yaml
  tests/stacks/examples/alice_gcp/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_notebooks.kubeflow.org.yaml
  tests/stacks/examples/alice_gcp/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_profiles.kubeflow.org.yaml
  tests/stacks/gcp/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_notebooks.kubeflow.org.yaml
  tests/stacks/gcp/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_profiles.kubeflow.org.yaml
  tests/tests/legacy_kustomizations/application-crds/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_applications.app.k8s.io.yaml
  tests/tests/legacy_kustomizations/cert-manager-crds/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_certificaterequests.cert-manager.io.yaml
  tests/tests/legacy_kustomizations/cert-manager-crds/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_certificates.cert-manager.io.yaml
  tests/tests/legacy_kustomizations/cert-manager-crds/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_challenges.acme.cert-manager.io.yaml
  tests/tests/legacy_kustomizations/cert-manager-crds/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_issuers.cert-manager.io.yaml
  tests/tests/legacy_kustomizations/cert-manager-crds/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_orders.acme.cert-manager.io.yaml
  tests/tests/legacy_kustomizations/kfserving-crds/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_inferenceservices.serving.kubeflow.org.yaml
  tests/tests/legacy_kustomizations/notebook-controller/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_notebooks.kubeflow.org.yaml
  tests/tests/legacy_kustomizations/profiles/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_profiles.kubeflow.org.yaml
  tests/tests/legacy_kustomizations/spark-operator/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_scheduledsparkapplications.sparkoperator.k8s.io.yaml
  tests/tests/legacy_kustomizations/spark-operator/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_sparkapplications.sparkoperator.k8s.io.yaml
  tests/validate_resources_test.go
  xgboost-job/xgboost-operator/base/crd.yaml
Labels: approved, cla: yes, lgtm, size/L

#1167 add a selector to deployment config for xgboost-operator, change the …
  xgboost-job/xgboost-operator/base/deployment.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#1179 Remove status fields from CRDs and empty annotations
  cert-manager/cert-manager-crds/base/crd.yaml
  istio-1-3-1/cluster-local-gateway-1-3-1/base/service.yaml
  istio/cluster-local-gateway/base/service.yaml
  istio/istio-install/base/istio-noauth.yaml
  kfdef/generic/istio/istio-noauth.yaml
  seldon/seldon-core-operator/base/resources.yaml
  tests/go.mod
  tests/go.sum
  tests/tests/legacy_kustomizations/cert-manager-crds/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_clusterissuers.cert-manager.io.yaml
  tests/tests/legacy_kustomizations/istio-install/test_data/expected/~g_v1_service_jaeger-query.yaml
  tests/tests/legacy_kustomizations/seldon-core-operator/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_seldondeployments.machinelearning.seldon.io.yaml
  tests/validate_resources_test.go
Labels: approved, cla: yes, lgtm, size/XL

#1185 Argo kustomize v3 manifests
  argo/base/service.yaml
  argo/base_v3/kustomization.yaml
  argo/base_v3/params.yaml
  argo/overlays/application/application.yaml
  tests/tests/legacy_kustomizations/argo/test_data/expected/app.k8s.io_v1beta1_application_argo.yaml
  tests/tests/legacy_kustomizations/argo/test_data/expected/~g_v1_service_argo-ui.yaml
Labels: approved, cla: yes, lgtm, size/L

#1184 Fix meshID and gcloud.compute.zone parameter set by kpt
  gcp/v2/asm/istio-operator.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1193 GCP CNRM should use release channels and autoprovisioning
  gcp/v2/cnrm/cluster/cluster.yaml
Labels: approved, cla: yes, lgtm, size/S

#1196 Add GCS scope to the cluster; create an OWNERs file.
  gcp/OWNERS
  gcp/v2/cnrm/cluster/cluster.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1202 New overlay for dex/dex-crds to support GitHub as dex identity provider
  dex-auth/dex-crds/overlays/github/config-map.yaml
  dex-auth/dex-crds/overlays/github/kustomization.yaml
  dex-auth/dex-crds/overlays/github/params.env
  dex-auth/dex-crds/overlays/github/params.yaml
  dex-auth/dex-crds/overlays/github/virtual-service.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/L
