Repository kubeflow/manifests, pull requests merged in 2020-03, with the labels that each got.

#969 Fix pipeline default service account
  pipeline/api-service/base/config-map.yaml
  pipeline/api-service/overlays/external-mysql/config-map.yaml
  pipeline/pipelines-runner/base/cluster-role-binding.yaml
  tests/pipeline-api-service-base_test.go
  tests/pipeline-api-service-overlays-application_test.go
  tests/pipeline-api-service-overlays-external-mysql_test.go
  tests/pipeline-pipelines-runner-base_test.go
  tests/pipeline-pipelines-runner-overlays-application_test.go
Labels: approved, cla: yes, lgtm, size/S

#970 Fix KFP tensorboard no GCP permission
  pipeline/pipelines-ui/overlays/gcp/configmap.yaml
  pipeline/pipelines-ui/overlays/gcp/deployment.yaml
  pipeline/pipelines-ui/overlays/gcp/kustomization.yaml
  tests/pipeline-pipelines-ui-overlays-gcp_test.go
Labels: approved, area/pipelines, cla: yes, kind/bug, lgtm, size/M

#813 updating dex container image
  dex-auth/dex-crds/base/deployment.yaml
  dex-auth/dex-crds/base/kustomization.yaml
  tests/dex-auth-dex-crds-base_test.go
  tests/dex-auth-dex-crds-overlays-istio_test.go
  tests/dex-auth-dex-crds-overlays-ldap_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#982 Change AWS OIDC manifest settings from auth-idp-cognito to auth-idp-oidc
  aws/istio-ingress/overlays/oidc/ingress.yaml
  tests/aws-istio-ingress-overlays-oidc_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#985 Automated cherry pick of #982: Fix OIDC settings Cherry pick of #982 on v1.0-branch. #982: Fix OIDC settings
  aws/istio-ingress/overlays/oidc/ingress.yaml
  tests/aws-istio-ingress-overlays-oidc_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#987 unpin gke version (#882)
  gcp/deployment_manager_configs/cluster-kubeflow.yaml
Labels: approved, cla: yes, lgtm, size/XS

#949 Adds kfserving ingressgateway for Istio 1.1.6
  istio/kfserving-gateway/base/deployment.yaml
  istio/kfserving-gateway/base/horizontal-pod-autoscaler.yaml
  istio/kfserving-gateway/base/kustomization.yaml
  istio/kfserving-gateway/base/service.yaml
  kfdef/kfctl_gcp_basic_auth.v1.0.0.yaml
  kfdef/kfctl_gcp_basic_auth.yaml
  kfdef/kfctl_gcp_iap.v1.0.0.yaml
  kfdef/kfctl_gcp_iap.yaml
  kfdef/kfctl_ibm.v1.0.0.yaml
  kfdef/kfctl_ibm.yaml
  kfdef/kfctl_k8s_istio.v1.0.0.yaml
  kfdef/kfctl_k8s_istio.yaml
  kfdef/source/master/kfctl_gcp_basic_auth.yaml
  kfdef/source/master/kfctl_gcp_iap.yaml
  kfdef/source/master/kfctl_ibm.yaml
  kfdef/source/master/kfctl_k8s_istio.yaml
  kfserving/kfserving-install/base/config-map.yaml
  knative/knative-serving-install/base/config-map.yaml
  knative/knative-serving-install/base/gateway.yaml
  tests/istio-kfserving-gateway-base_test.go
  tests/kfserving-kfserving-install-base_test.go
  tests/kfserving-kfserving-install-overlays-application_test.go
  tests/knative-knative-serving-install-base_test.go
  tests/knative-knative-serving-install-overlays-application_test.go
Labels: approved, cla: yes, lgtm, size/XL

#994 v1.0.1 patch manifests
  kfdef/kfctl_anthos.v1.0.1.yaml
  kfdef/kfctl_aws.v1.0.1.yaml
  kfdef/kfctl_aws_cognito.v1.0.1.yaml
  kfdef/kfctl_gcp_basic_auth.v1.0.1.yaml
  kfdef/kfctl_gcp_iap.v1.0.1.yaml
  kfdef/kfctl_ibm.v1.0.1.yaml
  kfdef/kfctl_istio_dex.v1.0.1.yaml
  kfdef/kfctl_k8s_istio.v1.0.1.yaml
  kfdef/source/v1.0.1/kfctl_anthos.yaml
  kfdef/source/v1.0.1/kfctl_aws.yaml
  kfdef/source/v1.0.1/kfctl_aws_cognito.yaml
  kfdef/source/v1.0.1/kfctl_gcp_basic_auth.yaml
  kfdef/source/v1.0.1/kfctl_gcp_iap.yaml
  kfdef/source/v1.0.1/kfctl_ibm.yaml
  kfdef/source/v1.0.1/kfctl_istio_dex.yaml
  kfdef/source/v1.0.1/kfctl_k8s_istio.yaml
  kfdef/source/v1.0.1/kustomization.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#995 Automated cherry pick of #994: v1.0.1 patch manifests Cherry pick of #994 on v1.0-branch. #994: v1.0.1 patch manifests
  kfdef/kfctl_anthos.v1.0.1.yaml
  kfdef/kfctl_aws.v1.0.1.yaml
  kfdef/kfctl_aws_cognito.v1.0.1.yaml
  kfdef/kfctl_gcp_basic_auth.v1.0.1.yaml
  kfdef/kfctl_gcp_iap.v1.0.1.yaml
  kfdef/kfctl_ibm.v1.0.1.yaml
  kfdef/kfctl_istio_dex.v1.0.1.yaml
  kfdef/kfctl_k8s_istio.v1.0.1.yaml
  kfdef/source/v1.0.1/kfctl_anthos.yaml
  kfdef/source/v1.0.1/kfctl_aws.yaml
  kfdef/source/v1.0.1/kfctl_aws_cognito.yaml
  kfdef/source/v1.0.1/kfctl_gcp_basic_auth.yaml
  kfdef/source/v1.0.1/kfctl_gcp_iap.yaml
  kfdef/source/v1.0.1/kfctl_ibm.yaml
  kfdef/source/v1.0.1/kfctl_istio_dex.yaml
  kfdef/source/v1.0.1/kfctl_k8s_istio.yaml
  kfdef/source/v1.0.1/kustomization.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#996 publish cloud endpoint API spec template
  experimental/gcp/template/openapi.yaml
Labels: approved, cla: yes, lgtm, size/M

#999 iap jwt public key service
  gcp/privateutil/base/iap-jwt-key.yaml
  gcp/privateutil/base/kustomization.yaml
Labels: approved, cla: yes, lgtm, size/L

#661 Adds necessary roles and roleBinding to Spark service account
  spark/spark-operator/base/kustomization.yaml
  spark/spark-operator/base/role.yaml
  spark/spark-operator/base/rolebinding.yaml
  spark/spark-operator/base/spark-sa.yaml
  tests/spark-spark-operator-base_test.go
  tests/spark-spark-operator-overlays-application_test.go
Labels: approved, cla: yes, lgtm, size/L

#967 OWNERS for pipeline folder
  pipeline/OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#971 Experimental GCP config for kubeflow setup
  gcp/cnrm/README.md
  gcp/cnrm/cluster/cluster.yaml
  gcp/cnrm/cluster/istio-operator.yaml
  gcp/cnrm/cluster/nodepool.yaml
  gcp/cnrm/project/enable-services.yaml
  gcp/cnrm/project/kf-admin-sa.yaml
  gcp/cnrm/project/kf-user-sa.yaml
  gcp/cnrm/project/kf-vm-sa.yaml
  istio/iap-gateway/base/istio-ingressgateway.yaml
  istio/iap-gateway/base/kustomization.yaml
  istio/istio/base/kf-istio-resources.yaml
  istio/istio/base/params.env
  kfdef/kfctl_gcp_asm_exp.yaml
  tests/gcp-iap-ingress-base_test.go
  tests/istio-iap-gateway-base_test.go
  tests/istio-istio-base_test.go
  tests/istio-istio-overlays-https-gateway_test.go
  tests/istio-oidc-authservice-base_test.go
  tests/istio-oidc-authservice-overlays-application_test.go
  tests/istio-oidc-authservice-overlays-ibm-storage-config_test.go
Labels: approved, cla: yes, lgtm, size/XXL

#1020 Shorten the name of the workflows to fix the tests #1012.
  prow_config.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1028 Automated cherry pick of #1020: Shorten the name of the workflows to fix the tests #1012. Cherry pick of #1020 on v1.0-branch. #1020: Shorten the name of the workflows to fix the tests #1012.
  prow_config.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1027 Automated cherry pick of #949: Adds kfserving ingressgateway for Istio 1.1.6 Modifies Cherry pick of #949 on v1.0-branch. #949: Adds kfserving ingressgateway for Istio 1.1.6 Modifies
  istio/kfserving-gateway/base/deployment.yaml
  istio/kfserving-gateway/base/horizontal-pod-autoscaler.yaml
  istio/kfserving-gateway/base/kustomization.yaml
  istio/kfserving-gateway/base/service.yaml
  kfdef/kfctl_gcp_basic_auth.v1.0.0.yaml
  kfdef/kfctl_gcp_basic_auth.yaml
  kfdef/kfctl_gcp_iap.v1.0.0.yaml
  kfdef/kfctl_gcp_iap.yaml
  kfdef/kfctl_ibm.v1.0.0.yaml
  kfdef/kfctl_ibm.yaml
  kfdef/kfctl_k8s_istio.v1.0.0.yaml
  kfdef/kfctl_k8s_istio.yaml
  kfdef/source/master/kfctl_gcp_basic_auth.yaml
  kfdef/source/master/kfctl_gcp_iap.yaml
  kfdef/source/master/kfctl_ibm.yaml
  kfdef/source/master/kfctl_k8s_istio.yaml
  kfserving/kfserving-install/base/config-map.yaml
  knative/knative-serving-install/base/config-map.yaml
  knative/knative-serving-install/base/gateway.yaml
  tests/istio-kfserving-gateway-base_test.go
  tests/kfserving-kfserving-install-base_test.go
  tests/kfserving-kfserving-install-overlays-application_test.go
  tests/knative-knative-serving-install-base_test.go
  tests/knative-knative-serving-install-overlays-application_test.go
Labels: approved, cla: yes, lgtm, size/XL

#1037 Revert "Automated cherry pick of #949: Adds kfserving ingressgateway …
  istio/kfserving-gateway/base/deployment.yaml
  istio/kfserving-gateway/base/horizontal-pod-autoscaler.yaml
  istio/kfserving-gateway/base/kustomization.yaml
  istio/kfserving-gateway/base/service.yaml
  kfdef/kfctl_gcp_basic_auth.v1.0.0.yaml
  kfdef/kfctl_gcp_basic_auth.yaml
  kfdef/kfctl_gcp_iap.v1.0.0.yaml
  kfdef/kfctl_gcp_iap.yaml
  kfdef/kfctl_ibm.v1.0.0.yaml
  kfdef/kfctl_ibm.yaml
  kfdef/kfctl_k8s_istio.v1.0.0.yaml
  kfdef/kfctl_k8s_istio.yaml
  kfdef/source/master/kfctl_gcp_basic_auth.yaml
  kfdef/source/master/kfctl_gcp_iap.yaml
  kfdef/source/master/kfctl_ibm.yaml
  kfdef/source/master/kfctl_k8s_istio.yaml
  kfserving/kfserving-install/base/config-map.yaml
  knative/knative-serving-install/base/config-map.yaml
  knative/knative-serving-install/base/gateway.yaml
  tests/istio-kfserving-gateway-base_test.go
  tests/kfserving-kfserving-install-base_test.go
  tests/kfserving-kfserving-install-overlays-application_test.go
  tests/knative-knative-serving-install-base_test.go
  tests/knative-knative-serving-install-overlays-application_test.go
Labels: approved, cla: yes, lgtm, size/XL

#1042 Add container port to profile controller
  profiles/base/deployment.yaml
  tests/profiles/base/test_data/expected/apps_v1_deployment_profiles-deployment.yaml
  tests/profiles/overlays/application/test_data/expected/app.k8s.io_v1beta1_application_profiles.yaml
  tests/profiles/overlays/application/test_data/expected/apps_v1_deployment_profiles-deployment.yaml
  tests/profiles/overlays/application/test_data/expected/~g_v1_configmap_profiles-profiles-parameters-tf7b8dmggt.yaml
  tests/profiles/overlays/application/test_data/expected/~g_v1_service_profiles-kfam.yaml
  tests/profiles/overlays/application/test_data/expected/~g_v1_serviceaccount_profiles-controller-service-account.yaml
  tests/profiles/overlays/debug/test_data/expected/apps_v1_deployment_profiles-deployment.yaml
  tests/profiles/overlays/debug/test_data/expected/~g_v1_configmap_parameters.yaml
  tests/profiles/overlays/debug/test_data/expected/~g_v1_configmap_profiles-profiles-parameters-tf7b8dmggt.yaml
  tests/profiles/overlays/debug/test_data/expected/~g_v1_service_profiles-kfam.yaml
  tests/profiles/overlays/debug/test_data/expected/~g_v1_serviceaccount_profiles-controller-service-account.yaml
  tests/profiles/overlays/devices/test_data/expected/apps_v1_deployment_profiles-deployment.yaml
  tests/profiles/overlays/istio/test_data/expected/apps_v1_deployment_profiles-deployment.yaml
  tests/profiles/overlays/istio/test_data/expected/networking.istio.io_v1alpha3_virtualservice_kfam.yaml
  tests/profiles/overlays/istio/test_data/expected/~g_v1_configmap_profiles-profiles-parameters-tf7b8dmggt.yaml
  tests/profiles/overlays/istio/test_data/expected/~g_v1_service_profiles-kfam.yaml
  tests/profiles/overlays/istio/test_data/expected/~g_v1_serviceaccount_profiles-controller-service-account.yaml
  tests/profiles/overlays/test/test_data/expected/apps_v1_deployment_profiles-deployment.yaml
Labels: approved, cla: yes, lgtm, size/M

#1044 update cnrm to adapt to kcc mode
  gcp/cnrm/README.md
  gcp/cnrm/cluster/cluster.yaml
  gcp/cnrm/cluster/istio-operator.yaml
  gcp/cnrm/project/enable-services.yaml
  gcp/cnrm/project/kf-admin-sa.yaml
  gcp/v2/asm/istio-operator.yaml
  gcp/v2/cnrm/cluster.yaml
  gcp/v2/cnrm/compute-address.yaml
  gcp/v2/cnrm/disk.yaml
  gcp/v2/cnrm/kf-admin-policy.yaml
  gcp/v2/cnrm/kf-admin-sa.yaml
  gcp/v2/cnrm/kf-user-policy.yaml
  gcp/v2/cnrm/kf-user-sa.yaml
  gcp/v2/cnrm/kf-vm-policy.yaml
  gcp/v2/cnrm/kf-vm-sa.yaml
  gcp/v2/cnrm/kustomization.yaml
  gcp/v2/cnrm/nodepool.yaml
  kfdef/kfctl_gcp_asm_exp.yaml
Labels: approved, cla: yes, lgtm, size/XL

#1053 OWNERS for tests/pipeline folder
  tests/pipeline/OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#950 pipeline/api-service: Set minio secure=false
  pipeline/api-service/base/config-map.yaml
  tests/pipeline/api-service/base/test_data/expected/~g_v1_configmap_ml-pipeline-config.yaml
  tests/pipeline/api-service/overlays/application/test_data/expected/~g_v1_configmap_ml-pipeline-config.yaml
  tests/pipeline/api-service/overlays/use-kf-user/test_data/expected/~g_v1_configmap_ml-pipeline-config.yaml
Labels: approved, cla: yes, lgtm, size/S

#1013 Use a configmap generator for the spawner_ui_config.yaml
  jupyter/jupyter-web-app/base/configs/spawner_ui_config.yaml
  jupyter/jupyter-web-app/base/deployment.yaml
  jupyter/jupyter-web-app/base/kustomization.yaml
  tests/jupyter/jupyter-web-app/base/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
  tests/jupyter/jupyter-web-app/base/test_data/expected/~g_v1_configmap_jupyter-web-app-jupyter-web-app-config.yaml
  tests/jupyter/jupyter-web-app/overlays/application/test_data/expected/kubeflow_apps_v1_deployment_jupyter-web-app-deployment.yaml
  tests/jupyter/jupyter-web-app/overlays/application/test_data/expected/kubeflow_~g_v1_configmap_jupyter-web-app-config.yaml
  tests/jupyter/jupyter-web-app/overlays/application/test_data/expected/kubeflow_~g_v1_configmap_jupyter-web-app-jupyter-web-app-config.yaml
Labels: approved, cla: yes, lgtm, size/L

#1058 Update anthos kfdef manifests
  kfdef/kfctl_anthos.v1.0.0.yaml
  kfdef/kfctl_anthos.v1.0.1.yaml
  kfdef/kfctl_anthos.yaml
  kfdef/source/master/kfctl_anthos.yaml
Labels: approved, cla: yes, lgtm, size/M

#989 Update DBConfig.GroupConcatMaxLen in ml-pipeline apiserver config map
  pipeline/api-service/base/config-map.yaml
  tests/pipeline/api-service/base/test_data/expected/~g_v1_configmap_ml-pipeline-config.yaml
  tests/pipeline/api-service/overlays/application/test_data/expected/~g_v1_configmap_ml-pipeline-config.yaml
  tests/pipeline/api-service/overlays/use-kf-user/test_data/expected/~g_v1_configmap_ml-pipeline-config.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/S
