Repository kubeflow/manifests, pull requests merged in 2020-11, with the labels that each got.

#1604 [Fix tests] Skip non SequenceNode yaml to work around on the old kyaml bug
  tests/validate_resources_test.go
Labels: approved, cla: yes, lgtm, size/XS

#1599 Update Notebook OWNERS
  jupyter/OWNERS
  tests/OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#1606 Add PatrickXYS as OWNER of manifests repo
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#1601 Add E2E Test on Kubeflow Shared Test-infra
  prow_config.yaml
  tests/workflows/components/workflows.libsonnet
Labels: approved, cla: yes, do-not-merge/hold, lgtm, size/L

#1607 Update OWNERS file with Arrikto folk
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#1610 Add a test to verify no more use of deprecated env syntax
  aws/fluentd-cloud-watch/base_v3/kustomization.yaml
  prow_config.yaml
  tests/go.mod
  tests/validate_resources_test.go
Labels: approved, cla: yes, lgtm, size/L

#1612 Add AWS Periodic Tests
  prow_config.yaml
Labels: approved, cla: yes, lgtm, size/S

#1594 Ibmcloud appid
  kfdef/kfctl_ibm_multi_user.yaml
  stacks/ibm/application/oidc-authservice-appid/container-env-vars.yaml
  stacks/ibm/application/oidc-authservice-appid/kustomization.yaml
  stacks/ibm/application/oidc-authservice-appid/params.env
  stacks/ibm/application/oidc-authservice-appid/service-account.yaml
  stacks/ibm/application/oidc-authservice-appid/sts-patch.yaml
  stacks/ibm/application/oidc-authservice-appid/vs.yaml
Labels: approved, cla: yes, lgtm, size/M

#1611 Increase unit test argo workflow TTL
  tests/workflows/components/workflows.libsonnet
Labels: approved, cla: yes, lgtm, size/XS

#1615 Add Periodic Tests back
  prow_config.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1567 Adding Openshift stack
  kfdef/kfctl_openshift.v1.1.0.yaml
  stacks/openshift/OWNERS
  stacks/openshift/application/argo/kustomization.yaml
  stacks/openshift/application/cert-manager-crds/kustomization.yaml
  stacks/openshift/application/cert-manager-kube-system-resources/kustomization.yaml
  stacks/openshift/application/cert-manager/kustomization.yaml
  stacks/openshift/application/istio-stack/ingressgateway.route.yaml
  stacks/openshift/application/istio-stack/kustomization.yaml
  stacks/openshift/application/istio/kustomization.yaml
  stacks/openshift/application/istio/params.env
  stacks/openshift/application/istio/params.yaml
  stacks/openshift/application/jupyter-web-app/configs/spawner_ui_config.yaml
  stacks/openshift/application/jupyter-web-app/kustomization.yaml
  stacks/openshift/application/katib/katib-controller-deployment.yaml
  stacks/openshift/application/katib/katib-mysql-deployment-patch.yaml
  stacks/openshift/application/katib/katib-mysql-deployment.yaml
  stacks/openshift/application/katib/katib-mysql-secret.yaml
  stacks/openshift/application/katib/kustomization.yaml
  stacks/openshift/application/metadata/kustomization.yaml
  stacks/openshift/application/metadata/metadata-db-deployment.yaml
  stacks/openshift/application/metadata/metadata-db-serviceaccount.yaml
  stacks/openshift/application/metadata/patchdb.yaml
  stacks/openshift/application/notebook-controller/configs/addfsgroup-env.yaml
  stacks/openshift/application/notebook-controller/kustomization.yaml
  stacks/openshift/application/openshift/openshift-scc/kubeflow-anyuid-scc-istio.yaml
  stacks/openshift/application/openshift/openshift-scc/kubeflow-anyuid-scc.yaml
  stacks/openshift/application/openshift/openshift-scc/kustomization.yaml
  stacks/openshift/application/openshift/openshift-scc/params.env
  stacks/openshift/application/openshift/openshift-scc/params.yaml
  stacks/openshift/application/pipeline/kustomization.yaml
  stacks/openshift/application/pipeline/patchuirule.yaml
  stacks/openshift/application/pipeline/sync.py
  stacks/openshift/application/profiles/kustomization.yaml
  stacks/openshift/application/pytorch-job/kustomization.yaml
  stacks/openshift/application/seldon/deploymentpatchport.yaml
  stacks/openshift/application/seldon/kustomization.yaml
  stacks/openshift/application/seldon/patchport.yaml
  stacks/openshift/application/seldon/resourcepatchport.yaml
  stacks/openshift/application/seldon/vpatchport.yaml
  stacks/openshift/application/tf-job/kustomization.yaml
  stacks/openshift/config/params.env
  stacks/openshift/kustomization.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#1624 Pin test manifest to v1.2-branch
  prow_config.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1562 fix mysql deployment strategy
  katib/katib-controller/base/katib-mysql-deployment.yaml
  metadata/overlays/db/metadata-db-deployment.yaml
  tests/katib/installs/katib-standalone-ibm/test_data/expected/apps_v1_deployment_katib-mysql.yaml
  tests/katib/installs/katib-standalone/test_data/expected/apps_v1_deployment_katib-mysql.yaml
  tests/stacks/aws/test_data/expected/apps_v1_deployment_katib-mysql.yaml
  tests/stacks/aws/test_data/expected/apps_v1_deployment_metadata-db.yaml
  tests/stacks/examples/alice/test_data/expected/apps_v1_deployment_katib-mysql.yaml
  tests/stacks/examples/alice/test_data/expected/apps_v1_deployment_metadata-db.yaml
  tests/stacks/gcp/test_data/expected/apps_v1_deployment_katib-mysql.yaml
  tests/stacks/gcp/test_data/expected/apps_v1_deployment_metadata-db.yaml
  tests/stacks/generic/test_data/expected/apps_v1_deployment_katib-mysql.yaml
  tests/stacks/generic/test_data/expected/apps_v1_deployment_metadata-db.yaml
  tests/stacks/ibm/application/katib/test_data/expected/apps_v1_deployment_katib-mysql.yaml
  tests/stacks/ibm/application/metadata/test_data/expected/apps_v1_deployment_metadata-db.yaml
  tests/stacks/ibm/multi-user/test_data/expected/apps_v1_deployment_katib-mysql.yaml
  tests/stacks/ibm/multi-user/test_data/expected/apps_v1_deployment_metadata-db.yaml
  tests/stacks/ibm/test_data/expected/apps_v1_deployment_katib-mysql.yaml
  tests/stacks/ibm/test_data/expected/apps_v1_deployment_metadata-db.yaml
  tests/stacks/kubernetes/test_data/expected/apps_v1_deployment_katib-mysql.yaml
  tests/stacks/kubernetes/test_data/expected/apps_v1_deployment_metadata-db.yaml
  tests/stacks/openshift/application/katib/test_data/expected/apps_v1_deployment_katib-mysql.yaml
  tests/stacks/openshift/application/metadata/test_data/expected/apps_v1_deployment_metadata-db.yaml
  tests/tests/legacy_kustomizations/katib-controller/test_data/expected/apps_v1_deployment_katib-mysql.yaml
  tests/tests/legacy_kustomizations/metadata/test_data/expected/apps_v1_deployment_metadata-db.yaml
Labels: approved, cla: yes, lgtm, size/M

#1627 Pin IBM v1.2 manifests
  kfdef/kfctl_ibm.v1.2.0.yaml
  kfdef/kfctl_ibm_multi_user.v1.2.0.yaml
Labels: approved, cla: yes, lgtm, size/L

#1629 Remove Tensorboard for AWS 1.2 Manifests
  kfdef/kfctl_aws.v1.2.0.yaml
  kfdef/kfctl_aws_cognito.v1.2.0.yaml
Labels: approved, cla: yes, lgtm, size/S

#1630 Presubmit kicked off by istio_dex manifests
  prow_config.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1631 Cherry-Pick AWS PR #1629 #1630
  kfdef/kfctl_aws.v1.2.0.yaml
  kfdef/kfctl_aws_cognito.v1.2.0.yaml
  prow_config.yaml
Labels: approved, cla: yes, lgtm, size/S

#1632 Add Paul as a reviewer
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#1636 Rollout AWS Jupyter images to 1.2.0
  stacks/aws/application/jupyter-web-app/configs/spawner_ui_config.yaml
  tests/stacks/aws/application/jupyter-web-app/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
  tests/stacks/aws/application/jupyter-web-app/test_data/expected/~g_v1_configmap_jupyter-web-app-jupyter-web-app-config-8fc6g84c8k.yaml
  tests/stacks/aws/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
  tests/stacks/aws/test_data/expected/~g_v1_configmap_jupyter-web-app-jupyter-web-app-config-8fc6g84c8k.yaml
Labels: approved, cla: yes, lgtm, size/M

#1633 Replacement PR for PR #1625 - Azure kfdef manifests for 1.2 and previous
  istio/add-anonymous-user-filter-istio-1.6/envoy-filter.yaml
  istio/add-anonymous-user-filter-istio-1.6/kustomization.yaml
  kfdef/OWNERS
  kfdef/kfctl_azure.v1.1.0.yaml
  kfdef/kfctl_azure.v1.2.0.yaml
  kfdef/kfctl_azure_aad.v1.1.0.yaml
  kfdef/kfctl_azure_aad.v1.2.0.yaml
  stacks/azure/OWNERS
  stacks/azure/application/add-anonymous-user-filter-istio-1.6/kustomization.yaml
  stacks/azure/application/cert-manager-crds/kustomization.yaml
  stacks/azure/application/cert-manager-kube-system-resources/kustomization.yaml
  stacks/azure/application/cert-manager/kustomization.yaml
  stacks/azure/application/istio-1-3-1-stack/kustomization.yaml
  stacks/azure/application/istio/kustomization.yaml
  stacks/azure/application/istio/params.env
  stacks/azure/application/istio/params.yaml
  stacks/azure/application/jupyter-web-app/base/deployment_patch.yaml
  stacks/azure/application/jupyter-web-app/base/kustomization.yaml
  stacks/azure/application/jupyter-web-app/base/params.env
  stacks/azure/application/jupyter-web-app/base/params.yaml
  stacks/azure/application/jupyter-web-app/kustomization.yaml
  stacks/azure/application/oidc-authservice/kustomization.yaml
  stacks/azure/application/spark-operator/kustomization.yaml
  stacks/azure/application/spartakus/kustomization.yaml
  stacks/azure/config/params.env
  stacks/azure/kustomization.yaml
  stacks/azure/metadata/Readme.md
  stacks/azure/metadata/kustomization.yaml
  stacks/azure/metadata/metadata-deployment.yaml
  stacks/azure/metadata/params.env
  stacks/azure/metadata/secrets.env
Labels: approved, cla: yes, lgtm, size/XL

#1638 feat: remove kf metadata server
  metadata/base/metadata-deployment.yaml
  metadata/base/metadata-service.yaml
  metadata/overlays/db/metadata-deployment.yaml
  metadata/overlays/external-mysql/metadata-deployment.yaml
  tests/stacks/aws/test_data/expected/apps_v1_deployment_metadata-deployment.yaml
  tests/stacks/aws/test_data/expected/~g_v1_service_metadata-service.yaml
  tests/stacks/examples/alice/test_data/expected/apps_v1_deployment_metadata-deployment.yaml
  tests/stacks/examples/alice/test_data/expected/~g_v1_service_metadata-service.yaml
  tests/stacks/gcp/test_data/expected/apps_v1_deployment_metadata-deployment.yaml
  tests/stacks/gcp/test_data/expected/~g_v1_service_metadata-service.yaml
  tests/stacks/generic/test_data/expected/apps_v1_deployment_metadata-deployment.yaml
  tests/stacks/generic/test_data/expected/~g_v1_service_metadata-service.yaml
  tests/stacks/ibm/application/metadata/test_data/expected/apps_v1_deployment_metadata-deployment.yaml
  tests/stacks/ibm/application/metadata/test_data/expected/~g_v1_service_metadata-service.yaml
  tests/stacks/ibm/multi-user/test_data/expected/apps_v1_deployment_metadata-deployment.yaml
  tests/stacks/ibm/multi-user/test_data/expected/~g_v1_service_metadata-service.yaml
  tests/stacks/ibm/test_data/expected/apps_v1_deployment_metadata-deployment.yaml
  tests/stacks/ibm/test_data/expected/~g_v1_service_metadata-service.yaml
  tests/stacks/kubernetes/test_data/expected/apps_v1_deployment_metadata-deployment.yaml
  tests/stacks/kubernetes/test_data/expected/~g_v1_service_metadata-service.yaml
  tests/stacks/openshift/application/metadata/test_data/expected/apps_v1_deployment_metadata-deployment.yaml
  tests/stacks/openshift/application/metadata/test_data/expected/~g_v1_service_metadata-service.yaml
  tests/tests/legacy_kustomizations/metadata/test_data/expected/apps_v1_deployment_metadata-deployment.yaml
  tests/tests/legacy_kustomizations/metadata/test_data/expected/~g_v1_service_metadata-service.yaml
Labels: approved, cla: yes, lgtm, size/XL

#1639 Cherry-Pick #1637 PR into v1.2-branch
  stacks/aws/application/jupyter-web-app/configs/spawner_ui_config.yaml
  tests/stacks/aws/application/jupyter-web-app/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
  tests/stacks/aws/application/jupyter-web-app/test_data/expected/~g_v1_configmap_jupyter-web-app-jupyter-web-app-config-8fc6g84c8k.yaml
  tests/stacks/aws/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
  tests/stacks/aws/test_data/expected/~g_v1_configmap_jupyter-web-app-jupyter-web-app-config-8fc6g84c8k.yaml
Labels: approved, cla: yes, lgtm, size/M

#1641 Cherry pick of "feat: remove kf metadata server #1638"
  metadata/base/metadata-deployment.yaml
  metadata/base/metadata-service.yaml
  metadata/overlays/db/metadata-deployment.yaml
  metadata/overlays/external-mysql/metadata-deployment.yaml
  tests/stacks/aws/test_data/expected/apps_v1_deployment_metadata-deployment.yaml
  tests/stacks/aws/test_data/expected/~g_v1_service_metadata-service.yaml
  tests/stacks/examples/alice/test_data/expected/apps_v1_deployment_metadata-deployment.yaml
  tests/stacks/examples/alice/test_data/expected/~g_v1_service_metadata-service.yaml
  tests/stacks/gcp/test_data/expected/apps_v1_deployment_metadata-deployment.yaml
  tests/stacks/gcp/test_data/expected/~g_v1_service_metadata-service.yaml
  tests/stacks/generic/test_data/expected/apps_v1_deployment_metadata-deployment.yaml
  tests/stacks/generic/test_data/expected/~g_v1_service_metadata-service.yaml
  tests/stacks/ibm/application/metadata/test_data/expected/apps_v1_deployment_metadata-deployment.yaml
  tests/stacks/ibm/application/metadata/test_data/expected/~g_v1_service_metadata-service.yaml
  tests/stacks/ibm/multi-user/test_data/expected/apps_v1_deployment_metadata-deployment.yaml
  tests/stacks/ibm/multi-user/test_data/expected/~g_v1_service_metadata-service.yaml
  tests/stacks/ibm/test_data/expected/apps_v1_deployment_metadata-deployment.yaml
  tests/stacks/ibm/test_data/expected/~g_v1_service_metadata-service.yaml
  tests/stacks/kubernetes/test_data/expected/apps_v1_deployment_metadata-deployment.yaml
  tests/stacks/kubernetes/test_data/expected/~g_v1_service_metadata-service.yaml
  tests/stacks/openshift/application/metadata/test_data/expected/apps_v1_deployment_metadata-deployment.yaml
  tests/stacks/openshift/application/metadata/test_data/expected/~g_v1_service_metadata-service.yaml
  tests/tests/legacy_kustomizations/metadata/test_data/expected/apps_v1_deployment_metadata-deployment.yaml
  tests/tests/legacy_kustomizations/metadata/test_data/expected/~g_v1_service_metadata-service.yaml
Labels: approved, cla: yes, lgtm, size/XL

#1643 fix mysql deployment strategy (#1562)
  katib/katib-controller/base/katib-mysql-deployment.yaml
  metadata/overlays/db/metadata-db-deployment.yaml
  tests/katib/installs/katib-standalone-ibm/test_data/expected/apps_v1_deployment_katib-mysql.yaml
  tests/katib/installs/katib-standalone/test_data/expected/apps_v1_deployment_katib-mysql.yaml
  tests/stacks/aws/test_data/expected/apps_v1_deployment_katib-mysql.yaml
  tests/stacks/aws/test_data/expected/apps_v1_deployment_metadata-db.yaml
  tests/stacks/azure/test_data/expected/apps_v1_deployment_katib-mysql.yaml
  tests/stacks/azure/test_data/expected/apps_v1_deployment_metadata-db.yaml
  tests/stacks/examples/alice/test_data/expected/apps_v1_deployment_katib-mysql.yaml
  tests/stacks/examples/alice/test_data/expected/apps_v1_deployment_metadata-db.yaml
  tests/stacks/gcp/test_data/expected/apps_v1_deployment_katib-mysql.yaml
  tests/stacks/gcp/test_data/expected/apps_v1_deployment_metadata-db.yaml
  tests/stacks/generic/test_data/expected/apps_v1_deployment_katib-mysql.yaml
  tests/stacks/generic/test_data/expected/apps_v1_deployment_metadata-db.yaml
  tests/stacks/ibm/application/katib/test_data/expected/apps_v1_deployment_katib-mysql.yaml
  tests/stacks/ibm/application/metadata/test_data/expected/apps_v1_deployment_metadata-db.yaml
  tests/stacks/ibm/multi-user/test_data/expected/apps_v1_deployment_katib-mysql.yaml
  tests/stacks/ibm/multi-user/test_data/expected/apps_v1_deployment_metadata-db.yaml
  tests/stacks/ibm/test_data/expected/apps_v1_deployment_katib-mysql.yaml
  tests/stacks/ibm/test_data/expected/apps_v1_deployment_metadata-db.yaml
  tests/stacks/kubernetes/test_data/expected/apps_v1_deployment_katib-mysql.yaml
  tests/stacks/kubernetes/test_data/expected/apps_v1_deployment_metadata-db.yaml
  tests/stacks/openshift/application/katib/test_data/expected/apps_v1_deployment_katib-mysql.yaml
  tests/stacks/openshift/application/metadata/test_data/expected/apps_v1_deployment_metadata-db.yaml
  tests/tests/legacy_kustomizations/katib-controller/test_data/expected/apps_v1_deployment_katib-mysql.yaml
  tests/tests/legacy_kustomizations/metadata/test_data/expected/apps_v1_deployment_metadata-db.yaml
Labels: approved, cla: yes, lgtm, size/M

#1644 update jupyter config with tolerations/selectors
  jupyter/jupyter-web-app/base/configs/spawner_ui_config.yaml
  tests/stacks/azure/application/jupyter-web-app/base/test_data/expected/~g_v1_configmap_jupyter-web-app-jupyter-web-app-config.yaml
  tests/stacks/azure/application/jupyter-web-app/test_data/expected/~g_v1_configmap_jupyter-web-app-jupyter-web-app-config.yaml
  tests/stacks/azure/test_data/expected/~g_v1_configmap_jupyter-web-app-jupyter-web-app-config.yaml
  tests/stacks/gcp/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
  tests/stacks/gcp/test_data/expected/~g_v1_configmap_jupyter-web-app-jupyter-web-app-config-8kcgd8t8th.yaml
  tests/stacks/generic/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
  tests/stacks/generic/test_data/expected/~g_v1_configmap_jupyter-web-app-jupyter-web-app-config-8kcgd8t8th.yaml
  tests/stacks/ibm/application/jupyter-web-app/base/test_data/expected/~g_v1_configmap_jupyter-web-app-jupyter-web-app-config.yaml
  tests/stacks/ibm/application/jupyter-web-app/test_data/expected/~g_v1_configmap_jupyter-web-app-jupyter-web-app-config.yaml
  tests/stacks/ibm/application/notebooks/test_data/expected/~g_v1_configmap_jupyter-web-app-jupyter-web-app-config.yaml
  tests/stacks/ibm/multi-user/test_data/expected/~g_v1_configmap_jupyter-web-app-jupyter-web-app-config.yaml
  tests/stacks/ibm/test_data/expected/~g_v1_configmap_jupyter-web-app-jupyter-web-app-config.yaml
  tests/stacks/kubernetes/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
  tests/stacks/kubernetes/test_data/expected/~g_v1_configmap_jupyter-web-app-jupyter-web-app-config-8kcgd8t8th.yaml
  tests/tests/legacy_kustomizations/jupyter-web-app/test_data/expected/~g_v1_configmap_jupyter-web-app-jupyter-web-app-config.yaml
Labels: approved, cla: yes, lgtm, size/XL

#1645 update image tags
  admission-webhook/webhook/base/kustomization.yaml
  common/centraldashboard/base/kustomization.yaml
  common/centraldashboard/base_v3/kustomization.yaml
  jupyter/jupyter-web-app/base_v3/kustomization.yaml
  jupyter/notebook-controller/base_v3/kustomization.yaml
  profiles/base_v3/kustomization.yaml
  tests/stacks/aws/application/jupyter-web-app/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
  tests/stacks/aws/test_data/expected/apps_v1_deployment_admission-webhook-deployment.yaml
  tests/stacks/aws/test_data/expected/apps_v1_deployment_centraldashboard.yaml
  tests/stacks/aws/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
  tests/stacks/aws/test_data/expected/apps_v1_deployment_notebook-controller-deployment.yaml
  tests/stacks/aws/test_data/expected/apps_v1_deployment_profiles-deployment.yaml
  tests/stacks/azure/test_data/expected/apps_v1_deployment_admission-webhook-deployment.yaml
  tests/stacks/azure/test_data/expected/apps_v1_deployment_centraldashboard.yaml
  tests/stacks/azure/test_data/expected/apps_v1_deployment_notebook-controller-deployment.yaml
  tests/stacks/azure/test_data/expected/apps_v1_deployment_profiles-deployment.yaml
  tests/stacks/examples/alice/test_data/expected/apps_v1_deployment_admission-webhook-deployment.yaml
  tests/stacks/examples/alice/test_data/expected/apps_v1_deployment_centraldashboard.yaml
  tests/stacks/examples/alice/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
  tests/stacks/examples/alice/test_data/expected/apps_v1_deployment_notebook-controller-deployment.yaml
  tests/stacks/examples/alice/test_data/expected/apps_v1_deployment_profiles-deployment.yaml
  tests/stacks/gcp/test_data/expected/apps_v1_deployment_admission-webhook-deployment.yaml
  tests/stacks/gcp/test_data/expected/apps_v1_deployment_centraldashboard.yaml
  tests/stacks/gcp/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
  tests/stacks/gcp/test_data/expected/apps_v1_deployment_notebook-controller-deployment.yaml
  tests/stacks/gcp/test_data/expected/apps_v1_deployment_profiles-deployment.yaml
  tests/stacks/generic/test_data/expected/apps_v1_deployment_admission-webhook-deployment.yaml
  tests/stacks/generic/test_data/expected/apps_v1_deployment_centraldashboard.yaml
  tests/stacks/generic/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
  tests/stacks/generic/test_data/expected/apps_v1_deployment_notebook-controller-deployment.yaml
  tests/stacks/generic/test_data/expected/apps_v1_deployment_profiles-deployment.yaml
  tests/stacks/ibm/application/admission-webhook/test_data/expected/apps_v1_deployment_admission-webhook-deployment.yaml
  tests/stacks/ibm/application/profile-control-plane/test_data/expected/apps_v1_deployment_centraldashboard.yaml
  tests/stacks/ibm/multi-user/test_data/expected/apps_v1_deployment_admission-webhook-deployment.yaml
  tests/stacks/ibm/multi-user/test_data/expected/apps_v1_deployment_centraldashboard.yaml
  tests/stacks/ibm/test_data/expected/apps_v1_deployment_admission-webhook-deployment.yaml
  tests/stacks/ibm/test_data/expected/apps_v1_deployment_centraldashboard.yaml
  tests/stacks/kubernetes/test_data/expected/apps_v1_deployment_admission-webhook-deployment.yaml
  tests/stacks/kubernetes/test_data/expected/apps_v1_deployment_centraldashboard.yaml
  tests/stacks/kubernetes/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
  tests/stacks/kubernetes/test_data/expected/apps_v1_deployment_notebook-controller-deployment.yaml
  tests/stacks/kubernetes/test_data/expected/apps_v1_deployment_profiles-deployment.yaml
  tests/stacks/openshift/application/notebook-controller/test_data/expected/apps_v1_deployment_notebook-controller-deployment.yaml
  tests/stacks/openshift/application/profiles/test_data/expected/apps_v1_deployment_profiles-deployment.yaml
  tests/stacks/openshift/test_data/expected/apps_v1_deployment_centraldashboard.yaml
  tests/stacks/openshift/test_data/expected/apps_v1_deployment_profiles-deployment.yaml
  tests/tests/legacy_kustomizations/centraldashboard/test_data/expected/apps_v1_deployment_centraldashboard.yaml
  tests/tests/legacy_kustomizations/webhook/test_data/expected/apps_v1_deployment_admission-webhook-deployment.yaml
Labels: approved, cla: yes, lgtm, size/L

#1650 Enable AWS Kubeflow-Kubernetes Periodic Tests
  prow_config.yaml
Labels: approved, cla: yes, lgtm, size/M

#1651 Enable AWS Kubeflow-Kubernetes Periodic Tests in v1.2-branch
  prow_config.yaml
Labels: approved, cla: yes, lgtm, size/M

#1652 [IBM] Update notebooks and profiles image tags
  stacks/ibm/application/jupyter-web-app/base/kustomization.yaml
  stacks/ibm/application/notebook-controller/base/kustomization.yaml
  stacks/ibm/application/profiles/base/kustomization.yaml
  tests/stacks/ibm/application/jupyter-web-app/base/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
  tests/stacks/ibm/application/jupyter-web-app/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
  tests/stacks/ibm/application/notebook-controller/base/test_data/expected/apps_v1_deployment_notebook-controller-deployment.yaml
  tests/stacks/ibm/application/notebook-controller/test_data/expected/kubeflow_apps_v1_deployment_notebook-controller-deployment.yaml
  tests/stacks/ibm/application/notebooks/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
  tests/stacks/ibm/application/notebooks/test_data/expected/apps_v1_deployment_notebook-controller-deployment.yaml
  tests/stacks/ibm/application/profile-control-plane/test_data/expected/apps_v1_deployment_profiles-deployment.yaml
  tests/stacks/ibm/application/profiles/base/test_data/expected/apps_v1_deployment_profiles-deployment.yaml
  tests/stacks/ibm/application/profiles/test_data/expected/apps_v1_deployment_profiles-deployment.yaml
  tests/stacks/ibm/multi-user/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
  tests/stacks/ibm/multi-user/test_data/expected/apps_v1_deployment_notebook-controller-deployment.yaml
  tests/stacks/ibm/multi-user/test_data/expected/apps_v1_deployment_profiles-deployment.yaml
  tests/stacks/ibm/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
  tests/stacks/ibm/test_data/expected/apps_v1_deployment_notebook-controller-deployment.yaml
  tests/stacks/ibm/test_data/expected/apps_v1_deployment_profiles-deployment.yaml
Labels: approved, cla: yes, lgtm, size/M

#1653 Cherry-pick of '[IBM] Update notebooks and profiles image tags' (#1652) to v1.2-branch
  stacks/ibm/application/jupyter-web-app/base/kustomization.yaml
  stacks/ibm/application/notebook-controller/base/kustomization.yaml
  stacks/ibm/application/profiles/base/kustomization.yaml
  tests/stacks/ibm/application/jupyter-web-app/base/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
  tests/stacks/ibm/application/jupyter-web-app/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
  tests/stacks/ibm/application/notebook-controller/base/test_data/expected/apps_v1_deployment_notebook-controller-deployment.yaml
  tests/stacks/ibm/application/notebook-controller/test_data/expected/kubeflow_apps_v1_deployment_notebook-controller-deployment.yaml
  tests/stacks/ibm/application/notebooks/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
  tests/stacks/ibm/application/notebooks/test_data/expected/apps_v1_deployment_notebook-controller-deployment.yaml
  tests/stacks/ibm/application/profile-control-plane/test_data/expected/apps_v1_deployment_profiles-deployment.yaml
  tests/stacks/ibm/application/profiles/base/test_data/expected/apps_v1_deployment_profiles-deployment.yaml
  tests/stacks/ibm/application/profiles/test_data/expected/apps_v1_deployment_profiles-deployment.yaml
  tests/stacks/ibm/multi-user/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
  tests/stacks/ibm/multi-user/test_data/expected/apps_v1_deployment_notebook-controller-deployment.yaml
  tests/stacks/ibm/multi-user/test_data/expected/apps_v1_deployment_profiles-deployment.yaml
  tests/stacks/ibm/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
  tests/stacks/ibm/test_data/expected/apps_v1_deployment_notebook-controller-deployment.yaml
  tests/stacks/ibm/test_data/expected/apps_v1_deployment_profiles-deployment.yaml
Labels: approved, cla: yes, lgtm, size/M

#1469 Add Flink Operator to Kubeflow manifests
  flink/OWNERS
  flink/flink-operator/README.md
  flink/flink-operator/base/cluster-role-binding.yaml
  flink/flink-operator/base/cluster-role.yaml
  flink/flink-operator/base/configmap.yaml
  flink/flink-operator/base/crd.yaml
  flink/flink-operator/base/deployment.yaml
  flink/flink-operator/base/kustomization.yaml
  flink/flink-operator/base/leader-election-role-binding.yaml
  flink/flink-operator/base/leader-election-role.yaml
  flink/flink-operator/base/service-account.yaml
  flink/flink-operator/base/service.yaml
  flink/flink-operator/base/setup-job.yaml
  flink/flink-operator/base/webhook.yaml
  flink/flink-operator/overlay/application/application.yaml
  flink/flink-operator/overlay/application/kustomization.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#1657 Update jupyter web app image tag for Azure Stack
  stacks/azure/application/jupyter-web-app/base/kustomization.yaml
  tests/stacks/azure/application/jupyter-web-app/base/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
  tests/stacks/azure/application/jupyter-web-app/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
  tests/stacks/azure/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1662 Update jupyter config with tolerations/selectors for aws
  stacks/aws/application/jupyter-web-app/configs/spawner_ui_config.yaml
  tests/stacks/aws/application/jupyter-web-app/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
  tests/stacks/aws/application/jupyter-web-app/test_data/expected/~g_v1_configmap_jupyter-web-app-jupyter-web-app-config-24bth2gbkc.yaml
  tests/stacks/aws/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
  tests/stacks/aws/test_data/expected/~g_v1_configmap_jupyter-web-app-jupyter-web-app-config-24bth2gbkc.yaml
Labels: approved, cla: yes, lgtm, size/L

#1663 fix(kfp): fix application label selector. Part of #1573
  pipeline/installs/generic/application.yaml
  tests/stacks/aws/test_data/expected/app.k8s.io_v1beta1_application_kubeflow-pipelines.yaml
  tests/stacks/azure/test_data/expected/app.k8s.io_v1beta1_application_kubeflow-pipelines.yaml
  tests/stacks/examples/alice/test_data/expected/app.k8s.io_v1beta1_application_kubeflow-pipelines.yaml
  tests/stacks/gcp/test_data/expected/app.k8s.io_v1beta1_application_kubeflow-pipelines.yaml
  tests/stacks/generic/test_data/expected/app.k8s.io_v1beta1_application_kubeflow-pipelines.yaml
  tests/stacks/ibm/application/kfp-argo-multi-user/test_data/expected/app.k8s.io_v1beta1_application_kubeflow-pipelines.yaml
  tests/stacks/ibm/application/kfp-argo/test_data/expected/app.k8s.io_v1beta1_application_kubeflow-pipelines.yaml
  tests/stacks/ibm/application/kfp-tekton-multi-user/test_data/expected/app.k8s.io_v1beta1_application_kubeflow-pipelines.yaml
  tests/stacks/ibm/application/kfp-tekton/test_data/expected/app.k8s.io_v1beta1_application_kubeflow-pipelines.yaml
  tests/stacks/ibm/multi-user/test_data/expected/app.k8s.io_v1beta1_application_kubeflow-pipelines.yaml
  tests/stacks/ibm/test_data/expected/app.k8s.io_v1beta1_application_kubeflow-pipelines.yaml
  tests/stacks/kubernetes/test_data/expected/app.k8s.io_v1beta1_application_kubeflow-pipelines.yaml
  tests/stacks/openshift/application/pipeline/test_data/expected/app.k8s.io_v1beta1_application_kubeflow-pipelines.yaml
Labels: approved, cla: yes, lgtm, size/S

#1664 Automated cherry pick of #1662: Update jupyter config with tolerations/selectors for aws
  stacks/aws/application/jupyter-web-app/configs/spawner_ui_config.yaml
  tests/stacks/aws/application/jupyter-web-app/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
  tests/stacks/aws/application/jupyter-web-app/test_data/expected/~g_v1_configmap_jupyter-web-app-jupyter-web-app-config-24bth2gbkc.yaml
  tests/stacks/aws/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
  tests/stacks/aws/test_data/expected/~g_v1_configmap_jupyter-web-app-jupyter-web-app-config-24bth2gbkc.yaml
Labels: approved, cla: yes, size/L

#1665 Cherry picks "fix(kfp): fix application label selector. Part of #1573"
  pipeline/installs/generic/application.yaml
  tests/stacks/aws/test_data/expected/app.k8s.io_v1beta1_application_kubeflow-pipelines.yaml
  tests/stacks/azure/test_data/expected/app.k8s.io_v1beta1_application_kubeflow-pipelines.yaml
  tests/stacks/examples/alice/test_data/expected/app.k8s.io_v1beta1_application_kubeflow-pipelines.yaml
  tests/stacks/gcp/test_data/expected/app.k8s.io_v1beta1_application_kubeflow-pipelines.yaml
  tests/stacks/generic/test_data/expected/app.k8s.io_v1beta1_application_kubeflow-pipelines.yaml
  tests/stacks/ibm/application/kfp-argo-multi-user/test_data/expected/app.k8s.io_v1beta1_application_kubeflow-pipelines.yaml
  tests/stacks/ibm/application/kfp-argo/test_data/expected/app.k8s.io_v1beta1_application_kubeflow-pipelines.yaml
  tests/stacks/ibm/application/kfp-tekton-multi-user/test_data/expected/app.k8s.io_v1beta1_application_kubeflow-pipelines.yaml
  tests/stacks/ibm/application/kfp-tekton/test_data/expected/app.k8s.io_v1beta1_application_kubeflow-pipelines.yaml
  tests/stacks/ibm/multi-user/test_data/expected/app.k8s.io_v1beta1_application_kubeflow-pipelines.yaml
  tests/stacks/ibm/test_data/expected/app.k8s.io_v1beta1_application_kubeflow-pipelines.yaml
  tests/stacks/kubernetes/test_data/expected/app.k8s.io_v1beta1_application_kubeflow-pipelines.yaml
  tests/stacks/openshift/application/pipeline/test_data/expected/app.k8s.io_v1beta1_application_kubeflow-pipelines.yaml
Labels: approved, cla: yes, lgtm, size/S

#1670 Fix web hook variables in seldon kustomize not being updated by kfctl
  seldon/Makefile
  seldon/seldon-core-operator/base/resources.yaml
  tests/stacks/aws/test_data/expected/admissionregistration.k8s.io_v1beta1_mutatingwebhookconfiguration_seldon-mutating-webhook-configuration-kubeflow.yaml
  tests/stacks/aws/test_data/expected/admissionregistration.k8s.io_v1beta1_validatingwebhookconfiguration_seldon-validating-webhook-configuration-kubeflow.yaml
  tests/stacks/aws/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_seldondeployments.machinelearning.seldon.io.yaml
  tests/stacks/ibm/application/seldon-core-operator/test_data/expected/admissionregistration.k8s.io_v1beta1_mutatingwebhookconfiguration_seldon-mutating-webhook-configuration-kubeflow.yaml
  tests/stacks/ibm/application/seldon-core-operator/test_data/expected/admissionregistration.k8s.io_v1beta1_validatingwebhookconfiguration_seldon-validating-webhook-configuration-kubeflow.yaml
  tests/stacks/ibm/multi-user/test_data/expected/admissionregistration.k8s.io_v1beta1_mutatingwebhookconfiguration_seldon-mutating-webhook-configuration-kubeflow.yaml
  tests/stacks/ibm/multi-user/test_data/expected/admissionregistration.k8s.io_v1beta1_validatingwebhookconfiguration_seldon-validating-webhook-configuration-kubeflow.yaml
  tests/stacks/ibm/multi-user/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_seldondeployments.machinelearning.seldon.io.yaml
  tests/stacks/ibm/test_data/expected/admissionregistration.k8s.io_v1beta1_mutatingwebhookconfiguration_seldon-mutating-webhook-configuration-kubeflow.yaml
  tests/stacks/ibm/test_data/expected/admissionregistration.k8s.io_v1beta1_validatingwebhookconfiguration_seldon-validating-webhook-configuration-kubeflow.yaml
  tests/stacks/ibm/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_seldondeployments.machinelearning.seldon.io.yaml
  tests/stacks/kubernetes/test_data/expected/admissionregistration.k8s.io_v1beta1_mutatingwebhookconfiguration_seldon-mutating-webhook-configuration-kubeflow.yaml
  tests/stacks/kubernetes/test_data/expected/admissionregistration.k8s.io_v1beta1_validatingwebhookconfiguration_seldon-validating-webhook-configuration-kubeflow.yaml
  tests/stacks/kubernetes/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_seldondeployments.machinelearning.seldon.io.yaml
  tests/stacks/openshift/application/seldon/test_data/expected/admissionregistration.k8s.io_v1beta1_mutatingwebhookconfiguration_seldon-mutating-webhook-configuration-kubeflow.yaml
  tests/stacks/openshift/application/seldon/test_data/expected/admissionregistration.k8s.io_v1beta1_validatingwebhookconfiguration_seldon-validating-webhook-configuration-kubeflow.yaml
  tests/tests/legacy_kustomizations/seldon-core-operator/test_data/expected/admissionregistration.k8s.io_v1beta1_mutatingwebhookconfiguration_seldon-mutating-webhook-configuration-kubeflow.yaml
  tests/tests/legacy_kustomizations/seldon-core-operator/test_data/expected/admissionregistration.k8s.io_v1beta1_validatingwebhookconfiguration_seldon-validating-webhook-configuration-kubeflow.yaml
Labels: approved, cla: yes, lgtm, size/L

#1671 Cherry pick: Fix web hook variables in seldon kustomize not being updated by kfctl
  seldon/Makefile
  seldon/seldon-core-operator/base/resources.yaml
  tests/stacks/aws/test_data/expected/admissionregistration.k8s.io_v1beta1_mutatingwebhookconfiguration_seldon-mutating-webhook-configuration-kubeflow.yaml
  tests/stacks/aws/test_data/expected/admissionregistration.k8s.io_v1beta1_validatingwebhookconfiguration_seldon-validating-webhook-configuration-kubeflow.yaml
  tests/stacks/aws/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_seldondeployments.machinelearning.seldon.io.yaml
  tests/stacks/ibm/application/seldon-core-operator/test_data/expected/admissionregistration.k8s.io_v1beta1_mutatingwebhookconfiguration_seldon-mutating-webhook-configuration-kubeflow.yaml
  tests/stacks/ibm/application/seldon-core-operator/test_data/expected/admissionregistration.k8s.io_v1beta1_validatingwebhookconfiguration_seldon-validating-webhook-configuration-kubeflow.yaml
  tests/stacks/ibm/multi-user/test_data/expected/admissionregistration.k8s.io_v1beta1_mutatingwebhookconfiguration_seldon-mutating-webhook-configuration-kubeflow.yaml
  tests/stacks/ibm/multi-user/test_data/expected/admissionregistration.k8s.io_v1beta1_validatingwebhookconfiguration_seldon-validating-webhook-configuration-kubeflow.yaml
  tests/stacks/ibm/multi-user/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_seldondeployments.machinelearning.seldon.io.yaml
  tests/stacks/ibm/test_data/expected/admissionregistration.k8s.io_v1beta1_mutatingwebhookconfiguration_seldon-mutating-webhook-configuration-kubeflow.yaml
  tests/stacks/ibm/test_data/expected/admissionregistration.k8s.io_v1beta1_validatingwebhookconfiguration_seldon-validating-webhook-configuration-kubeflow.yaml
  tests/stacks/ibm/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_seldondeployments.machinelearning.seldon.io.yaml
  tests/stacks/kubernetes/test_data/expected/admissionregistration.k8s.io_v1beta1_mutatingwebhookconfiguration_seldon-mutating-webhook-configuration-kubeflow.yaml
  tests/stacks/kubernetes/test_data/expected/admissionregistration.k8s.io_v1beta1_validatingwebhookconfiguration_seldon-validating-webhook-configuration-kubeflow.yaml
  tests/stacks/kubernetes/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_seldondeployments.machinelearning.seldon.io.yaml
  tests/stacks/openshift/application/seldon/test_data/expected/admissionregistration.k8s.io_v1beta1_mutatingwebhookconfiguration_seldon-mutating-webhook-configuration-kubeflow.yaml
  tests/stacks/openshift/application/seldon/test_data/expected/admissionregistration.k8s.io_v1beta1_validatingwebhookconfiguration_seldon-validating-webhook-configuration-kubeflow.yaml
  tests/tests/legacy_kustomizations/seldon-core-operator/test_data/expected/admissionregistration.k8s.io_v1beta1_mutatingwebhookconfiguration_seldon-mutating-webhook-configuration-kubeflow.yaml
  tests/tests/legacy_kustomizations/seldon-core-operator/test_data/expected/admissionregistration.k8s.io_v1beta1_validatingwebhookconfiguration_seldon-validating-webhook-configuration-kubeflow.yaml
Labels: approved, cla: yes, lgtm, size/L

#1672 Pin manifest to stable tag v1.2.0
  kfdef/kfctl_aws.v1.2.0.yaml
  kfdef/kfctl_aws_cognito.v1.2.0.yaml
  kfdef/kfctl_azure.v1.2.0.yaml
  kfdef/kfctl_azure_aad.v1.2.0.yaml
  kfdef/kfctl_ibm.v1.2.0.yaml
  kfdef/kfctl_ibm_multi_user.v1.2.0.yaml
  kfdef/kfctl_istio_dex.v1.2.0.yaml
  kfdef/kfctl_k8s_istio.v1.2.0.yaml
  kfdef/kfctl_openshift.v1.2.0.yaml
Labels: approved, cla: yes, lgtm, size/S

#1678 Fix v1.2 Azure stack config
  stacks/azure/application/centraldashboard/links-configmap.yaml
  stacks/azure/kustomization.yaml
  tests/stacks/azure/application/centraldashboard/test_data/expected/~g_v1_configmap_centraldashboard-links-config.yaml
  tests/stacks/azure/test_data/expected/networking.istio.io_v1alpha3_virtualservice_argo-ui.yaml
  tests/stacks/azure/test_data/expected/networking.istio.io_v1alpha3_virtualservice_centraldashboard.yaml
  tests/stacks/azure/test_data/expected/networking.istio.io_v1alpha3_virtualservice_jupyter-web-app.yaml
  tests/stacks/azure/test_data/expected/networking.istio.io_v1alpha3_virtualservice_katib-ui.yaml
  tests/stacks/azure/test_data/expected/networking.istio.io_v1alpha3_virtualservice_ml-pipeline-ui.yaml
  tests/stacks/azure/test_data/expected/networking.istio.io_v1alpha3_virtualservice_profiles-kfam.yaml
  tests/stacks/azure/test_data/expected/~g_v1_configmap_centraldashboard-links-config.yaml
  tests/stacks/azure/test_data/expected/~g_v1_service_centraldashboard.yaml
  tests/stacks/azure/test_data/expected/~g_v1_service_jupyter-web-app-service.yaml
Labels: approved, cla: yes, lgtm, size/M

#1679 Fix Azure stack config for v1.2
  stacks/azure/application/centraldashboard/links-configmap.yaml
  stacks/azure/kustomization.yaml
  tests/stacks/azure/application/centraldashboard/test_data/expected/~g_v1_configmap_centraldashboard-links-config.yaml
  tests/stacks/azure/test_data/expected/networking.istio.io_v1alpha3_virtualservice_argo-ui.yaml
  tests/stacks/azure/test_data/expected/networking.istio.io_v1alpha3_virtualservice_centraldashboard.yaml
  tests/stacks/azure/test_data/expected/networking.istio.io_v1alpha3_virtualservice_jupyter-web-app.yaml
  tests/stacks/azure/test_data/expected/networking.istio.io_v1alpha3_virtualservice_katib-ui.yaml
  tests/stacks/azure/test_data/expected/networking.istio.io_v1alpha3_virtualservice_ml-pipeline-ui.yaml
  tests/stacks/azure/test_data/expected/networking.istio.io_v1alpha3_virtualservice_profiles-kfam.yaml
  tests/stacks/azure/test_data/expected/~g_v1_configmap_centraldashboard-links-config.yaml
  tests/stacks/azure/test_data/expected/~g_v1_service_centraldashboard.yaml
  tests/stacks/azure/test_data/expected/~g_v1_service_jupyter-web-app-service.yaml
Labels: approved, cla: yes, lgtm, size/M

#1681 Pin Azure v1.2 kfdef to include fix
  kfdef/kfctl_azure.v1.2.0.yaml
  kfdef/kfctl_azure_aad.v1.2.0.yaml
Labels: approved, cla: yes, lgtm, size/XS
