Repository kubeflow/manifests, pull requests merged in 2020-06, with the labels that each got.

#1218 Manifest changes to support GCP blueprints on private GKE.
  cert-manager/cert-manager/v3/kustomization.yaml
  experimental/mirror-images/gcp_template.yaml
  gcp/v2/asm/istio-operator.yaml
  gcp/v2/cnrm/cluster/cluster.yaml
  gcp/v2/cnrm/cluster/kf-vm-policy.yaml
  gcp/v2/cnrm/cluster/kf-vm-sa.yaml
  gcp/v2/cnrm/cluster/nodepool.yaml
  gcp/v2/cnrm/iam/kf-admin-policy.yaml
  gcp/v2/cnrm/iam/kf-admin-sa.yaml
  gcp/v2/cnrm/iam/kf-user-policy.yaml
  gcp/v2/cnrm/iam/kf-user-sa.yaml
  gcp/v2/cnrm/ingress/compute-address.yaml
  gcp/v2/cnrm/kustomization.yaml
  gcp/v2/cnrm/pipelines/disk.yaml
  gcp/v2/management/cluster/cluster.yaml
  gcp/v2/management/cluster/nodepool.yaml
  gcp/v2/privateGKE/README.md
  gcp/v2/privateGKE/cluster-private-patch.yaml
  gcp/v2/privateGKE/compute-network.yaml
  gcp/v2/privateGKE/dns-gcr.yaml
  gcp/v2/privateGKE/dns-google-apis.yaml
  gcp/v2/privateGKE/enable-services.yaml
  gcp/v2/privateGKE/firewall.yaml
  gcp/v2/privateGKE/kustomization.yaml
  gcp/v2/privateGKE/nat.yaml
  tests/Makefile
Labels: approved, cla: yes, lgtm, size/XL

#1220 Add Katib CRD to components
  katib/components/katib-crds/kustomization.yaml
  katib/components/katib-db-manager/kustomization.yaml
  katib/components/katib-db-mysql/kustomization.yaml
  katib/installs/katib-external-db/kustomization.yaml
  katib/installs/katib-standalone/kustomization.yaml
  tests/katib/installs/katib-external-db/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_experiments.kubeflow.org.yaml
  tests/katib/installs/katib-external-db/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_suggestions.kubeflow.org.yaml
  tests/katib/installs/katib-external-db/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_trials.kubeflow.org.yaml
  tests/katib/installs/katib-external-db/test_data/expected/app.k8s.io_v1beta1_application_katib-crds.yaml
  tests/katib/installs/katib-standalone-ibm/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_experiments.kubeflow.org.yaml
  tests/katib/installs/katib-standalone-ibm/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_suggestions.kubeflow.org.yaml
  tests/katib/installs/katib-standalone-ibm/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_trials.kubeflow.org.yaml
  tests/katib/installs/katib-standalone-ibm/test_data/expected/app.k8s.io_v1beta1_application_katib-crds.yaml
  tests/katib/installs/katib-standalone/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_experiments.kubeflow.org.yaml
  tests/katib/installs/katib-standalone/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_suggestions.kubeflow.org.yaml
  tests/katib/installs/katib-standalone/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_trials.kubeflow.org.yaml
  tests/katib/installs/katib-standalone/test_data/expected/app.k8s.io_v1beta1_application_katib-crds.yaml
Labels: approved, cla: yes, lgtm, size/XL

#1210 KFP visualization-service: Fix double ml-pipeline- prefix in names
  pipeline/pipeline-visualization-service/base/kustomization.yaml
  tests/tests/legacy_kustomizations/pipeline-visualization-service/test_data/expected/apps_v1_deployment_ml-pipeline-visualizationserver.yaml
  tests/tests/legacy_kustomizations/pipeline-visualization-service/test_data/expected/~g_v1_service_ml-pipeline-visualizationserver.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1227 Add Bobgy to tests/OWNERS
  tests/OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#1226 Delete old v3 Katib kustomization
  katib/katib-controller/v3/kustomization.yaml
  katib/katib-controller/v3/params.yaml
  katib/katib-crds/v3/kustomization.yaml
Labels: approved, cla: yes, lgtm, size/M

#1230 Fix a bunch issues with GCP blueprints for private gke.
  common/centraldashboard/base_v3/kustomization.yaml
  experimental/mirror-images/gcp_template.yaml
  gcp/iap-ingress/base/policy.yaml
  gcp/v2/cnrm/cluster/cluster.yaml
  gcp/v2/cnrm/gcp-services.yaml
  gcp/v2/cnrm/kustomization.yaml
  gcp/v2/privateGKE/compute-network.yaml
  gcp/v2/privateGKE/dns-gcr.yaml
  gcp/v2/privateGKE/dns-google-apis.yaml
  gcp/v2/privateGKE/firewall.yaml
  gcp/v2/privateGKE/kustomize-fns/README.md
  gcp/v2/privateGKE/kustomize-fns/image_prefix.yaml
  tests/stacks/examples/alice_gcp/test_data/expected/apps_v1_deployment_centraldashboard.yaml
  tests/stacks/gcp/test_data/expected/apps_v1_deployment_centraldashboard.yaml
  tests/tests/legacy_kustomizations/iap-ingress/test_data/expected/authentication.istio.io_v1alpha1_policy_ingress-jwt.yaml
Labels: approved, cla: yes, lgtm, size/L

#1231 Update Alibi image for kfserving 0.3.0
  kfserving/kfserving-install/base/config-map.yaml
  tests/tests/legacy_kustomizations/kfserving-install/test_data/expected/~g_v1_configmap_inferenceservice-config.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1237 Remove GCP KFDefs and E2E tests.
  kfdef/OWNERS
  kfdef/kfctl_gcp_asm_exp.yaml
  kfdef/kfctl_gcp_basic_auth.v1.0.0.yaml
  kfdef/kfctl_gcp_basic_auth.v1.0.1.yaml
  kfdef/kfctl_gcp_basic_auth.v1.0.2.yaml
  kfdef/kfctl_gcp_basic_auth.yaml
  kfdef/kfctl_gcp_iap.v1.0.0.yaml
  kfdef/kfctl_gcp_iap.v1.0.1.yaml
  kfdef/kfctl_gcp_iap.v1.0.2.yaml
  kfdef/kfctl_gcp_iap.yaml
  kfdef/kfctl_upgrade_gcp_iap_1.0.0.yaml
  kfdef/kfctl_upgrade_gcp_iap_1.0.2.yaml
  kfdef/source/master/kfctl_gcp_basic_auth.yaml
  kfdef/source/master/kfctl_gcp_iap.yaml
  kfdef/source/v1.0.0/kfctl_gcp_basic_auth.yaml
  kfdef/source/v1.0.0/kfctl_gcp_iap.yaml
  kfdef/source/v1.0.1/kfctl_gcp_basic_auth.yaml
  kfdef/source/v1.0.1/kfctl_gcp_iap.yaml
  kfdef/source/v1.0.2/kfctl_gcp_basic_auth.yaml
  kfdef/source/v1.0.2/kfctl_gcp_iap.yaml
  prow_config.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#1245 [AWS] Upgrade ingress APIVersion to support k8s 1.16
  aws/istio-ingress/base/ingress.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1249 Add Katib to Generic stacks
  stacks/generic/kustomization.yaml
  tests/stacks/examples/alice/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_experiments.kubeflow.org.yaml
  tests/stacks/examples/alice/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_suggestions.kubeflow.org.yaml
  tests/stacks/examples/alice/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_trials.kubeflow.org.yaml
  tests/stacks/examples/alice/test_data/expected/app.k8s.io_v1beta1_application_katib-controller.yaml
  tests/stacks/examples/alice/test_data/expected/app.k8s.io_v1beta1_application_katib-crds.yaml
  tests/stacks/examples/alice/test_data/expected/apps_v1_deployment_katib-controller.yaml
  tests/stacks/examples/alice/test_data/expected/apps_v1_deployment_katib-db-manager.yaml
  tests/stacks/examples/alice/test_data/expected/apps_v1_deployment_katib-mysql.yaml
  tests/stacks/examples/alice/test_data/expected/apps_v1_deployment_katib-ui.yaml
  tests/stacks/examples/alice/test_data/expected/networking.istio.io_v1alpha3_virtualservice_katib-ui.yaml
  tests/stacks/examples/alice/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_katib-controller.yaml
  tests/stacks/examples/alice/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_katib-ui.yaml
  tests/stacks/examples/alice/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_kubeflow-katib-admin.yaml
  tests/stacks/examples/alice/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_kubeflow-katib-edit.yaml
  tests/stacks/examples/alice/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_kubeflow-katib-view.yaml
  tests/stacks/examples/alice/test_data/expected/rbac.authorization.k8s.io_v1_clusterrolebinding_katib-controller.yaml
  tests/stacks/examples/alice/test_data/expected/rbac.authorization.k8s.io_v1_clusterrolebinding_katib-ui.yaml
  tests/stacks/examples/alice/test_data/expected/~g_v1_configmap_katib-config.yaml
  tests/stacks/examples/alice/test_data/expected/~g_v1_configmap_trial-template.yaml
  tests/stacks/examples/alice/test_data/expected/~g_v1_persistentvolumeclaim_katib-mysql.yaml
  tests/stacks/examples/alice/test_data/expected/~g_v1_secret_katib-controller.yaml
  tests/stacks/examples/alice/test_data/expected/~g_v1_secret_katib-mysql-secrets.yaml
  tests/stacks/examples/alice/test_data/expected/~g_v1_service_katib-controller.yaml
  tests/stacks/examples/alice/test_data/expected/~g_v1_service_katib-db-manager.yaml
  tests/stacks/examples/alice/test_data/expected/~g_v1_service_katib-mysql.yaml
  tests/stacks/examples/alice/test_data/expected/~g_v1_service_katib-ui.yaml
  tests/stacks/examples/alice/test_data/expected/~g_v1_serviceaccount_katib-controller.yaml
  tests/stacks/examples/alice/test_data/expected/~g_v1_serviceaccount_katib-ui.yaml
  tests/stacks/generic/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_experiments.kubeflow.org.yaml
  tests/stacks/generic/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_suggestions.kubeflow.org.yaml
  tests/stacks/generic/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_trials.kubeflow.org.yaml
  tests/stacks/generic/test_data/expected/app.k8s.io_v1beta1_application_katib-controller.yaml
  tests/stacks/generic/test_data/expected/app.k8s.io_v1beta1_application_katib-crds.yaml
  tests/stacks/generic/test_data/expected/apps_v1_deployment_katib-controller.yaml
  tests/stacks/generic/test_data/expected/apps_v1_deployment_katib-db-manager.yaml
  tests/stacks/generic/test_data/expected/apps_v1_deployment_katib-mysql.yaml
  tests/stacks/generic/test_data/expected/apps_v1_deployment_katib-ui.yaml
  tests/stacks/generic/test_data/expected/networking.istio.io_v1alpha3_virtualservice_katib-ui.yaml
  tests/stacks/generic/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_katib-controller.yaml
  tests/stacks/generic/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_katib-ui.yaml
  tests/stacks/generic/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_kubeflow-katib-admin.yaml
  tests/stacks/generic/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_kubeflow-katib-edit.yaml
  tests/stacks/generic/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_kubeflow-katib-view.yaml
  tests/stacks/generic/test_data/expected/rbac.authorization.k8s.io_v1_clusterrolebinding_katib-controller.yaml
  tests/stacks/generic/test_data/expected/rbac.authorization.k8s.io_v1_clusterrolebinding_katib-ui.yaml
  tests/stacks/generic/test_data/expected/~g_v1_configmap_katib-config.yaml
  tests/stacks/generic/test_data/expected/~g_v1_configmap_trial-template.yaml
  tests/stacks/generic/test_data/expected/~g_v1_persistentvolumeclaim_katib-mysql.yaml
  tests/stacks/generic/test_data/expected/~g_v1_secret_katib-controller.yaml
  tests/stacks/generic/test_data/expected/~g_v1_secret_katib-mysql-secrets.yaml
  tests/stacks/generic/test_data/expected/~g_v1_service_katib-controller.yaml
  tests/stacks/generic/test_data/expected/~g_v1_service_katib-db-manager.yaml
  tests/stacks/generic/test_data/expected/~g_v1_service_katib-mysql.yaml
  tests/stacks/generic/test_data/expected/~g_v1_service_katib-ui.yaml
  tests/stacks/generic/test_data/expected/~g_v1_serviceaccount_katib-controller.yaml
  tests/stacks/generic/test_data/expected/~g_v1_serviceaccount_katib-ui.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#1239 Katib manifests for Kubeflow 1.1
  katib/components/katib-controller/kustomization.yaml
  katib/components/katib-db-manager/kustomization.yaml
  katib/katib-controller/base/katib-configmap.yaml
  katib/katib-controller/base/katib-ui-rbac.yaml
  katib/katib-controller/base/kustomization.yaml
  katib/katib-controller/base/trial-template-configmap-labeled.yaml
  tests/katib/installs/katib-external-db/test_data/expected/apps_v1_deployment_katib-controller.yaml
  tests/katib/installs/katib-external-db/test_data/expected/apps_v1_deployment_katib-db-manager.yaml
  tests/katib/installs/katib-external-db/test_data/expected/apps_v1_deployment_katib-ui.yaml
  tests/katib/installs/katib-external-db/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_katib-ui.yaml
  tests/katib/installs/katib-external-db/test_data/expected/~g_v1_configmap_katib-config.yaml
  tests/katib/installs/katib-external-db/test_data/expected/~g_v1_configmap_trial-template-labeled.yaml
  tests/katib/installs/katib-standalone-ibm/test_data/expected/apps_v1_deployment_katib-controller.yaml
  tests/katib/installs/katib-standalone-ibm/test_data/expected/apps_v1_deployment_katib-db-manager.yaml
  tests/katib/installs/katib-standalone-ibm/test_data/expected/apps_v1_deployment_katib-ui.yaml
  tests/katib/installs/katib-standalone-ibm/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_katib-ui.yaml
  tests/katib/installs/katib-standalone-ibm/test_data/expected/~g_v1_configmap_katib-config.yaml
  tests/katib/installs/katib-standalone-ibm/test_data/expected/~g_v1_configmap_trial-template-labeled.yaml
  tests/katib/installs/katib-standalone/test_data/expected/apps_v1_deployment_katib-controller.yaml
  tests/katib/installs/katib-standalone/test_data/expected/apps_v1_deployment_katib-db-manager.yaml
  tests/katib/installs/katib-standalone/test_data/expected/apps_v1_deployment_katib-ui.yaml
  tests/katib/installs/katib-standalone/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_katib-ui.yaml
  tests/katib/installs/katib-standalone/test_data/expected/~g_v1_configmap_katib-config.yaml
  tests/katib/installs/katib-standalone/test_data/expected/~g_v1_configmap_trial-template-labeled.yaml
  tests/tests/legacy_kustomizations/katib-controller/test_data/expected/apps_v1_deployment_katib-controller.yaml
  tests/tests/legacy_kustomizations/katib-controller/test_data/expected/apps_v1_deployment_katib-db-manager.yaml
  tests/tests/legacy_kustomizations/katib-controller/test_data/expected/apps_v1_deployment_katib-ui.yaml
  tests/tests/legacy_kustomizations/katib-controller/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_katib-ui.yaml
  tests/tests/legacy_kustomizations/katib-controller/test_data/expected/~g_v1_configmap_katib-config.yaml
  tests/tests/legacy_kustomizations/katib-controller/test_data/expected/~g_v1_configmap_trial-template-labeled.yaml
Labels: approved, cla: yes, lgtm, size/XL

#1240 Document recommendation of kustomize version
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#1255 Fixes local tests
  tests/stacks/examples/alice/test_data/expected/apps_v1_deployment_katib-controller.yaml
  tests/stacks/examples/alice/test_data/expected/apps_v1_deployment_katib-db-manager.yaml
  tests/stacks/examples/alice/test_data/expected/apps_v1_deployment_katib-ui.yaml
  tests/stacks/examples/alice/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_katib-ui.yaml
  tests/stacks/examples/alice/test_data/expected/~g_v1_configmap_katib-config.yaml
  tests/stacks/examples/alice/test_data/expected/~g_v1_configmap_trial-template-labeled.yaml
  tests/stacks/generic/test_data/expected/apps_v1_deployment_katib-controller.yaml
  tests/stacks/generic/test_data/expected/apps_v1_deployment_katib-db-manager.yaml
  tests/stacks/generic/test_data/expected/apps_v1_deployment_katib-ui.yaml
  tests/stacks/generic/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_katib-ui.yaml
  tests/stacks/generic/test_data/expected/~g_v1_configmap_katib-config.yaml
  tests/stacks/generic/test_data/expected/~g_v1_configmap_trial-template-labeled.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/L

#1223 unmatched label for deployment config
  xgboost-job/xgboost-operator/base/deployment.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#1257 Use ON_WITH_EXCLUSION for istio dex
  kfdef/kfctl_istio_dex.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1286 GCP stack
  stacks/gcp/OWNERS
  stacks/gcp/config/params.env
  stacks/gcp/kustomization.yaml
  stacks/generic/OWNERS
Labels: approved, cla: yes, lgtm, size/M

#1283 Update PyTorch operator RBAC for Kubeflow 1.1
  pytorch-job/pytorch-operator/base/cluster-role.yaml
  tests/stacks/examples/alice/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_kubeflow-pytorchjobs-edit.yaml
  tests/stacks/examples/alice/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_kubeflow-pytorchjobs-view.yaml
  tests/stacks/examples/alice/test_data/expected/rbac.authorization.k8s.io_v1beta1_clusterrole_pytorch-operator.yaml
  tests/stacks/generic/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_kubeflow-pytorchjobs-edit.yaml
  tests/stacks/generic/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_kubeflow-pytorchjobs-view.yaml
  tests/stacks/generic/test_data/expected/rbac.authorization.k8s.io_v1beta1_clusterrole_pytorch-operator.yaml
  tests/tests/legacy_kustomizations/pytorch-operator/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_kubeflow-pytorchjobs-edit.yaml
  tests/tests/legacy_kustomizations/pytorch-operator/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_kubeflow-pytorchjobs-view.yaml
  tests/tests/legacy_kustomizations/pytorch-operator/test_data/expected/rbac.authorization.k8s.io_v1beta1_clusterrole_pytorch-operator.yaml
Labels: approved, cla: yes, lgtm, size/S

#1284 Add namespace selector and test case for admission
  admission-webhook/webhook/base/mutating-webhook-configuration.yaml
  profiles/base/kustomization.yaml
  tests/stacks/examples/alice/test_data/expected/admissionregistration.k8s.io_v1beta1_mutatingwebhookconfiguration_admission-webhook-mutating-webhook-configuration.yaml
  tests/stacks/generic/test_data/expected/admissionregistration.k8s.io_v1beta1_mutatingwebhookconfiguration_admission-webhook-mutating-webhook-configuration.yaml
  tests/tests/legacy_kustomizations/profiles/test_data/expected/apps_v1_deployment_profiles-deployment.yaml
  tests/tests/legacy_kustomizations/webhook/test_data/expected/admissionregistration.k8s.io_v1beta1_mutatingwebhookconfiguration_admission-webhook-mutating-webhook-configuration.yaml
  tests/validate_resources_test.go
Labels: approved, cla: yes, lgtm, size/L

#1287 Update ingresses and deployments to work with 1.16
  aws/aws-istio-authz-adaptor/base/deployment.yaml
  aws/istio-ingress/overlays/cognito/ingress.yaml
  aws/istio-ingress/overlays/oidc/ingress.yaml
  aws/istio-ingress/overlays/secure/ingress.yaml
  gcp/basic-auth-ingress/base/backend-config.yaml
  gcp/basic-auth-ingress/base/cloud-endpoint.yaml
  gcp/basic-auth-ingress/base/cluster-role-binding.yaml
  gcp/basic-auth-ingress/base/cluster-role.yaml
  gcp/basic-auth-ingress/base/config-map.yaml
  gcp/basic-auth-ingress/base/deployment.yaml
  gcp/basic-auth-ingress/base/gcp-credentials-patch.yaml
  gcp/basic-auth-ingress/base/ingress.yaml
  gcp/basic-auth-ingress/base/istio-mapping-svc.yaml
  gcp/basic-auth-ingress/base/kustomization.yaml
  gcp/basic-auth-ingress/base/params.env
  gcp/basic-auth-ingress/base/params.yaml
  gcp/basic-auth-ingress/base/service-account.yaml
  gcp/basic-auth-ingress/base/service.yaml
  gcp/basic-auth-ingress/base/stateful-set.yaml
  gcp/basic-auth-ingress/overlays/application/application.yaml
  gcp/basic-auth-ingress/overlays/application/kustomization.yaml
  gcp/basic-auth-ingress/overlays/certmanager/certificate.yaml
  gcp/basic-auth-ingress/overlays/certmanager/job.yaml
  gcp/basic-auth-ingress/overlays/certmanager/kustomization.yaml
  gcp/basic-auth-ingress/overlays/gcp-credentials/gcp-credentials-patch.yaml
  gcp/basic-auth-ingress/overlays/gcp-credentials/kustomization.yaml
  gcp/basic-auth-ingress/overlays/managed-cert/cert.yaml
  gcp/basic-auth-ingress/overlays/managed-cert/kustomization.yaml
  gcp/iap-ingress/base/ingress.yaml
  kfdef/generic/istio/crds.yaml
  kfdef/generic/istio/istio-noauth.yaml
  tests/stacks/gcp/test_data/expected/admissionregistration.k8s.io_v1beta1_mutatingwebhookconfiguration_admission-webhook-mutating-webhook-configuration.yaml
  tests/tests/legacy_kustomizations/iap-ingress/test_data/expected/networking.k8s.io_v1beta1_ingress_envoy-ingress.yaml
  tests/validate_resources_test.go
Labels: approved, cla: yes, lgtm, size/XXL

#1297 Generates and fixes unit-tests
  pipeline/installs/generic/kustomization.yaml
  tests/stacks/gcp/test_data/expected/apps_v1_deployment_tf-job-operator.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1300 Synchronize the tests
  tests/go.mod
  tests/stacks/ibm/test_data/expected/admissionregistration.k8s.io_v1beta1_mutatingwebhookconfiguration_admission-webhook-mutating-webhook-configuration.yaml
  tests/stacks/ibm/test_data/expected/apps_v1_deployment_pytorch-operator.yaml
  tests/stacks/ibm/test_data/expected/apps_v1_deployment_tf-job-operator.yaml
  tests/stacks/ibm/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_kubeflow-pytorchjobs-edit.yaml
  tests/stacks/ibm/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_kubeflow-pytorchjobs-view.yaml
  tests/stacks/ibm/test_data/expected/rbac.authorization.k8s.io_v1beta1_clusterrole_pytorch-operator.yaml
  tests/stacks/ibm/test_data/expected/~g_v1_service_minio-service.yaml
  tests/stacks/ibm/test_data/expected/~g_v1_service_mysql.yaml
Labels: approved, cla: yes, lgtm, size/S

#1299 Add Support For AWS Dex Basic-Authentication
  aws/aws-alb-ingress-controller/overlays/application/kustomization.yaml
  kfdef/kfctl_aws.yaml
  kfdef/source/master/kfctl_aws.yaml
Labels: approved, cla: yes, lgtm, size/L

#1313 Correct XGBoostJob CRD group name and add singular name
  xgboost-job/xgboost-operator/base/cluster-role.yaml
  xgboost-job/xgboost-operator/base/crd.yaml
  xgboost-job/xgboost-operator/overlays/application/application.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1312 Upgrade aws cognito manifest istio version to 1.3.1
  kfdef/kfctl_aws_cognito.yaml
  kfdef/source/master/kfctl_aws_cognito.yaml
Labels: approved, cla: yes, lgtm, size/S

#1326 Update mxnet-operator manifest to v1
  mxnet-job/mxnet-operator/base/crd.yaml
  mxnet-job/mxnet-operator/base/deployment.yaml
  mxnet-job/mxnet-operator/base/kustomization.yaml
  mxnet-job/mxnet-operator/overlays/application/application.yaml
Labels: approved, cla: yes, lgtm, size/M

#1327 Add mxnet-operator to aws kfdefs
  kfdef/kfctl_aws.yaml
  kfdef/kfctl_aws_cognito.yaml
  kfdef/source/master/kfctl_aws.yaml
  kfdef/source/master/kfctl_aws_cognito.yaml
Labels: approved, cla: yes, lgtm, size/S

#1328 Enable IRSA by default for AWS users
  kfdef/kfctl_aws.yaml
  kfdef/kfctl_aws_cognito.yaml
  kfdef/source/master/kfctl_aws.yaml
  kfdef/source/master/kfctl_aws_cognito.yaml
Labels: approved, cla: yes, lgtm, size/S

#1317 fix(gcp): default workload identity bindings
  gcp/v2/cnrm/iam/kf-admin-policy.yaml
  gcp/v2/cnrm/iam/kf-user-policy.yaml
  stacks/gcp/kustomization.yaml
  stacks/gcp/workload-identity-bindings-patch.yaml
  tests/stacks/examples/alice/test_data/expected/~g_v1_serviceaccount_ml-pipeline-ui.yaml
  tests/stacks/examples/alice/test_data/expected/~g_v1_serviceaccount_ml-pipeline-visualizationserver.yaml
  tests/stacks/examples/alice/test_data/expected/~g_v1_serviceaccount_pipeline-runner.yaml
  tests/stacks/examples/alice/test_data/expected/~g_v1_serviceaccount_profiles-controller-service-account.yaml
  tests/stacks/gcp/test_data/expected/~g_v1_serviceaccount_ml-pipeline-ui.yaml
  tests/stacks/gcp/test_data/expected/~g_v1_serviceaccount_ml-pipeline-visualizationserver.yaml
  tests/stacks/gcp/test_data/expected/~g_v1_serviceaccount_pipeline-runner.yaml
  tests/stacks/gcp/test_data/expected/~g_v1_serviceaccount_profiles-controller-service-account.yaml
Labels: approved, cla: yes, lgtm, size/M

#1311 KFServing and KNative manifests Owners files
  kfserving/OWNERS
  knative/OWNERS
Labels: approved, cla: yes, lgtm, size/S

#1331 Cherrypick "fix(gcp): default workload identity bindings (#1317)"
  gcp/v2/cnrm/iam/kf-admin-policy.yaml
  gcp/v2/cnrm/iam/kf-user-policy.yaml
  stacks/gcp/kustomization.yaml
  stacks/gcp/workload-identity-bindings-patch.yaml
  tests/stacks/examples/alice/test_data/expected/~g_v1_serviceaccount_ml-pipeline-ui.yaml
  tests/stacks/examples/alice/test_data/expected/~g_v1_serviceaccount_ml-pipeline-visualizationserver.yaml
  tests/stacks/examples/alice/test_data/expected/~g_v1_serviceaccount_pipeline-runner.yaml
  tests/stacks/examples/alice/test_data/expected/~g_v1_serviceaccount_profiles-controller-service-account.yaml
  tests/stacks/gcp/test_data/expected/~g_v1_serviceaccount_ml-pipeline-ui.yaml
  tests/stacks/gcp/test_data/expected/~g_v1_serviceaccount_ml-pipeline-visualizationserver.yaml
  tests/stacks/gcp/test_data/expected/~g_v1_serviceaccount_pipeline-runner.yaml
  tests/stacks/gcp/test_data/expected/~g_v1_serviceaccount_profiles-controller-service-account.yaml
Labels: approved, cla: yes, lgtm, size/M

#1330 Fix registered issue for aws overlay of Jupyter-web-app
  jupyter/jupyter-web-app/overlays/aws/config-map.yaml
  jupyter/jupyter-web-app/overlays/aws/deployment-aws-patch.yaml
  jupyter/jupyter-web-app/overlays/aws/kustomization.yaml
  jupyter/jupyter-web-app/overlays/aws/spawner_ui_config.yaml
Labels: approved, cla: yes, lgtm, size/L

#1334 Cherry pick AWS changes #1299 #1312 #1326 #1327 #1328 #1330 to v1.1-branch
  aws/aws-alb-ingress-controller/overlays/application/kustomization.yaml
  jupyter/jupyter-web-app/overlays/aws/config-map.yaml
  jupyter/jupyter-web-app/overlays/aws/deployment-aws-patch.yaml
  jupyter/jupyter-web-app/overlays/aws/kustomization.yaml
  jupyter/jupyter-web-app/overlays/aws/spawner_ui_config.yaml
  kfdef/kfctl_aws.yaml
  kfdef/kfctl_aws_cognito.yaml
  kfdef/source/master/kfctl_aws.yaml
  kfdef/source/master/kfctl_aws_cognito.yaml
  mxnet-job/mxnet-operator/base/crd.yaml
  mxnet-job/mxnet-operator/base/deployment.yaml
  mxnet-job/mxnet-operator/base/kustomization.yaml
  mxnet-job/mxnet-operator/overlays/application/application.yaml
Labels: approved, cla: yes, lgtm, size/XL

#1324 Add missing finalizers for Katib experiment
  katib/katib-controller/base/katib-controller-rbac.yaml
  tests/katib/installs/katib-external-db/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_katib-controller.yaml
  tests/katib/installs/katib-standalone-ibm/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_katib-controller.yaml
  tests/katib/installs/katib-standalone/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_katib-controller.yaml
  tests/stacks/examples/alice/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_katib-controller.yaml
  tests/stacks/gcp/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_katib-controller.yaml
  tests/stacks/generic/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_katib-controller.yaml
  tests/stacks/ibm/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_katib-controller.yaml
  tests/tests/legacy_kustomizations/katib-controller/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_katib-controller.yaml
Labels: approved, cla: yes, lgtm, size/S

#1337 Remove aws overlay for jupyter web app
  kfdef/kfctl_aws.yaml
  kfdef/kfctl_aws_cognito.yaml
  kfdef/source/master/kfctl_aws.yaml
  kfdef/source/master/kfctl_aws_cognito.yaml
Labels: approved, lgtm, size/XS

#1338 Remove aws overlay for jupyter web app (#1337)
  kfdef/kfctl_aws.yaml
  kfdef/kfctl_aws_cognito.yaml
  kfdef/source/master/kfctl_aws.yaml
  kfdef/source/master/kfctl_aws_cognito.yaml
Labels: approved, cla: yes, lgtm, size/XS
