Repository kubeflow/manifests, pull requests merged in 2020-08, with the labels that each got.

#1446 Add a kustomize function to remove namespace
  gcp/kustomize-fns/remove_namespace.yaml
  gcp/v2/cnrm/gcp-services.yaml
Labels: approved, cla: yes, lgtm, size/M

#1440 Update Katib image tag to ce89cbf on master
  katib/components/katib-controller/kustomization.yaml
  katib/components/katib-db-manager/kustomization.yaml
  katib/katib-controller/base/katib-configmap.yaml
  katib/katib-controller/base/kustomization.yaml
  tests/katib/installs/katib-external-db/test_data/expected/apps_v1_deployment_katib-controller.yaml
  tests/katib/installs/katib-external-db/test_data/expected/apps_v1_deployment_katib-db-manager.yaml
  tests/katib/installs/katib-external-db/test_data/expected/apps_v1_deployment_katib-ui.yaml
  tests/katib/installs/katib-external-db/test_data/expected/~g_v1_configmap_katib-config.yaml
  tests/katib/installs/katib-standalone-ibm/test_data/expected/apps_v1_deployment_katib-controller.yaml
  tests/katib/installs/katib-standalone-ibm/test_data/expected/apps_v1_deployment_katib-db-manager.yaml
  tests/katib/installs/katib-standalone-ibm/test_data/expected/apps_v1_deployment_katib-ui.yaml
  tests/katib/installs/katib-standalone-ibm/test_data/expected/~g_v1_configmap_katib-config.yaml
  tests/katib/installs/katib-standalone/test_data/expected/apps_v1_deployment_katib-controller.yaml
  tests/katib/installs/katib-standalone/test_data/expected/apps_v1_deployment_katib-db-manager.yaml
  tests/katib/installs/katib-standalone/test_data/expected/apps_v1_deployment_katib-ui.yaml
  tests/katib/installs/katib-standalone/test_data/expected/~g_v1_configmap_katib-config.yaml
  tests/stacks/aws/test_data/expected/apps_v1_deployment_katib-controller.yaml
  tests/stacks/aws/test_data/expected/apps_v1_deployment_katib-db-manager.yaml
  tests/stacks/aws/test_data/expected/apps_v1_deployment_katib-ui.yaml
  tests/stacks/aws/test_data/expected/~g_v1_configmap_katib-config.yaml
  tests/stacks/examples/alice/test_data/expected/apps_v1_deployment_katib-controller.yaml
  tests/stacks/examples/alice/test_data/expected/apps_v1_deployment_katib-db-manager.yaml
  tests/stacks/examples/alice/test_data/expected/apps_v1_deployment_katib-ui.yaml
  tests/stacks/examples/alice/test_data/expected/~g_v1_configmap_katib-config.yaml
  tests/stacks/gcp/test_data/expected/apps_v1_deployment_katib-controller.yaml
  tests/stacks/gcp/test_data/expected/apps_v1_deployment_katib-db-manager.yaml
  tests/stacks/gcp/test_data/expected/apps_v1_deployment_katib-ui.yaml
  tests/stacks/gcp/test_data/expected/~g_v1_configmap_katib-config.yaml
  tests/stacks/generic/test_data/expected/apps_v1_deployment_katib-controller.yaml
  tests/stacks/generic/test_data/expected/apps_v1_deployment_katib-db-manager.yaml
  tests/stacks/generic/test_data/expected/apps_v1_deployment_katib-ui.yaml
  tests/stacks/generic/test_data/expected/~g_v1_configmap_katib-config.yaml
  tests/stacks/ibm/test_data/expected/apps_v1_deployment_katib-controller.yaml
  tests/stacks/ibm/test_data/expected/apps_v1_deployment_katib-db-manager.yaml
  tests/stacks/ibm/test_data/expected/apps_v1_deployment_katib-ui.yaml
  tests/stacks/ibm/test_data/expected/~g_v1_configmap_katib-config.yaml
  tests/tests/legacy_kustomizations/katib-controller/test_data/expected/apps_v1_deployment_katib-controller.yaml
  tests/tests/legacy_kustomizations/katib-controller/test_data/expected/apps_v1_deployment_katib-db-manager.yaml
  tests/tests/legacy_kustomizations/katib-controller/test_data/expected/apps_v1_deployment_katib-ui.yaml
  tests/tests/legacy_kustomizations/katib-controller/test_data/expected/~g_v1_configmap_katib-config.yaml
Labels: approved, cla: yes, lgtm, size/L

#1454 Update unit test for the latest changes
  tests/stacks/ibm/multi-user/test_data/expected/apps_v1_deployment_katib-controller.yaml
  tests/stacks/ibm/multi-user/test_data/expected/apps_v1_deployment_katib-db-manager.yaml
  tests/stacks/ibm/multi-user/test_data/expected/apps_v1_deployment_katib-ui.yaml
  tests/stacks/ibm/multi-user/test_data/expected/~g_v1_configmap_katib-config.yaml
Labels: approved, cla: yes, lgtm, size/S

#1451 cert-manager namespace needs label control-plane
  namespaces/base/namespaces.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1453 Add Bobgy to OWNERS
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#1295 Add Seldon Owners
  seldon/OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#1463 Fix XGBoost Operator manifest issue
  xgboost-job/xgboost-operator/base/cluster-role.yaml
  xgboost-job/xgboost-operator/base/crd.yaml
  xgboost-job/xgboost-operator/base/kustomization.yaml
  xgboost-job/xgboost-operator/overlays/application/application.yaml
Labels: approved, cla: yes, lgtm, size/S

#1426 Migrate istio and dex to V3
  dex-auth/dex-authenticator/base_v3/kustomization.yaml
  dex-auth/dex-crds/base_v3/kustomization.yaml
  dex-auth/keycloak-gatekeeper/base_v3/kustomization.yaml
  istio-1-3-1/cluster-local-gateway-1-3-1/base_v3/kustomization.yaml
  istio-1-3-1/istio-install-1-3-1/base_v3/kustomization.yaml
  istio/cluster-local-gateway/base_v3/kustomization.yaml
  istio/ingressgateway-self-signed-cert/base_v3/kustomization.yaml
  istio/istio/base_v3/kustomization.yaml
  istio/oidc-authservice/base_v3/kustomization.yaml
Labels: approved, cla: yes, lgtm, size/L

#1458 Clean up inactive approvers
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#1459 Remove tensorboard manifest
  kfdef/kfctl_aws.yaml
  kfdef/kfctl_aws_cognito.yaml
  kfdef/kfctl_ibm.yaml
  kfdef/kfctl_ibm_dex_multi_user.v1.1.0.yaml
  kfdef/kfctl_ibm_dex_multi_user.yaml
  kfdef/kfctl_istio_dex.yaml
  kfdef/kfctl_k8s_istio.yaml
  kfdef/source/master/kfctl_anthos.yaml
  kfdef/source/master/kfctl_aws.yaml
  kfdef/source/master/kfctl_aws_cognito.yaml
  kfdef/source/master/kfctl_ibm.yaml
  kfdef/source/master/kfctl_istio_dex.yaml
  kfdef/source/master/kfctl_k8s_istio.yaml
  stacks/ibm/application/tensorboard/kustomization.yaml
  tensorboard/base/deployment.yaml
  tensorboard/base/kustomization.yaml
  tensorboard/base/params.env
  tensorboard/base/params.yaml
  tensorboard/base/service.yaml
  tensorboard/overlays/istio/kustomization.yaml
  tensorboard/overlays/istio/params.yaml
  tensorboard/overlays/istio/virtual-service.yaml
  tests/legacy_kustomizations/tensorboard/kustomization.yaml
  tests/legacy_kustomizations/tensorboard/params_0.env
  tests/stacks/ibm/application/tensorboard/kustomize_test.go
  tests/stacks/ibm/application/tensorboard/test_data/expected/apps_v1_deployment_tensorboard.yaml
  tests/stacks/ibm/application/tensorboard/test_data/expected/networking.istio.io_v1alpha3_virtualservice_tensorboard.yaml
  tests/stacks/ibm/application/tensorboard/test_data/expected/~g_v1_configmap_parameters-dgd4h256h5.yaml
  tests/stacks/ibm/application/tensorboard/test_data/expected/~g_v1_service_tensorboard.yaml
  tests/tests/legacy_kustomizations/tensorboard/kustomize_test.go
  tests/tests/legacy_kustomizations/tensorboard/test_data/expected/apps_v1_deployment_tensorboard.yaml
  tests/tests/legacy_kustomizations/tensorboard/test_data/expected/networking.istio.io_v1alpha3_virtualservice_tensorboard.yaml
  tests/tests/legacy_kustomizations/tensorboard/test_data/expected/~g_v1_configmap_parameters-dgd4h256h5.yaml
  tests/tests/legacy_kustomizations/tensorboard/test_data/expected/~g_v1_service_tensorboard.yaml
Labels: approved, cla: yes, lgtm, size/XL

#1488 fix: update kfp profile controller's version
  pipeline/installs/multi-user/pipelines-profile-controller/composite-controller.yaml
  pipeline/installs/multi-user/pipelines-profile-controller/deployment.yaml
  pipeline/installs/multi-user/pipelines-profile-controller/kustomization.yaml
  pipeline/installs/multi-user/pipelines-profile-controller/params.env
  pipeline/installs/multi-user/pipelines-profile-controller/service.yaml
  tests/stacks/aws/test_data/expected/apps_v1_deployment_kubeflow-pipelines-profile-controller.yaml
  tests/stacks/aws/test_data/expected/~g_v1_configmap_kubeflow-pipelines-profile-controller-env-mgh6th2gff.yaml
  tests/stacks/examples/alice/test_data/expected/apps_v1_deployment_kubeflow-pipelines-profile-controller.yaml
  tests/stacks/examples/alice/test_data/expected/~g_v1_configmap_kubeflow-pipelines-profile-controller-env-mgh6th2gff.yaml
  tests/stacks/gcp/test_data/expected/apps_v1_deployment_kubeflow-pipelines-profile-controller.yaml
  tests/stacks/gcp/test_data/expected/~g_v1_configmap_kubeflow-pipelines-profile-controller-env-mgh6th2gff.yaml
  tests/stacks/ibm/multi-user/test_data/expected/apps_v1_deployment_kubeflow-pipelines-profile-controller.yaml
  tests/stacks/ibm/multi-user/test_data/expected/~g_v1_configmap_kubeflow-pipelines-profile-controller-env-mgh6th2gff.yaml
Labels: approved, cla: yes, lgtm, size/M

#1492 Cherry pick of "fix: update kfp profile controller's version #1488"
  pipeline/installs/multi-user/pipelines-profile-controller/composite-controller.yaml
  pipeline/installs/multi-user/pipelines-profile-controller/deployment.yaml
  pipeline/installs/multi-user/pipelines-profile-controller/kustomization.yaml
  pipeline/installs/multi-user/pipelines-profile-controller/params.env
  pipeline/installs/multi-user/pipelines-profile-controller/service.yaml
  tests/stacks/aws/test_data/expected/apps_v1_deployment_kubeflow-pipelines-profile-controller.yaml
  tests/stacks/aws/test_data/expected/~g_v1_configmap_kubeflow-pipelines-profile-controller-env-mgh6th2gff.yaml
  tests/stacks/examples/alice/test_data/expected/apps_v1_deployment_kubeflow-pipelines-profile-controller.yaml
  tests/stacks/examples/alice/test_data/expected/~g_v1_configmap_kubeflow-pipelines-profile-controller-env-mgh6th2gff.yaml
  tests/stacks/gcp/test_data/expected/apps_v1_deployment_kubeflow-pipelines-profile-controller.yaml
  tests/stacks/gcp/test_data/expected/~g_v1_configmap_kubeflow-pipelines-profile-controller-env-mgh6th2gff.yaml
  tests/stacks/ibm/multi-user/test_data/expected/apps_v1_deployment_kubeflow-pipelines-profile-controller.yaml
  tests/stacks/ibm/multi-user/test_data/expected/~g_v1_configmap_kubeflow-pipelines-profile-controller-env-mgh6th2gff.yaml
Labels: approved, cla: yes, lgtm, size/M

#1483 v1.1 manifests for vanilla k8s
  kfdef/kfctl_k8s_istio.v1.1.0.yaml
  stacks/kubernetes/application/add-anonymous-user-filter/kustomization.yaml
  tests/stacks/kubernetes/application/add-anonymous-user-filter/kustomize_test.go
  tests/stacks/kubernetes/application/add-anonymous-user-filter/test_data/expected/networking.istio.io_v1alpha3_envoyfilter_add-user-filter.yaml
Labels: approved, cla: yes, lgtm, size/L

#1501 Cherry pick of "chore: upgrade istio to 1.4.10-asm.15 #1412"
  gcp/v2/asm/istio-operator.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1123 add parameter for istio gateway in oidc-authservice
  istio/oidc-authservice/base/envoy-filter.yaml
  istio/oidc-authservice/base/kustomization.yaml
  istio/oidc-authservice/base/params.env
  istio/oidc-authservice/base/params.yaml
  tests/stacks/aws/application/oidc-authservice/test_data/expected/~g_v1_configmap_oidc-authservice-parameters.yaml
  tests/stacks/ibm/application/oidc-authservice/test_data/expected/~g_v1_configmap_oidc-authservice-parameters.yaml
  tests/stacks/kubernetes/application/oidc-authservice/test_data/expected/~g_v1_configmap_oidc-authservice-parameters.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1513 Remove http from the GCP ingress and explicitly set the default backend.
  gcp/iap-ingress/base/ingress.yaml
  tests/go.mod
  tests/stacks/kubernetes/application/add-anonymous-user-filter/kustomize_test.go
  tests/tests/legacy_kustomizations/iap-ingress/test_data/expected/networking.k8s.io_v1beta1_ingress_envoy-ingress.yaml
Labels: approved, cla: yes, lgtm, size/S

#1515 Add missing files for k8s_istio.v1.1.0 KFDef
  kfdef/kfctl_k8s_istio.v1.1.0.yaml
  stacks/kubernetes/application/spark-operator/kustomization.yaml
  stacks/kubernetes/application/spartakus/kustomization.yaml
  tests/stacks/kubernetes/application/spark-operator/kustomize_test.go
  tests/stacks/kubernetes/application/spark-operator/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_scheduledsparkapplications.sparkoperator.k8s.io.yaml
  tests/stacks/kubernetes/application/spark-operator/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_sparkapplications.sparkoperator.k8s.io.yaml
  tests/stacks/kubernetes/application/spark-operator/test_data/expected/app.k8s.io_v1beta1_application_spark-operator.yaml
  tests/stacks/kubernetes/application/spark-operator/test_data/expected/apps_v1_deployment_spark-operatorsparkoperator.yaml
  tests/stacks/kubernetes/application/spark-operator/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_spark-operatoroperator-cr.yaml
  tests/stacks/kubernetes/application/spark-operator/test_data/expected/rbac.authorization.k8s.io_v1_clusterrolebinding_spark-operatorsparkoperator-crb.yaml
  tests/stacks/kubernetes/application/spark-operator/test_data/expected/rbac.authorization.k8s.io_v1_role_spark-operatorspark-role.yaml
  tests/stacks/kubernetes/application/spark-operator/test_data/expected/rbac.authorization.k8s.io_v1_rolebinding_spark-operatorspark-role-binding.yaml
  tests/stacks/kubernetes/application/spark-operator/test_data/expected/~g_v1_serviceaccount_spark-operatoroperator-sa.yaml
  tests/stacks/kubernetes/application/spark-operator/test_data/expected/~g_v1_serviceaccount_spark-operatorspark.yaml
  tests/stacks/kubernetes/application/spartakus/kustomize_test.go
  tests/stacks/kubernetes/application/spartakus/test_data/expected/app.k8s.io_v1beta1_application_spartakus.yaml
  tests/stacks/kubernetes/application/spartakus/test_data/expected/apps_v1_deployment_spartakus-volunteer.yaml
  tests/stacks/kubernetes/application/spartakus/test_data/expected/rbac.authorization.k8s.io_v1beta1_clusterrole_spartakus.yaml
  tests/stacks/kubernetes/application/spartakus/test_data/expected/rbac.authorization.k8s.io_v1beta1_clusterrolebinding_spartakus.yaml
  tests/stacks/kubernetes/application/spartakus/test_data/expected/~g_v1_configmap_spartakus-config.yaml
  tests/stacks/kubernetes/application/spartakus/test_data/expected/~g_v1_serviceaccount_spartakus.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XXL
