Repository kubeflow/manifests, pull requests merged in 2020-10, with the labels that each got.

#1576 Create v1.1.0 Azure Kfdef manifests with OIDC Azure AD
  kfdef/kfctl_azure_aad.v1.1.0.yaml
  stacks/azure/application/istio-1-3-1-stack/kustomization.yaml
  stacks/azure/application/oidc-authservice/kustomization.yaml
Labels: approved, cla: yes, lgtm, size/M

#1587 Add overlay to support Azure Database for MySQL
  stacks/azure/kustomization.yaml
  stacks/azure/metadata/Readme.md
  stacks/azure/metadata/kustomization.yaml
  stacks/azure/metadata/metadata-deployment.yaml
  stacks/azure/metadata/params.env
  stacks/azure/metadata/secrets.env
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/L

#1595 Upgrade CNRM from 1.15 to 1.27.2
  gcp/v2/management/cnrm-install/README.md
  gcp/v2/management/cnrm-install/install-system/0-cnrm-system.yaml
  gcp/v2/management/cnrm-install/install-system/crds.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#1598 Add PatrickXYS as tests folder approver
  tests/OWNERS
  tests/stacks/ibm/components/tf-job/test_data/expected/apps_v1_deployment_tf-job-operator.yaml
  tests/stacks/kubernetes/test_data/expected/apps_v1_deployment_tf-job-operator.yaml
Labels: approved, cla: yes, lgtm, size/XS
