Repository kubeflow/manifests, pull requests merged in 2020-01, with the labels that each got.

#689 metadata: Adding metadata-grpc config map
  metadata/base/grpc-params.env
  metadata/base/kustomization.yaml
  metadata/base/metadata-deployment.yaml
  metadata/overlays/db/metadata-deployment.yaml
  tests/metadata-base_test.go
  tests/metadata-overlays-application_test.go
  tests/metadata-overlays-db_test.go
  tests/metadata-overlays-ibm-storage-config_test.go
  tests/metadata-overlays-istio_test.go
Labels: approved, cla: yes, lgtm, size/M

#672 Add allowheader X-Auth-Token in authn-filter
  istio/oidc-authservice/base/envoy-filter.yaml
  tests/istio-oidc-authservice-base_test.go
  tests/istio-oidc-authservice-overlays-application_test.go
  tests/istio-oidc-authservice-overlays-ibm-storage-config_test.go
Labels: approved, cla: yes, lgtm, size/S

#674 Update istio_dex config to support Spark operator
  kfdef/kfctl_istio_dex.yaml
Labels: approved, cla: yes, lgtm, size/S

#702 oidc-authservice: Various fixes
  istio/oidc-authservice/base/kustomization.yaml
  istio/oidc-authservice/base/params.yaml
  istio/oidc-authservice/base/service.yaml
  istio/oidc-authservice/base/statefulset.yaml
  istio/oidc-authservice/overlays/application/application.yaml
  istio/oidc-authservice/overlays/ibm-storage-config/kustomization.yaml
  istio/oidc-authservice/overlays/ibm-storage-config/statefulset.yaml
  tests/istio-oidc-authservice-base_test.go
  tests/istio-oidc-authservice-overlays-application_test.go
  tests/istio-oidc-authservice-overlays-ibm-storage-config_test.go
Labels: approved, cla: yes, lgtm, size/M

#703 Two examples for disabling istio injection in kubeflow namespace
  argo/base/deployment.yaml
  tests/argo-base_test.go
  tests/argo-overlays-application_test.go
  tests/argo-overlays-istio_test.go
  tests/tf-training-tf-job-operator-base_test.go
  tests/tf-training-tf-job-operator-overlays-application_test.go
  tf-training/tf-job-operator/base/deployment.yaml
Labels: approved, cla: yes, lgtm, size/S

#699 Unittests for manifests should run on postsubmit and periodic; not ju…
  prow_config.yaml
Labels: approved, cla: yes, lgtm, size/XS

#711 Add sidecar.istio.io/inject false annotations to all stateful sets in kubeflow ns
  admission-webhook/bootstrap/base/stateful-set.yaml
  application/application/base/stateful-set.yaml
  application/application/overlays/debug/stateful-set.yaml
  aws/aws-efs-csi-driver/base/csi-controller-stateful-set.yaml
  aws/aws-fsx-csi-driver/base/csi-controller-stateful-set.yaml
  kfserving/kfserving-install/base/statefulset.yaml
  metacontroller/base/stateful-set.yaml
  seldon/seldon-core-operator/base/seldon-operator-controller-manager-statefulset.yaml
  tests/admission-webhook-bootstrap-base_test.go
  tests/admission-webhook-bootstrap-overlays-application_test.go
  tests/application-application-base_test.go
  tests/application-application-overlays-application_test.go
  tests/application-application-overlays-debug_test.go
  tests/aws-aws-efs-csi-driver-base_test.go
  tests/aws-aws-fsx-csi-driver-base_test.go
  tests/kfserving-kfserving-install-base_test.go
  tests/kfserving-kfserving-install-overlays-application_test.go
  tests/metacontroller-base_test.go
  tests/seldon-seldon-core-operator-base_test.go
  tests/seldon-seldon-core-operator-overlays-application_test.go
Labels: approved, cla: yes, lgtm, size/M

#704 Update kfctl_istio_dex.yaml with missing name 'istio'
  kfdef/kfctl_istio_dex.yaml
Labels: approved, cla: yes, lgtm, size/XS

#691 Add kfdef for IBM Cloud Kubernetes Service
  kfdef/kfctl_ibm.yaml
Labels: approved, cla: yes, lgtm, size/L

#708 remove users
  gcp/deployment_manager_configs/cluster-kubeflow.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#734 profile & kfam: add livenessProbe; update image
  profiles/base/crd.yaml
  profiles/base/deployment.yaml
  profiles/base/kustomization.yaml
  tests/profiles-base_test.go
  tests/profiles-overlays-application_test.go
  tests/profiles-overlays-debug_test.go
  tests/profiles-overlays-devices_test.go
  tests/profiles-overlays-istio_test.go
  tests/profiles-overlays-test_test.go
Labels: approved, cla: yes, lgtm, size/L

#738 profile application update
  profiles/overlays/application/application.yaml
  tests/profiles-overlays-application_test.go
Labels: approved, cla: yes, lgtm, size/M

#741 kubeflow v0.7 use GKE 1.14.8
  gcp/deployment_manager_configs/cluster-kubeflow.yaml
Labels: approved, cla: yes, lgtm, size/XS

#758 Pin GKE to 1.14.8 because the latest 1.14 release breaks workload identity
  gcp/deployment_manager_configs/cluster-kubeflow.yaml
Labels: approved, cla: yes, lgtm, size/XS

#760 Pin GKE to 1.14.8 because the latest 1.14 release breaks workload identity
  gcp/deployment_manager_configs/cluster-kubeflow.yaml
Labels: approved, cla: yes, lgtm, size/XS

#742 Cherry pick of #739 on v1.0-branch. #739: update notebook manifest
  jupyter/notebook-controller/base/crd.yaml
  jupyter/notebook-controller/overlays/application/application.yaml
  jupyter/notebook-controller/overlays/application/kustomization.yaml
  tests/jupyter-notebook-controller-base_test.go
  tests/jupyter-notebook-controller-overlays-application_test.go
  tests/jupyter-notebook-controller-overlays-istio_test.go
Labels: approved, cla: yes, lgtm, size/M

#739 Update Notebook Controller to v1.0.0
  jupyter/notebook-controller/base/crd.yaml
  jupyter/notebook-controller/overlays/application/application.yaml
  jupyter/notebook-controller/overlays/application/kustomization.yaml
  tests/jupyter-notebook-controller-base_test.go
  tests/jupyter-notebook-controller-overlays-application_test.go
  tests/jupyter-notebook-controller-overlays-istio_test.go
Labels: approved, cla: yes, lgtm, size/M

#775 Sync profile change to v1.0
  profiles/base/crd.yaml
  profiles/base/deployment.yaml
  profiles/base/kustomization.yaml
  profiles/overlays/application/application.yaml
  tests/profiles-base_test.go
  tests/profiles-overlays-application_test.go
  tests/profiles-overlays-debug_test.go
  tests/profiles-overlays-devices_test.go
  tests/profiles-overlays-istio_test.go
  tests/profiles-overlays-test_test.go
Labels: approved, cla: yes, lgtm, size/L

#777 centraldashboard livenessProbe
  common/centraldashboard/base/deployment.yaml
  tests/common-centraldashboard-base_test.go
  tests/common-centraldashboard-overlays-application_test.go
  tests/common-centraldashboard-overlays-istio_test.go
Labels: approved, cla: yes, lgtm, size/M

#795 Update TFJob manifest to work with new distroless image.
  tests/tf-training-tf-job-operator-base_test.go
  tests/tf-training-tf-job-operator-overlays-application_test.go
  tf-training/tf-job-operator/base/deployment.yaml
  tf-training/tf-job-operator/base/kustomization.yaml
Labels: approved, cla: yes, lgtm, size/S

#803 Automated cherry pick of #795: Update TFJob manifest to work with new distroless image. Cherry pick of #795 on v1.0-branch. #795: Update TFJob manifest to work with new distroless image.
  tests/tf-training-tf-job-operator-base_test.go
  tests/tf-training-tf-job-operator-overlays-application_test.go
  tf-training/tf-job-operator/base/deployment.yaml
  tf-training/tf-job-operator/base/kustomization.yaml
Labels: approved, cla: yes, lgtm, size/S

#804 Added istio sidecar false annotation to metadata deployments
  hack/gen-test-target.sh
  metadata/base/metadata-deployment.yaml
  metadata/base/metadata-envoy-deployment.yaml
  metadata/base/metadata-ui-deployment.yaml
  metadata/overlays/db/metadata-db-deployment.yaml
  tests/metadata-base_test.go
  tests/metadata-overlays-application_test.go
  tests/metadata-overlays-db_test.go
  tests/metadata-overlays-ibm-storage-config_test.go
  tests/metadata-overlays-istio_test.go
Labels: approved, cla: yes, lgtm, size/M

#801 Fix autoprovisioning settings.
  gcp/deployment_manager_configs/cluster-kubeflow.yaml
  gcp/deployment_manager_configs/cluster.jinja
Labels: approved, cla: yes, lgtm, size/XS

#809 Automated cherry pick of #801: Fix autoprovisioning settings. Cherry pick of #801 on v1.0-branch. #801: Fix autoprovisioning settings.
  gcp/deployment_manager_configs/cluster-kubeflow.yaml
  gcp/deployment_manager_configs/cluster.jinja
Labels: approved, cla: yes, lgtm, size/XS

#811 Metadata: Updating gRPC server version to v0.21.1
  metadata/base/kustomization.yaml
  metadata/base/metadata-deployment.yaml
  tests/metadata-base_test.go
  tests/metadata-overlays-application_test.go
  tests/metadata-overlays-db_test.go
  tests/metadata-overlays-ibm-storage-config_test.go
  tests/metadata-overlays-istio_test.go
Labels: approved, cla: yes, lgtm, size/S

#651 Upgrade Knative serving to 0.11.1
  kfserving/kfserving-crds/base/crd.yaml
  kfserving/kfserving-install/base/config-map.yaml
  knative/knative-serving-crds/base/crd.yaml
  knative/knative-serving-crds/base/namespace.yaml
  knative/knative-serving-crds/overlays/application/application.yaml
  knative/knative-serving-crds/overlays/application/kustomization.yaml
  knative/knative-serving-install/base/apiservice.yaml
  knative/knative-serving-install/base/cluster-role-binding.yaml
  knative/knative-serving-install/base/cluster-role.yaml
  knative/knative-serving-install/base/config-map.yaml
  knative/knative-serving-install/base/deployment.yaml
  knative/knative-serving-install/base/gateway.yaml
  knative/knative-serving-install/base/hpa.yaml
  knative/knative-serving-install/base/image.yaml
  knative/knative-serving-install/base/kustomization.yaml
  knative/knative-serving-install/base/role-binding.yaml
  knative/knative-serving-install/base/service-account.yaml
  knative/knative-serving-install/base/service.yaml
  knative/knative-serving-install/base/webhook-configuration.yaml
  knative/knative-serving-install/overlays/application/application.yaml
  knative/knative-serving-install/overlays/application/kustomization.yaml
  tests/kfserving-kfserving-install-base_test.go
  tests/kfserving-kfserving-install-overlays-application_test.go
  tests/knative-knative-serving-crds-base_test.go
  tests/knative-knative-serving-crds-overlays-application_test.go
  tests/knative-knative-serving-install-base_test.go
  tests/knative-knative-serving-install-overlays-application_test.go
Labels: approved, cla: yes, lgtm, size/XXL

#802 Update pipeline images to the 0.2.0 release.
  pipeline/api-service/base/kustomization.yaml
  pipeline/api-service/base/role.yaml
  pipeline/persistent-agent/base/kustomization.yaml
  pipeline/pipeline-visualization-service/base/kustomization.yaml
  pipeline/pipelines-ui/base/kustomization.yaml
  pipeline/pipelines-viewer/base/kustomization.yaml
  pipeline/scheduledworkflow/base/kustomization.yaml
  tests/pipeline-api-service-base_test.go
  tests/pipeline-api-service-overlays-application_test.go
  tests/pipeline-persistent-agent-base_test.go
  tests/pipeline-persistent-agent-overlays-application_test.go
  tests/pipeline-pipeline-visualization-service-base_test.go
  tests/pipeline-pipeline-visualization-service-overlays-application_test.go
  tests/pipeline-pipelines-ui-base_test.go
  tests/pipeline-pipelines-ui-overlays-application_test.go
  tests/pipeline-pipelines-ui-overlays-gcp_test.go
  tests/pipeline-pipelines-ui-overlays-istio_test.go
  tests/pipeline-pipelines-viewer-base_test.go
  tests/pipeline-pipelines-viewer-overlays-application_test.go
  tests/pipeline-scheduledworkflow-base_test.go
  tests/pipeline-scheduledworkflow-overlays-application_test.go
Labels: approved, cla: yes, lgtm, size/M

#815 Automated cherry pick of #802: Update pipeline images to the 0.2.0 release. Cherry pick of #802 on v1.0-branch. #802: Update pipeline images to the 0.2.0 release.
  pipeline/api-service/base/kustomization.yaml
  pipeline/api-service/base/role.yaml
  pipeline/persistent-agent/base/kustomization.yaml
  pipeline/pipeline-visualization-service/base/kustomization.yaml
  pipeline/pipelines-ui/base/kustomization.yaml
  pipeline/pipelines-viewer/base/kustomization.yaml
  pipeline/scheduledworkflow/base/kustomization.yaml
  tests/pipeline-api-service-base_test.go
  tests/pipeline-api-service-overlays-application_test.go
  tests/pipeline-persistent-agent-base_test.go
  tests/pipeline-persistent-agent-overlays-application_test.go
  tests/pipeline-pipeline-visualization-service-base_test.go
  tests/pipeline-pipeline-visualization-service-overlays-application_test.go
  tests/pipeline-pipelines-ui-base_test.go
  tests/pipeline-pipelines-ui-overlays-application_test.go
  tests/pipeline-pipelines-ui-overlays-gcp_test.go
  tests/pipeline-pipelines-ui-overlays-istio_test.go
  tests/pipeline-pipelines-viewer-base_test.go
  tests/pipeline-pipelines-viewer-overlays-application_test.go
  tests/pipeline-scheduledworkflow-base_test.go
  tests/pipeline-scheduledworkflow-overlays-application_test.go
Labels: approved, cla: yes, lgtm, size/M

#817 Automated cherry pick of #777: centraldashboard livenessProbe Cherry pick of #777 on v1.0-branch. #777: centraldashboard livenessProbe
  common/centraldashboard/base/deployment.yaml
  tests/common-centraldashboard-base_test.go
  tests/common-centraldashboard-overlays-application_test.go
  tests/common-centraldashboard-overlays-istio_test.go
Labels: approved, cla: yes, lgtm, size/M

#816 Address #4699 RBAC permissions for Jupyter web app
  jupyter/jupyter-web-app/base/cluster-role.yaml
  tests/jupyter-jupyter-web-app-base_test.go
  tests/jupyter-jupyter-web-app-overlays-application_test.go
  tests/jupyter-jupyter-web-app-overlays-istio_test.go
Labels: approved, cla: yes, lgtm, size/L

#820 Automated cherry pick of #816: Address #4699 RBAC permissions for Jupyter web app Cherry pick of #816 on v1.0-branch. #816: Address #4699 RBAC permissions for Jupyter web app
  jupyter/jupyter-web-app/base/cluster-role.yaml
  tests/jupyter-jupyter-web-app-base_test.go
  tests/jupyter-jupyter-web-app-overlays-application_test.go
  tests/jupyter-jupyter-web-app-overlays-istio_test.go
Labels: approved, cla: yes, lgtm, size/L
