Repository kubeflow/manifests, pull requests merged in 2020-12, with the labels that each got.

#1673 OpenShift jupyter-web-app update imagetag to v2.0.0
  stacks/openshift/application/jupyter-web-app/kustomization.yaml
  tests/stacks/openshift/application/jupyter-web-app/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1686 fix jupyter-web-app image tag
  jupyter/jupyter-web-app/base/kustomization.yaml
  jupyter/jupyter-web-app/base_v3/kustomization.yaml
  stacks/azure/application/jupyter-web-app/base/kustomization.yaml
  stacks/ibm/application/jupyter-web-app/base/kustomization.yaml
  tests/stacks/aws/application/jupyter-web-app/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
  tests/stacks/aws/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
  tests/stacks/azure/application/jupyter-web-app/base/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
  tests/stacks/azure/application/jupyter-web-app/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
  tests/stacks/azure/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
  tests/stacks/examples/alice/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
  tests/stacks/gcp/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
  tests/stacks/generic/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
  tests/stacks/ibm/application/jupyter-web-app/base/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
  tests/stacks/ibm/application/jupyter-web-app/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
  tests/stacks/ibm/application/notebooks/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
  tests/stacks/ibm/multi-user/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
  tests/stacks/ibm/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
  tests/stacks/kubernetes/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
  tests/tests/legacy_kustomizations/jupyter-web-app/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
Labels: approved, cla: yes, lgtm, size/M

#1684 Bump istio version to 1.3.1
  kfdef/kfctl_aws_cognito.v1.2.0.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1689 fix jupyter-web-app image tag (#1686)
  jupyter/jupyter-web-app/base/kustomization.yaml
  jupyter/jupyter-web-app/base_v3/kustomization.yaml
  stacks/azure/application/jupyter-web-app/base/kustomization.yaml
  stacks/ibm/application/jupyter-web-app/base/kustomization.yaml
  tests/stacks/aws/application/jupyter-web-app/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
  tests/stacks/aws/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
  tests/stacks/azure/application/jupyter-web-app/base/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
  tests/stacks/azure/application/jupyter-web-app/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
  tests/stacks/azure/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
  tests/stacks/examples/alice/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
  tests/stacks/gcp/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
  tests/stacks/generic/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
  tests/stacks/ibm/application/jupyter-web-app/base/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
  tests/stacks/ibm/application/jupyter-web-app/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
  tests/stacks/ibm/application/notebooks/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
  tests/stacks/ibm/multi-user/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
  tests/stacks/ibm/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
  tests/stacks/kubernetes/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
  tests/tests/legacy_kustomizations/jupyter-web-app/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
Labels: approved, cla: yes, lgtm, size/M

#1693 Update Tekton to use the fixed version of minio/mc image
  pipeline/installs/tekton/kfp-tekton/kfp-pipeline-config.yaml
  tests/stacks/ibm/application/kfp-tekton-multi-user/test_data/expected/~g_v1_configmap_kfp-tekton-config.yaml
  tests/stacks/ibm/application/kfp-tekton/test_data/expected/~g_v1_configmap_kfp-tekton-config.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1694 Automated cherry pick of #1693 [Update Tekton to use the fixed version of minio/mc image] to v1.2 branch
  pipeline/installs/tekton/kfp-tekton/kfp-pipeline-config.yaml
  tests/stacks/ibm/application/kfp-tekton-multi-user/test_data/expected/~g_v1_configmap_kfp-tekton-config.yaml
  tests/stacks/ibm/application/kfp-tekton/test_data/expected/~g_v1_configmap_kfp-tekton-config.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1685 update owners file
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS
