Repository kubeflow/manifests, pull requests merged in 2020-09, with the labels that each got.

#1524 Add Azure owners
  kfdef/OWNERS
  stacks/azure/OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#1487 Create v1.1.0 Azure Kfdef manifests
  istio/add-anonymous-user-filter-istio-1.6/envoy-filter.yaml
  istio/add-anonymous-user-filter-istio-1.6/kustomization.yaml
  kfdef/kfctl_azure.v1.1.0.yaml
  stacks/azure/application/add-anonymous-user-filter-istio-1.6/kustomization.yaml
  stacks/azure/application/cert-manager-crds/kustomization.yaml
  stacks/azure/application/cert-manager-kube-system-resources/kustomization.yaml
  stacks/azure/application/cert-manager/kustomization.yaml
  stacks/azure/application/istio/kustomization.yaml
  stacks/azure/application/istio/params.env
  stacks/azure/application/istio/params.yaml
  stacks/azure/application/jupyter-web-app/base/deployment_patch.yaml
  stacks/azure/application/jupyter-web-app/base/kustomization.yaml
  stacks/azure/application/jupyter-web-app/base/params.env
  stacks/azure/application/jupyter-web-app/base/params.yaml
  stacks/azure/application/jupyter-web-app/kustomization.yaml
  stacks/azure/application/spark-operator/kustomization.yaml
  stacks/azure/application/spartakus/kustomization.yaml
  stacks/azure/application/tensorboard/kustomization.yaml
  stacks/azure/config/params.env
  stacks/azure/kustomization.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/L

#1540 cherry-pick k8s_istio.v1.1.0 KFDef (#1515)
  kfdef/kfctl_k8s_istio.v1.1.0.yaml
  stacks/kubernetes/application/spark-operator/kustomization.yaml
  stacks/kubernetes/application/spartakus/kustomization.yaml
  tests/stacks/kubernetes/application/spark-operator/kustomize_test.go
  tests/stacks/kubernetes/application/spark-operator/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_scheduledsparkapplications.sparkoperator.k8s.io.yaml
  tests/stacks/kubernetes/application/spark-operator/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_sparkapplications.sparkoperator.k8s.io.yaml
  tests/stacks/kubernetes/application/spark-operator/test_data/expected/app.k8s.io_v1beta1_application_spark-operator.yaml
  tests/stacks/kubernetes/application/spark-operator/test_data/expected/apps_v1_deployment_spark-operatorsparkoperator.yaml
  tests/stacks/kubernetes/application/spark-operator/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_spark-operatoroperator-cr.yaml
  tests/stacks/kubernetes/application/spark-operator/test_data/expected/rbac.authorization.k8s.io_v1_clusterrolebinding_spark-operatorsparkoperator-crb.yaml
  tests/stacks/kubernetes/application/spark-operator/test_data/expected/rbac.authorization.k8s.io_v1_role_spark-operatorspark-role.yaml
  tests/stacks/kubernetes/application/spark-operator/test_data/expected/rbac.authorization.k8s.io_v1_rolebinding_spark-operatorspark-role-binding.yaml
  tests/stacks/kubernetes/application/spark-operator/test_data/expected/~g_v1_serviceaccount_spark-operatoroperator-sa.yaml
  tests/stacks/kubernetes/application/spark-operator/test_data/expected/~g_v1_serviceaccount_spark-operatorspark.yaml
  tests/stacks/kubernetes/application/spartakus/kustomize_test.go
  tests/stacks/kubernetes/application/spartakus/test_data/expected/app.k8s.io_v1beta1_application_spartakus.yaml
  tests/stacks/kubernetes/application/spartakus/test_data/expected/apps_v1_deployment_spartakus-volunteer.yaml
  tests/stacks/kubernetes/application/spartakus/test_data/expected/rbac.authorization.k8s.io_v1beta1_clusterrole_spartakus.yaml
  tests/stacks/kubernetes/application/spartakus/test_data/expected/rbac.authorization.k8s.io_v1beta1_clusterrolebinding_spartakus.yaml
  tests/stacks/kubernetes/application/spartakus/test_data/expected/~g_v1_configmap_spartakus-config.yaml
  tests/stacks/kubernetes/application/spartakus/test_data/expected/~g_v1_serviceaccount_spartakus.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#1538 Delete Deployment manager configs for GCP
  gcp/deployment_manager_configs/README.md
  gcp/deployment_manager_configs/cluster-kubeflow.yaml
  gcp/deployment_manager_configs/cluster.jinja
  gcp/deployment_manager_configs/cluster.jinja.schema
  gcp/deployment_manager_configs/gcfs.yaml
  gcp/deployment_manager_configs/iam_bindings_template.yaml
  gcp/deployment_manager_configs/network.jinja
  gcp/deployment_manager_configs/network.yaml
  gcp/deployment_manager_configs/storage-kubeflow.yaml
  gcp/deployment_manager_configs/storage.jinja
  gcp/deployment_manager_configs/storage.jinja.schema
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XL

#1106 fix application specs
  cert-manager/cert-manager/overlays/application/application.yaml
  kfserving/kfserving-install/overlays/application/application.yaml
  mpi-job/mpi-operator/overlays/application/application.yaml
  seldon/seldon-core-operator/overlays/application/application.yaml
  tests/stacks/aws/application/cert-manager/test_data/expected/app.k8s.io_v1beta1_application_cert-manager.yaml
  tests/stacks/aws/test_data/expected/app.k8s.io_v1beta1_application_mpi-operator.yaml
  tests/stacks/aws/test_data/expected/app.k8s.io_v1beta1_application_seldon-core-operator.yaml
  tests/stacks/examples/alice/test_data/expected/app.k8s.io_v1beta1_application_kfserving.yaml
  tests/stacks/gcp/test_data/expected/app.k8s.io_v1beta1_application_kfserving.yaml
  tests/stacks/ibm/application/cert-manager/test_data/expected/app.k8s.io_v1beta1_application_cert-manager.yaml
  tests/stacks/ibm/multi-user/test_data/expected/app.k8s.io_v1beta1_application_seldon-core-operator.yaml
  tests/stacks/ibm/test_data/expected/app.k8s.io_v1beta1_application_seldon-core-operator.yaml
  tests/stacks/kubernetes/application/cert-manager/test_data/expected/app.k8s.io_v1beta1_application_cert-manager.yaml
  tests/stacks/kubernetes/test_data/expected/app.k8s.io_v1beta1_application_mpi-operator.yaml
  tests/stacks/kubernetes/test_data/expected/app.k8s.io_v1beta1_application_seldon-core-operator.yaml
  tests/tests/legacy_kustomizations/cert-manager/test_data/expected/app.k8s.io_v1beta1_application_cert-manager.yaml
  tests/tests/legacy_kustomizations/kfserving-install/test_data/expected/app.k8s.io_v1beta1_application_kfserving.yaml
  tests/tests/legacy_kustomizations/seldon-core-operator/test_data/expected/app.k8s.io_v1beta1_application_seldon-core-operator.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1559 Add USERID_HEADER argument in access management
  profiles/base_v3/deployment_patch.yaml
  tests/stacks/aws/test_data/expected/apps_v1_deployment_profiles-deployment.yaml
  tests/stacks/examples/alice/test_data/expected/apps_v1_deployment_profiles-deployment.yaml
  tests/stacks/gcp/test_data/expected/apps_v1_deployment_profiles-deployment.yaml
  tests/stacks/generic/test_data/expected/apps_v1_deployment_profiles-deployment.yaml
  tests/stacks/kubernetes/test_data/expected/apps_v1_deployment_profiles-deployment.yaml
Labels: approved, cla: yes, lgtm, size/S

#1557 Add Myself into AWS OWNERS
  aws/OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#1561 Automated cherry pick of #1559: Add USERID_HEADER argument in access management
  profiles/base_v3/deployment_patch.yaml
  tests/stacks/aws/test_data/expected/apps_v1_deployment_profiles-deployment.yaml
  tests/stacks/examples/alice/test_data/expected/apps_v1_deployment_profiles-deployment.yaml
  tests/stacks/gcp/test_data/expected/apps_v1_deployment_profiles-deployment.yaml
  tests/stacks/generic/test_data/expected/apps_v1_deployment_profiles-deployment.yaml
  tests/stacks/kubernetes/test_data/expected/apps_v1_deployment_profiles-deployment.yaml
Labels: approved, cla: yes, lgtm, size/S

#1560 Add AWS v1.1.0 manifest to master branch
  kfdef/kfctl_aws.v1.1.0.yaml
  kfdef/kfctl_aws_cognito.v1.1.0.yaml
Labels: approved, cla: yes, lgtm, size/L

#1563 ASM Mesh id should be proj-${PROJECTNUBMER}
  gcp/Kptfile
  gcp/v2/asm/istio-operator.yaml
  gcp/v2/cnrm/cluster/cluster.yaml
  gcp/v2/cnrm/cluster/nodepool.yaml
  gcp/v2/cnrm/pipelines/disk.yaml
  gcp/v2/management/cluster/cluster.yaml
  gcp/v2/management/cluster/nodepool.yaml
  gcp/v2/privateGKE/cluster-private-patch.yaml
  gcp/v2/privateGKE/compute-network.yaml
  gcp/v2/privateGKE/nat.yaml
  tests/Makefile
Labels: approved, cla: yes, lgtm, size/M
