Repository kubeflow/manifests, pull requests merged in 2020-04, with the labels that each got.

#1051 jupyter web app manifest version v3
  jupyter/jupyter-web-app/base/deployment.yaml
  jupyter/jupyter-web-app/base/deployment_patch.yaml
  jupyter/jupyter-web-app/base/kustomization.yaml
  jupyter/jupyter-web-app/base_v3/deployment_patch.yaml
  jupyter/jupyter-web-app/base_v3/kustomization.yaml
  jupyter/jupyter-web-app/overlays/application/kustomization.yaml
  tests/jupyter/jupyter-web-app/base_v3/kustomize_test.go
  tests/jupyter/jupyter-web-app/base_v3/test_data/expected/app.k8s.io_v1beta1_application_jupyter-web-app-jupyter-web-app.yaml
  tests/jupyter/jupyter-web-app/base_v3/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
  tests/jupyter/jupyter-web-app/base_v3/test_data/expected/networking.istio.io_v1alpha3_virtualservice_jupyter-web-app-jupyter-web-app.yaml
  tests/jupyter/jupyter-web-app/base_v3/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_jupyter-web-app-cluster-role.yaml
  tests/jupyter/jupyter-web-app/base_v3/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_jupyter-web-app-kubeflow-notebook-ui-admin.yaml
  tests/jupyter/jupyter-web-app/base_v3/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_jupyter-web-app-kubeflow-notebook-ui-edit.yaml
  tests/jupyter/jupyter-web-app/base_v3/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_jupyter-web-app-kubeflow-notebook-ui-view.yaml
  tests/jupyter/jupyter-web-app/base_v3/test_data/expected/rbac.authorization.k8s.io_v1_clusterrolebinding_jupyter-web-app-cluster-role-binding.yaml
  tests/jupyter/jupyter-web-app/base_v3/test_data/expected/rbac.authorization.k8s.io_v1beta1_role_jupyter-web-app-jupyter-notebook-role.yaml
  tests/jupyter/jupyter-web-app/base_v3/test_data/expected/rbac.authorization.k8s.io_v1beta1_rolebinding_jupyter-web-app-jupyter-notebook-role-binding.yaml
  tests/jupyter/jupyter-web-app/base_v3/test_data/expected/~g_v1_configmap_jupyter-web-app-jupyter-web-app-config-dhcbh64467.yaml
  tests/jupyter/jupyter-web-app/base_v3/test_data/expected/~g_v1_service_jupyter-web-app-service.yaml
  tests/jupyter/jupyter-web-app/base_v3/test_data/expected/~g_v1_serviceaccount_jupyter-web-app-service-account.yaml
  tests/jupyter/jupyter-web-app/overlays/application/test_data/expected/app.k8s.io_v1beta1_application_jupyter-web-app.yaml
  tests/jupyter/jupyter-web-app/overlays/application/test_data/expected/kubeflow_~g_v1_configmap_jupyter-web-app-parameters.yaml
  tests/jupyter/jupyter-web-app/overlays/application/test_data/expected/kubeflow_~g_v1_service_jupyter-web-app-service.yaml
  tests/jupyter/jupyter-web-app/overlays/application/test_data/expected/kubeflow_~g_v1_serviceaccount_jupyter-web-app-service-account.yaml
Labels: approved, cla: yes, lgtm, size/L

#1067 add instruction for kubeflow on KCC
  gcp/v2/README.md
Labels: approved, cla: yes, lgtm, size/M

#1079 Remove istio-ingress component in kfctl_aws
  kfdef/kfctl_aws.v1.0.0.yaml
  kfdef/kfctl_aws.v1.0.1.yaml
  kfdef/kfctl_aws.yaml
  kfdef/source/master/kfctl_aws.yaml
Labels: approved, cla: yes, lgtm, size/M

#1080 Automated cherry pick of #1079: Remove istio-ingress component in kfctl_aws on v1.0-branch
  kfdef/kfctl_aws.v1.0.0.yaml
  kfdef/kfctl_aws.v1.0.1.yaml
  kfdef/kfctl_aws.yaml
  kfdef/source/master/kfctl_aws.yaml
Labels: cla: yes, lgtm, size/M

#1072 Cherry pick 949 - Kfserving gateway
  istio/kfserving-gateway/base/deployment.yaml
  istio/kfserving-gateway/base/horizontal-pod-autoscaler.yaml
  istio/kfserving-gateway/base/kustomization.yaml
  istio/kfserving-gateway/base/service.yaml
  kfserving/kfserving-install/base/config-map.yaml
  knative/knative-serving-install/base/config-map.yaml
  knative/knative-serving-install/base/gateway.yaml
  tests/istio-kfserving-gateway-base_test.go
  tests/kfserving-kfserving-install-base_test.go
  tests/kfserving-kfserving-install-overlays-application_test.go
  tests/knative-knative-serving-install-base_test.go
  tests/knative-knative-serving-install-overlays-application_test.go
Labels: approved, cla: yes, lgtm, size/XL

#1064 Cherry pick of #969 and #997: fix pipeline default sa
  kfdef/source/master/kfctl_gcp_iap.yaml
  pipeline/api-service/overlays/use-kf-user/deployment.yaml
  pipeline/api-service/overlays/use-kf-user/kustomization.yaml
  pipeline/pipelines-runner/overlays/use-kf-user/cluster-role-binding.yaml
  pipeline/pipelines-runner/overlays/use-kf-user/kustomization.yaml
  tests/pipeline-api-service-overlays-use-kf-user_test.go
  tests/pipeline-pipelines-runner-overlays-use-kf-user_test.go
Labels: approved, cla: yes, lgtm, size/L

#1065 Cherry pick of Fix KFP tensorboard no GCP permission (#970)
  pipeline/pipelines-ui/overlays/gcp/configmap.yaml
  pipeline/pipelines-ui/overlays/gcp/deployment.yaml
  pipeline/pipelines-ui/overlays/gcp/kustomization.yaml
  tests/pipeline-pipelines-ui-overlays-gcp_test.go
Labels: approved, cla: yes, lgtm, size/M

#1083 Bump KFP to 0.2.5
  kfdef/kfctl_gcp_iap.yaml
  kfdef/source/master/kfctl_gcp_iap.yaml
  metadata/base/kustomization.yaml
  metadata/base/metadata-deployment.yaml
  metadata/overlays/db/metadata-deployment.yaml
  metadata/overlays/external-mysql/metadata-deployment.yaml
  pipeline/api-service/base/kustomization.yaml
  pipeline/api-service/overlays/application/application.yaml
  pipeline/api-service/overlays/application/kustomization.yaml
  pipeline/minio/overlays/application/application.yaml
  pipeline/minio/overlays/application/kustomization.yaml
  pipeline/mysql/overlays/application/application.yaml
  pipeline/mysql/overlays/application/kustomization.yaml
  pipeline/persistent-agent/base/kustomization.yaml
  pipeline/persistent-agent/overlays/application/application.yaml
  pipeline/persistent-agent/overlays/application/kustomization.yaml
  pipeline/pipeline-visualization-service/base/kustomization.yaml
  pipeline/pipeline-visualization-service/overlays/application/application.yaml
  pipeline/pipeline-visualization-service/overlays/application/kustomization.yaml
  pipeline/pipeline-visualization-service/overlays/use-kf-user/deployment.yaml
  pipeline/pipeline-visualization-service/overlays/use-kf-user/kustomization.yaml
  pipeline/pipelines-runner/overlays/application/application.yaml
  pipeline/pipelines-runner/overlays/application/kustomization.yaml
  pipeline/pipelines-ui/base/deployment.yaml
  pipeline/pipelines-ui/base/kustomization.yaml
  pipeline/pipelines-ui/overlays/application/application.yaml
  pipeline/pipelines-ui/overlays/application/kustomization.yaml
  pipeline/pipelines-viewer/base/kustomization.yaml
  pipeline/pipelines-viewer/overlays/application/application.yaml
  pipeline/pipelines-viewer/overlays/application/kustomization.yaml
  pipeline/scheduledworkflow/base/kustomization.yaml
  pipeline/scheduledworkflow/overlays/application/application.yaml
  pipeline/scheduledworkflow/overlays/application/kustomization.yaml
  tests/legacy_kustomizations/metadata/kustomization.yaml
  tests/tests/legacy_kustomizations/api-service/test_data/expected/app.k8s.io_v1beta1_application_api-service.yaml
  tests/tests/legacy_kustomizations/api-service/test_data/expected/apps_v1_deployment_ml-pipeline.yaml
  tests/tests/legacy_kustomizations/metadata/test_data/expected/apps_v1_deployment_metadata-grpc-deployment.yaml
  tests/tests/legacy_kustomizations/metadata/test_data/expected/~g_v1_configmap_metadata-grpc-configmap.yaml
  tests/tests/legacy_kustomizations/metadata/test_data/expected/~g_v1_configmap_metadata-ui-parameters.yaml
  tests/tests/legacy_kustomizations/persistent-agent/test_data/expected/app.k8s.io_v1beta1_application_persistent-agent.yaml
  tests/tests/legacy_kustomizations/persistent-agent/test_data/expected/apps_v1_deployment_ml-pipeline-persistenceagent.yaml
  tests/tests/legacy_kustomizations/pipeline-visualization-service/test_data/expected/app.k8s.io_v1beta1_application_pipeline-visualization-service.yaml
  tests/tests/legacy_kustomizations/pipeline-visualization-service/test_data/expected/apps_v1_deployment_ml-pipeline-ml-pipeline-visualizationserver.yaml
  tests/tests/legacy_kustomizations/pipelines-runner/test_data/expected/app.k8s.io_v1beta1_application_pipelines-runner.yaml
  tests/tests/legacy_kustomizations/pipelines-ui/test_data/expected/app.k8s.io_v1beta1_application_pipelines-ui.yaml
  tests/tests/legacy_kustomizations/pipelines-ui/test_data/expected/apps_v1_deployment_ml-pipeline-ui.yaml
  tests/tests/legacy_kustomizations/pipelines-viewer/test_data/expected/app.k8s.io_v1beta1_application_pipelines-viewer.yaml
  tests/tests/legacy_kustomizations/pipelines-viewer/test_data/expected/apps_v1_deployment_ml-pipeline-viewer-controller-deployment.yaml
  tests/tests/legacy_kustomizations/scheduledworkflow/test_data/expected/app.k8s.io_v1beta1_application_scheduledworkflow.yaml
  tests/tests/legacy_kustomizations/scheduledworkflow/test_data/expected/apps_v1_deployment_ml-pipeline-scheduledworkflow.yaml
Labels: approved, cla: yes, lgtm, size/L

#1087 Update generated kfdefs
  kfdef/kfctl_gcp_iap.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1100 v1.0.2 manifests
  kfdef/kfctl_anthos.v1.0.2.yaml
  kfdef/kfctl_aws.v1.0.2.yaml
  kfdef/kfctl_aws_cognito.v1.0.2.yaml
  kfdef/kfctl_gcp_basic_auth.v1.0.2.yaml
  kfdef/kfctl_gcp_iap.v1.0.2.yaml
  kfdef/kfctl_ibm.v1.0.2.yaml
  kfdef/kfctl_istio_dex.v1.0.2.yaml
  kfdef/kfctl_k8s_istio.v1.0.2.yaml
  kfdef/source/v1.0.2/kfctl_anthos.yaml
  kfdef/source/v1.0.2/kfctl_aws.yaml
  kfdef/source/v1.0.2/kfctl_aws_cognito.yaml
  kfdef/source/v1.0.2/kfctl_gcp_basic_auth.yaml
  kfdef/source/v1.0.2/kfctl_gcp_iap.yaml
  kfdef/source/v1.0.2/kfctl_ibm.yaml
  kfdef/source/v1.0.2/kfctl_istio_dex.yaml
  kfdef/source/v1.0.2/kfctl_k8s_istio.yaml
  kfdef/source/v1.0.2/kustomization.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#1101 Automated cherry pick of #1100: v1.0.2 manifests Cherry pick of #1100 on v1.0-branch. #1100: v1.0.2 manifests
  kfdef/kfctl_anthos.v1.0.2.yaml
  kfdef/kfctl_aws.v1.0.2.yaml
  kfdef/kfctl_aws_cognito.v1.0.2.yaml
  kfdef/kfctl_gcp_basic_auth.v1.0.2.yaml
  kfdef/kfctl_gcp_iap.v1.0.2.yaml
  kfdef/kfctl_ibm.v1.0.2.yaml
  kfdef/kfctl_istio_dex.v1.0.2.yaml
  kfdef/kfctl_k8s_istio.v1.0.2.yaml
  kfdef/source/v1.0.2/kfctl_anthos.yaml
  kfdef/source/v1.0.2/kfctl_aws.yaml
  kfdef/source/v1.0.2/kfctl_aws_cognito.yaml
  kfdef/source/v1.0.2/kfctl_gcp_basic_auth.yaml
  kfdef/source/v1.0.2/kfctl_gcp_iap.yaml
  kfdef/source/v1.0.2/kfctl_ibm.yaml
  kfdef/source/v1.0.2/kfctl_istio_dex.yaml
  kfdef/source/v1.0.2/kfctl_k8s_istio.yaml
  kfdef/source/v1.0.2/kustomization.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#1102 Add upgrade spec for v1.0.0 to v1.0.2
  kfdef/kfctl_upgrade_gcp_iap_1.0.2.yaml
Labels: approved, cla: yes, lgtm, size/S

#1104 Fix unittests by upgrading to go 1.14
  tests/workflows/components/workflows.libsonnet
Labels: approved, cla: yes, lgtm, size/XS

#1060 Update resources in pipeline-runner role
  pipeline/pipelines-runner/base/cluster-role.yaml
  tests/tests/legacy_kustomizations/pipelines-runner/test_data/expected/rbac.authorization.k8s.io_v1beta1_clusterrole_pipeline-runner.yaml
Labels: approved, cla: yes, lgtm, size/M

#1081 Update AWS storage options to 1.14 CSI compatible
  aws/aws-efs-csi-driver/base/csi-attacher-cluster-role-binding.yaml
  aws/aws-efs-csi-driver/base/csi-attacher-cluster-role.yaml
  aws/aws-efs-csi-driver/base/csi-controller-sa.yaml
  aws/aws-efs-csi-driver/base/csi-controller-stateful-set.yaml
  aws/aws-efs-csi-driver/base/csi-default-storage.yaml
  aws/aws-efs-csi-driver/base/csi-driver.yaml
  aws/aws-efs-csi-driver/base/csi-node-cluster-role-binding.yaml
  aws/aws-efs-csi-driver/base/csi-node-cluster-role.yaml
  aws/aws-efs-csi-driver/base/csi-node-daemonset.yaml
  aws/aws-efs-csi-driver/base/csi-node-sa.yaml
  aws/aws-efs-csi-driver/base/kustomization.yaml
  aws/aws-fsx-csi-driver/base/csi-attacher-cluster-role-binding.yaml
  aws/aws-fsx-csi-driver/base/csi-attacher-cluster-role.yaml
  aws/aws-fsx-csi-driver/base/csi-controller-cluster-role-binding.yaml
  aws/aws-fsx-csi-driver/base/csi-controller-cluster-role.yaml
  aws/aws-fsx-csi-driver/base/csi-controller-sa.yaml
  aws/aws-fsx-csi-driver/base/csi-controller.yaml
  aws/aws-fsx-csi-driver/base/csi-default-storage.yaml
  aws/aws-fsx-csi-driver/base/csi-driver.yaml
  aws/aws-fsx-csi-driver/base/csi-node-cluster-role-binding.yaml
  aws/aws-fsx-csi-driver/base/csi-node-cluster-role.yaml
  aws/aws-fsx-csi-driver/base/csi-node-daemonset.yaml
  aws/aws-fsx-csi-driver/base/csi-node-sa.yaml
  aws/aws-fsx-csi-driver/base/csi-provisioner-cluster-role-binding.yaml
  aws/aws-fsx-csi-driver/base/csi-provisioner-cluster-role.yaml
  aws/aws-fsx-csi-driver/base/kustomization.yaml
Labels: approved, cla: yes, lgtm, size/L

#1098 Create a v3 version of the metadata package
  metadata/base/kustomization.yaml
  metadata/overlays/istio/virtual-service.yaml
  metadata/v3/kustomization.yaml
  metadata/v3/params.yaml
Labels: approved, cla: yes, lgtm, size/S

#1041 add knative and kfserving in AWS kfdef
  kfdef/kfctl_aws.v1.0.2.yaml
  kfdef/kfctl_aws.yaml
  kfdef/kfctl_aws_cognito.v1.0.2.yaml
  kfdef/kfctl_aws_cognito.yaml
  kfdef/source/master/kfctl_aws.yaml
  kfdef/source/master/kfctl_aws_cognito.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1105 Cherry-pick #1041 #1060 #1081 to v1.0-branch
  aws/aws-efs-csi-driver/base/csi-attacher-cluster-role-binding.yaml
  aws/aws-efs-csi-driver/base/csi-attacher-cluster-role.yaml
  aws/aws-efs-csi-driver/base/csi-controller-sa.yaml
  aws/aws-efs-csi-driver/base/csi-controller-stateful-set.yaml
  aws/aws-efs-csi-driver/base/csi-default-storage.yaml
  aws/aws-efs-csi-driver/base/csi-driver.yaml
  aws/aws-efs-csi-driver/base/csi-node-cluster-role-binding.yaml
  aws/aws-efs-csi-driver/base/csi-node-cluster-role.yaml
  aws/aws-efs-csi-driver/base/csi-node-daemonset.yaml
  aws/aws-efs-csi-driver/base/csi-node-sa.yaml
  aws/aws-efs-csi-driver/base/kustomization.yaml
  aws/aws-fsx-csi-driver/base/csi-attacher-cluster-role-binding.yaml
  aws/aws-fsx-csi-driver/base/csi-attacher-cluster-role.yaml
  aws/aws-fsx-csi-driver/base/csi-controller-cluster-role-binding.yaml
  aws/aws-fsx-csi-driver/base/csi-controller-cluster-role.yaml
  aws/aws-fsx-csi-driver/base/csi-controller-sa.yaml
  aws/aws-fsx-csi-driver/base/csi-controller.yaml
  aws/aws-fsx-csi-driver/base/csi-default-storage.yaml
  aws/aws-fsx-csi-driver/base/csi-driver.yaml
  aws/aws-fsx-csi-driver/base/csi-node-cluster-role-binding.yaml
  aws/aws-fsx-csi-driver/base/csi-node-cluster-role.yaml
  aws/aws-fsx-csi-driver/base/csi-node-daemonset.yaml
  aws/aws-fsx-csi-driver/base/csi-node-sa.yaml
  aws/aws-fsx-csi-driver/base/csi-provisioner-cluster-role-binding.yaml
  aws/aws-fsx-csi-driver/base/csi-provisioner-cluster-role.yaml
  aws/aws-fsx-csi-driver/base/kustomization.yaml
  kfdef/kfctl_aws.v1.0.2.yaml
  kfdef/kfctl_aws.yaml
  kfdef/kfctl_aws_cognito.v1.0.2.yaml
  kfdef/kfctl_aws_cognito.yaml
  kfdef/source/master/kfctl_aws.yaml
  kfdef/source/master/kfctl_aws_cognito.yaml
  pipeline/pipelines-runner/base/cluster-role.yaml
  tests/aws-aws-alb-ingress-controller-base_test.go
  tests/aws-aws-alb-ingress-controller-overlays-application_test.go
  tests/aws-aws-alb-ingress-controller-overlays-vpc_test.go
  tests/aws-aws-efs-csi-driver-base_test.go
  tests/aws-aws-fsx-csi-driver-base_test.go
  tests/pipeline-pipelines-runner-base_test.go
  tests/pipeline-pipelines-runner-overlays-application_test.go
  tests/pipeline-pipelines-runner-overlays-use-kf-user_test.go
Labels: approved, cla: yes, lgtm, size/XXL

#1094 v3 versions of default-install, kubeflow-roles, and spartakus
  common/spartakus/base/deployment.yaml
  common/spartakus/base/kustomization.yaml
  default-install/base/kustomization.yaml
  stacks/examples/kfctl_gcp_stacks.experimental.yaml
  stacks/gcp/kustomization.yaml
  tests/legacy_kustomizations/default-install/kustomization.yaml
  tests/legacy_kustomizations/spartakus/kustomization.yaml
  tests/stacks/examples/alice_gcp/test_data/expected/kubeflow.org_v1beta1_profile_anonymous.yaml
  tests/stacks/examples/alice_gcp/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_kubeflow-admin.yaml
  tests/stacks/examples/alice_gcp/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_kubeflow-edit.yaml
  tests/stacks/examples/alice_gcp/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_kubeflow-kubernetes-admin.yaml
  tests/stacks/examples/alice_gcp/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_kubeflow-kubernetes-edit.yaml
  tests/stacks/examples/alice_gcp/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_kubeflow-kubernetes-view.yaml
  tests/stacks/examples/alice_gcp/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_kubeflow-view.yaml
  tests/stacks/examples/alice_gcp/test_data/expected/~g_v1_configmap_default-install-config-h877hbtmf7.yaml
  tests/stacks/gcp/test_data/expected/kubeflow.org_v1beta1_profile_anonymous.yaml
  tests/stacks/gcp/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_kubeflow-admin.yaml
  tests/stacks/gcp/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_kubeflow-edit.yaml
  tests/stacks/gcp/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_kubeflow-kubernetes-admin.yaml
  tests/stacks/gcp/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_kubeflow-kubernetes-edit.yaml
  tests/stacks/gcp/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_kubeflow-kubernetes-view.yaml
  tests/stacks/gcp/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_kubeflow-view.yaml
  tests/stacks/gcp/test_data/expected/~g_v1_configmap_default-install-config-h877hbtmf7.yaml
  tests/tests/legacy_kustomizations/default-install/test_data/expected/~g_v1_configmap_default-install-config-6mcgbmmtg6.yaml
  tests/tests/legacy_kustomizations/spartakus/test_data/expected/apps_v1_deployment_spartakus-volunteer.yaml
  tests/tests/legacy_kustomizations/spartakus/test_data/expected/~g_v1_configmap_spartakus-config.yaml
Labels: approved, cla: yes, lgtm, size/XL

#1109 Update kfdefs for v1.0.2
  kfdef/kfctl_anthos.v1.0.2.yaml
  kfdef/kfctl_aws.v1.0.2.yaml
  kfdef/kfctl_aws_cognito.v1.0.2.yaml
  kfdef/kfctl_gcp_basic_auth.v1.0.2.yaml
  kfdef/kfctl_gcp_iap.v1.0.2.yaml
  kfdef/kfctl_ibm.v1.0.2.yaml
  kfdef/kfctl_istio_dex.v1.0.2.yaml
  kfdef/kfctl_k8s_istio.v1.0.2.yaml
  kfdef/source/v1.0.2/kfctl_anthos.yaml
  kfdef/source/v1.0.2/kfctl_aws.yaml
  kfdef/source/v1.0.2/kfctl_aws_cognito.yaml
  kfdef/source/v1.0.2/kfctl_gcp_basic_auth.yaml
  kfdef/source/v1.0.2/kfctl_gcp_iap.yaml
  kfdef/source/v1.0.2/kfctl_ibm.yaml
  kfdef/source/v1.0.2/kfctl_istio_dex.yaml
  kfdef/source/v1.0.2/kfctl_k8s_istio.yaml
Labels: approved, cla: yes, lgtm, size/M

#1111 Automated cherry pick of #1109: Update kfdefs for v1.0.2 Cherry pick of #1109 on v1.0-branch. #1109: Update kfdefs for v1.0.2
  kfdef/kfctl_anthos.v1.0.2.yaml
  kfdef/kfctl_aws.v1.0.2.yaml
  kfdef/kfctl_aws.yaml
  kfdef/kfctl_aws_cognito.v1.0.2.yaml
  kfdef/kfctl_aws_cognito.yaml
  kfdef/kfctl_gcp_basic_auth.v1.0.0.yaml
  kfdef/kfctl_gcp_basic_auth.v1.0.2.yaml
  kfdef/kfctl_gcp_iap.v1.0.0.yaml
  kfdef/kfctl_gcp_iap.v1.0.2.yaml
  kfdef/kfctl_ibm.v1.0.0.yaml
  kfdef/kfctl_ibm.v1.0.2.yaml
  kfdef/kfctl_istio_dex.v1.0.2.yaml
  kfdef/kfctl_k8s_istio.v1.0.0.yaml
  kfdef/kfctl_k8s_istio.v1.0.2.yaml
  kfdef/source/master/kfctl_aws.yaml
  kfdef/source/master/kfctl_aws_cognito.yaml
  kfdef/source/v1.0.2/kfctl_anthos.yaml
  kfdef/source/v1.0.2/kfctl_aws.yaml
  kfdef/source/v1.0.2/kfctl_aws_cognito.yaml
  kfdef/source/v1.0.2/kfctl_gcp_basic_auth.yaml
  kfdef/source/v1.0.2/kfctl_gcp_iap.yaml
  kfdef/source/v1.0.2/kfctl_ibm.yaml
  kfdef/source/v1.0.2/kfctl_istio_dex.yaml
  kfdef/source/v1.0.2/kfctl_k8s_istio.yaml
Labels: approved, cla: yes, lgtm, size/L

#1108 Add aggregation rule for mpi-operator and mxnet-operator clusterroles
  mpi-job/mpi-operator/base/cluster-role.yaml
  mxnet-job/mxnet-operator/base/cluster-role.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1120 Update maintainers info for MPIJob and MXJob manifests
  OWNERS
  mpi-job/mpi-operator/overlays/application/application.yaml
  mxnet-job/mxnet-operator/overlays/application/application.yaml
Labels: approved, cla: yes, lgtm, size/S

#1009 Fix & Update the Spark Operator
  argo/base/cluster-role.yaml
  pipeline/pipelines-runner/base/cluster-role.yaml
  spark/spark-operator/base/Kube-descriptor.yaml
  spark/spark-operator/base/cr-clusterrole.yaml
  spark/spark-operator/base/crd-cleanup-job.yaml
  spark/spark-operator/base/deploy.yaml
  spark/spark-operator/base/kustomization.yaml
  spark/spark-operator/base/scheduledsparkapplications.sparkoperator.k8s.io-crd.yaml
  spark/spark-operator/base/spark-sa.yaml
  spark/spark-operator/base/sparkapplications.sparkoperator.k8s.io-crd.yaml
  tests/tests/legacy_kustomizations/argo/test_data/expected/rbac.authorization.k8s.io_v1beta1_clusterrole_argo.yaml
  tests/tests/legacy_kustomizations/pipelines-runner/test_data/expected/rbac.authorization.k8s.io_v1beta1_clusterrole_pipeline-runner.yaml
  tests/tests/legacy_kustomizations/spark-operator/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_scheduledsparkapplications.sparkoperator.k8s.io.yaml
  tests/tests/legacy_kustomizations/spark-operator/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_sparkapplications.sparkoperator.k8s.io.yaml
  tests/tests/legacy_kustomizations/spark-operator/test_data/expected/apps_v1_deployment_spark-operatorsparkoperator.yaml
  tests/tests/legacy_kustomizations/spark-operator/test_data/expected/batch_v1_job_spark-operatorcrd-cleanup.yaml
  tests/tests/legacy_kustomizations/spark-operator/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_spark-operatoroperator-cr.yaml
Labels: approved, cla: yes, lgtm, size/L

#1116 Seldon 1.1.0
  seldon/Makefile
  seldon/kustomization.tpl
  seldon/seldon-core-operator/base/kustomization.yaml
  seldon/seldon-core-operator/base/resources.yaml
  seldon/seldon-core-operator/overlays/application/application.yaml
  seldon/values.yaml
  tests/tests/legacy_kustomizations/seldon-core-operator/test_data/expected/admissionregistration.k8s.io_v1beta1_mutatingwebhookconfiguration_seldon-mutating-webhook-configuration-kubeflow.yaml
  tests/tests/legacy_kustomizations/seldon-core-operator/test_data/expected/admissionregistration.k8s.io_v1beta1_validatingwebhookconfiguration_seldon-validating-webhook-configuration-kubeflow.yaml
  tests/tests/legacy_kustomizations/seldon-core-operator/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_seldondeployments.machinelearning.seldon.io.yaml
  tests/tests/legacy_kustomizations/seldon-core-operator/test_data/expected/app.k8s.io_v1beta1_application_seldon-core-operator.yaml
  tests/tests/legacy_kustomizations/seldon-core-operator/test_data/expected/apps_v1_deployment_seldon-controller-manager.yaml
  tests/tests/legacy_kustomizations/seldon-core-operator/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_seldon-manager-role-kubeflow.yaml
  tests/tests/legacy_kustomizations/seldon-core-operator/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_seldon-webhook-role-kubeflow.yaml
  tests/tests/legacy_kustomizations/seldon-core-operator/test_data/expected/rbac.authorization.k8s.io_v1_clusterrolebinding_seldon-webhook-rolebinding-kubeflow.yaml
  tests/tests/legacy_kustomizations/seldon-core-operator/test_data/expected/rbac.authorization.k8s.io_v1_rolebinding_seldon-manager-cm-rolebinding.yaml
  tests/tests/legacy_kustomizations/seldon-core-operator/test_data/expected/~g_v1_configmap_seldon-config.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#1128 upgrade mpi-operator manifests to v1
  mpi-job/mpi-operator/base/cluster-role.yaml
  mpi-job/mpi-operator/base/crd.yaml
  mpi-job/mpi-operator/base/deployment.yaml
  mpi-job/mpi-operator/base/kustomization.yaml
  mpi-job/mpi-operator/base/params.env
  mpi-job/mpi-operator/overlays/application/application.yaml
  mpi-job/mpi-operator/overlays/application/kustomization.yaml
Labels: approved, cla: yes, lgtm, size/L

#1110 Add google-cloudsql overlay for metadata
  metadata/overlays/google-cloudsql/README.md
  metadata/overlays/google-cloudsql/kustomization.yaml
  metadata/overlays/google-cloudsql/metadata-deployment.yaml
  metadata/overlays/google-cloudsql/params.env
Labels: approved, cla: yes, lgtm, size/L

#1132 Allow to specify paths to different Python and Kustomize binary
  hack/generate_tests.py
  tests/Makefile
Labels: approved, cla: yes, lgtm, size/XS

#1133 Fix In-compatibility Kustomize Go API Version
  go.mod
  go.sum
Labels: approved, cla: yes, lgtm, size/S

#1122 * Change the version on the GKE cluster because the version specified
  cert-manager/cert-manager/base/service-account.yaml
  cert-manager/cert-manager/v3/kustomization.yaml
  common/ambassador/base/cluster-role-binding.yaml
  common/ambassador/base/cluster-role.yaml
  common/ambassador/base/deployment-ambassador-patch.yaml
  common/ambassador/base/deployment.yaml
  common/ambassador/base/kustomization.yaml
  common/ambassador/base/params.env
  common/ambassador/base/params.yaml
  common/ambassador/base/service-account.yaml
  common/ambassador/base/service.yaml
  gcp/cloud-endpoints/overlays/application/kustomization.yaml
  gcp/v2/asm/istio-operator.yaml
  gcp/v2/cnrm/cluster.yaml
  gcp/v2/management/cluster/README.md
  gcp/v2/management/cluster/cluster.yaml
  gcp/v2/management/cluster/enable-services.yaml
  gcp/v2/management/cluster/kustomization.yaml
  gcp/v2/management/cluster/nodepool.yaml
  gcp/v2/management/cnrm-install/README.md
  gcp/v2/management/cnrm-install/enable-services.yaml
  gcp/v2/management/cnrm-install/iam.yaml
  gcp/v2/management/cnrm-install/install-system/0-cnrm-system.yaml
  gcp/v2/management/cnrm-install/install-system/crds.yaml
  gcp/v2/management/cnrm-install/install-system/kustomization.yaml
  istio/iap-gateway/base/istio-ingressgateway.yaml
  tests/Makefile
  tests/tests/legacy_kustomizations/cert-manager/test_data/expected/~g_v1_serviceaccount_cert-manager.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#1129 Add Abhilash to MPIJob manifests maintainers
  mpi-job/mpi-operator/overlays/application/application.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1126 private GKE templates
  gcp/v2/privateGKE/compute-network.yaml
  gcp/v2/privateGKE/dns-gcr.yaml
  gcp/v2/privateGKE/dns-google-apis.yaml
  gcp/v2/privateGKE/firewall.yaml
  gcp/v2/privateGKE/kustomization.yaml
Labels: approved, cla: yes, lgtm, size/L

#928 metadata deployment: Add liveness probe
  metadata/base/metadata-deployment.yaml
  tests/tests/legacy_kustomizations/metadata/test_data/expected/apps_v1_deployment_metadata-deployment.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1135 Fix CNRM cluster package.
  gcp/v2/asm/istio-operator.yaml
  gcp/v2/cnrm/cluster/cluster.yaml
  gcp/v2/cnrm/cluster/kf-vm-policy.yaml
  gcp/v2/cnrm/cluster/kf-vm-sa.yaml
  gcp/v2/cnrm/cluster/kustomization.yaml
  gcp/v2/cnrm/cluster/nodepool.yaml
  gcp/v2/cnrm/iam/kf-admin-policy.yaml
  gcp/v2/cnrm/iam/kf-admin-sa.yaml
  gcp/v2/cnrm/iam/kf-user-policy.yaml
  gcp/v2/cnrm/iam/kf-user-sa.yaml
  gcp/v2/cnrm/iam/kustomization.yaml
  gcp/v2/cnrm/ingress/compute-address.yaml
  gcp/v2/cnrm/ingress/kustomization.yaml
  gcp/v2/cnrm/kf-admin-policy.yaml
  gcp/v2/cnrm/kf-user-policy.yaml
  gcp/v2/cnrm/kf-vm-policy.yaml
  gcp/v2/cnrm/kustomization.yaml
  gcp/v2/cnrm/pipelines/disk.yaml
  gcp/v2/cnrm/pipelines/kustomization.yaml
Labels: approved, cla: yes, lgtm, size/XL

#1113 Add v1alpha1 XGBoostJob manifests
  xgboost-job/xgboost-operator/base/cluster-role-binding.yaml
  xgboost-job/xgboost-operator/base/cluster-role.yaml
  xgboost-job/xgboost-operator/base/crd.yaml
  xgboost-job/xgboost-operator/base/deployment.yaml
  xgboost-job/xgboost-operator/base/kustomization.yaml
  xgboost-job/xgboost-operator/base/params.env
  xgboost-job/xgboost-operator/base/service-account.yaml
  xgboost-job/xgboost-operator/base/service.yaml
  xgboost-job/xgboost-operator/overlays/application/application.yaml
  xgboost-job/xgboost-operator/overlays/application/kustomization.yaml
Labels: approved, cla: yes, lgtm, size/L

#1139 Standardize names for management blueprint.
  gcp/v2/management/cluster/cluster.yaml
  gcp/v2/management/cluster/nodepool.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1134 Fix certmanager race condition and version numbers.
  cert-manager/cert-manager/kubeflow-issuer/kustomization.yaml
  cert-manager/cert-manager/overlays/application/application.yaml
  cert-manager/cert-manager/overlays/application/kustomization.yaml
  cert-manager/cert-manager/overlays/self-signed/kustomization.yaml
  cert-manager/cert-manager/v3/kustomization.yaml
  tests/tests/legacy_kustomizations/cert-manager/test_data/expected/app.k8s.io_v1beta1_application_cert-manager.yaml
Labels: approved, cla: yes, lgtm, size/S
