Repository kubeflow/manifests, pull requests merged in 2020-07, with the labels that each got.

#1340 Disable sidecar for activator and autoscaler
  knative/knative-serving-install/base/deployment.yaml
  tests/tests/legacy_kustomizations/knative-install/test_data/expected/apps_v1_deployment_activator.yaml
  tests/tests/legacy_kustomizations/knative-install/test_data/expected/apps_v1_deployment_autoscaler.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1347 fix(gcp): Use IAMPolicyMember for workload identity bindings
  gcp/v2/cnrm/iam/admin-manages-user-policy.yaml
  gcp/v2/cnrm/iam/kf-admin-policy.yaml
  gcp/v2/cnrm/iam/kf-admin-workload-identity-bindings.yaml
  gcp/v2/cnrm/iam/kf-user-policy.yaml
  gcp/v2/cnrm/iam/kf-user-workload-identity-bindings.yaml
  gcp/v2/cnrm/iam/kustomization.yaml
Labels: approved, cla: yes, lgtm, size/M

#1349 Cherry pick "fix(gcp): Use IAMPolicyMember for workload identity bindings #1347"
  gcp/v2/cnrm/iam/admin-manages-user-policy.yaml
  gcp/v2/cnrm/iam/kf-admin-policy.yaml
  gcp/v2/cnrm/iam/kf-admin-workload-identity-bindings.yaml
  gcp/v2/cnrm/iam/kf-user-policy.yaml
  gcp/v2/cnrm/iam/kf-user-workload-identity-bindings.yaml
  gcp/v2/cnrm/iam/kustomization.yaml
Labels: approved, cla: yes, lgtm, size/M

#1335 added support for registration flow env variable
  common/centraldashboard/base/deployment_patch.yaml
  common/centraldashboard/base/kustomization.yaml
  common/centraldashboard/base/params.env
  tests/tests/legacy_kustomizations/centraldashboard/test_data/expected/apps_v1_deployment_centraldashboard.yaml
  tests/tests/legacy_kustomizations/centraldashboard/test_data/expected/~g_v1_configmap_parameters.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1342 feat: KFP multi user mode PR1 - enable multi user mode without istio authorization
  hack/pull_kfp_upstream.sh
  pipeline/installs/multi-user/api-service/cluster-role-binding.yaml
  pipeline/installs/multi-user/api-service/cluster-role.yaml
  pipeline/installs/multi-user/api-service/deployment-patch.yaml
  pipeline/installs/multi-user/api-service/kustomization.yaml
  pipeline/installs/multi-user/api-service/params.env
  pipeline/installs/multi-user/cache/cluster-role-binding.yaml
  pipeline/installs/multi-user/cache/cluster-role.yaml
  pipeline/installs/multi-user/cache/deployment-patch.yaml
  pipeline/installs/multi-user/cache/kustomization.yaml
  pipeline/installs/multi-user/kustomization.yaml
  pipeline/installs/multi-user/metadata-writer/cluster-role-binding.yaml
  pipeline/installs/multi-user/metadata-writer/cluster-role.yaml
  pipeline/installs/multi-user/metadata-writer/deployment-patch.yaml
  pipeline/installs/multi-user/metadata-writer/kustomization.yaml
  pipeline/installs/multi-user/persistence-agent/cluster-role-binding.yaml
  pipeline/installs/multi-user/persistence-agent/cluster-role.yaml
  pipeline/installs/multi-user/persistence-agent/deployment-patch.yaml
  pipeline/installs/multi-user/persistence-agent/kustomization.yaml
  pipeline/installs/multi-user/pipelines-profile-controller/composite-controller.yaml
  pipeline/installs/multi-user/pipelines-profile-controller/deployment.yaml
  pipeline/installs/multi-user/pipelines-profile-controller/kustomization.yaml
  pipeline/installs/multi-user/pipelines-profile-controller/params.env
  pipeline/installs/multi-user/pipelines-profile-controller/service.yaml
  pipeline/installs/multi-user/pipelines-profile-controller/sync.py
  pipeline/installs/multi-user/pipelines-ui/cluster-role-binding.yaml
  pipeline/installs/multi-user/pipelines-ui/cluster-role.yaml
  pipeline/installs/multi-user/pipelines-ui/configmap.yaml
  pipeline/installs/multi-user/pipelines-ui/deployment-patch.yaml
  pipeline/installs/multi-user/pipelines-ui/kustomization.yaml
  pipeline/installs/multi-user/scheduled-workflow/cluster-role-binding.yaml
  pipeline/installs/multi-user/scheduled-workflow/cluster-role.yaml
  pipeline/installs/multi-user/scheduled-workflow/deployment-patch.yaml
  pipeline/installs/multi-user/scheduled-workflow/kustomization.yaml
  pipeline/installs/multi-user/viewer-controller/cluster-role-binding.yaml
  pipeline/installs/multi-user/viewer-controller/cluster-role.yaml
  pipeline/installs/multi-user/viewer-controller/deployment-patch.yaml
  pipeline/installs/multi-user/viewer-controller/kustomization.yaml
Labels: approved, cla: yes, lgtm, size/XL

#1353 [AWS] Upgrade istio auth adapter version
  aws/aws-istio-authz-adaptor/base/kustomization.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1358 Automated cherry pick of #1353: Upgrade istio auth adapter version
  aws/aws-istio-authz-adaptor/base/kustomization.yaml
Labels: approved, lgtm, size/XS

#1360 [AWS] Revert istio version in cognito manifest back to 1.1.x
  kfdef/kfctl_aws_cognito.yaml
  kfdef/source/master/kfctl_aws_cognito.yaml
Labels: approved, cla: yes, lgtm, size/S

#1361 Automated cherry pick of #1360: Revert istio version in cognito manifest back to 1.1.x
  kfdef/kfctl_aws_cognito.yaml
  kfdef/source/master/kfctl_aws_cognito.yaml
Labels: approved, cla: yes, lgtm, size/S

#1355 add myself to kfdef/OWNERS
  kfdef/OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#1366 Switch GCP to regular channel which is on GKE 1.16
  gcp/v2/cnrm/cluster/cluster.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1365 Use kubeflow userid header and prefix config for KFP servers
  pipeline/installs/multi-user/api-service/deployment-patch.yaml
  pipeline/installs/multi-user/pipelines-ui/deployment-patch.yaml
Labels: approved, cla: yes, lgtm, size/S

#1368 feat: KFP multi user mode PR2 - secure KFP with istio mTLS and authz
  pipeline/installs/multi-user/istio-authorization-config.yaml
  pipeline/installs/multi-user/kustomization.yaml
  pipeline/installs/multi-user/pipelines-profile-controller/params.env
  pipeline/minio/installs/gcp-pd/kustomization.yaml
  pipeline/minio/installs/generic/deployment-patch.yaml
  pipeline/minio/installs/generic/kustomization.yaml
  pipeline/minio/installs/ibm/kustomization.yaml
  tests/stacks/examples/alice/test_data/expected/apps_v1_deployment_minio.yaml
  tests/stacks/gcp/test_data/expected/apps_v1_deployment_minio.yaml
  tests/stacks/generic/test_data/expected/apps_v1_deployment_minio.yaml
  tests/stacks/ibm/test_data/expected/apps_v1_deployment_minio.yaml
Labels: approved, cla: yes, lgtm, size/L

#1372 refactor: pipelines profile controller should get minio access keys from the secret
  pipeline/installs/multi-user/pipelines-profile-controller/deployment.yaml
  pipeline/installs/multi-user/pipelines-profile-controller/sync.py
Labels: approved, cla: yes, lgtm, size/M

#1375 Fix for Seldon custom namespace installs of kubeflow
  seldon/Makefile
  seldon/kustomization.tpl
  seldon/kustomizeconfig.tpl
  seldon/seldon-core-operator/base/kustomization.yaml
  seldon/seldon-core-operator/base/kustomizeconfig.yaml
  seldon/seldon-core-operator/base/resources.yaml
  seldon/seldon-core-operator/overlays/application/application.yaml
  seldon/seldon-core-operator/overlays/application/kustomization.yaml
  seldon/values.yaml
  tests/stacks/ibm/test_data/expected/admissionregistration.k8s.io_v1beta1_mutatingwebhookconfiguration_seldon-mutating-webhook-configuration-kubeflow.yaml
  tests/stacks/ibm/test_data/expected/admissionregistration.k8s.io_v1beta1_validatingwebhookconfiguration_seldon-validating-webhook-configuration-kubeflow.yaml
  tests/stacks/ibm/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_seldondeployments.machinelearning.seldon.io.yaml
  tests/stacks/ibm/test_data/expected/app.k8s.io_v1beta1_application_seldon-core-operator.yaml
  tests/stacks/ibm/test_data/expected/apps_v1_deployment_seldon-controller-manager.yaml
  tests/stacks/ibm/test_data/expected/cert-manager.io_v1alpha2_certificate_seldon-serving-cert.yaml
  tests/stacks/ibm/test_data/expected/cert-manager.io_v1alpha2_issuer_seldon-selfsigned-issuer.yaml
  tests/stacks/ibm/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_seldon-manager-role-kubeflow.yaml
  tests/stacks/ibm/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_seldon-manager-sas-role-kubeflow.yaml
  tests/stacks/ibm/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_seldon-webhook-role-kubeflow.yaml
  tests/stacks/ibm/test_data/expected/rbac.authorization.k8s.io_v1_clusterrolebinding_seldon-manager-rolebinding-kubeflow.yaml
  tests/stacks/ibm/test_data/expected/rbac.authorization.k8s.io_v1_clusterrolebinding_seldon-manager-sas-rolebinding-kubeflow.yaml
  tests/stacks/ibm/test_data/expected/rbac.authorization.k8s.io_v1_clusterrolebinding_seldon-webhook-rolebinding-kubeflow.yaml
  tests/stacks/ibm/test_data/expected/rbac.authorization.k8s.io_v1_role_seldon-leader-election-role.yaml
  tests/stacks/ibm/test_data/expected/rbac.authorization.k8s.io_v1_rolebinding_seldon-leader-election-rolebinding.yaml
  tests/stacks/ibm/test_data/expected/~g_v1_configmap_seldon-config.yaml
  tests/stacks/ibm/test_data/expected/~g_v1_service_seldon-webhook-service.yaml
  tests/stacks/ibm/test_data/expected/~g_v1_serviceaccount_seldon-manager.yaml
  tests/tests/legacy_kustomizations/seldon-core-operator/test_data/expected/admissionregistration.k8s.io_v1beta1_mutatingwebhookconfiguration_seldon-mutating-webhook-configuration-kubeflow.yaml
  tests/tests/legacy_kustomizations/seldon-core-operator/test_data/expected/admissionregistration.k8s.io_v1beta1_validatingwebhookconfiguration_seldon-validating-webhook-configuration-kubeflow.yaml
  tests/tests/legacy_kustomizations/seldon-core-operator/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_seldondeployments.machinelearning.seldon.io.yaml
  tests/tests/legacy_kustomizations/seldon-core-operator/test_data/expected/app.k8s.io_v1beta1_application_seldon-core-operator.yaml
  tests/tests/legacy_kustomizations/seldon-core-operator/test_data/expected/apps_v1_deployment_seldon-controller-manager.yaml
  tests/tests/legacy_kustomizations/seldon-core-operator/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_seldon-webhook-role-kubeflow.yaml
  tests/tests/legacy_kustomizations/seldon-core-operator/test_data/expected/rbac.authorization.k8s.io_v1_clusterrolebinding_seldon-webhook-rolebinding-kubeflow.yaml
  tests/tests/legacy_kustomizations/seldon-core-operator/test_data/expected/~g_v1_configmap_seldon-config.yaml
  tests/validate_resources_test.go
Labels: approved, cla: yes, lgtm, size/XL

#1350 Update Katib image tag to c3b38d8 on master
  katib/components/katib-controller/kustomization.yaml
  katib/components/katib-db-manager/kustomization.yaml
  katib/katib-controller/base/katib-configmap.yaml
  katib/katib-controller/base/kustomization.yaml
  tests/katib/installs/katib-external-db/test_data/expected/apps_v1_deployment_katib-controller.yaml
  tests/katib/installs/katib-external-db/test_data/expected/apps_v1_deployment_katib-db-manager.yaml
  tests/katib/installs/katib-external-db/test_data/expected/apps_v1_deployment_katib-ui.yaml
  tests/katib/installs/katib-external-db/test_data/expected/~g_v1_configmap_katib-config.yaml
  tests/katib/installs/katib-standalone-ibm/test_data/expected/apps_v1_deployment_katib-controller.yaml
  tests/katib/installs/katib-standalone-ibm/test_data/expected/apps_v1_deployment_katib-db-manager.yaml
  tests/katib/installs/katib-standalone-ibm/test_data/expected/apps_v1_deployment_katib-ui.yaml
  tests/katib/installs/katib-standalone-ibm/test_data/expected/~g_v1_configmap_katib-config.yaml
  tests/katib/installs/katib-standalone/test_data/expected/apps_v1_deployment_katib-controller.yaml
  tests/katib/installs/katib-standalone/test_data/expected/apps_v1_deployment_katib-db-manager.yaml
  tests/katib/installs/katib-standalone/test_data/expected/apps_v1_deployment_katib-ui.yaml
  tests/katib/installs/katib-standalone/test_data/expected/~g_v1_configmap_katib-config.yaml
  tests/stacks/examples/alice/test_data/expected/apps_v1_deployment_katib-controller.yaml
  tests/stacks/examples/alice/test_data/expected/apps_v1_deployment_katib-db-manager.yaml
  tests/stacks/examples/alice/test_data/expected/apps_v1_deployment_katib-ui.yaml
  tests/stacks/examples/alice/test_data/expected/~g_v1_configmap_katib-config.yaml
  tests/stacks/gcp/test_data/expected/apps_v1_deployment_katib-controller.yaml
  tests/stacks/gcp/test_data/expected/apps_v1_deployment_katib-db-manager.yaml
  tests/stacks/gcp/test_data/expected/apps_v1_deployment_katib-ui.yaml
  tests/stacks/gcp/test_data/expected/~g_v1_configmap_katib-config.yaml
  tests/stacks/generic/test_data/expected/apps_v1_deployment_katib-controller.yaml
  tests/stacks/generic/test_data/expected/apps_v1_deployment_katib-db-manager.yaml
  tests/stacks/generic/test_data/expected/apps_v1_deployment_katib-ui.yaml
  tests/stacks/generic/test_data/expected/~g_v1_configmap_katib-config.yaml
  tests/stacks/ibm/test_data/expected/apps_v1_deployment_katib-controller.yaml
  tests/stacks/ibm/test_data/expected/apps_v1_deployment_katib-db-manager.yaml
  tests/stacks/ibm/test_data/expected/apps_v1_deployment_katib-ui.yaml
  tests/stacks/ibm/test_data/expected/~g_v1_configmap_katib-config.yaml
  tests/tests/legacy_kustomizations/katib-controller/test_data/expected/apps_v1_deployment_katib-controller.yaml
  tests/tests/legacy_kustomizations/katib-controller/test_data/expected/apps_v1_deployment_katib-db-manager.yaml
  tests/tests/legacy_kustomizations/katib-controller/test_data/expected/apps_v1_deployment_katib-ui.yaml
  tests/tests/legacy_kustomizations/katib-controller/test_data/expected/~g_v1_configmap_katib-config.yaml
Labels: approved, cla: yes, lgtm, size/L

#1359 Automated cherry pick of #1340 upstream v1.1 branch
  knative/knative-serving-install/base/deployment.yaml
  tests/tests/legacy_kustomizations/knative-install/test_data/expected/apps_v1_deployment_activator.yaml
  tests/tests/legacy_kustomizations/knative-install/test_data/expected/apps_v1_deployment_autoscaler.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1387 Remove katib-metricscollector-injection label from Kubeflow namespace
  namespaces/base/namespaces.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1388 Automated cherry-pick of #1387: Remove katib-metricscollector-injection label from Kubeflow namespace on v1.1-branch
  namespaces/base/namespaces.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1389 Revert CRD status exception and remove status from Seldon CRD
  seldon/seldon-core-operator/base/resources.yaml
  tests/stacks/ibm/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_seldondeployments.machinelearning.seldon.io.yaml
  tests/tests/legacy_kustomizations/seldon-core-operator/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_seldondeployments.machinelearning.seldon.io.yaml
  tests/validate_resources_test.go
Labels: approved, cla: yes, lgtm, size/S

#1393 Check in expected kpt output for Kptfile refactoring
  hack/generate_gcp_kpt_data.py
  tests/testdata_gcp_kpt/gcp/v2/README.md
  tests/testdata_gcp_kpt/gcp/v2/asm/istio-operator.yaml
  tests/testdata_gcp_kpt/gcp/v2/cnrm/cluster/cluster.yaml
  tests/testdata_gcp_kpt/gcp/v2/cnrm/cluster/kf-vm-policy.yaml
  tests/testdata_gcp_kpt/gcp/v2/cnrm/cluster/kf-vm-sa.yaml
  tests/testdata_gcp_kpt/gcp/v2/cnrm/cluster/kustomization.yaml
  tests/testdata_gcp_kpt/gcp/v2/cnrm/cluster/nodepool.yaml
  tests/testdata_gcp_kpt/gcp/v2/cnrm/gcp-services.yaml
  tests/testdata_gcp_kpt/gcp/v2/cnrm/iam/admin-manages-user-policy.yaml
  tests/testdata_gcp_kpt/gcp/v2/cnrm/iam/kf-admin-policy.yaml
  tests/testdata_gcp_kpt/gcp/v2/cnrm/iam/kf-admin-sa.yaml
  tests/testdata_gcp_kpt/gcp/v2/cnrm/iam/kf-admin-workload-identity-bindings.yaml
  tests/testdata_gcp_kpt/gcp/v2/cnrm/iam/kf-user-policy.yaml
  tests/testdata_gcp_kpt/gcp/v2/cnrm/iam/kf-user-sa.yaml
  tests/testdata_gcp_kpt/gcp/v2/cnrm/iam/kf-user-workload-identity-bindings.yaml
  tests/testdata_gcp_kpt/gcp/v2/cnrm/iam/kustomization.yaml
  tests/testdata_gcp_kpt/gcp/v2/cnrm/ingress/compute-address.yaml
  tests/testdata_gcp_kpt/gcp/v2/cnrm/ingress/kustomization.yaml
  tests/testdata_gcp_kpt/gcp/v2/cnrm/kustomization.yaml
  tests/testdata_gcp_kpt/gcp/v2/cnrm/pipelines/disk.yaml
  tests/testdata_gcp_kpt/gcp/v2/cnrm/pipelines/kustomization.yaml
  tests/testdata_gcp_kpt/gcp/v2/management/cluster/README.md
  tests/testdata_gcp_kpt/gcp/v2/management/cluster/cluster.yaml
  tests/testdata_gcp_kpt/gcp/v2/management/cluster/enable-services.yaml
  tests/testdata_gcp_kpt/gcp/v2/management/cluster/kustomization.yaml
  tests/testdata_gcp_kpt/gcp/v2/management/cluster/nodepool.yaml
  tests/testdata_gcp_kpt/gcp/v2/management/cnrm-install/README.md
  tests/testdata_gcp_kpt/gcp/v2/management/cnrm-install/enable-services.yaml
  tests/testdata_gcp_kpt/gcp/v2/management/cnrm-install/iam.yaml
  tests/testdata_gcp_kpt/gcp/v2/management/cnrm-install/install-system/0-cnrm-system.yaml
  tests/testdata_gcp_kpt/gcp/v2/management/cnrm-install/install-system/crds.yaml
  tests/testdata_gcp_kpt/gcp/v2/management/cnrm-install/install-system/kustomization.yaml
  tests/testdata_gcp_kpt/gcp/v2/privateGKE/README.md
  tests/testdata_gcp_kpt/gcp/v2/privateGKE/cluster-private-patch.yaml
  tests/testdata_gcp_kpt/gcp/v2/privateGKE/compute-network.yaml
  tests/testdata_gcp_kpt/gcp/v2/privateGKE/dns-gcr.yaml
  tests/testdata_gcp_kpt/gcp/v2/privateGKE/dns-google-apis.yaml
  tests/testdata_gcp_kpt/gcp/v2/privateGKE/enable-services.yaml
  tests/testdata_gcp_kpt/gcp/v2/privateGKE/firewall.yaml
  tests/testdata_gcp_kpt/gcp/v2/privateGKE/kustomization.yaml
  tests/testdata_gcp_kpt/gcp/v2/privateGKE/kustomize-fns/README.md
  tests/testdata_gcp_kpt/gcp/v2/privateGKE/kustomize-fns/image_prefix.yaml
  tests/testdata_gcp_kpt/gcp/v2/privateGKE/nat.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#1395 Seldon 1.2.1 cherrypick to v1.1 branch
  seldon/Makefile
  seldon/kustomization.tpl
  seldon/kustomizeconfig.tpl
  seldon/seldon-core-operator/base/kustomization.yaml
  seldon/seldon-core-operator/base/kustomizeconfig.yaml
  seldon/seldon-core-operator/base/resources.yaml
  seldon/seldon-core-operator/overlays/application/application.yaml
  seldon/seldon-core-operator/overlays/application/kustomization.yaml
  seldon/values.yaml
  tests/stacks/ibm/test_data/expected/admissionregistration.k8s.io_v1beta1_mutatingwebhookconfiguration_seldon-mutating-webhook-configuration-kubeflow.yaml
  tests/stacks/ibm/test_data/expected/admissionregistration.k8s.io_v1beta1_validatingwebhookconfiguration_seldon-validating-webhook-configuration-kubeflow.yaml
  tests/stacks/ibm/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_seldondeployments.machinelearning.seldon.io.yaml
  tests/stacks/ibm/test_data/expected/app.k8s.io_v1beta1_application_seldon-core-operator.yaml
  tests/stacks/ibm/test_data/expected/apps_v1_deployment_seldon-controller-manager.yaml
  tests/stacks/ibm/test_data/expected/cert-manager.io_v1alpha2_certificate_seldon-serving-cert.yaml
  tests/stacks/ibm/test_data/expected/cert-manager.io_v1alpha2_issuer_seldon-selfsigned-issuer.yaml
  tests/stacks/ibm/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_seldon-manager-role-kubeflow.yaml
  tests/stacks/ibm/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_seldon-manager-sas-role-kubeflow.yaml
  tests/stacks/ibm/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_seldon-webhook-role-kubeflow.yaml
  tests/stacks/ibm/test_data/expected/rbac.authorization.k8s.io_v1_clusterrolebinding_seldon-manager-rolebinding-kubeflow.yaml
  tests/stacks/ibm/test_data/expected/rbac.authorization.k8s.io_v1_clusterrolebinding_seldon-manager-sas-rolebinding-kubeflow.yaml
  tests/stacks/ibm/test_data/expected/rbac.authorization.k8s.io_v1_clusterrolebinding_seldon-webhook-rolebinding-kubeflow.yaml
  tests/stacks/ibm/test_data/expected/rbac.authorization.k8s.io_v1_role_seldon-leader-election-role.yaml
  tests/stacks/ibm/test_data/expected/rbac.authorization.k8s.io_v1_rolebinding_seldon-leader-election-rolebinding.yaml
  tests/stacks/ibm/test_data/expected/~g_v1_configmap_seldon-config.yaml
  tests/stacks/ibm/test_data/expected/~g_v1_service_seldon-webhook-service.yaml
  tests/stacks/ibm/test_data/expected/~g_v1_serviceaccount_seldon-manager.yaml
  tests/tests/legacy_kustomizations/seldon-core-operator/test_data/expected/admissionregistration.k8s.io_v1beta1_mutatingwebhookconfiguration_seldon-mutating-webhook-configuration-kubeflow.yaml
  tests/tests/legacy_kustomizations/seldon-core-operator/test_data/expected/admissionregistration.k8s.io_v1beta1_validatingwebhookconfiguration_seldon-validating-webhook-configuration-kubeflow.yaml
  tests/tests/legacy_kustomizations/seldon-core-operator/test_data/expected/app.k8s.io_v1beta1_application_seldon-core-operator.yaml
  tests/tests/legacy_kustomizations/seldon-core-operator/test_data/expected/apps_v1_deployment_seldon-controller-manager.yaml
  tests/tests/legacy_kustomizations/seldon-core-operator/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_seldon-webhook-role-kubeflow.yaml
  tests/tests/legacy_kustomizations/seldon-core-operator/test_data/expected/rbac.authorization.k8s.io_v1_clusterrolebinding_seldon-webhook-rolebinding-kubeflow.yaml
  tests/tests/legacy_kustomizations/seldon-core-operator/test_data/expected/~g_v1_configmap_seldon-config.yaml
Labels: approved, cla: yes, lgtm, size/XL

#1385 Automated cherry pick of #1376: Add knative and kfserving to GCP stack #1381: knative shouldn't be part of GCP stack kustomization Cherry pick of #1376 #1381 on v1.1-branch. #1376: Add knative and kfserving to GCP stack #1381: knative shouldn't be part of GCP stack kustomization
  kfserving/installs/generic/kustomization.yaml
  knative/installs/generic/kustomization.yaml
  stacks/gcp/kustomization.yaml
  tests/stacks/examples/alice/test_data/expected/admissionregistration.k8s.io_v1beta1_mutatingwebhookconfiguration_inferenceservice.serving.kubeflow.org.yaml
  tests/stacks/examples/alice/test_data/expected/admissionregistration.k8s.io_v1beta1_validatingwebhookconfiguration_inferenceservice.serving.kubeflow.org.yaml
  tests/stacks/examples/alice/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_inferenceservices.serving.kubeflow.org.yaml
  tests/stacks/examples/alice/test_data/expected/app.k8s.io_v1beta1_application_kfserving-crds.yaml
  tests/stacks/examples/alice/test_data/expected/app.k8s.io_v1beta1_application_kfserving.yaml
  tests/stacks/examples/alice/test_data/expected/apps_v1_statefulset_kfserving-controller-manager.yaml
  tests/stacks/examples/alice/test_data/expected/cert-manager.io_v1alpha2_certificate_serving-cert.yaml
  tests/stacks/examples/alice/test_data/expected/cert-manager.io_v1alpha2_issuer_selfsigned-issuer.yaml
  tests/stacks/examples/alice/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_kfserving-proxy-role.yaml
  tests/stacks/examples/alice/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_kubeflow-kfserving-admin.yaml
  tests/stacks/examples/alice/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_kubeflow-kfserving-edit.yaml
  tests/stacks/examples/alice/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_kubeflow-kfserving-view.yaml
  tests/stacks/examples/alice/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_manager-role.yaml
  tests/stacks/examples/alice/test_data/expected/rbac.authorization.k8s.io_v1_clusterrolebinding_kfserving-proxy-rolebinding.yaml
  tests/stacks/examples/alice/test_data/expected/rbac.authorization.k8s.io_v1_clusterrolebinding_manager-rolebinding.yaml
  tests/stacks/examples/alice/test_data/expected/~g_v1_configmap_inferenceservice-config.yaml
  tests/stacks/examples/alice/test_data/expected/~g_v1_configmap_kfserving-config.yaml
  tests/stacks/examples/alice/test_data/expected/~g_v1_secret_kfserving-webhook-server-secret.yaml
  tests/stacks/examples/alice/test_data/expected/~g_v1_service_kfserving-controller-manager-metrics-service.yaml
  tests/stacks/examples/alice/test_data/expected/~g_v1_service_kfserving-controller-manager-service.yaml
  tests/stacks/examples/alice/test_data/expected/~g_v1_service_kfserving-webhook-server-service.yaml
  tests/stacks/gcp/test_data/expected/admissionregistration.k8s.io_v1beta1_mutatingwebhookconfiguration_inferenceservice.serving.kubeflow.org.yaml
  tests/stacks/gcp/test_data/expected/admissionregistration.k8s.io_v1beta1_validatingwebhookconfiguration_inferenceservice.serving.kubeflow.org.yaml
  tests/stacks/gcp/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_inferenceservices.serving.kubeflow.org.yaml
  tests/stacks/gcp/test_data/expected/app.k8s.io_v1beta1_application_kfserving-crds.yaml
  tests/stacks/gcp/test_data/expected/app.k8s.io_v1beta1_application_kfserving.yaml
  tests/stacks/gcp/test_data/expected/apps_v1_statefulset_kfserving-controller-manager.yaml
  tests/stacks/gcp/test_data/expected/cert-manager.io_v1alpha2_certificate_serving-cert.yaml
  tests/stacks/gcp/test_data/expected/cert-manager.io_v1alpha2_issuer_selfsigned-issuer.yaml
  tests/stacks/gcp/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_kfserving-proxy-role.yaml
  tests/stacks/gcp/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_kubeflow-kfserving-admin.yaml
  tests/stacks/gcp/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_kubeflow-kfserving-edit.yaml
  tests/stacks/gcp/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_kubeflow-kfserving-view.yaml
  tests/stacks/gcp/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_manager-role.yaml
  tests/stacks/gcp/test_data/expected/rbac.authorization.k8s.io_v1_clusterrolebinding_kfserving-proxy-rolebinding.yaml
  tests/stacks/gcp/test_data/expected/rbac.authorization.k8s.io_v1_clusterrolebinding_manager-rolebinding.yaml
  tests/stacks/gcp/test_data/expected/~g_v1_configmap_inferenceservice-config.yaml
  tests/stacks/gcp/test_data/expected/~g_v1_configmap_kfserving-config.yaml
  tests/stacks/gcp/test_data/expected/~g_v1_secret_kfserving-webhook-server-secret.yaml
  tests/stacks/gcp/test_data/expected/~g_v1_service_kfserving-controller-manager-metrics-service.yaml
  tests/stacks/gcp/test_data/expected/~g_v1_service_kfserving-controller-manager-service.yaml
  tests/stacks/gcp/test_data/expected/~g_v1_service_kfserving-webhook-server-service.yaml
  tests/validate_resources_test.go
Labels: approved, cla: yes, lgtm, size/XXL

#1391 Update tektoncd pipeline and dashboard version to the latest release
  tektoncd/tektoncd-dashboard/base/cluster-role-binding.yaml
  tektoncd/tektoncd-dashboard/base/cluster-role.yaml
  tektoncd/tektoncd-dashboard/base/crds.yaml
  tektoncd/tektoncd-dashboard/base/deployment.yaml
  tektoncd/tektoncd-dashboard/base/kustomization.yaml
  tektoncd/tektoncd-dashboard/base/pipeline.yaml
  tektoncd/tektoncd-dashboard/base/service-account.yaml
  tektoncd/tektoncd-dashboard/base/service.yaml
  tektoncd/tektoncd-dashboard/base/task.yaml
  tektoncd/tektoncd-install/base/cluster-role-binding.yaml
  tektoncd/tektoncd-install/base/cluster-role.yaml
  tektoncd/tektoncd-install/base/config-map.yaml
  tektoncd/tektoncd-install/base/crds.yaml
  tektoncd/tektoncd-install/base/deployment.yaml
  tektoncd/tektoncd-install/base/kustomization.yaml
  tektoncd/tektoncd-install/base/params.env
  tektoncd/tektoncd-install/base/role-binding.yaml
  tektoncd/tektoncd-install/base/role.yaml
  tektoncd/tektoncd-install/base/secret.yaml
  tektoncd/tektoncd-install/base/service-account.yaml
  tektoncd/tektoncd-install/base/service.yaml
  tektoncd/tektoncd-install/base/webhook-configuration.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#1370 Automated cherry pick of #1335: added support for registration flow env variable Cherry pick of #1335 on v1.1-branch. #1335: added support for registration flow env variable
  common/centraldashboard/base/deployment_patch.yaml
  common/centraldashboard/base/kustomization.yaml
  common/centraldashboard/base/params.env
  tests/tests/legacy_kustomizations/centraldashboard/test_data/expected/apps_v1_deployment_centraldashboard.yaml
  tests/tests/legacy_kustomizations/centraldashboard/test_data/expected/~g_v1_configmap_parameters.yaml
Labels: approved, cla: yes, lgtm, size/S

#1394 Moving central dashboard links to configmap
  common/centraldashboard/base/deployment_patch.yaml
  common/centraldashboard/base/links-configmap.yaml
  common/centraldashboard/base/role.yaml
  tests/stacks/examples/alice/test_data/expected/rbac.authorization.k8s.io_v1_role_centraldashboard.yaml
  tests/stacks/gcp/test_data/expected/rbac.authorization.k8s.io_v1_role_centraldashboard.yaml
  tests/stacks/generic/test_data/expected/rbac.authorization.k8s.io_v1_role_centraldashboard.yaml
  tests/stacks/ibm/test_data/expected/rbac.authorization.k8s.io_v1_role_centraldashboard.yaml
  tests/tests/legacy_kustomizations/centraldashboard/test_data/expected/apps_v1_deployment_centraldashboard.yaml
  tests/tests/legacy_kustomizations/centraldashboard/test_data/expected/rbac.authorization.k8s.io_v1_role_centraldashboard.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1425 Add PatrickXYS into reviewer list
  OWNERS
  tests/stacks/aws/test_data/expected/rbac.authorization.k8s.io_v1_role_centraldashboard.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1412 chore: upgrade istio to 1.4.10-asm.15
  gcp/v2/asm/istio-operator.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1429 Bring back some istio virtual services back to kubeflow namespace
  kfdef/kfctl_aws.yaml
  kfdef/kfctl_aws_cognito.yaml
  stacks/aws/kustomization.yaml
  tests/stacks/aws/test_data/expected/apps_v1_deployment_metadata-db.yaml
  tests/stacks/aws/test_data/expected/apps_v1_deployment_metadata-deployment.yaml
  tests/stacks/aws/test_data/expected/apps_v1_deployment_metadata-envoy-deployment.yaml
  tests/stacks/aws/test_data/expected/apps_v1_deployment_metadata-grpc-deployment.yaml
  tests/stacks/aws/test_data/expected/apps_v1_deployment_metadata-ui.yaml
  tests/stacks/aws/test_data/expected/networking.istio.io_v1alpha3_virtualservice_metadata-grpc.yaml
  tests/stacks/aws/test_data/expected/networking.istio.io_v1alpha3_virtualservice_metadata-ui.yaml
  tests/stacks/aws/test_data/expected/rbac.authorization.k8s.io_v1beta1_role_metadata-ui.yaml
  tests/stacks/aws/test_data/expected/rbac.authorization.k8s.io_v1beta1_rolebinding_metadata-ui.yaml
  tests/stacks/aws/test_data/expected/~g_v1_configmap_metadata-db-parameters.yaml
  tests/stacks/aws/test_data/expected/~g_v1_configmap_metadata-grpc-configmap.yaml
  tests/stacks/aws/test_data/expected/~g_v1_configmap_metadata-ui-parameters.yaml
  tests/stacks/aws/test_data/expected/~g_v1_persistentvolumeclaim_metadata-mysql.yaml
  tests/stacks/aws/test_data/expected/~g_v1_secret_metadata-db-secrets.yaml
  tests/stacks/aws/test_data/expected/~g_v1_service_metadata-db.yaml
  tests/stacks/aws/test_data/expected/~g_v1_service_metadata-envoy-service.yaml
  tests/stacks/aws/test_data/expected/~g_v1_service_metadata-grpc-service.yaml
  tests/stacks/aws/test_data/expected/~g_v1_service_metadata-service.yaml
  tests/stacks/aws/test_data/expected/~g_v1_service_metadata-ui.yaml
  tests/stacks/aws/test_data/expected/~g_v1_serviceaccount_metadata-ui.yaml
Labels: approved, cla: yes, lgtm, size/L

#1433 Cherry-pick #1429 into v1.1-branch
  kfdef/kfctl_aws.yaml
  kfdef/kfctl_aws_cognito.yaml
  stacks/aws/kustomization.yaml
  tests/stacks/aws/test_data/expected/apps_v1_deployment_metadata-db.yaml
  tests/stacks/aws/test_data/expected/apps_v1_deployment_metadata-deployment.yaml
  tests/stacks/aws/test_data/expected/apps_v1_deployment_metadata-envoy-deployment.yaml
  tests/stacks/aws/test_data/expected/apps_v1_deployment_metadata-grpc-deployment.yaml
  tests/stacks/aws/test_data/expected/apps_v1_deployment_metadata-ui.yaml
  tests/stacks/aws/test_data/expected/networking.istio.io_v1alpha3_virtualservice_metadata-grpc.yaml
  tests/stacks/aws/test_data/expected/networking.istio.io_v1alpha3_virtualservice_metadata-ui.yaml
  tests/stacks/aws/test_data/expected/rbac.authorization.k8s.io_v1beta1_role_metadata-ui.yaml
  tests/stacks/aws/test_data/expected/rbac.authorization.k8s.io_v1beta1_rolebinding_metadata-ui.yaml
  tests/stacks/aws/test_data/expected/~g_v1_configmap_metadata-db-parameters.yaml
  tests/stacks/aws/test_data/expected/~g_v1_configmap_metadata-grpc-configmap.yaml
  tests/stacks/aws/test_data/expected/~g_v1_configmap_metadata-ui-parameters.yaml
  tests/stacks/aws/test_data/expected/~g_v1_persistentvolumeclaim_metadata-mysql.yaml
  tests/stacks/aws/test_data/expected/~g_v1_secret_metadata-db-secrets.yaml
  tests/stacks/aws/test_data/expected/~g_v1_service_metadata-db.yaml
  tests/stacks/aws/test_data/expected/~g_v1_service_metadata-envoy-service.yaml
  tests/stacks/aws/test_data/expected/~g_v1_service_metadata-grpc-service.yaml
  tests/stacks/aws/test_data/expected/~g_v1_service_metadata-service.yaml
  tests/stacks/aws/test_data/expected/~g_v1_service_metadata-ui.yaml
  tests/stacks/aws/test_data/expected/~g_v1_serviceaccount_metadata-ui.yaml
Labels: approved, cla: yes, lgtm, size/L

#1434 Create v1.1.0 AWS Kfdef manifests
  kfdef/kfctl_aws.v1.1.0.yaml
  kfdef/kfctl_aws_cognito.v1.1.0.yaml
Labels: approved, cla: yes, lgtm, size/L

#1435 Correct AWS authz adaptor header
  aws/aws-istio-authz-adaptor/base/params.env
Labels: approved, cla: yes, lgtm, size/XS

#1436 Automated cherry pick of #1435: Correct AWS authz adaptor header
  aws/aws-istio-authz-adaptor/base/params.env
Labels: approved, cla: yes, lgtm, size/XS

#1437 Fix cloudresourcemanager service; missing ApiVersion.
  gcp/v2/management/cnrm-install/services/enable-services.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1439 Automated cherry pick of #1432: Fix management blueprint kptfile and stop using namespace #1437: Fix cloudresourcemanager service; missing ApiVersion. Cherry pick of #1432 #1437 on v1.1-branch. #1432: Fix management blueprint kptfile and stop using namespace #1437: Fix cloudresourcemanager service; missing ApiVersion.
  gcp/v2/management/Kptfile
  gcp/v2/management/cluster/cluster.yaml
  gcp/v2/management/cluster/enable-services.yaml
  gcp/v2/management/cluster/nodepool.yaml
  gcp/v2/management/cnrm-install/README.md
  gcp/v2/management/cnrm-install/enable-services.yaml
  gcp/v2/management/cnrm-install/iam.yaml
  gcp/v2/management/cnrm-install/iam/iam.yaml
  gcp/v2/management/cnrm-install/iam/kustomization.yaml
  gcp/v2/management/cnrm-install/install-system/0-cnrm-system.yaml
  gcp/v2/management/cnrm-install/install-system/crds.yaml
  gcp/v2/management/cnrm-install/services/enable-services.yaml
  gcp/v2/management/cnrm-install/services/kustomization.yaml
  hack/create_kptfile.py
Labels: approved, cla: yes, lgtm, size/XXL

#1442 Upgrade AWS jupyter images to 1.1.0
  stacks/aws/application/jupyter-web-app/configs/spawner_ui_config.yaml
  tests/stacks/aws/application/jupyter-web-app/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
  tests/stacks/aws/application/jupyter-web-app/test_data/expected/~g_v1_configmap_jupyter-web-app-jupyter-web-app-config-57ddmh4ht8.yaml
  tests/stacks/aws/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
  tests/stacks/aws/test_data/expected/~g_v1_configmap_jupyter-web-app-jupyter-web-app-config-57ddmh4ht8.yaml
Labels: approved, cla: yes, lgtm, size/M

#1444 Automated cherry pick of #1442: Upgrade AWS jupyter images to 1.1.0
  stacks/aws/application/jupyter-web-app/configs/spawner_ui_config.yaml
  tests/stacks/aws/application/jupyter-web-app/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
  tests/stacks/aws/application/jupyter-web-app/test_data/expected/~g_v1_configmap_jupyter-web-app-jupyter-web-app-config-57ddmh4ht8.yaml
  tests/stacks/aws/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
  tests/stacks/aws/test_data/expected/~g_v1_configmap_jupyter-web-app-jupyter-web-app-config-57ddmh4ht8.yaml
Labels: approved, cla: yes, lgtm, size/M

#1445 Pass userid-header param to kfam
  stacks/ibm/application/profiles/base/deployment_patch.yaml
  tests/stacks/ibm/application/profiles/base/test_data/expected/apps_v1_deployment_profiles-deployment.yaml
  tests/stacks/ibm/application/profiles/test_data/expected/apps_v1_deployment_profiles-deployment.yaml
  tests/stacks/ibm/multi-user/test_data/expected/apps_v1_deployment_profiles-deployment.yaml
  tests/stacks/ibm/test_data/expected/apps_v1_deployment_profiles-deployment.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1447 [IBM] update manifests repo link
  kfdef/kfctl_ibm.v1.1.0.yaml
  kfdef/kfctl_ibm_dex_multi_user.v1.1.0.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1448 Automated cherry pick of #1445: Pass userid-header param to kfam Cherry pick of #1445 on v1.1-branch. #1445: Pass userid-header param to kfam
  stacks/ibm/application/profiles/base/deployment_patch.yaml
  tests/stacks/ibm/application/profiles/base/test_data/expected/apps_v1_deployment_profiles-deployment.yaml
  tests/stacks/ibm/application/profiles/test_data/expected/apps_v1_deployment_profiles-deployment.yaml
  tests/stacks/ibm/multi-user/test_data/expected/apps_v1_deployment_profiles-deployment.yaml
  tests/stacks/ibm/test_data/expected/apps_v1_deployment_profiles-deployment.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/S

#1449 Automated cherry pick of #1447: update manifests repo link Cherry pick of #1447 on v1.1-branch. #1447: update manifests repo link
  kfdef/kfctl_ibm.v1.1.0.yaml
  kfdef/kfctl_ibm_dex_multi_user.v1.1.0.yaml
Labels: approved, cla: yes, lgtm, size/XS
