Repository kubeflow/manifests, pull requests merged in 2021-02, with the labels that each got.

#1737 Add comment for PR template
  .github/pull_request_template.md
Labels: approved, cla: yes, lgtm, size/XS

#1747 Update Seldon to 1.6.0
  contrib/seldon/Makefile
  contrib/seldon/seldon-core-operator/base/resources.yaml
  contrib/seldon/values.yaml
Labels: approved, cla: yes, lgtm, size/L

#1748 Delete leftover jupyter folder and amend pr template
  .github/pull_request_template.md
  jupyter/OWNERS
Labels: approved, cla: yes, lgtm, size/S

#1746 Private gke fixes
  distributions/gcp/Kptfile
  distributions/gcp/v2/privateGKE/cluster-private-patch.yaml
  distributions/gcp/v2/privateGKE/firewall.yaml
  go.sum
  tests/go.mod
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/M
