Repository kubeflow/manifests, pull requests merged in 2021-06, with the labels that each got.

#1898 Add kimwnasptd to the owners file
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#1900 docs: Add 1.3 release retrospective
  docs/release/retrospectives/release-1.3.md
Labels: approved, cla: yes, lgtm, size/L

#1902 Change user name to user@example.com in README
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#1905 Add linguist configuration
  .gitattributes
Labels: approved, cla: yes, lgtm, size/XS

#1768 Update Knative serving/eventing to 0.17
  common/knative/README.md
  common/knative/knative-eventing-crds/base/crd.yaml
  common/knative/knative-eventing-crds/base/kustomization.yaml
  common/knative/knative-eventing-crds/base/namespace.yaml
  common/knative/knative-eventing-crds/base/upstream/eventing-crds.yaml
  common/knative/knative-eventing-crds/base/upstream/in-memory-channel-crds.yaml
  common/knative/knative-eventing-install/base/cluster-role-binding.yaml
  common/knative/knative-eventing-install/base/cluster-role.yaml
  common/knative/knative-eventing-install/base/config-map.yaml
  common/knative/knative-eventing-install/base/deployment.yaml
  common/knative/knative-eventing-install/base/kustomization.yaml
  common/knative/knative-eventing-install/base/secret.yaml
  common/knative/knative-eventing-install/base/service-account.yaml
  common/knative/knative-eventing-install/base/service.yaml
  common/knative/knative-eventing-install/base/upstream/eventing-core.yaml
  common/knative/knative-eventing-install/base/upstream/in-memory-channel.yaml
  common/knative/knative-eventing-install/base/upstream/mt-channel-broker.yaml
  common/knative/knative-eventing-install/base/webhook-configuration.yaml
  common/knative/knative-serving-crds/base/crd.yaml
  common/knative/knative-serving-crds/base/kustomization.yaml
  common/knative/knative-serving-crds/base/namespace.yaml
  common/knative/knative-serving-crds/base/upstream/serving-crds.yaml
  common/knative/knative-serving-install/base/cluster-role-binding.yaml
  common/knative/knative-serving-install/base/cluster-role.yaml
  common/knative/knative-serving-install/base/config-map.yaml
  common/knative/knative-serving-install/base/deployment.yaml
  common/knative/knative-serving-install/base/gateway.yaml
  common/knative/knative-serving-install/base/hpa.yaml
  common/knative/knative-serving-install/base/image.yaml
  common/knative/knative-serving-install/base/istio-authorization-policy.yaml
  common/knative/knative-serving-install/base/kustomization.yaml
  common/knative/knative-serving-install/base/patches/configmap-patch.yaml
  common/knative/knative-serving-install/base/secret.yaml
  common/knative/knative-serving-install/base/service-account.yaml
  common/knative/knative-serving-install/base/service.yaml
  common/knative/knative-serving-install/base/upstream/net-istio.yaml
  common/knative/knative-serving-install/base/upstream/serving-core.yaml
  common/knative/knative-serving-install/base/webhook-configuration.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#1820 Update cert-manager manifests to 1.3.1 version
  README.md
  common/cert-manager/cert-manager-crds/base/crd.yaml
  common/cert-manager/cert-manager-crds/base/kustomization.yaml
  common/cert-manager/cert-manager-kube-system-resources/base/kustomization.yaml
  common/cert-manager/cert-manager-kube-system-resources/base/params.env
  common/cert-manager/cert-manager-kube-system-resources/base/params.yaml
  common/cert-manager/cert-manager-kube-system-resources/base/role-binding.yaml
  common/cert-manager/cert-manager-kube-system-resources/base/role.yaml
  common/cert-manager/cert-manager/base/api-service.yaml
  common/cert-manager/cert-manager/base/cert-manager.yaml
  common/cert-manager/cert-manager/base/cluster-role-binding.yaml
  common/cert-manager/cert-manager/base/cluster-role.yaml
  common/cert-manager/cert-manager/base/deployment.yaml
  common/cert-manager/cert-manager/base/kustomization.yaml
  common/cert-manager/cert-manager/base/mutating-webhook-configuration.yaml
  common/cert-manager/cert-manager/base/namespace.yaml
  common/cert-manager/cert-manager/base/params.env
  common/cert-manager/cert-manager/base/params.yaml
  common/cert-manager/cert-manager/base/patches/crd-preserve-unknown-fields.yaml
  common/cert-manager/cert-manager/base/service-account.yaml
  common/cert-manager/cert-manager/base/service.yaml
  common/cert-manager/cert-manager/base/validating-webhook-configuration.yaml
  common/cert-manager/cert-manager/kubeflow-issuer/base/cluster-issuer.yaml
  common/cert-manager/cert-manager/kubeflow-issuer/base/kustomization.yaml
  common/cert-manager/cert-manager/overlays/letsencrypt/cluster-issuer.yaml
  common/cert-manager/cert-manager/overlays/letsencrypt/kustomization.yaml
  common/cert-manager/cert-manager/overlays/letsencrypt/params.env
  common/cert-manager/cert-manager/overlays/letsencrypt/params.yaml
  common/cert-manager/cert-manager/overlays/self-signed/kustomization.yaml
  example/kustomization.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#1916 cert-manager: Split kubeflow-issuer into separate kustomization
  common/cert-manager/kubeflow-issuer/base/cluster-issuer.yaml
  common/cert-manager/kubeflow-issuer/base/kustomization.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1908 Upgrade Istio to 1.9.5
  README.md
  common/istio-1-9-0/cluster-local-gateway/base/istio-rbac.yaml
  common/istio-1-9/README.md
  common/istio-1-9/cluster-local-gateway/base/cluster-local-gateway.yaml
  common/istio-1-9/cluster-local-gateway/base/gateway-authorizationpolicy.yaml
  common/istio-1-9/cluster-local-gateway/base/gateway.yaml
  common/istio-1-9/cluster-local-gateway/base/kustomization.yaml
  common/istio-1-9/cluster-local-gateway/base/patches/remove-pdb.yaml
  common/istio-1-9/istio-crds/base/crd.yaml
  common/istio-1-9/istio-crds/base/kustomization.yaml
  common/istio-1-9/istio-install/base/deny_all_authorizationpolicy.yaml
  common/istio-1-9/istio-install/base/gateway.yaml
  common/istio-1-9/istio-install/base/gateway_authorizationpolicy.yaml
  common/istio-1-9/istio-install/base/install.yaml
  common/istio-1-9/istio-install/base/kustomization.yaml
  common/istio-1-9/istio-install/base/patches/istio-configmap-disable-tracing.yaml
  common/istio-1-9/istio-install/base/patches/remove-pdb.yaml
  common/istio-1-9/istio-install/base/patches/service.yaml
  common/istio-1-9/istio-install/base/x-forwarded-host.yaml
  common/istio-1-9/istio-namespace/base/kustomization.yaml
  common/istio-1-9/istio-namespace/base/namespace.yaml
  common/istio-1-9/kubeflow-istio-resources/base/cluster-roles.yaml
  common/istio-1-9/kubeflow-istio-resources/base/kf-istio-resources.yaml
  common/istio-1-9/kubeflow-istio-resources/base/kustomization.yaml
  common/istio-1-9/profile-overlay.yaml
  common/istio-1-9/profile.yaml
  common/istio-1-9/split-istio-packages
  distributions/kfdef/kfctl_aws.v1.3.0.yaml
  distributions/kfdef/kfctl_aws.yaml
  distributions/kfdef/kfctl_ibm.v1.3.0.yaml
  distributions/kfdef/kfctl_ibm_multi_user.v1.3.0.yaml
  distributions/kfdef/kfctl_openshift_v1.3.0.yaml
  distributions/stacks/aws/application/istio-1-9-1-stack/kustomization.yaml
  distributions/stacks/ibm/application/istio-1-9-0/kustomization.yaml
  distributions/stacks/ibm/application/knative/kustomization.yaml
  distributions/stacks/ibm/application/kubeflow-istio-resources/kustomization.yaml
  distributions/stacks/openshift/application/istio-1-9-0-Openshift/kustomization.yaml
  distributions/stacks/openshift/application/istio-1-9-0/kustomization.yaml
  distributions/stacks/openshift/application/knative/kustomization.yaml
  distributions/stacks/openshift/kustomization.yaml
  example/kustomization.yaml
Labels: approved, area/common, cla: yes, lgtm, size/XL

#1917 Knative 0.17
  README.md
  common/knative/README.md
  common/knative/knative-eventing-crds/base/kustomization.yaml
  common/knative/knative-eventing-crds/base/upstream/in-memory-channel-crds.yaml
  common/knative/knative-eventing-install/base/upstream/eventing-core.yaml
  common/knative/knative-eventing-post-install-jobs/base/eventing-post-install-jobs.yaml
  common/knative/knative-eventing-post-install-jobs/base/kustomization.yaml
  common/knative/knative-eventing/base/kustomization.yaml
  common/knative/knative-eventing/base/upstream/eventing-core.yaml
  common/knative/knative-eventing/base/upstream/in-memory-channel.yaml
  common/knative/knative-eventing/base/upstream/mt-channel-broker.yaml
  common/knative/knative-serving-crds/base/kustomization.yaml
  common/knative/knative-serving-crds/base/upstream/serving-crds.yaml
  common/knative/knative-serving-post-install-jobs/base/kustomization.yaml
  common/knative/knative-serving-post-install-jobs/base/serving-post-install-jobs.yaml
  common/knative/knative-serving/base/istio-authorization-policy.yaml
  common/knative/knative-serving/base/kustomization.yaml
  common/knative/knative-serving/base/patches/configmap-patch.yaml
  common/knative/knative-serving/base/patches/namespace-injection.yaml
  common/knative/knative-serving/base/patches/sidecar-injection.yaml
  common/knative/knative-serving/base/upstream/net-istio.yaml
  common/knative/knative-serving/base/upstream/serving-core.yaml
  example/kustomization.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#1907 First iteration of the Release Hanbook
  docs/release/handbook.md
Labels: approved, cla: yes, lgtm, size/L

#1927 common: Upgrade Istio to 1.9.6
  common/istio-1-9/cluster-local-gateway/base/cluster-local-gateway.yaml
  common/istio-1-9/istio-install/base/install.yaml
  common/istio-1-9/profile.yaml
Labels: approved, cla: yes, lgtm, size/S

#1929 Automated cherry pick of #1927: common: Upgrade Istio to 1.9.6
  common/istio-1-9/cluster-local-gateway/base/cluster-local-gateway.yaml
  common/istio-1-9/istio-install/base/install.yaml
  common/istio-1-9/profile.yaml
Labels: approved, cla: yes, lgtm, size/S
