Repository kubeflow/manifests, pull requests merged in 2021-07, with the labels that each got.

#1934 Openshift distribution: Fixing the uri to point to a tag 1.3.0 and not a branch 1.3.0
  distributions/kfdef/kfctl_openshift_v1.3.0.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1936 Openshift distribution: Fixing the uri to point to a tag 1.3.0 and no…
  distributions/kfdef/kfctl_openshift_v1.3.0.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1944 Update Seldon OWNERS file
  contrib/seldon/OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#1914 Upgrade to Seldon 1.9.0 Release
  contrib/seldon/seldon-core-operator/base/resources.yaml
  contrib/seldon/values.yaml
Labels: approved, cla: yes, lgtm, size/M

#1946 chore(gcp): delete distributions/stacks/gcp directory
  distributions/stacks/gcp/Kptfile
  distributions/stacks/gcp/OWNERS
  distributions/stacks/gcp/README.md
  distributions/stacks/gcp/config/params.env
  distributions/stacks/gcp/kustomization.yaml
  distributions/stacks/gcp/workload-identity-bindings-patch.yaml
Labels: approved, cla: yes, lgtm, size/L

#1877 fix(knative): aggregate knative namespaced roles to kubeflow roles
  common/knative/knative-eventing/base/kustomization.yaml
  common/knative/knative-eventing/base/patches/clusterrole-patch.yaml
  common/knative/knative-serving/base/kustomization.yaml
  common/knative/knative-serving/base/patches/clusterrole-patch.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#1948 cherry-pick: Permissions for Knative objects
  common/knative/knative-eventing/base/kustomization.yaml
  common/knative/knative-eventing/base/patches/clusterrole-patch.yaml
  common/knative/knative-serving/base/kustomization.yaml
  common/knative/knative-serving/base/patches/clusterrole-patch.yaml
Labels: approved, cla: yes, lgtm, size/M
