Repository kubeflow/manifests, pull requests merged in 2021-09, with the labels that each got.

#2012 Use MPI operator tag v0.3.0
  README.md
  apps/mpi-job/upstream/base/deployment.yaml
  apps/mpi-job/upstream/overlays/kubeflow/kustomization.yaml
  apps/mpi-job/upstream/overlays/standalone/kustomization.yaml
Labels: lgtm, approved, size/S, cla: yes

#2013 feat: add seldon permissions to default-editor
  contrib/seldon/seldon-core-operator/base/kubeflow-edit-seldon.yaml
  contrib/seldon/seldon-core-operator/base/kustomization.yaml
Labels: lgtm, approved, needs-ok-to-test, size/S, cla: yes

#2008 Update manifests for Katib 0.12.0-rc.1 release
  README.md
  apps/katib/upstream/components/controller/katib-config.yaml
  apps/katib/upstream/installs/katib-cert-manager/kustomization.yaml
  apps/katib/upstream/installs/katib-external-db/kustomization.yaml
  apps/katib/upstream/installs/katib-openshift/kustomization.yaml
  apps/katib/upstream/installs/katib-standalone/kustomization.yaml
  apps/katib/upstream/installs/katib-with-kubeflow/kustomization.yaml
Labels: lgtm, approved, size/M, cla: yes

#2019 Cherry-pick: Use MPI operator tag v0.3.0
  README.md
  apps/mpi-job/upstream/base/deployment.yaml
  apps/mpi-job/upstream/overlays/kubeflow/kustomization.yaml
  apps/mpi-job/upstream/overlays/standalone/kustomization.yaml
Labels: lgtm, approved, size/S, cla: yes

#2016 Adding Virtual Service to enable metadata
  distributions/stacks/openshift/application/pipeline-agnostic/kustomization.yaml
  distributions/stacks/openshift/application/pipeline-agnostic/metadata-gprc.yaml
  distributions/stacks/openshift/kustomization.yaml
Labels: lgtm, approved, size/XS, cla: yes

#2021 Update Notebooks WG manifests from RC1
  apps/admission-webhook/upstream/base/kustomization.yaml
  apps/centraldashboard/upstream/base/kustomization.yaml
  apps/jupyter/jupyter-web-app/upstream/base/configs/spawner_ui_config.yaml
  apps/jupyter/jupyter-web-app/upstream/base/kustomization.yaml
  apps/jupyter/notebook-controller/upstream/base/kustomization.yaml
  apps/profiles/upstream/base/kustomization.yaml
  apps/profiles/upstream/overlays/kubeflow/kustomization.yaml
  apps/tensorboard/tensorboard-controller/upstream/base/kustomization.yaml
  apps/tensorboard/tensorboards-web-app/upstream/base/kustomization.yaml
  apps/volumes-web-app/upstream/base/kustomization.yaml
Labels: lgtm, approved, size/M, cla: yes

#2020 git: Ignore Vim files
  .gitignore
Labels: lgtm, approved, size/XS, cla: yes

#2023 Fix apps description in example/kustomization.yaml
  example/kustomization.yaml
Labels: lgtm, approved, size/XS, ok-to-test, cla: yes

#2024 Update training operator to v1.3.0-rc.1
  README.md
  apps/training-operator/upstream/base/deployment.yaml
  apps/training-operator/upstream/base/service.yaml
  apps/training-operator/upstream/overlays/kubeflow/kustomization.yaml
  apps/training-operator/upstream/overlays/standalone/kustomization.yaml
Labels: lgtm, approved, size/S, cla: yes

#2026 Cherry pick of #2024: Update training operator to v1.3.0-rc.1
  README.md
  apps/training-operator/upstream/base/deployment.yaml
  apps/training-operator/upstream/base/service.yaml
  apps/training-operator/upstream/overlays/kubeflow/kustomization.yaml
  apps/training-operator/upstream/overlays/standalone/kustomization.yaml
Labels: lgtm, approved, size/S, cla: yes

#2032 Update training operator to v1.3.0-rc.2
  README.md
  apps/training-operator/upstream/base/kubeflow.org_mxjobs.yaml
  apps/training-operator/upstream/base/kubeflow.org_pytorchjobs.yaml
  apps/training-operator/upstream/base/kubeflow.org_tfjobs.yaml
  apps/training-operator/upstream/base/kubeflow.org_xgboostjobs.yaml
  apps/training-operator/upstream/overlays/kubeflow/kustomization.yaml
  apps/training-operator/upstream/overlays/standalone/kustomization.yaml
Labels: lgtm, approved, size/L, cla: yes

#2034 Use MPI operator tag v0.2.3
  apps/mpi-job/upstream/overlays/kubeflow/kustomization.yaml
  apps/mpi-job/upstream/overlays/standalone/kustomization.yaml
Labels: lgtm, approved, size/XS, cla: yes

#2033 Cherry pick of #2032: Update training operator to v1.3.0-rc.2
  README.md
  apps/training-operator/upstream/base/kubeflow.org_mxjobs.yaml
  apps/training-operator/upstream/base/kubeflow.org_pytorchjobs.yaml
  apps/training-operator/upstream/base/kubeflow.org_tfjobs.yaml
  apps/training-operator/upstream/base/kubeflow.org_xgboostjobs.yaml
  apps/training-operator/upstream/overlays/kubeflow/kustomization.yaml
  apps/training-operator/upstream/overlays/standalone/kustomization.yaml
Labels: lgtm, approved, size/L, cla: yes
