Repository kubeflow/manifests, pull requests merged in 2021-01, with the labels that each got.

#1702 Fix a typo in the overlay of metadata's external-mysql
  metadata/overlays/external-mysql/secrets.env
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#1706 Pin IBM 1.2 kfdef to include cherry-pick fixes
  kfdef/kfctl_ibm.v1.2.0.yaml
  kfdef/kfctl_ibm_multi_user.v1.2.0.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1709 Add Test README support
  README.md
Labels: approved, cla: yes, lgtm, size/S

#1712 Change cluster-admin role to `ml-pipeline-persistenceagent` for the pipeline/persistent-agent sa
  pipeline/persistent-agent/base/clusterrole-binding.yaml
  tests/tests/legacy_kustomizations/persistent-agent/test_data/expected/rbac.authorization.k8s.io_v1beta1_clusterrolebinding_ml-pipeline-persistenceagent.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1713 [Test] Remove stale ksonnet code
  .github/workflows/manifests_unittests.yaml
  README.md
  prow_config.yaml
  tests/workflows/app.yaml
  tests/workflows/components/params.libsonnet
  tests/workflows/components/util.libsonnet
  tests/workflows/components/workflows.jsonnet
  tests/workflows/components/workflows.libsonnet
  tests/workflows/environments/base.libsonnet
  tests/workflows/environments/releasing/main.jsonnet
  tests/workflows/environments/releasing/params.libsonnet
  tests/workflows/lib/v1.7.0/k.libsonnet
  tests/workflows/lib/v1.7.0/k8s.libsonnet
  tests/workflows/lib/v1.7.0/swagger.json
Labels: approved, cla: yes, lgtm, size/XXL

#1718 chore: delete outdated metadata google cloudsql overlay
  metadata/overlays/google-cloudsql/README.md
  metadata/overlays/google-cloudsql/kustomization.yaml
  metadata/overlays/google-cloudsql/metadata-deployment.yaml
  metadata/overlays/google-cloudsql/params.env
Labels: approved, cla: yes, lgtm, size/L

#1726 Migrate manifests repo
  prow_config.yaml
Labels: approved, cla: yes, size/XS
