Repository kubeflow/manifests, pull requests merged in 2021-08, with the labels that each got.

#1953 Add the release team as owners in the relevant dir
  docs/release/OWNERS
Labels: lgtm, approved, size/S, cla: yes

#1883 Fix dex for Kubernetes 1.21
  common/dex/base/deployment.yaml
Labels: lgtm, approved, size/XS, cla: yes

#1967 Update KFServing manifests to 0.6
  apps/kfserving/upstream/configmap/inferenceservice.yaml
  apps/kfserving/upstream/crd/patches/protocol.yaml
  apps/kfserving/upstream/crd/serving.kubeflow.org_inferenceservices.yaml
  apps/kfserving/upstream/default/kustomization.yaml
  apps/kfserving/upstream/default/manager_image_patch.yaml
  apps/kfserving/upstream/default/params.env
  apps/kfserving/upstream/default/params.yaml
  apps/kfserving/upstream/overlays/kubeflow/cluster-role.yaml
  apps/kfserving/upstream/overlays/kubeflow/kustomization.yaml
  apps/kfserving/upstream/overlays/kubeflow/params.env
  apps/kfserving/upstream/overlays/kubeflow/params.yaml
  apps/kfserving/upstream/overlays/kubeflow/patches/namespace.yaml
  apps/kfserving/upstream/overlays/kubeflow/patches/statefulset.yaml
  apps/kfserving/upstream/overlays/kubeflow/patches/web-app-sidecar.yaml
  apps/kfserving/upstream/overlays/kubeflow/patches/web-app-vsvc.yaml
  apps/kfserving/upstream/overlays/kubeflow/web-app-authorization-policy.yaml
  apps/kfserving/upstream/overlays/test/configmap/inferenceservice.yaml
  apps/kfserving/upstream/web-app/deployment.yaml
  apps/kfserving/upstream/web-app/istio.yaml
  apps/kfserving/upstream/web-app/kustomization.yaml
  apps/kfserving/upstream/web-app/rbac.yaml
  apps/kfserving/upstream/web-app/service.yaml
Labels: lgtm, approved, size/XL, cla: yes

#1987 Sync manifests for Notebooks WG v1.4-rc.0
  apps/admission-webhook/upstream/base/crd.yaml
  apps/admission-webhook/upstream/base/kustomization.yaml
  apps/centraldashboard/upstream/base/configmap.yaml
  apps/centraldashboard/upstream/base/kustomization.yaml
  apps/jupyter/jupyter-web-app/upstream/base/configs/spawner_ui_config.yaml
  apps/jupyter/jupyter-web-app/upstream/base/kustomization.yaml
  apps/jupyter/notebook-controller/upstream/base/kustomization.yaml
  apps/profiles/upstream/README.md
  apps/profiles/upstream/base/kustomization.yaml
  apps/profiles/upstream/base/namespace-labels.yaml
  apps/profiles/upstream/base/patches/manager.yaml
  apps/profiles/upstream/overlays/kubeflow/kustomization.yaml
  apps/tensorboard/tensorboard-controller/upstream/base/kustomization.yaml
  apps/tensorboard/tensorboard-controller/upstream/default/kustomization.yaml
  apps/tensorboard/tensorboards-web-app/upstream/base/kustomization.yaml
  apps/volumes-web-app/upstream/base/kustomization.yaml
Labels: lgtm, approved, size/L, cla: yes

#1988 Update manifests for AutoML WG 0.12-rc.0
  README.md
  apps/katib/upstream/components/cert-generator/cert-generator.yaml
  apps/katib/upstream/components/cert-generator/kustomization.yaml
  apps/katib/upstream/components/controller/controller.yaml
  apps/katib/upstream/components/controller/katib-config.yaml
  apps/katib/upstream/components/controller/kustomization.yaml
  apps/katib/upstream/components/controller/rbac.yaml
  apps/katib/upstream/components/controller/service.yaml
  apps/katib/upstream/components/controller/trial-templates.yaml
  apps/katib/upstream/components/crd/experiment.yaml
  apps/katib/upstream/components/crd/kustomization.yaml
  apps/katib/upstream/components/crd/suggestion.yaml
  apps/katib/upstream/components/crd/trial.yaml
  apps/katib/upstream/components/db-manager/db-manager.yaml
  apps/katib/upstream/components/db-manager/kustomization.yaml
  apps/katib/upstream/components/db-manager/service.yaml
  apps/katib/upstream/components/mysql/kustomization.yaml
  apps/katib/upstream/components/mysql/mysql.yaml
  apps/katib/upstream/components/mysql/pv.yaml
  apps/katib/upstream/components/mysql/pvc.yaml
  apps/katib/upstream/components/mysql/service.yaml
  apps/katib/upstream/components/ui/kustomization.yaml
  apps/katib/upstream/components/ui/service.yaml
  apps/katib/upstream/components/ui/ui.yaml
  apps/katib/upstream/components/webhook/kustomization.yaml
  apps/katib/upstream/installs/katib-cert-manager/certificate.yaml
  apps/katib/upstream/installs/katib-cert-manager/kustomization.yaml
  apps/katib/upstream/installs/katib-cert-manager/params.yaml
  apps/katib/upstream/installs/katib-external-db/kustomization.yaml
  apps/katib/upstream/installs/katib-external-db/patches/db-manager.yaml
  apps/katib/upstream/installs/katib-ibm/kustomization.yaml
  apps/katib/upstream/installs/katib-ibm/mysql-patch.yaml
  apps/katib/upstream/installs/katib-openshift/kustomization.yaml
  apps/katib/upstream/installs/katib-openshift/patches/service-serving-cert.yaml
  apps/katib/upstream/installs/katib-openshift/patches/webhook-inject-cabundle.yaml
  apps/katib/upstream/installs/katib-standalone/kustomization.yaml
  apps/katib/upstream/installs/katib-with-kubeflow/kustomization.yaml
  apps/katib/upstream/installs/katib-with-kubeflow/patches/mysql-pvc.yaml
  apps/katib/upstream/installs/katib-with-kubeflow/patches/remove-namespace.yaml
  apps/katib/upstream/installs/katib-with-kubeflow/patches/remove-resources-patch.yaml
Labels: lgtm, approved, size/XL, cla: yes

#1965 Update Knative to 0.22.1
  common/knative/README.md
  common/knative/knative-eventing-post-install-jobs/base/eventing-post-install-jobs.yaml
  common/knative/knative-eventing/base/upstream/eventing-core.yaml
  common/knative/knative-eventing/base/upstream/in-memory-channel.yaml
  common/knative/knative-eventing/base/upstream/mt-channel-broker.yaml
  common/knative/knative-serving-post-install-jobs/base/serving-post-install-jobs.yaml
  common/knative/knative-serving/base/istio-authorization-policy.yaml
  common/knative/knative-serving/base/kustomization.yaml
  common/knative/knative-serving/base/upstream/net-istio.yaml
  common/knative/knative-serving/base/upstream/serving-core.yaml
Labels: lgtm, approved, size/XXL, cla: yes

#1989 Update the versions of components in README
  README.md
Labels: lgtm, approved, size/S, cla: yes

#1974 Add 1.4 release information
  docs/releases/OWNERS
  docs/releases/handbook.md
  docs/releases/release-1.4/README.md
  docs/releases/release-1.4/release-team.md
  docs/releases/retrospectives/release-1.3.md
Labels: lgtm, approved, size/M, cla: yes

#1996 Allocate 3 weeks for distribution testing
  docs/releases/release-1.4/README.md
Labels: lgtm, approved, size/XS, cla: yes

#1997 Update pipelines to 1.7.0
  apps/pipeline/upstream/base/cache-deployer/kustomization.yaml
  apps/pipeline/upstream/base/cache/kustomization.yaml
  apps/pipeline/upstream/base/installs/generic/pipeline-install-config.yaml
  apps/pipeline/upstream/base/metadata/base/kustomization.yaml
  apps/pipeline/upstream/base/pipeline/kustomization.yaml
  apps/pipeline/upstream/base/pipeline/metadata-writer/kustomization.yaml
  apps/pipeline/upstream/env/gcp/inverse-proxy/kustomization.yaml
  apps/pipeline/upstream/env/platform-agnostic-multi-user-emissary/workflow-controller-configmap-patch.yaml
  apps/pipeline/upstream/env/platform-agnostic-multi-user-pns/workflow-controller-configmap-patch.yaml
  apps/pipeline/upstream/env/platform-agnostic-pns/workflow-controller-configmap-patch.yaml
  apps/pipeline/upstream/third-party/argo/base/workflow-controller-configmap-patch.yaml
  apps/pipeline/upstream/third-party/argo/base/workflow-controller-deployment-patch.yaml
  apps/pipeline/upstream/third-party/argo/installs/cluster/kustomization.yaml
  apps/pipeline/upstream/third-party/argo/installs/cluster/workflow-controller-clusterrolebinding-patch.json
Labels: lgtm, approved, size/M, cla: yes

#1999 Update README for pipelines 1.7.0
  README.md
Labels: lgtm, approved, size/XS, cla: yes

#2000 Cherry pick updates to the RC 0
  README.md
  apps/pipeline/upstream/base/cache-deployer/kustomization.yaml
  apps/pipeline/upstream/base/cache/kustomization.yaml
  apps/pipeline/upstream/base/installs/generic/pipeline-install-config.yaml
  apps/pipeline/upstream/base/metadata/base/kustomization.yaml
  apps/pipeline/upstream/base/pipeline/kustomization.yaml
  apps/pipeline/upstream/base/pipeline/metadata-writer/kustomization.yaml
  apps/pipeline/upstream/env/gcp/inverse-proxy/kustomization.yaml
  apps/pipeline/upstream/env/platform-agnostic-multi-user-emissary/workflow-controller-configmap-patch.yaml
  apps/pipeline/upstream/env/platform-agnostic-multi-user-pns/workflow-controller-configmap-patch.yaml
  apps/pipeline/upstream/env/platform-agnostic-pns/workflow-controller-configmap-patch.yaml
  apps/pipeline/upstream/third-party/argo/base/workflow-controller-configmap-patch.yaml
  apps/pipeline/upstream/third-party/argo/base/workflow-controller-deployment-patch.yaml
  apps/pipeline/upstream/third-party/argo/installs/cluster/kustomization.yaml
  apps/pipeline/upstream/third-party/argo/installs/cluster/workflow-controller-clusterrolebinding-patch.json
  docs/releases/OWNERS
  docs/releases/handbook.md
  docs/releases/release-1.4/README.md
  docs/releases/release-1.4/release-team.md
  docs/releases/retrospectives/release-1.3.md
Labels: lgtm, approved, size/L, cla: yes
