Repository kubeflow/manifests, pull requests merged in 2021-03, with the labels that each got.

#1752 feat(backend): Updated to make possible to evict pods even with empty dir. Fixes #4530 kubeflow/pipelines
  apps/pipeline/upstream/installs/multi-user/pipelines-profile-controller/sync.py
  apps/pipeline/upstream/installs/tekton-multi-user/sync.py
Labels: approved, cla: yes, lgtm, size/S

#1759 remove spartakus from kfctl_k8s_istio.yaml
  distributions/kfdef/kfctl_k8s_istio.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/S

#1762 OWNERS: Update top-level owners to match wg-manifests charter
  OWNERS
Labels: approved, cla: yes, lgtm, size/S

#1755 Add Feast to Kubeflow Contrib
  contrib/feast/Makefile
  contrib/feast/OWNERS
  contrib/feast/README.md
  contrib/feast/feast/base/kustomization.yaml
  contrib/feast/feast/base/resources.yaml
  contrib/feast/feast/base/static.yaml
  contrib/feast/feast/overlays/application/application.yaml
  contrib/feast/feast/overlays/application/kustomization.yaml
  contrib/feast/values.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#1772 cert-manager: Remove v3 manifests
  common/cert-manager/cert-manager/kubeflow-issuer/kustomization.yaml
  common/cert-manager/cert-manager/overlays/application/kustomization.yaml
  common/cert-manager/cert-manager/overlays/letsencrypt/kustomization.yaml
  common/cert-manager/cert-manager/overlays/self-signed/kustomization.yaml
  common/cert-manager/cert-manager/v3/kustomization.yaml
Labels: approved, cla: yes, lgtm, size/S

#1774 fix namespace conflict deploying feast to kubeflow
  contrib/feast/Makefile
  contrib/feast/feast/base/resources.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/M

#1771 consolidate dex manifests
  common/dex-auth/dex-crds/base_v3/kustomization.yaml
  common/dex-auth/dex-crds/overlays/istio/kustomization.yaml
  common/dex-auth/dex-crds/overlays/istio/params.env
  common/dex/OWNERS
  common/dex/base/config-map.yaml
  common/dex/base/crds.yaml
  common/dex/base/deployment.yaml
  common/dex/base/kustomization.yaml
  common/dex/base/namespace.yaml
  common/dex/base/params.env
  common/dex/base/params.yaml
  common/dex/base/service.yaml
  common/dex/overlays/github/config-map.yaml
  common/dex/overlays/github/kustomization.yaml
  common/dex/overlays/github/params.env
  common/dex/overlays/github/params.yaml
  common/dex/overlays/github/virtual-service.yaml
  common/dex/overlays/istio/kustomization.yaml
  common/dex/overlays/istio/params.yaml
  common/dex/overlays/istio/virtual-service.yaml
  common/dex/overlays/ldap/config-map.yaml
  common/dex/overlays/ldap/deployment.yaml
  common/dex/overlays/ldap/kustomization.yaml
  common/dex/overlays/ldap/params.env
  common/dex/overlays/ldap/params.yaml
  contrib/dex-auth/OWNERS
  contrib/dex-auth/README.md
  contrib/dex-auth/dex-authenticator/base/config-map.yaml
  contrib/dex-auth/dex-authenticator/base/deployment.yaml
  contrib/dex-auth/dex-authenticator/base/kustomization.yaml
  contrib/dex-auth/dex-authenticator/base/namespace.yaml
  contrib/dex-auth/dex-authenticator/base/params.env
  contrib/dex-auth/dex-authenticator/base/params.yaml
  contrib/dex-auth/dex-authenticator/base/service.yaml
  contrib/dex-auth/dex-authenticator/base_v3/kustomization.yaml
  contrib/dex-auth/dex-ldap/base/deployment.yaml
  contrib/dex-auth/dex-ldap/base/kustomization.yaml
  contrib/dex-auth/dex-ldap/base/namespace.yaml
  contrib/dex-auth/dex-ldap/base/service.yaml
  contrib/dex-auth/keycloak-gatekeeper/base/config-map.yaml
  contrib/dex-auth/keycloak-gatekeeper/base/deployment.yaml
  contrib/dex-auth/keycloak-gatekeeper/base/kustomization.yaml
  contrib/dex-auth/keycloak-gatekeeper/base/namespace.yaml
  contrib/dex-auth/keycloak-gatekeeper/base/params.env
  contrib/dex-auth/keycloak-gatekeeper/base/params.yaml
  contrib/dex-auth/keycloak-gatekeeper/base/service.yaml
  contrib/dex-auth/keycloak-gatekeeper/base/virtualservice.yaml
  contrib/dex-auth/keycloak-gatekeeper/base_v3/kustomization.yaml
Labels: approved, cla: yes, lgtm, size/L

#1765 chore: delete kubeflow/metadata manifests
  contrib/metadata/OWNERS
  contrib/metadata/base/grpc-params.env
  contrib/metadata/base/kustomization.yaml
  contrib/metadata/base/metadata-deployment.yaml
  contrib/metadata/base/metadata-envoy-deployment.yaml
  contrib/metadata/base/metadata-envoy-service.yaml
  contrib/metadata/base/metadata-service.yaml
  contrib/metadata/base/params.env
  contrib/metadata/overlays/application/application.yaml
  contrib/metadata/overlays/application/kustomization.yaml
  contrib/metadata/overlays/db/kustomization.yaml
  contrib/metadata/overlays/db/metadata-db-deployment.yaml
  contrib/metadata/overlays/db/metadata-db-pvc.yaml
  contrib/metadata/overlays/db/metadata-db-service.yaml
  contrib/metadata/overlays/db/metadata-deployment.yaml
  contrib/metadata/overlays/db/params.env
  contrib/metadata/overlays/db/secrets.env
  contrib/metadata/overlays/external-mysql/kustomization.yaml
  contrib/metadata/overlays/external-mysql/metadata-deployment.yaml
  contrib/metadata/overlays/external-mysql/params.env
  contrib/metadata/overlays/external-mysql/secrets.env
  contrib/metadata/overlays/ibm-storage-config/kustomization.yaml
  contrib/metadata/overlays/istio/kustomization.yaml
  contrib/metadata/overlays/istio/params.yaml
  contrib/metadata/overlays/istio/virtual-service-metadata-grpc.yaml
  contrib/metadata/v3/kustomization.yaml
  contrib/metadata/v3/params.yaml
Labels: approved, cla: yes, lgtm, size/L

#1782 fix(GCP): Set fixed Kubernetes version to be 1.16 for successful Kubeflow 1.2 deployment. Fixes kubeflow/gcp-blueprints#198
  gcp/v2/cnrm/cluster/cluster.yaml
Labels: approved, cla: yes, lgtm, size/XS
