Repository kubeflow/manifests, pull requests merged in 2021-04, with the labels that each got.

#1786 Fix default dex, authservice config
  common/dex/base/config-map.yaml
  common/dex/base/deployment.yaml
  common/dex/base/kustomization.yaml
  common/dex/base/params.env
  common/dex/base/secret_params.env
  common/dex/overlays/istio/kustomization.yaml
  common/istio/oidc-authservice/base/params.env
Labels: approved, cla: yes, lgtm, size/L

#1787 namespace-related kustomizations
  common/kubeflow-namespace/base/kustomization.yaml
  common/kubeflow-namespace/base/namespace.yaml
  common/user-namespace/base/kustomization.yaml
  common/user-namespace/base/params.env
  common/user-namespace/base/params.yaml
  common/user-namespace/base/profile-instance.yaml
  contrib/default-install/base/params.env
Labels: approved, cla: yes, lgtm, size/S

#1788 istio: Change Istio IngressGateway Service to NodePort
  common/istio-1-9-0/cluster-local-gateway/base/gateway-authorizationpolicy.yaml
  common/istio-1-9-0/cluster-local-gateway/base/kustomization.yaml
  common/istio-1-9-0/istio-install/base/kustomization.yaml
  common/istio-1-9-0/istio-install/base/patches/service.yaml
  common/istio-1-9-0/profile-overlay.yaml
Labels: approved, cla: yes, lgtm, size/S

#1793 Updated the feast helm repo url
  contrib/feast/Makefile
  contrib/feast/feast/base/resources.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#1800 fix(doc): PyTorch Operator instruction in README
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#1804 README: Small fixes
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#1789 oidc-authservice: fix secret generator envs
  common/oidc-authservice/base/kustomization.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1795 Fix using newer kustomize for knative-eventing-install
  common/knative/knative-eventing-install/base/cluster-role.yaml
  common/knative/knative-eventing-install/base/deployment.yaml
Labels: approved, cla: yes, lgtm, size/L

#1802 fix feast-core names in the generated resource.yaml
  contrib/feast/feast/base/resources.yaml
  contrib/feast/values.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/S

#1815 Automated cherry pick of #1800: fix(doc): PyTorch Operator instruction in README Cherry pick of #1800 on v1.3-branch. #1800: fix(doc): PyTorch Operator instruction in README
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#1816 Automated cherry pick of #1804: README: Fix Notebooks commands Cherry pick of #1804 on v1.3-branch. #1804: README: Fix Notebooks commands
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#1817 Automated cherry pick of #1789: fix secret generator envs Cherry pick of #1789 on v1.3-branch. #1789: fix secret generator envs
  common/oidc-authservice/base/kustomization.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1818 Automated cherry pick of #1795: FIx using newer kustomize Cherry pick of #1795 on v1.3-branch. #1795: FIx using newer kustomize
  common/knative/knative-eventing-install/base/cluster-role.yaml
  common/knative/knative-eventing-install/base/deployment.yaml
Labels: approved, cla: yes, lgtm, size/L

#1790 Dex-overlays use reference instead of base
  common/dex/overlays/github/kustomization.yaml
  common/dex/overlays/istio/kustomization.yaml
  common/dex/overlays/ldap/kustomization.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1809 Dex: Fix user must be valid email address
  common/dex/base/config-map.yaml
  common/user-namespace/base/params.env
Labels: approved, cla: yes, lgtm, size/XS

#1821 Automated cherry pick of #1790: use resource instead of base reference Cherry pick of #1790 on v1.3-branch. #1790: use resource instead of base reference
  common/dex/overlays/github/kustomization.yaml
  common/dex/overlays/istio/kustomization.yaml
  common/dex/overlays/ldap/kustomization.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1822 Automated cherry pick of #1809: Fix user must be valig email address Cherry pick of #1809 on v1.3-branch. #1809: Fix user must be valig email address
  common/dex/base/config-map.yaml
  common/user-namespace/base/params.env
Labels: approved, cla: yes, lgtm, size/XS

#1827 knative: Remove use of yaml ref
  common/knative/knative-serving-install/base/deployment.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1828 Automated cherry pick of #1827: knative: Remove use of yaml ref Cherry pick of #1827 on v1.3-branch. #1827: knative: Remove use of yaml ref
  common/knative/knative-serving-install/base/deployment.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1830 knative: Remove use of last yaml ref
  common/knative/knative-serving-install/base/deployment.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1813 chore: remove argo manifests from contrib
  contrib/argo/base/cluster-role-binding.yaml
  contrib/argo/base/cluster-role.yaml
  contrib/argo/base/config-map.yaml
  contrib/argo/base/crd.yaml
  contrib/argo/base/deployment.yaml
  contrib/argo/base/kustomization.yaml
  contrib/argo/base/params.env
  contrib/argo/base/params.yaml
  contrib/argo/base/service-account.yaml
  contrib/argo/base/service.yaml
  contrib/argo/base_v3/kustomization.yaml
  contrib/argo/base_v3/params.yaml
  contrib/argo/overlays/application/application.yaml
  contrib/argo/overlays/application/kustomization.yaml
  contrib/argo/overlays/istio/kustomization.yaml
  contrib/argo/overlays/istio/params.yaml
  contrib/argo/overlays/istio/virtual-service.yaml
Labels: approved, cla: yes, lgtm, size/XL

#1826 Make note of knative-eventing being optional in README
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#1841 README: Expand section for connecting to a Kubeflow cluster
  README.md
Labels: approved, cla: yes, lgtm, size/S

#1846 Sync wg-notebooks apps to revision 1.3.0-rc.1
  apps/admission-webhook/upstream/base/kustomization.yaml
  apps/centraldashboard/upstream/base/kustomization.yaml
  apps/jupyter/jupyter-web-app/upstream/base/configs/logos-configmap.yaml
  apps/jupyter/jupyter-web-app/upstream/base/configs/spawner_ui_config.yaml
  apps/jupyter/jupyter-web-app/upstream/base/deployment.yaml
  apps/jupyter/jupyter-web-app/upstream/base/kustomization.yaml
  apps/jupyter/notebook-controller/upstream/base/kustomization.yaml
  apps/profiles/upstream/base/kustomization.yaml
  apps/profiles/upstream/crd/bases/kubeflow.org_profiles.yaml
  apps/profiles/upstream/overlays/kubeflow/kustomization.yaml
  apps/tensorboard/tensorboard-controller/upstream/base/kustomization.yaml
  apps/tensorboard/tensorboards-web-app/upstream/base/kustomization.yaml
  apps/volumes-web-app/upstream/base/kustomization.yaml
Labels: approved, cla: yes, lgtm, size/L

#1844 Remove load_restrictor kustomize flag and lint README markdown
  README.md
  docs/KustomizeBestPractices.md
  tests/test_util.go
Labels: approved, cla: yes, lgtm, size/M

#1847 README: Add component version matrix
  README.md
Labels: approved, cla: yes, lgtm, size/S

#1848 README: Add FAQ, elaborate kustomize version, update version matrix
  README.md
Labels: approved, cla: yes, lgtm, size/M

#1851 docs(kfp): introduce multi-user KFP dependencies and KFP standalone as alternative
  README.md
Labels: approved, cla: yes, lgtm, size/S

#1857 Update user references in README to use email
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#1860 Cherry-pick of #1857 on v1.3-branch: Update user references in README to use email
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#1854 Cherry pick #1851: docs(kfp): introduce multi-user KFP dependencies and KFP standalone as alternative
  README.md
Labels: approved, cla: yes, lgtm, size/S

#1811 KF 1.3 on Openshift
  distributions/kfdef/OWNERS
  distributions/kfdef/kfctl_openshift.master.kfptekton.yaml
  distributions/kfdef/kfctl_openshift_v1.3.0.yaml
  distributions/stacks/openshift/application/cert-manager/kustomization.yaml
  distributions/stacks/openshift/application/istio-1-9-0-Openshift/ingressgateway.route.yaml
  distributions/stacks/openshift/application/istio-1-9-0-Openshift/kustomization.yaml
  distributions/stacks/openshift/application/istio-1-9-0-Openshift/namespace.yaml
  distributions/stacks/openshift/application/istio-1-9-0-Openshift/network-attachment.yaml
  distributions/stacks/openshift/application/istio-1-9-0-Openshift/openshift_dump.yaml
  distributions/stacks/openshift/application/istio-1-9-0/ingressgateway.route.yaml
  distributions/stacks/openshift/application/istio-1-9-0/kustomization.yaml
  distributions/stacks/openshift/application/istio-1-9-0/network-attachment.yaml
  distributions/stacks/openshift/application/jupyter-web-app/addnoauthflags.yaml
  distributions/stacks/openshift/application/jupyter-web-app/kustomization.yaml
  distributions/stacks/openshift/application/katib/kustomization.yaml
  distributions/stacks/openshift/application/kfp-tekton/kustomization.yaml
  distributions/stacks/openshift/application/kfp-tekton/removesidemenu.yaml
  distributions/stacks/openshift/application/kfserving/kustomization.yaml
  distributions/stacks/openshift/application/knative/kustomization.yaml
  distributions/stacks/openshift/application/notebook-controller/kustomization.yaml
  distributions/stacks/openshift/application/openshift/openshift-scc/kubeflow-anyuid-scc.yaml
  distributions/stacks/openshift/application/openshift/openshift-scc/kubeflow-privileged-scc-istio.yaml
  distributions/stacks/openshift/application/openshift/openshift-scc/tekton-anyuid-scc.yaml
  distributions/stacks/openshift/application/pipeline-agnostic/kustomization.yaml
  distributions/stacks/openshift/application/pipeline-agnostic/metadata-gprc.yaml
  distributions/stacks/openshift/application/pipeline-agnostic/removesidemenu.yaml
  distributions/stacks/openshift/application/pipeline-agnostic/virtual-service.yaml
  distributions/stacks/openshift/application/pytorch-job/kustomization.yaml
  distributions/stacks/openshift/application/tensorboard/kustomization.yaml
  distributions/stacks/openshift/application/tf-job/kustomization.yaml
  distributions/stacks/openshift/application/volumes-web-app/addnoauthflags.yaml
  distributions/stacks/openshift/application/volumes-web-app/kustomization.yaml
  distributions/stacks/openshift/kustomization.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#1864 Cherry Pick of KF 1.3 on Openshift (#1811)
  distributions/kfdef/OWNERS
  distributions/kfdef/kfctl_openshift.master.kfptekton.yaml
  distributions/kfdef/kfctl_openshift_v1.3.0.yaml
  distributions/stacks/openshift/application/cert-manager/kustomization.yaml
  distributions/stacks/openshift/application/istio-1-9-0-Openshift/ingressgateway.route.yaml
  distributions/stacks/openshift/application/istio-1-9-0-Openshift/kustomization.yaml
  distributions/stacks/openshift/application/istio-1-9-0-Openshift/namespace.yaml
  distributions/stacks/openshift/application/istio-1-9-0-Openshift/network-attachment.yaml
  distributions/stacks/openshift/application/istio-1-9-0-Openshift/openshift_dump.yaml
  distributions/stacks/openshift/application/istio-1-9-0/ingressgateway.route.yaml
  distributions/stacks/openshift/application/istio-1-9-0/kustomization.yaml
  distributions/stacks/openshift/application/istio-1-9-0/network-attachment.yaml
  distributions/stacks/openshift/application/jupyter-web-app/addnoauthflags.yaml
  distributions/stacks/openshift/application/jupyter-web-app/kustomization.yaml
  distributions/stacks/openshift/application/katib/kustomization.yaml
  distributions/stacks/openshift/application/kfp-tekton/kustomization.yaml
  distributions/stacks/openshift/application/kfp-tekton/removesidemenu.yaml
  distributions/stacks/openshift/application/kfserving/kustomization.yaml
  distributions/stacks/openshift/application/knative/kustomization.yaml
  distributions/stacks/openshift/application/notebook-controller/kustomization.yaml
  distributions/stacks/openshift/application/openshift/openshift-scc/kubeflow-anyuid-scc.yaml
  distributions/stacks/openshift/application/openshift/openshift-scc/kubeflow-privileged-scc-istio.yaml
  distributions/stacks/openshift/application/openshift/openshift-scc/tekton-anyuid-scc.yaml
  distributions/stacks/openshift/application/pipeline-agnostic/kustomization.yaml
  distributions/stacks/openshift/application/pipeline-agnostic/metadata-gprc.yaml
  distributions/stacks/openshift/application/pipeline-agnostic/removesidemenu.yaml
  distributions/stacks/openshift/application/pipeline-agnostic/virtual-service.yaml
  distributions/stacks/openshift/application/pytorch-job/kustomization.yaml
  distributions/stacks/openshift/application/tensorboard/kustomization.yaml
  distributions/stacks/openshift/application/tf-job/kustomization.yaml
  distributions/stacks/openshift/application/volumes-web-app/addnoauthflags.yaml
  distributions/stacks/openshift/application/volumes-web-app/kustomization.yaml
  distributions/stacks/openshift/kustomization.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XXL

#1825 Add Kubeflow overlay to Feast
  contrib/feast/Makefile
  contrib/feast/README.md
  contrib/feast/feast/base/resources.yaml
  contrib/feast/feast/base/static.yaml
  contrib/feast/feast/overlays/kubeflow/kustomization.yaml
  contrib/feast/feast/overlays/kubeflow/patches/kafka.yaml
  contrib/feast/feast/overlays/kubeflow/patches/namespace.yaml
  contrib/feast/feast/overlays/kubeflow/patches/redis.yaml
  contrib/feast/feast/overlays/kubeflow/patches/zookeeper.yaml
  contrib/feast/values.yaml
Labels: approved, cla: yes, lgtm, size/L

#1836 Remove application cr for Feast
  contrib/feast/feast/overlays/application/application.yaml
  contrib/feast/feast/overlays/application/kustomization.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/M

#1866 Add tedhtchang to Feast OWNERS
  contrib/feast/OWNERS
Labels: approved, cla: yes, lgtm, size/XS
