Repository kubeflow/manifests, pull requests merged in 2022-03, with the labels that each got.

#2152 Update kubeflow/pipelines manifests from 1.8.1
  README.md
  apps/pipeline/upstream/base/cache-deployer/kustomization.yaml
  apps/pipeline/upstream/base/cache/kustomization.yaml
  apps/pipeline/upstream/base/installs/generic/pipeline-install-config.yaml
  apps/pipeline/upstream/base/metadata/base/kustomization.yaml
  apps/pipeline/upstream/base/pipeline/kustomization.yaml
  apps/pipeline/upstream/base/pipeline/metadata-writer/kustomization.yaml
  apps/pipeline/upstream/env/gcp/inverse-proxy/kustomization.yaml
Labels: lgtm, approved, size/S

#2157 Update the README
  README.md
Labels: lgtm, approved, size/XS

#2156 Sync kubeflow katib manifests v0.13.0
  README.md
  apps/katib/upstream/components/controller/katib-config.yaml
  apps/katib/upstream/components/controller/trial-templates.yaml
  apps/katib/upstream/installs/katib-cert-manager/kustomization.yaml
  apps/katib/upstream/installs/katib-external-db/kustomization.yaml
  apps/katib/upstream/installs/katib-openshift/kustomization.yaml
  apps/katib/upstream/installs/katib-standalone/kustomization.yaml
  apps/katib/upstream/installs/katib-with-kubeflow/kustomization.yaml
  hack/sync-katib-manifests.sh
Labels: lgtm, approved, size/M

#2158 kserve: Update the Models web app
  contrib/kserve/models-web-app/base/istio.yaml
  contrib/kserve/models-web-app/base/kustomization.yaml
  contrib/kserve/models-web-app/overlays/kubeflow/kustomization.yaml
  contrib/kserve/models-web-app/overlays/kubeflow/patches/web-app-vsvc.yaml
Labels: lgtm, approved, size/XS

#2153 kserve: Add distinct file for cluster-roles
  contrib/kserve/kserve/aggregated-roles.yaml
  contrib/kserve/kserve/kustomization.yaml
  example/kustomization.yaml
Labels: lgtm, approved, size/M

#2162 docs: Update KServe/KFServing section in README
  README.md
Labels: lgtm, approved, size/S

#2166 sync single-line install command with individual component install
  README.md
Labels: lgtm, approved, size/XS

#2167 Update kubeflow/kubeflow manifests from v1.5.0
  README.md
  apps/admission-webhook/upstream/base/kustomization.yaml
  apps/centraldashboard/upstream/base/kustomization.yaml
  apps/jupyter/jupyter-web-app/upstream/base/configs/spawner_ui_config.yaml
  apps/jupyter/jupyter-web-app/upstream/base/kustomization.yaml
  apps/jupyter/notebook-controller/upstream/base/kustomization.yaml
  apps/profiles/upstream/base/kustomization.yaml
  apps/profiles/upstream/overlays/kubeflow/kustomization.yaml
  apps/tensorboard/tensorboard-controller/upstream/base/kustomization.yaml
  apps/tensorboard/tensorboards-web-app/upstream/base/kustomization.yaml
  apps/volumes-web-app/upstream/base/kustomization.yaml
Labels: lgtm, approved, size/M
