Repository kubeflow/manifests, pull requests merged in 2022-09, with the labels that each got.

#2273 Update kubeflow/katib manifests from v0.14.0
  .github/workflows/katib_kind_test.yaml
  apps/katib/upstream/components/controller/katib-config.yaml
  apps/katib/upstream/components/controller/trial-templates.yaml
  apps/katib/upstream/installs/katib-cert-manager/kustomization.yaml
  apps/katib/upstream/installs/katib-external-db/kustomization.yaml
  apps/katib/upstream/installs/katib-openshift/kustomization.yaml
  apps/katib/upstream/installs/katib-standalone/kustomization.yaml
  apps/katib/upstream/installs/katib-with-kubeflow/kustomization.yaml
Labels: lgtm, approved, size/M

#2279 Update kubeflow/kubeflow manifests from v1.6.0-rc.3
  README.md
  apps/profiles/upstream/manager/manager.yaml
Labels: lgtm, approved, size/S

#2269 Extend Training Operator GH action to also apply a TFJob and assert it runs
  .github/workflows/train_operator_kind_test.yaml
  tests/gh-actions/kf-objects/tfjob.yaml
Labels: lgtm, approved, size/S

#2281 Update kubeflow/kubeflow manifests from v1.6.0
  README.md
  apps/admission-webhook/upstream/base/kustomization.yaml
  apps/centraldashboard/upstream/base/kustomization.yaml
  apps/jupyter/jupyter-web-app/upstream/base/configs/spawner_ui_config.yaml
  apps/jupyter/jupyter-web-app/upstream/base/kustomization.yaml
  apps/jupyter/notebook-controller/upstream/base/kustomization.yaml
  apps/profiles/upstream/base/kustomization.yaml
  apps/profiles/upstream/overlays/kubeflow/kustomization.yaml
  apps/tensorboard/tensorboard-controller/upstream/base/kustomization.yaml
  apps/tensorboard/tensorboards-web-app/upstream/base/kustomization.yaml
  apps/volumes-web-app/upstream/base/kustomization.yaml
Labels: lgtm, approved, size/M

#2291 Update kubeflow/kubeflow manifests from v1.6.1-rc.0
  README.md
  apps/admission-webhook/upstream/base/kustomization.yaml
  apps/centraldashboard/upstream/base/kustomization.yaml
  apps/jupyter/jupyter-web-app/upstream/base/configs/spawner_ui_config.yaml
  apps/jupyter/jupyter-web-app/upstream/base/kustomization.yaml
  apps/jupyter/notebook-controller/upstream/base/kustomization.yaml
  apps/profiles/upstream/base/kustomization.yaml
  apps/profiles/upstream/overlays/kubeflow/kustomization.yaml
  apps/tensorboard/tensorboard-controller/upstream/base/kustomization.yaml
  apps/tensorboard/tensorboards-web-app/upstream/base/kustomization.yaml
  apps/volumes-web-app/upstream/base/kustomization.yaml
Labels: lgtm, approved, size/M

#2288 istio: Include patches and resources in Istio install kustomization
  common/istio-1-14/istio-install/base/kustomization.yaml
Labels: lgtm, approved, size/XS
