Repository kubeflow/manifests, pull requests merged in 2022-07, with the labels that each got.

#2231 Update Knative 1.4
  common/knative/README.md
  common/knative/knative-eventing-post-install-jobs/base/eventing-post-install-jobs.yaml
  common/knative/knative-eventing/base/kustomization.yaml
  common/knative/knative-eventing/base/upstream/eventing-core.yaml
  common/knative/knative-eventing/base/upstream/in-memory-channel.yaml
  common/knative/knative-eventing/base/upstream/mt-channel-broker.yaml
  common/knative/knative-serving-post-install-jobs/base/serving-post-install-jobs.yaml
  common/knative/knative-serving/base/upstream/net-istio.yaml
  common/knative/knative-serving/base/upstream/serving-core.yaml
Labels: lgtm, approved, size/XXL

#2237 Move all tests under tests dir
  .github/workflows/centraldb_kind_test.yaml
  .github/workflows/jwa_kind_test.yaml
  .github/workflows/katib_kind_test.yaml
  .github/workflows/kserve_kind_test.yaml
  .github/workflows/nb_controller_kind_test.yaml
  .github/workflows/pipeline_kind_test.yaml
  .github/workflows/poddefaults_kind_test.yaml
  .github/workflows/profiles_kind_test.yaml
  .github/workflows/tb_controller_kind_test.yaml
  .github/workflows/train_operator_kind_test.yaml
  .github/workflows/twa_kind_test.yaml
  .github/workflows/vwa_kind_test.yaml
  tests/gh-actions/install_cert_manager.sh
  tests/gh-actions/install_istio.sh
  tests/gh-actions/install_kind.sh
  tests/gh-actions/install_kustomize.sh
  tests/gh-actions/kind-1-22.yaml
Labels: lgtm, approved, size/L

#2238 Change images of KinD configuration files to be compatible with v0.14.0
  .github/workflows/centraldb_kind_test.yaml
  .github/workflows/jwa_kind_test.yaml
  .github/workflows/katib_kind_test.yaml
  .github/workflows/kserve_kind_test.yaml
  .github/workflows/nb_controller_kind_test.yaml
  .github/workflows/pipeline_kind_test.yaml
  .github/workflows/poddefaults_kind_test.yaml
  .github/workflows/profiles_kind_test.yaml
  .github/workflows/tb_controller_kind_test.yaml
  .github/workflows/train_operator_kind_test.yaml
  .github/workflows/twa_kind_test.yaml
  .github/workflows/vwa_kind_test.yaml
  tests/gh-actions/kind-cluster-1-20.yaml
  tests/gh-actions/kind-cluster-1-21.yaml
  tests/gh-actions/kind-cluster-1-22.yaml
Labels: lgtm, approved, size/M

#2240 Sync kserve manifests for v0.8.0
  .github/workflows/kserve_kind_test.yaml
  README.md
  contrib/kserve/kserve/kserve-runtimes.yaml
  contrib/kserve/kserve/kserve.yaml
  contrib/kserve/kserve/kserve_kubeflow.yaml
  contrib/kserve/kserve/kustomization.yaml
  contrib/kserve/kserve/params.env
  contrib/kserve/models-web-app/base/deployment.yaml
  contrib/kserve/models-web-app/base/istio.yaml
  contrib/kserve/models-web-app/base/kustomization.yaml
  contrib/kserve/models-web-app/overlays/kubeflow/kustomization.yaml
  contrib/kserve/models-web-app/overlays/kubeflow/patches/web-app-vsvc.yaml
  hack/sync-kserve-manifests.sh
  tests/gh-actions/install_kserve.sh
Labels: lgtm, approved, size/XXL

#2243 Update Dex for K8s 1.22
  .github/workflows/dex_kind_test.yaml
  common/dex/base/crds.yaml
  common/dex/base/deployment.yaml
Labels: lgtm, approved, size/M

#2252 istio: Remove Istio 1.14 overlays
  common/istio-1-14/kubeflow-istio-resources/overlays/deploy/kustomization.yaml
  common/istio-1-14/kubeflow-istio-resources/overlays/ekf/kustomization.yaml
  common/istio-1-14/kubeflow-istio-resources/overlays/minikf/kustomization.yaml
Labels: lgtm, approved, size/S

#2251 knative: Updrade Knative to version 1.2
  common/knative/README.md
  common/knative/knative-eventing-post-install-jobs/base/eventing-post-install-jobs.yaml
  common/knative/knative-eventing/base/kustomization.yaml
  common/knative/knative-eventing/base/upstream/eventing-core.yaml
  common/knative/knative-eventing/base/upstream/in-memory-channel.yaml
  common/knative/knative-eventing/base/upstream/mt-channel-broker.yaml
  common/knative/knative-serving-post-install-jobs/base/serving-post-install-jobs.yaml
  common/knative/knative-serving/base/istio-authorization-policy.yaml
  common/knative/knative-serving/base/upstream/net-istio.yaml
  common/knative/knative-serving/base/upstream/serving-core.yaml
Labels: lgtm, approved, size/XXL

#2253 readme: Update component versions
  README.md
Labels: lgtm, approved, size/XS

#2254 Fix typo in the networkpolicies
  contrib/networkpolicies/kustomization.yaml
Labels: lgtm, approved, size/XS

#2164 Use KServe component in tests instead of KFServing
  tests/README.md
  tests/e2e/README.md
  tests/e2e/mnist.py
  tests/e2e/utils/isvc.py
  tests/e2e/utils/kfserving.py
  tests/e2e/utils/kserve.py
Labels: lgtm, approved, size/M

#2249 Extend Katib GH action to also create an experiment and assert it succeeds
  .github/workflows/katib_kind_test.yaml
  tests/gh-actions/kf-objects/katib_test.yaml
Labels: lgtm, approved, size/M

#2256 Sync kserve web app manifests v0.8.1
  README.md
  contrib/kserve/models-web-app/base/istio.yaml
  contrib/kserve/models-web-app/base/kustomization.yaml
  contrib/kserve/models-web-app/overlays/kubeflow/kustomization.yaml
  contrib/kserve/models-web-app/overlays/kubeflow/patches/web-app-vsvc.yaml
  hack/sync-kserve-kserve-manifests.sh
  hack/sync-kserve-web-app-manifests.sh
  tests/e2e/hack/cleanup_yamls.sh
  tests/e2e/settings.py
Labels: lgtm, approved, size/L

#2257 chore: Add James Liu and Ablai to manage metacontroller
  contrib/metacontroller/OWNERS
Labels: lgtm, approved, size/XS

#2255 Update metacontroller
  contrib/metacontroller/Kptfile
  contrib/metacontroller/README.md
  contrib/metacontroller/base/cluster-role-binding.yaml
  contrib/metacontroller/base/crd.yaml
  contrib/metacontroller/base/kustomization.yaml
  contrib/metacontroller/base/service-account.yaml
  contrib/metacontroller/base/stateful-set.yaml
Labels: lgtm, approved, size/XL

#2260 Update kubeflow/kubeflow manifests from v1.6.0-rc.1
  README.md
  apps/admission-webhook/upstream/base/kustomization.yaml
  apps/centraldashboard/upstream/base/kustomization.yaml
  apps/jupyter/jupyter-web-app/upstream/base/configs/spawner_ui_config.yaml
  apps/jupyter/jupyter-web-app/upstream/base/kustomization.yaml
  apps/jupyter/notebook-controller/upstream/base/kustomization.yaml
  apps/profiles/upstream/base/kustomization.yaml
  apps/profiles/upstream/crd/bases/kubeflow.org_profiles.yaml
  apps/profiles/upstream/crd/kustomization.yaml
  apps/profiles/upstream/crd/kustomizeconfig.yaml
  apps/profiles/upstream/crd/patches/cainjection_in_profiles.yaml
  apps/profiles/upstream/crd/patches/trivial_conversion_patch.yaml
  apps/profiles/upstream/crd/patches/webhook_in_profiles.yaml
  apps/profiles/upstream/default/kustomization.yaml
  apps/profiles/upstream/default/manager_auth_proxy_patch.yaml
  apps/profiles/upstream/manager/kustomization.yaml
  apps/profiles/upstream/manager/manager.yaml
  apps/profiles/upstream/overlays/kubeflow/kustomization.yaml
  apps/profiles/upstream/prometheus/kustomization.yaml
  apps/profiles/upstream/prometheus/monitor.yaml
  apps/profiles/upstream/rbac/auth_proxy_client_clusterrole.yaml
  apps/profiles/upstream/rbac/auth_proxy_role.yaml
  apps/profiles/upstream/rbac/auth_proxy_service.yaml
  apps/profiles/upstream/rbac/kustomization.yaml
  apps/profiles/upstream/rbac/leader_election_role_binding.yaml
  apps/profiles/upstream/rbac/profile_editor_role.yaml
  apps/profiles/upstream/rbac/profile_viewer_role.yaml
  apps/profiles/upstream/rbac/role.yaml
  apps/profiles/upstream/rbac/role_binding.yaml
  apps/profiles/upstream/rbac/service_account.yaml
  apps/profiles/upstream/samples/_v1_profile.yaml
  apps/profiles/upstream/samples/_v1beta1_profile.yaml
  apps/profiles/upstream/samples/profile_v1_aws_iam.yaml
  apps/profiles/upstream/samples/profile_v1_profile.yaml
  apps/profiles/upstream/samples/profile_v1beta1_profile.yaml
  apps/tensorboard/tensorboard-controller/upstream/base/kustomization.yaml
  apps/tensorboard/tensorboards-web-app/upstream/base/kustomization.yaml
  apps/volumes-web-app/upstream/base/kustomization.yaml
Labels: lgtm, approved, size/XL
