Repository kubeflow/manifests, pull requests merged in 2022-06, with the labels that each got.

#2223 Sync kubeflow/pipelines manifests 1.8.2
  README.md
  apps/pipeline/upstream/base/cache-deployer/kustomization.yaml
  apps/pipeline/upstream/base/cache/kustomization.yaml
  apps/pipeline/upstream/base/installs/generic/pipeline-install-config.yaml
  apps/pipeline/upstream/base/metadata/base/kustomization.yaml
  apps/pipeline/upstream/base/pipeline/kustomization.yaml
  apps/pipeline/upstream/base/pipeline/metadata-writer/kustomization.yaml
  apps/pipeline/upstream/env/cert-manager/base/cache-cert-issuer.yaml
  apps/pipeline/upstream/env/cert-manager/base/cache-cert.yaml
  apps/pipeline/upstream/env/cert-manager/base/cache-webhook-config.yaml
  apps/pipeline/upstream/env/cert-manager/base/kustomization.yaml
  apps/pipeline/upstream/env/cert-manager/base/params.yaml
  apps/pipeline/upstream/env/cert-manager/cluster-scoped-resources/kustomization.yaml
  apps/pipeline/upstream/env/cert-manager/dev/delete-cache-deployer.yaml
  apps/pipeline/upstream/env/cert-manager/dev/kustomization.yaml
  apps/pipeline/upstream/env/cert-manager/dev/namespace.yaml
  apps/pipeline/upstream/env/cert-manager/dev/params.yaml
  apps/pipeline/upstream/env/cert-manager/platform-agnostic-multi-user/delete-cache-deployer.yaml
  apps/pipeline/upstream/env/cert-manager/platform-agnostic-multi-user/kustomization.yaml
  apps/pipeline/upstream/env/gcp/inverse-proxy/kustomization.yaml
  example/kustomization.yaml
  hack/setup-kubeflow-light.sh
  tests/README.md
Labels: lgtm, approved, size/L

#2233 common: Add Istio 1.14.1 manifests
  common/istio-1-14/README.md
  common/istio-1-14/cluster-local-gateway/base/cluster-local-gateway.yaml
  common/istio-1-14/cluster-local-gateway/base/gateway-authorizationpolicy.yaml
  common/istio-1-14/cluster-local-gateway/base/gateway.yaml
  common/istio-1-14/cluster-local-gateway/base/kustomization.yaml
  common/istio-1-14/cluster-local-gateway/base/patches/remove-pdb.yaml
  common/istio-1-14/istio-crds/base/crd.yaml
  common/istio-1-14/istio-crds/base/kustomization.yaml
  common/istio-1-14/istio-install/base/deny_all_authorizationpolicy.yaml
  common/istio-1-14/istio-install/base/gateway.yaml
  common/istio-1-14/istio-install/base/gateway_authorizationpolicy.yaml
  common/istio-1-14/istio-install/base/install.yaml
  common/istio-1-14/istio-install/base/kustomization.yaml
  common/istio-1-14/istio-install/base/patches/istio-configmap-disable-tracing.yaml
  common/istio-1-14/istio-install/base/patches/remove-pdb.yaml
  common/istio-1-14/istio-install/base/patches/service.yaml
  common/istio-1-14/istio-install/base/x-forwarded-host.yaml
  common/istio-1-14/istio-namespace/base/kustomization.yaml
  common/istio-1-14/istio-namespace/base/namespace.yaml
  common/istio-1-14/kubeflow-istio-resources/base/cluster-roles.yaml
  common/istio-1-14/kubeflow-istio-resources/base/kf-istio-resources.yaml
  common/istio-1-14/kubeflow-istio-resources/base/kustomization.yaml
  common/istio-1-14/kubeflow-istio-resources/overlays/deploy/kustomization.yaml
  common/istio-1-14/kubeflow-istio-resources/overlays/ekf/kustomization.yaml
  common/istio-1-14/kubeflow-istio-resources/overlays/minikf/kustomization.yaml
  common/istio-1-14/profile-overlay.yaml
  common/istio-1-14/profile.yaml
  common/istio-1-14/split-istio-packages
  testing/gh-actions/install_istio.sh
Labels: lgtm, approved, size/XXL

#2232 Sync kubeflow training operator manifests v1.5.0 rc.0
  README.md
  apps/training-operator/upstream/base/crds/kubeflow.org_mpijobs.yaml
  apps/training-operator/upstream/base/crds/kubeflow.org_mxjobs.yaml
  apps/training-operator/upstream/base/crds/kubeflow.org_pytorchjobs.yaml
  apps/training-operator/upstream/base/crds/kubeflow.org_tfjobs.yaml
  apps/training-operator/upstream/base/crds/kubeflow.org_xgboostjobs.yaml
  apps/training-operator/upstream/base/deployment.yaml
  apps/training-operator/upstream/overlays/kubeflow/kubeflow-training-roles.yaml
  apps/training-operator/upstream/overlays/kubeflow/kustomization.yaml
  apps/training-operator/upstream/overlays/standalone/kustomization.yaml
  hack/sync-training-operator-manifests.sh
Labels: lgtm, approved, size/XXL

#2234 Update kubeflow/katib manifests from v0.14.0-rc.0
  README.md
  apps/katib/upstream/components/cert-generator/cert-generator.yaml
  apps/katib/upstream/components/cert-generator/kustomization.yaml
  apps/katib/upstream/components/cert-generator/rbac.yaml
  apps/katib/upstream/components/controller/controller.yaml
  apps/katib/upstream/components/controller/katib-config.yaml
  apps/katib/upstream/components/controller/kustomization.yaml
  apps/katib/upstream/components/controller/rbac.yaml
  apps/katib/upstream/components/controller/service.yaml
  apps/katib/upstream/components/controller/trial-templates.yaml
  apps/katib/upstream/components/crd/experiment.yaml
  apps/katib/upstream/components/crd/kustomization.yaml
  apps/katib/upstream/components/crd/suggestion.yaml
  apps/katib/upstream/components/crd/trial.yaml
  apps/katib/upstream/components/db-manager/db-manager.yaml
  apps/katib/upstream/components/db-manager/kustomization.yaml
  apps/katib/upstream/components/db-manager/service.yaml
  apps/katib/upstream/components/mysql/kustomization.yaml
  apps/katib/upstream/components/mysql/mysql.yaml
  apps/katib/upstream/components/mysql/pvc.yaml
  apps/katib/upstream/components/mysql/secret.yaml
  apps/katib/upstream/components/mysql/service.yaml
  apps/katib/upstream/components/namespace/kustomization.yaml
  apps/katib/upstream/components/namespace/namespace.yaml
  apps/katib/upstream/components/ui/kustomization.yaml
  apps/katib/upstream/components/ui/rbac.yaml
  apps/katib/upstream/components/ui/service.yaml
  apps/katib/upstream/components/ui/ui.yaml
  apps/katib/upstream/components/webhook/kustomization.yaml
  apps/katib/upstream/components/webhook/webhooks.yaml
  apps/katib/upstream/installs/katib-cert-manager/certificate.yaml
  apps/katib/upstream/installs/katib-cert-manager/kustomization.yaml
  apps/katib/upstream/installs/katib-cert-manager/params.yaml
  apps/katib/upstream/installs/katib-cert-manager/patches/katib-cert-injection.yaml
  apps/katib/upstream/installs/katib-external-db/kustomization.yaml
  apps/katib/upstream/installs/katib-external-db/patches/db-manager.yaml
  apps/katib/upstream/installs/katib-leader-election/kustomization.yaml
  apps/katib/upstream/installs/katib-leader-election/leader-election-rbac.yaml
  apps/katib/upstream/installs/katib-leader-election/patches/controller.yaml
  apps/katib/upstream/installs/katib-openshift/kustomization.yaml
  apps/katib/upstream/installs/katib-openshift/patches/service-serving-cert.yaml
  apps/katib/upstream/installs/katib-openshift/patches/webhook-inject-cabundle.yaml
  apps/katib/upstream/installs/katib-standalone/kustomization.yaml
  apps/katib/upstream/installs/katib-with-kubeflow/kubeflow-katib-roles.yaml
  apps/katib/upstream/installs/katib-with-kubeflow/kustomization.yaml
  apps/katib/upstream/installs/katib-with-kubeflow/params.yaml
  apps/katib/upstream/installs/katib-with-kubeflow/patches/remove-namespace.yaml
  apps/katib/upstream/installs/katib-with-kubeflow/ui-virtual-service.yaml
Labels: lgtm, approved, size/L

#2163 chore: Remove outdated Istio manifests
  common/istio-1-9/README.md
  common/istio-1-9/cluster-local-gateway/base/cluster-local-gateway.yaml
  common/istio-1-9/cluster-local-gateway/base/gateway-authorizationpolicy.yaml
  common/istio-1-9/cluster-local-gateway/base/gateway.yaml
  common/istio-1-9/cluster-local-gateway/base/kustomization.yaml
  common/istio-1-9/cluster-local-gateway/base/patches/remove-pdb.yaml
  common/istio-1-9/istio-crds/base/crd.yaml
  common/istio-1-9/istio-crds/base/kustomization.yaml
  common/istio-1-9/istio-install/base/deny_all_authorizationpolicy.yaml
  common/istio-1-9/istio-install/base/gateway.yaml
  common/istio-1-9/istio-install/base/gateway_authorizationpolicy.yaml
  common/istio-1-9/istio-install/base/install.yaml
  common/istio-1-9/istio-install/base/kustomization.yaml
  common/istio-1-9/istio-install/base/patches/istio-configmap-disable-tracing.yaml
  common/istio-1-9/istio-install/base/patches/remove-pdb.yaml
  common/istio-1-9/istio-install/base/patches/service.yaml
  common/istio-1-9/istio-install/base/x-forwarded-host.yaml
  common/istio-1-9/istio-namespace/base/kustomization.yaml
  common/istio-1-9/istio-namespace/base/namespace.yaml
  common/istio-1-9/kubeflow-istio-resources/base/cluster-roles.yaml
  common/istio-1-9/kubeflow-istio-resources/base/kf-istio-resources.yaml
  common/istio-1-9/kubeflow-istio-resources/base/kustomization.yaml
  common/istio-1-9/profile-overlay.yaml
  common/istio-1-9/profile.yaml
  common/istio-1-9/split-istio-packages
  common/istio/add-anonymous-user-filter-istio-1.6/envoy-filter.yaml
  common/istio/add-anonymous-user-filter-istio-1.6/kustomization.yaml
  prow_config.yaml
Labels: lgtm, approved, size/XXL, needs-ok-to-test

#2235 Update README with Istio 1.4.1
  README.md
Labels: lgtm, approved, size/XS
