Repository kubeflow/manifests, pull requests merged in 2022-02, with the labels that each got.

#2131 Sync kubeflow pipelines manifests 1.8.0 rc.2
  README.md
  apps/pipeline/upstream/base/cache-deployer/kustomization.yaml
  apps/pipeline/upstream/base/cache/kustomization.yaml
  apps/pipeline/upstream/base/installs/generic/pipeline-install-config.yaml
  apps/pipeline/upstream/base/metadata/base/kustomization.yaml
  apps/pipeline/upstream/base/pipeline/kustomization.yaml
  apps/pipeline/upstream/base/pipeline/metadata-writer/kustomization.yaml
  apps/pipeline/upstream/env/gcp/cloudsql-proxy/cloudsql-proxy-deployment.yaml
  apps/pipeline/upstream/env/gcp/inverse-proxy/kustomization.yaml
  hack/sync-pipelines-manifests.sh
Labels: lgtm, approved, size/M

#2134 Sync kubeflow kubeflow manifests v1.5.0 rc.1
  README.md
  apps/admission-webhook/upstream/base/kustomization.yaml
  apps/centraldashboard/upstream/base/kustomization.yaml
  apps/jupyter/jupyter-web-app/upstream/base/cluster-role.yaml
  apps/jupyter/jupyter-web-app/upstream/base/configs/spawner_ui_config.yaml
  apps/jupyter/jupyter-web-app/upstream/base/kustomization.yaml
  apps/jupyter/jupyter-web-app/upstream/base/role-binding.yaml
  apps/jupyter/jupyter-web-app/upstream/base/role.yaml
  apps/jupyter/notebook-controller/upstream/base/kustomization.yaml
  apps/profiles/upstream/base/kustomization.yaml
  apps/profiles/upstream/overlays/kubeflow/kustomization.yaml
  apps/tensorboard/tensorboard-controller/upstream/base/kustomization.yaml
  apps/tensorboard/tensorboards-web-app/upstream/base/kustomization.yaml
  apps/volumes-web-app/upstream/base/kustomization.yaml
  hack/sync-kubeflow-manifests.sh
Labels: lgtm, approved, size/L

#2135 Sync kserve/models-web-app manifests
  contrib/kserve/kserve/kserve.yaml
  contrib/kserve/kserve/kserve_kubeflow.yaml
  contrib/kserve/kserve/kustomization.yaml
  contrib/kserve/models-web-app/base/deployment.yaml
  contrib/kserve/models-web-app/base/istio.yaml
  contrib/kserve/models-web-app/base/kustomization.yaml
  contrib/kserve/models-web-app/base/rbac.yaml
  contrib/kserve/models-web-app/base/service.yaml
  contrib/kserve/models-web-app/overlays/kubeflow/kustomization.yaml
  contrib/kserve/models-web-app/overlays/kubeflow/params.yaml
  contrib/kserve/models-web-app/overlays/kubeflow/patches/web-app-sidecar.yaml
  contrib/kserve/models-web-app/overlays/kubeflow/patches/web-app-vsvc.yaml
  contrib/kserve/models-web-app/overlays/kubeflow/web-app-authorization-policy.yaml
  example/kustomization.yaml
Labels: lgtm, approved, size/L

#2141 Update kubeflow/kfp-tekton manifests from v1.1.1
  README.md
  apps/kfp-tekton/upstream/base/cache-deployer/kustomization.yaml
  apps/kfp-tekton/upstream/base/cache/kustomization.yaml
  apps/kfp-tekton/upstream/base/installs/multi-user/scheduled-workflow/cluster-role.yaml
  apps/kfp-tekton/upstream/base/pipeline/kustomization.yaml
  apps/kfp-tekton/upstream/base/pipeline/ml-pipeline-scheduledworkflow-role.yaml
  apps/kfp-tekton/upstream/third-party/application/cluster-scoped/application-crd.yaml
  apps/kfp-tekton/upstream/third-party/metacontroller/base/crd.yaml
  apps/kfp-tekton/upstream/third-party/tekton-custom-task/kustomization.yaml
  hack/sync-kfp-tekton-manifests.sh
Labels: lgtm, approved, size/XXL

#2139 Update manifests for Katib v0.13.0-rc.1 release
  README.md
  apps/katib/upstream/components/controller/katib-config.yaml
  apps/katib/upstream/components/controller/trial-templates.yaml
  apps/katib/upstream/installs/katib-cert-manager/kustomization.yaml
  apps/katib/upstream/installs/katib-external-db/kustomization.yaml
  apps/katib/upstream/installs/katib-openshift/kustomization.yaml
  apps/katib/upstream/installs/katib-standalone/kustomization.yaml
  apps/katib/upstream/installs/katib-with-kubeflow/kustomization.yaml
Labels: lgtm, approved, size/M

#2143 readme: Remove MPI reference and add ingress distributions link
  README.md
Labels: lgtm, approved, size/S, ok-to-test

#2144 Update kubeflow/pipelines manifests from 1.8.0
  README.md
  apps/pipeline/upstream/base/cache-deployer/kustomization.yaml
  apps/pipeline/upstream/base/cache/kustomization.yaml
  apps/pipeline/upstream/base/installs/generic/pipeline-install-config.yaml
  apps/pipeline/upstream/base/installs/multi-user/pipelines-profile-controller/composite-controller.yaml
  apps/pipeline/upstream/base/installs/multi-user/scheduled-workflow/cluster-role.yaml
  apps/pipeline/upstream/base/metadata/base/kustomization.yaml
  apps/pipeline/upstream/base/pipeline/kustomization.yaml
  apps/pipeline/upstream/base/pipeline/metadata-writer/kustomization.yaml
  apps/pipeline/upstream/base/pipeline/ml-pipeline-scheduledworkflow-role.yaml
  apps/pipeline/upstream/env/gcp/inverse-proxy/kustomization.yaml
Labels: lgtm, approved, size/M

#2140 hack: Don't error if namespace kubeflow exists
  hack/setup-kubeflow-light.sh
  hack/setup-kubeflow.sh
Labels: lgtm, approved, size/XS
