Repository kubeflow/manifests, pull requests merged in 2022-11, with the labels that each got.

#2298 Missing namespace in authorizationpolicy
  common/istio-1-14/istio-install/base/gateway_authorizationpolicy.yaml
Labels: lgtm, approved, size/XS

#2283 Removed deprecated image override for dex
  common/dex/base/kustomization.yaml
Labels: lgtm, approved, size/XS

#2304 Add tensorboards-web-app.yaml networkpolicy
  contrib/networkpolicies/kustomization.yaml
  contrib/networkpolicies/tensorboards-web-app.yaml
Labels: lgtm, approved, size/S

#2313 Add unmaintained notice to contrib components
  contrib/application/README.md
  contrib/basic-auth/README.md
  contrib/experimental/README.md
  contrib/gatekeeper/README.md
  contrib/modeldb/README.md
  contrib/spartakus/README.md
Labels: lgtm, approved, size/M

#2324 Use K8s 1.25 for the tests
  .github/workflows/centraldb_kind_test.yaml
  .github/workflows/dex_kind_test.yaml
  .github/workflows/jwa_kind_test.yaml
  .github/workflows/katib_kind_test.yaml
  .github/workflows/kserve_kind_test.yaml
  .github/workflows/nb_controller_kind_test.yaml
  .github/workflows/pipeline_kind_test.yaml
  .github/workflows/poddefaults_kind_test.yaml
  .github/workflows/profiles_kind_test.yaml
  .github/workflows/tb_controller_kind_test.yaml
  .github/workflows/train_operator_kind_test.yaml
  .github/workflows/twa_kind_test.yaml
  .github/workflows/vwa_kind_test.yaml
  tests/gh-actions/install_kind.sh
  tests/gh-actions/kind-cluster-1.25.yaml
Labels: lgtm, approved, size/M

#2331 Refactor kind configuration file for testing with K8s-v1.25
  .github/workflows/centraldb_kind_test.yaml
  .github/workflows/dex_kind_test.yaml
  .github/workflows/jwa_kind_test.yaml
  .github/workflows/katib_kind_test.yaml
  .github/workflows/kserve_kind_test.yaml
  .github/workflows/nb_controller_kind_test.yaml
  .github/workflows/pipeline_kind_test.yaml
  .github/workflows/poddefaults_kind_test.yaml
  .github/workflows/profiles_kind_test.yaml
  .github/workflows/tb_controller_kind_test.yaml
  .github/workflows/train_operator_kind_test.yaml
  .github/workflows/twa_kind_test.yaml
  .github/workflows/vwa_kind_test.yaml
  tests/gh-actions/kind-cluster-1-20.yaml
  tests/gh-actions/kind-cluster-1-21.yaml
  tests/gh-actions/kind-cluster-1-22.yaml
  tests/gh-actions/kind-cluster.yaml
Labels: lgtm, approved, size/L

#2330 common: Upgate cert-manager manifests to v1.10.1
  .github/workflows/pipeline_kind_test.yaml
  .github/workflows/poddefaults_kind_test.yaml
  README.md
  common/cert-manager/cert-manager/base/cert-manager.yaml
  common/cert-manager/cert-manager/base/kustomization.yaml
  common/cert-manager/cert-manager/base/patches/crd-preserve-unknown-fields.yaml
Labels: lgtm, approved, size/XXL

#2332 Update Istio version references to v1.16
  .github/workflows/jwa_kind_test.yaml
  .github/workflows/twa_kind_test.yaml
  README.md
  common/istio-1-16/README.md
  hack/setup-kubeflow-light.sh
  tests/gh-actions/install_knative.sh
Labels: lgtm, approved, size/M

#2321 Add unmaintained notice to contrib tektoncd
  contrib/tektoncd/README.md
Labels: lgtm, approved, size/XS
