Repository kubeflow/manifests, pull requests merged in 2022-12, with the labels that each got.

#2326 Updated and tested Seldon Core 1.15.0
  .github/workflows/seldon_kind_test.yaml
  contrib/seldon/Makefile
  contrib/seldon/README.md
  contrib/seldon/UPGRADE.md
  contrib/seldon/example.yaml
  contrib/seldon/kustomization.tpl
  contrib/seldon/seldon-core-operator/base/kubeflow-edit-seldon.yaml
  contrib/seldon/seldon-core-operator/base/kustomization.yaml
  contrib/seldon/seldon-core-operator/base/resources.yaml
  contrib/seldon/values.yaml
  example/kustomization.yaml
  tests/gh-actions/kind-cluster-1-24.yaml
Labels: lgtm, approved, size/XXL

#2341 Fix contrib/metacontroller folder
  .github/workflows/metacontroller_kind_test.yaml
  contrib/metacontroller/Makefile
  contrib/metacontroller/README.md
  contrib/metacontroller/UPDGRADE.md
  contrib/metacontroller/base/stateful-set.yaml
  contrib/metacontroller/test/catset-controller.yaml
Labels: lgtm, approved, size/L

#2316 Add unmaintained notice to contrib dex-auth
  contrib/dex-auth/README.md
Labels: lgtm, approved, size/XS

#2319 Add unmaintained notice to contrib flink
  contrib/flink/README.md
Labels: lgtm, approved, size/XS
