Repository kubeflow/manifests, pull requests merged in 2023-03, with the labels that each got.

#2404 Update kubeflow/pipelines manifests from 2.0.0-alpha.7
  README.md
  apps/pipeline/upstream/base/cache-deployer/kustomization.yaml
  apps/pipeline/upstream/base/cache/kustomization.yaml
  apps/pipeline/upstream/base/installs/generic/pipeline-install-config.yaml
  apps/pipeline/upstream/base/metadata/base/kustomization.yaml
  apps/pipeline/upstream/base/pipeline/kustomization.yaml
  apps/pipeline/upstream/base/pipeline/metadata-writer/kustomization.yaml
  apps/pipeline/upstream/env/gcp/inverse-proxy/kustomization.yaml
  apps/pipeline/upstream/third-party/mysql/base/mysql-deployment.yaml
Labels: lgtm, approved, size/S

#2405 Update kubeflow/pipelines manifests from 2.0.0-alpha.7 (#2404)
  README.md
  apps/pipeline/upstream/base/cache-deployer/kustomization.yaml
  apps/pipeline/upstream/base/cache/kustomization.yaml
  apps/pipeline/upstream/base/installs/generic/pipeline-install-config.yaml
  apps/pipeline/upstream/base/metadata/base/kustomization.yaml
  apps/pipeline/upstream/base/pipeline/kustomization.yaml
  apps/pipeline/upstream/base/pipeline/metadata-writer/kustomization.yaml
  apps/pipeline/upstream/env/gcp/inverse-proxy/kustomization.yaml
  apps/pipeline/upstream/third-party/mysql/base/mysql-deployment.yaml
Labels: lgtm, approved, size/S

#2399 Update instructions for Kustomize 5
  .github/workflows/manifests_unittests.yaml
  README.md
  example/kustomization.yaml
  tests/gh-actions/install_kustomize.sh
Labels: lgtm, approved, size/M

#2408 Update instructions for Kustomize 5 (#2399)
  .github/workflows/manifests_unittests.yaml
  README.md
  example/kustomization.yaml
  tests/gh-actions/install_kustomize.sh
Labels: lgtm, approved, size/M

#2426 Change from istio demo profile to default (#2410)
  common/istio-1-16/README.md
  common/istio-1-16/cluster-local-gateway/base/cluster-local-gateway.yaml
  common/istio-1-16/istio-install/base/install.yaml
  common/istio-1-16/profile.yaml
  common/istio-1-16/split-istio-packages
Labels: lgtm, approved, size/XXL

#2428 Update kubeflow/kubeflow manifests from v1.7.0
  README.md
  apps/admission-webhook/upstream/base/kustomization.yaml
  apps/centraldashboard/upstream/base/kustomization.yaml
  apps/jupyter/jupyter-web-app/upstream/base/configs/spawner_ui_config.yaml
  apps/jupyter/jupyter-web-app/upstream/base/kustomization.yaml
  apps/jupyter/notebook-controller/upstream/base/kustomization.yaml
  apps/profiles/upstream/base/kustomization.yaml
  apps/profiles/upstream/overlays/kubeflow/kustomization.yaml
  apps/tensorboard/tensorboard-controller/upstream/base/kustomization.yaml
  apps/tensorboard/tensorboards-web-app/upstream/base/kustomization.yaml
  apps/volumes-web-app/upstream/base/kustomization.yaml
Labels: size/M

#2429 Add a script that extracts all images used by main KF components
  docs/kf_images.txt
  hack/extract_manifests_images.sh
Labels: size/L
