Repository kubeflow/manifests, pull requests merged in 2023-01, with the labels that each got.

#2348 Update README.md
  README.md
Labels: lgtm, approved, size/XS

#2318 Add unmaintained notice to contrib feast
  contrib/feast/README.md
Labels: lgtm, approved, size/XS

#2320 Add unmaintained notice to contrib spark
  contrib/README.md
Labels: lgtm, approved, size/XS

#2335 common: Upgrade Knative Serving manifests to version 1.8.1
  README.md
  common/knative/README.md
  common/knative/knative-serving-post-install-jobs/base/serving-post-install-jobs.yaml
  common/knative/knative-serving/base/upstream/net-istio.yaml
  common/knative/knative-serving/base/upstream/serving-core.yaml
Labels: lgtm, approved

#2333 common: Upgrade Knative Eventing manifests to version 1.8.1
  .github/workflows/kserve_kind_test.yaml
  common/knative/README.md
  common/knative/knative-eventing-post-install-jobs/base/eventing-post-install.yaml
  common/knative/knative-eventing-post-install-jobs/base/kustomization.yaml
  common/knative/knative-eventing/base/kustomization.yaml
  common/knative/knative-eventing/base/upstream/eventing-core.yaml
  common/knative/knative-eventing/base/upstream/in-memory-channel.yaml
  common/knative/knative-eventing/base/upstream/mt-channel-broker.yaml
Labels: lgtm, approved, size/XL

#2364 centraldashboard: Rename Models to Endpoints
  apps/centraldashboard/upstream/base/configmap.yaml
  apps/centraldashboard/upstream/overlays/kserve/patches/configmap.yaml
Labels: lgtm, approved, size/XS
