Repository kubeflow/manifests, pull requests merged in 2023-08, with the labels that each got.

#2486 Upgrade Knative serving to 1.10.2 and eventing to 1.10.1
  README.md
  common/knative/README.md
  common/knative/knative-eventing-post-install-jobs/base/eventing-post-install.yaml
  common/knative/knative-eventing/base/upstream/eventing-core.yaml
  common/knative/knative-eventing/base/upstream/in-memory-channel.yaml
  common/knative/knative-eventing/base/upstream/mt-channel-broker.yaml
  common/knative/knative-serving-post-install-jobs/base/serving-post-install-jobs.yaml
  common/knative/knative-serving/base/upstream/net-istio.yaml
  common/knative/knative-serving/base/upstream/serving-core.yaml
  common/knative/knative-serving/overlays/gateways/patches/gateway-selectors.yaml
  tests/gh-actions/kind-cluster-1-24.yaml
  tests/gh-actions/kind-cluster-1-25.yaml
  tests/gh-actions/kind-cluster.yaml
Labels: lgtm, approved, size/XXL

#2501 [kubeflow 1.8] Update kubeflow/training-operator manifests from v1.7.0-rc.0
  README.md
  apps/training-operator/upstream/base/cluster-role.yaml
  apps/training-operator/upstream/base/crds/kubeflow.org_mpijobs.yaml
  apps/training-operator/upstream/base/crds/kubeflow.org_mxjobs.yaml
  apps/training-operator/upstream/base/crds/kubeflow.org_paddlejobs.yaml
  apps/training-operator/upstream/base/crds/kubeflow.org_pytorchjobs.yaml
  apps/training-operator/upstream/base/crds/kubeflow.org_tfjobs.yaml
  apps/training-operator/upstream/base/crds/kubeflow.org_xgboostjobs.yaml
  apps/training-operator/upstream/base/kustomization.yaml
  apps/training-operator/upstream/base/rbac/cluster-role-binding.yaml
  apps/training-operator/upstream/base/rbac/role.yaml
  apps/training-operator/upstream/base/rbac/service-account.yaml
  apps/training-operator/upstream/overlays/kubeflow/kustomization.yaml
  apps/training-operator/upstream/overlays/standalone/kustomization.yaml
Labels: lgtm, approved, size/XXL

#2508 Update Katib tests for MySQL issue with GH Runner
  .github/workflows/katib_kind_test.yaml
  .github/workflows/train_operator_kind_test.yaml
  tests/gh-actions/install_istio.sh
Labels: lgtm, approved, size/S

#2506 [kubeflow 1.8] Update kubeflow/katib manifests from v0.16.0-rc.1
  README.md
  apps/katib/upstream/components/cert-generator/cert-generator.yaml
  apps/katib/upstream/components/cert-generator/kustomization.yaml
  apps/katib/upstream/components/cert-generator/rbac.yaml
  apps/katib/upstream/components/controller/controller.yaml
  apps/katib/upstream/components/controller/katib-config.yaml
  apps/katib/upstream/components/controller/kustomization.yaml
  apps/katib/upstream/components/controller/rbac.yaml
  apps/katib/upstream/components/controller/trial-templates.yaml
  apps/katib/upstream/components/db-manager/db-manager.yaml
  apps/katib/upstream/components/webhook/webhooks.yaml
  apps/katib/upstream/installs/katib-cert-manager/katib-config.yaml
  apps/katib/upstream/installs/katib-cert-manager/kustomization.yaml
  apps/katib/upstream/installs/katib-external-db/katib-config.yaml
  apps/katib/upstream/installs/katib-external-db/kustomization.yaml
  apps/katib/upstream/installs/katib-leader-election/katib-config.yaml
  apps/katib/upstream/installs/katib-leader-election/kustomization.yaml
  apps/katib/upstream/installs/katib-leader-election/patches/controller.yaml
  apps/katib/upstream/installs/katib-openshift/katib-config.yaml
  apps/katib/upstream/installs/katib-openshift/kustomization.yaml
  apps/katib/upstream/installs/katib-standalone-postgres/katib-config.yaml
  apps/katib/upstream/installs/katib-standalone-postgres/kustomization.yaml
  apps/katib/upstream/installs/katib-standalone/katib-config.yaml
  apps/katib/upstream/installs/katib-standalone/kustomization.yaml
  apps/katib/upstream/installs/katib-with-kubeflow/kustomization.yaml
Labels: lgtm, approved, size/XL

#2504 [kubeflow 1.8] Update kserve manifests from v0.11.0
  README.md
  contrib/kserve/kserve/kserve-runtimes.yaml
  contrib/kserve/kserve/kserve.yaml
  contrib/kserve/kserve/kserve_kubeflow.yaml
Labels: lgtm, approved, size/XXL

#2409 Adding oauth2-proxy as optional alternative to oidc-authservice
  README.md
  common/dex/overlays/oauth2-proxy/config-map.yaml
  common/dex/overlays/oauth2-proxy/kustomization.yaml
  common/oidc-authservice/base/kustomization.yaml
  common/oidc-client/README.md
  common/oidc-client/oauth2-proxy/OWNERS
  common/oidc-client/oauth2-proxy/base/deployment.yaml
  common/oidc-client/oauth2-proxy/base/envoy-filter.yaml
  common/oidc-client/oauth2-proxy/base/kustomization.yaml
  common/oidc-client/oauth2-proxy/base/oauth2-proxy-alpha-config.yaml
  common/oidc-client/oauth2-proxy/base/oauth2-proxy-config.yaml
  common/oidc-client/oauth2-proxy/base/params.yaml
  common/oidc-client/oauth2-proxy/base/rbac.yaml
  common/oidc-client/oauth2-proxy/base/secret_params.env
  common/oidc-client/oauth2-proxy/base/service.yaml
  common/oidc-client/oidc-authservice/base/envoy-filter.yaml
  common/oidc-client/oidc-authservice/base/kustomization.yaml
  common/oidc-client/oidc-authservice/base/params.env
  common/oidc-client/oidc-authservice/base/params.yaml
  common/oidc-client/oidc-authservice/base/pvc.yaml
  common/oidc-client/oidc-authservice/base/rbac.yaml
  common/oidc-client/oidc-authservice/base/secret_params.env
  common/oidc-client/oidc-authservice/base/service.yaml
  common/oidc-client/oidc-authservice/base/statefulset.yaml
  common/oidc-client/oidc-authservice/overlays/ibm-storage-config/kustomization.yaml
  common/oidc-client/oidc-authservice/overlays/ibm-storage-config/statefulset.yaml
  example/kustomization.yaml
Labels: lgtm, priority/p1, approved, size/L, kind/feature
