Repository kubeflow/manifests, pull requests merged in 2023-07, with the labels that each got.

#2460 documentation(ray): fix typo
  contrib/ray/README.md
Labels: lgtm, approved, size/XS

#2465 Add bash script that extracts used images
  docs/image_lists/.gitkeep
  hack/extract_images.sh
Labels: lgtm, approved, size/L

#2489 Upgrade dex to 2.36.0
  common/dex/base/deployment.yaml
Labels: lgtm, approved, size/XS

#2490 Upgrade kustomize to 5.0.3
  README.md
  tests/gh-actions/install_kustomize.sh
Labels: lgtm, approved, size/S

#2488 Upgrade cert-manager to 1.12.2
  README.md
  common/cert-manager/README.md
  common/cert-manager/cert-manager/base/cert-manager.yaml
Labels: lgtm, approved, size/XXL

#2493 Add juliusvonkohout as root reviewer
  OWNERS
Labels: lgtm, approved, size/XS
