Repository kubeflow/manifests, pull requests merged in 2023-12, with the labels that each got.

#2581 Remove copyright headers
  common/istio-1-17/istio-namespace/base/kustomization.yaml
Labels: lgtm, approved, size/XS

#2583 Fixes user-namespace for kustomize 5
  common/user-namespace/base/kustomization.yaml
Labels: lgtm, approved, size/M

#2229 Use hashFromEnv in dex component for static user passwords
  common/dex/base/config-map.yaml
  common/dex/base/deployment.yaml
  common/dex/base/dex-passwords.yaml
Labels: lgtm, approved, size/S
