Repository kubeflow/manifests, pull requests merged in 2023-11, with the labels that each got.

#2563 Update kubeflow/kfp-tekton manifests from v2.0.3
  README.md
  apps/kfp-tekton/upstream/OWNERS
  apps/kfp-tekton/upstream/base/cache-deployer/kustomization.yaml
  apps/kfp-tekton/upstream/base/cache/kustomization.yaml
  apps/kfp-tekton/upstream/base/installs/generic/pipeline-install-config.yaml
  apps/kfp-tekton/upstream/base/installs/multi-user/persistence-agent/cluster-role.yaml
  apps/kfp-tekton/upstream/base/metadata/base/kustomization.yaml
  apps/kfp-tekton/upstream/base/pipeline/kustomization.yaml
  apps/kfp-tekton/upstream/base/pipeline/metadata-writer/kustomization.yaml
  apps/kfp-tekton/upstream/base/pipeline/ml-pipeline-persistenceagent-role.yaml
  apps/kfp-tekton/upstream/cluster-scoped-resources-tekton/kustomization.yaml
  apps/kfp-tekton/upstream/cluster-scoped-resources-tekton/namespace.yaml
  apps/kfp-tekton/upstream/cluster-scoped-resources-tekton/params.yaml
  apps/kfp-tekton/upstream/env/gcp/inverse-proxy/kustomization.yaml
  apps/kfp-tekton/upstream/env/plain/kustomization.yaml
  apps/kfp-tekton/upstream/env/platform-agnostic-tekton-multi-user/kustomization.yaml
  apps/kfp-tekton/upstream/env/platform-agnostic-tekton-multi-user/tekton-config.yaml
  apps/kfp-tekton/upstream/env/platform-agnostic-tekton/kustomization.yaml
  apps/kfp-tekton/upstream/env/platform-openshift-pipelines/kustomization.yaml
  apps/kfp-tekton/upstream/third-party/tekton-custom-task/kustomization.yaml
  apps/kfp-tekton/upstream/third-party/tekton/upstream/manifests/base/tektoncd-install/tekton-config.yaml
  apps/kfp-tekton/upstream/third-party/tekton/upstream/manifests/base/tektoncd-install/tekton-release.yaml
Labels: lgtm, approved, size/L

#2565 Update kubeflow/katib manifests from v0.16.0
  README.md
  apps/katib/upstream/components/controller/trial-templates.yaml
  apps/katib/upstream/installs/katib-cert-manager/katib-config.yaml
  apps/katib/upstream/installs/katib-cert-manager/kustomization.yaml
  apps/katib/upstream/installs/katib-external-db/katib-config.yaml
  apps/katib/upstream/installs/katib-external-db/kustomization.yaml
  apps/katib/upstream/installs/katib-leader-election/katib-config.yaml
  apps/katib/upstream/installs/katib-openshift/katib-config.yaml
  apps/katib/upstream/installs/katib-openshift/kustomization.yaml
  apps/katib/upstream/installs/katib-standalone-postgres/katib-config.yaml
  apps/katib/upstream/installs/katib-standalone-postgres/kustomization.yaml
  apps/katib/upstream/installs/katib-standalone/katib-config.yaml
  apps/katib/upstream/installs/katib-standalone/kustomization.yaml
  apps/katib/upstream/installs/katib-with-kubeflow/kustomization.yaml
Labels: lgtm, approved, size/L

#2566 Update kubeflow/training-operator manifests from v1.7.0
  README.md
Labels: lgtm, approved, size/XS

#2567 Update kubeflow/kubeflow manifests from v1.8.0
  README.md
  apps/admission-webhook/upstream/base/kustomization.yaml
  apps/centraldashboard/upstream/base/kustomization.yaml
  apps/jupyter/jupyter-web-app/upstream/base/configs/spawner_ui_config.yaml
  apps/jupyter/jupyter-web-app/upstream/base/kustomization.yaml
  apps/jupyter/notebook-controller/upstream/base/kustomization.yaml
  apps/profiles/upstream/base/kustomization.yaml
  apps/profiles/upstream/overlays/kubeflow/kustomization.yaml
  apps/pvcviewer-controller/upstream/base/kustomization.yaml
  apps/tensorboard/tensorboard-controller/upstream/base/kustomization.yaml
  apps/tensorboard/tensorboards-web-app/upstream/base/kustomization.yaml
  apps/volumes-web-app/upstream/base/kustomization.yaml
Labels: lgtm, approved, size/M

#2574 Create pvcviewer-webhook
  contrib/networkpolicies/kustomization.yaml
  contrib/networkpolicies/pvcviewer-webhook.yaml
Labels: lgtm, approved, size/S

#2579 Remove annajung from OWNERS file
  OWNERS
Labels: lgtm, approved, size/XS
