Repository kubeflow/manifests, pull requests merged in 2023-10, with the labels that each got.

#2545 Update kubeflow/kfp-tekton manifests from 2.0.1
  README.md
  apps/kfp-tekton/upstream/base/cache-deployer/kustomization.yaml
  apps/kfp-tekton/upstream/base/cache/kustomization.yaml
  apps/kfp-tekton/upstream/base/installs/generic/pipeline-install-config.yaml
  apps/kfp-tekton/upstream/base/installs/multi-user/persistence-agent/cluster-role.yaml
  apps/kfp-tekton/upstream/base/metadata/base/kustomization.yaml
  apps/kfp-tekton/upstream/base/pipeline/kustomization.yaml
  apps/kfp-tekton/upstream/base/pipeline/metadata-writer/kustomization.yaml
  apps/kfp-tekton/upstream/base/pipeline/ml-pipeline-persistenceagent-deployment.yaml
  apps/kfp-tekton/upstream/base/pipeline/ml-pipeline-persistenceagent-role.yaml
  apps/kfp-tekton/upstream/env/gcp/inverse-proxy/kustomization.yaml
  apps/kfp-tekton/upstream/env/plain-multi-user/kustomization.yaml
  apps/kfp-tekton/upstream/env/plain/kustomization.yaml
  apps/kfp-tekton/upstream/env/platform-agnostic-tekton-multi-user/kustomization.yaml
  apps/kfp-tekton/upstream/env/platform-agnostic-tekton/kustomization.yaml
  apps/kfp-tekton/upstream/env/platform-openshift-pipelines/kustomization.yaml
  apps/kfp-tekton/upstream/third-party/tekton-custom-task/kustomization.yaml
  apps/kfp-tekton/upstream/v1/base/installs/multi-user/istio-authorization-config.yaml
Labels: lgtm, approved, size/L

#2552 Update kserve manifests from v0.11.1
  README.md
  contrib/kserve/kserve/kserve-runtimes.yaml
  contrib/kserve/kserve/kserve.yaml
  contrib/kserve/kserve/kserve_kubeflow.yaml
  tests/gh-actions/install_kserve.sh
Labels: lgtm, approved, size/XXL

#2557 Update kubeflow/kubeflow manifests from v1.8.0-rc.3
  README.md
  apps/admission-webhook/upstream/base/kustomization.yaml
  apps/centraldashboard/upstream/base/kustomization.yaml
  apps/jupyter/jupyter-web-app/upstream/base/configs/spawner_ui_config.yaml
  apps/jupyter/jupyter-web-app/upstream/base/kustomization.yaml
  apps/jupyter/notebook-controller/upstream/base/kustomization.yaml
  apps/profiles/upstream/base/kustomization.yaml
  apps/profiles/upstream/manager/kustomization.yaml
  apps/profiles/upstream/overlays/kubeflow/kustomization.yaml
  apps/pvcviewer-controller/upstream/base/kustomization.yaml
  apps/tensorboard/tensorboard-controller/upstream/base/kustomization.yaml
  apps/tensorboard/tensorboards-web-app/upstream/base/kustomization.yaml
  apps/volumes-web-app/upstream/base/kustomization.yaml
Labels: lgtm, approved, size/M

#2559 Update kubeflow/kubeflow manifests from v1.8.0-rc.5
  README.md
  apps/admission-webhook/upstream/base/kustomization.yaml
  apps/centraldashboard/upstream/base/kustomization.yaml
  apps/jupyter/jupyter-web-app/upstream/base/configs/spawner_ui_config.yaml
  apps/jupyter/jupyter-web-app/upstream/base/kustomization.yaml
  apps/jupyter/notebook-controller/upstream/base/kustomization.yaml
  apps/profiles/upstream/base/kustomization.yaml
  apps/profiles/upstream/overlays/kubeflow/kustomization.yaml
  apps/pvcviewer-controller/upstream/base/kustomization.yaml
  apps/tensorboard/tensorboard-controller/upstream/base/kustomization.yaml
  apps/tensorboard/tensorboards-web-app/upstream/base/kustomization.yaml
  apps/volumes-web-app/upstream/base/kustomization.yaml
Labels: lgtm, approved, size/M

#2562 Update kubeflow/pipelines manifests from 2.0.3
  README.md
  apps/pipeline/upstream/base/cache-deployer/kustomization.yaml
  apps/pipeline/upstream/base/cache/kustomization.yaml
  apps/pipeline/upstream/base/installs/generic/pipeline-install-config.yaml
  apps/pipeline/upstream/base/installs/generic/postgres/pipeline-install-config.yaml
  apps/pipeline/upstream/base/metadata/base/kustomization.yaml
  apps/pipeline/upstream/base/pipeline/kustomization.yaml
  apps/pipeline/upstream/base/pipeline/metadata-writer/kustomization.yaml
  apps/pipeline/upstream/env/gcp/inverse-proxy/kustomization.yaml
Labels: lgtm, approved, size/S
