Repository kubeflow/manifests, pull requests merged in 2023-02, with the labels that each got.

#2350 Feat: Add BentoML Yatai Stack contrib
  .github/workflows/bentoml_kind_test.yaml
  contrib/bentoml/Makefile
  contrib/bentoml/OWNERS
  contrib/bentoml/README.md
  contrib/bentoml/UPGRADE.md
  contrib/bentoml/bentoml-yatai-stack/bases/yatai-deployment/kustomization.yaml
  contrib/bentoml/bentoml-yatai-stack/bases/yatai-deployment/resources.yaml
  contrib/bentoml/bentoml-yatai-stack/bases/yatai-image-builder/kustomization.yaml
  contrib/bentoml/bentoml-yatai-stack/bases/yatai-image-builder/resources.yaml
  contrib/bentoml/bentoml-yatai-stack/default/kustomization.yaml
  contrib/bentoml/example.yaml
  contrib/bentoml/sources/kustomization-template.yaml
  contrib/bentoml/sources/yatai-deployment-values.yaml
  contrib/bentoml/sources/yatai-image-builder-values.yaml
  contrib/bentoml/test.sh
Labels: lgtm, approved, size/XXL

#2371 Add Julius von Kohout as reviewer for /contrib
  contrib/OWNERS
Labels: lgtm, approved, size/XS

#2362 Update the README for kustomize 4.5.7 support
  README.md
Labels: lgtm, approved, size/M

#2377 Update kubeflow/kubeflow manifests from v1.7.0-rc.0
  README.md
Labels: lgtm, approved, size/S

#2376 Update kubeflow/pipelines manifests from 2.0.0-alpha.6
  README.md
  apps/pipeline/upstream/base/cache-deployer/kustomization.yaml
  apps/pipeline/upstream/base/cache/cache-deployment.yaml
  apps/pipeline/upstream/base/cache/kustomization.yaml
  apps/pipeline/upstream/base/installs/generic/pipeline-install-config.yaml
  apps/pipeline/upstream/base/installs/multi-user/persistence-agent/cluster-role.yaml
  apps/pipeline/upstream/base/installs/multi-user/persistence-agent/deployment-patch.yaml
  apps/pipeline/upstream/base/installs/multi-user/persistence-agent/kustomization.yaml
  apps/pipeline/upstream/base/installs/multi-user/persistence-agent/params.env
  apps/pipeline/upstream/base/installs/multi-user/view-edit-cluster-roles.yaml
  apps/pipeline/upstream/base/metadata/base/kustomization.yaml
  apps/pipeline/upstream/base/pipeline/kustomization.yaml
  apps/pipeline/upstream/base/pipeline/metadata-writer/kustomization.yaml
  apps/pipeline/upstream/base/pipeline/ml-pipeline-persistenceagent-deployment.yaml
  apps/pipeline/upstream/base/pipeline/ml-pipeline-persistenceagent-role.yaml
  apps/pipeline/upstream/env/gcp/inverse-proxy/kustomization.yaml
  apps/pipeline/upstream/third-party/mysql/base/mysql-deployment.yaml
Labels: lgtm, approved, size/L

#2150 feat: upgrade oidc-authservice
  common/dex/base/config-map.yaml
  common/oidc-authservice/base/kustomization.yaml
  common/oidc-authservice/base/params.env
  common/oidc-authservice/base/rbac.yaml
  common/oidc-authservice/base/statefulset.yaml
Labels: lgtm, approved, size/M, ok-to-test

#2355 Kserve documents and Tests - issue# 2311
  .github/workflows/kserve_kind_test.yaml
  contrib/kserve/Makefile
  contrib/kserve/README.md
  contrib/kserve/UPGRADE.md
  contrib/kserve/assets/kserve.png
  contrib/kserve/kserve/kserve-runtimes.yaml
  contrib/kserve/kserve/kserve.yaml
  contrib/kserve/kserve/kserve_kubeflow.yaml
  contrib/kserve/kserve/kustomization.yaml
  contrib/kserve/tests/data/iris_input.json
  contrib/kserve/tests/requirements.txt
  contrib/kserve/tests/test_sklearn.py
  contrib/kserve/tests/utils.py
  tests/gh-actions/install_knative.sh
  tests/gh-actions/install_kserve.sh
Labels: lgtm, approved, size/XXL

#2380 Uncomment profiles manifests in example dir
  example/kustomization.yaml
Labels: lgtm, approved, size/XS

#2381 Sync MWA manifests from 0.10.0 and show KF version in README
  README.md
  contrib/kserve/models-web-app/base/deployment.yaml
  contrib/kserve/models-web-app/base/kustomization.yaml
  tests/gh-actions/install_knative.sh
  tests/gh-actions/install_kserve.sh
  tests/gh-actions/install_pipelines.sh
Labels: approved, size/S

#2382 README: Update the version for v1.7.0-rc.0
  README.md
Labels: lgtm, approved, size/XS

#2386 Update oidc image tag
  common/oidc-authservice/base/kustomization.yaml
Labels: lgtm, approved, size/XS

#2378 Add Anna Jung as reviewer
  OWNERS
  contrib/OWNERS
Labels: lgtm, approved, size/XS

#2390 Sync kubeflow training operator manifests v1.6.0 rc.1
  README.md
  apps/training-operator/upstream/overlays/kubeflow/kustomization.yaml
  apps/training-operator/upstream/overlays/standalone/kustomization.yaml
  common/oidc-authservice/base/kustomization.yaml
Labels: lgtm, approved, size/XS

#2395 Update kubeflow/kubeflow manifests from v1.7.0-rc.1
  README.md
  apps/admission-webhook/upstream/base/kustomization.yaml
  apps/centraldashboard/upstream/base/deployment.yaml
  apps/centraldashboard/upstream/base/kustomization.yaml
  apps/jupyter/jupyter-web-app/upstream/base/configs/spawner_ui_config.yaml
  apps/jupyter/jupyter-web-app/upstream/base/kustomization.yaml
  apps/jupyter/notebook-controller/upstream/base/kustomization.yaml
  apps/profiles/upstream/base/kustomization.yaml
  apps/profiles/upstream/overlays/kubeflow/kustomization.yaml
  apps/tensorboard/tensorboard-controller/upstream/base/kustomization.yaml
  apps/tensorboard/tensorboards-web-app/upstream/base/cluster-role.yaml
  apps/tensorboard/tensorboards-web-app/upstream/base/kustomization.yaml
  apps/volumes-web-app/upstream/base/kustomization.yaml
Labels: size/M

#2396 Document the release process for Manifest
  README.md
Labels: lgtm, approved, size/XS
