Repository kubeflow/manifests, pull requests merged in 2024-11, with the labels that each got.

#2906 update Readme file to fix Kustomize links and Tekton pipelines information
  README.md
Labels: lgtm, approved, size/XS

#2908 Synchronize kserve manifests v0.14.0
  README.md
  contrib/kserve/kserve/kserve-cluster-resources.yaml
  contrib/kserve/kserve/kserve.yaml
  contrib/kserve/kserve/kserve_kubeflow.yaml
  hack/synchronize-kserve-kserve-manifests.sh
  tests/gh-actions/install_kserve.sh
Labels: lgtm, approved, size/XXL

#2913 feat: synchronize kubeflow model registry manifests to v0.2.10
  README.md
  apps/model-registry/upstream/base/kustomization.yaml
  apps/model-registry/upstream/options/csi/clusterstoragecontainer.yaml
  apps/model-registry/upstream/options/csi/kustomization.yaml
  hack/synchronize-model-registry-manifests.sh
Labels: lgtm, approved, size/M

#2911 Dex,oauth2-proxy and k8s token documentation
  README.md
Labels: lgtm, approved, size/M

#2916 Update Dex and oauth2-proxy to 2.41.1 and 7.7.1
  common/dex/base/deployment.yaml
  common/oauth2-proxy/base/kustomization.yaml
Labels: lgtm, approved, size/S

#2918 Use $HOME .docker/config.json
  README.md
Labels: lgtm, approved, size/XS

#2917 Synchronize knative manifests v1.16.0
  .github/workflows/linting_bash_python_yaml_files.yaml
  .github/workflows/pipeline_run_from_notebook.yaml
  README.md
  common/knative/README.md
  common/knative/knative-eventing-post-install-jobs/base/eventing-post-install.yaml
  common/knative/knative-eventing/base/upstream/eventing-core.yaml
  common/knative/knative-eventing/base/upstream/in-memory-channel.yaml
  common/knative/knative-eventing/base/upstream/mt-channel-broker.yaml
  common/knative/knative-serving-post-install-jobs/base/serving-post-install-jobs.yaml
  common/knative/knative-serving/base/upstream/net-istio.yaml
  common/knative/knative-serving/base/upstream/serving-core.yaml
  hack/synchronize-knative-manifests.sh
  tests/gh-actions/install_knative-cni.sh
  tests/gh-actions/install_knative.sh
Labels: lgtm, approved, size/XXL

#2919 update cert-manager to 1.16.1 and move the upstream manifests to the upstream folder
  common/cert-manager/README.md
  common/cert-manager/base/kustomization.yaml
  common/cert-manager/base/upstream/cert-manager.yaml
  common/cert-manager/cert-manager/base/cert-manager.yaml
  contrib/kserve/README.md
  example/kustomization.yaml
  tests/gh-actions/install_cert_manager.sh
Labels: lgtm, approved, size/XXL

#2921 update cert-manager and kubernetes version information according to o…
  README.md
Labels: lgtm, approved, size/XS

#2920 remove seldon, bentoml and metacontroller (included in upstream KFP)
  .github/workflows/bentoml_test.yaml
  .github/workflows/metacontroller_test.yaml
  .github/workflows/seldon_test.yaml
  common/networkpolicies/base/kustomization.yaml
  common/networkpolicies/base/seldon.yaml
  contrib/bentoml/Makefile
  contrib/bentoml/OWNERS
  contrib/bentoml/README.md
  contrib/bentoml/UPGRADE.md
  contrib/bentoml/bentoml-yatai-stack/bases/yatai-deployment/kustomization.yaml
  contrib/bentoml/bentoml-yatai-stack/bases/yatai-deployment/resources.yaml
  contrib/bentoml/bentoml-yatai-stack/bases/yatai-image-builder/kustomization.yaml
  contrib/bentoml/bentoml-yatai-stack/bases/yatai-image-builder/resources.yaml
  contrib/bentoml/bentoml-yatai-stack/default/kustomization.yaml
  contrib/bentoml/deployment_from_bento.yaml
  contrib/bentoml/deployment_from_bentorequest.yaml
  contrib/bentoml/sources/kustomization-template.yaml
  contrib/bentoml/sources/yatai-deployment-values.yaml
  contrib/bentoml/sources/yatai-image-builder-values.yaml
  contrib/bentoml/test.sh
  contrib/metacontroller/Kptfile
  contrib/metacontroller/Makefile
  contrib/metacontroller/OWNERS
  contrib/metacontroller/README.md
  contrib/metacontroller/UPDGRADE.md
  contrib/metacontroller/base/cluster-role-binding.yaml
  contrib/metacontroller/base/crd.yaml
  contrib/metacontroller/base/kustomization.yaml
  contrib/metacontroller/base/service-account.yaml
  contrib/metacontroller/base/stateful-set.yaml
  contrib/metacontroller/test/catset-controller.yaml
  contrib/seldon/Makefile
  contrib/seldon/OWNERS
  contrib/seldon/README.md
  contrib/seldon/UPGRADE.md
  contrib/seldon/example.yaml
  contrib/seldon/kustomization.tpl
  contrib/seldon/kustomizeconfig.tpl
  contrib/seldon/seldon-core-operator/base/kustomization.yaml
  contrib/seldon/seldon-core-operator/base/kustomizeconfig.yaml
  contrib/seldon/seldon-core-operator/base/resources.yaml
  contrib/seldon/seldon-core-operator/overlays/application/application.yaml
  contrib/seldon/seldon-core-operator/overlays/application/kustomization.yaml
  contrib/seldon/values.yaml
  example/kustomization.yaml
  hack/synchronize-seldon-manifests.sh
Labels: lgtm, approved, size/XXL

#2924 fix cert-manager wrong path in standalone installation section
  README.md
Labels: lgtm, approved, size/XS
