Repository kubeflow/manifests, pull requests merged in 2024-02, with the labels that each got.

#2618 Update PR template to install kustomize 5.0.1
  .github/pull_request_template.md
Labels: size/XS

#2621 Change to kustomize 5.0.3
  .github/pull_request_template.md
Labels: lgtm, approved, size/XS

#2625 Create update.sh for KFP
  apps/pipeline/update.sh
Labels: approved, size/S

#2629 Update OWNERS
  OWNERS
Labels: lgtm, approved, size/XS

#2630 Update OWNERS with emeritus_approvers
  OWNERS
Labels: approved, size/XS

#2544 oauth2-proxy with istio mesh config and m2m bearer tokens
  .github/workflows/kserve_m2m_kind_test.yaml
  .github/workflows/nb_controller_m2m_kind_test.yaml
  .github/workflows/pipeline_kind_test.yaml
  .github/workflows/pipeline_m2m_kind_test.yaml
  apps/centraldashboard/upstream/overlays/oauth2-proxy/kustomization.yaml
  common/istio-1-17/istio-install/overlays/oauth2-proxy/kustomization.yaml
  common/istio-cni-1-17/istio-install/overlays/oauth2-proxy/kustomization.yaml
  common/oidc-client/README.md
  common/oidc-client/kubeflow_auth_diagram.svg
  common/oidc-client/oauth2-proxy/OWNERS
  common/oidc-client/oauth2-proxy/README.md
  common/oidc-client/oauth2-proxy/base/README.md
  common/oidc-client/oauth2-proxy/base/deployment.yaml
  common/oidc-client/oauth2-proxy/base/envoy-filter.yaml
  common/oidc-client/oauth2-proxy/base/kustomization.yaml
  common/oidc-client/oauth2-proxy/base/namespace.yaml
  common/oidc-client/oauth2-proxy/base/oauth2-proxy-alpha-config.yaml
  common/oidc-client/oauth2-proxy/base/oauth2-proxy-config.yaml
  common/oidc-client/oauth2-proxy/base/rbac.tokenreviews.yaml
  common/oidc-client/oauth2-proxy/base/secret_params.env
  common/oidc-client/oauth2-proxy/base/service.yaml
  common/oidc-client/oauth2-proxy/base/serviceaccount.yaml
  common/oidc-client/oauth2-proxy/components/README.md
  common/oidc-client/oauth2-proxy/components/allow-unauthenticated-issuer-discovery/README.md
  common/oidc-client/oauth2-proxy/components/allow-unauthenticated-issuer-discovery/clusterrolebinding.unauthenticated-oidc-viewer.yaml
  common/oidc-client/oauth2-proxy/components/allow-unauthenticated-issuer-discovery/kustomization.yaml
  common/oidc-client/oauth2-proxy/components/central-dashboard/kustomization.yaml
  common/oidc-client/oauth2-proxy/components/central-dashboard/patches/deployment.logout-url.yaml
  common/oidc-client/oauth2-proxy/components/configure-self-signed-kubernetes-oidc-issuer/README.md
  common/oidc-client/oauth2-proxy/components/configure-self-signed-kubernetes-oidc-issuer/job.configure-kubernetes-oidc-issuer-jwks-in-requestauthentication.yaml
  common/oidc-client/oauth2-proxy/components/configure-self-signed-kubernetes-oidc-issuer/kustomization.yaml
  common/oidc-client/oauth2-proxy/components/configure-self-signed-kubernetes-oidc-issuer/rbac.yaml
  common/oidc-client/oauth2-proxy/components/configure-self-signed-kubernetes-oidc-issuer/script.sh
  common/oidc-client/oauth2-proxy/components/istio-external-auth/README.md
  common/oidc-client/oauth2-proxy/components/istio-external-auth/authorizationpolicy.istio-ingressgateway-oauth2-proxy-cloudflare.yaml
  common/oidc-client/oauth2-proxy/components/istio-external-auth/authorizationpolicy.istio-ingressgateway-oauth2-proxy.yaml
  common/oidc-client/oauth2-proxy/components/istio-external-auth/kustomization.yaml
  common/oidc-client/oauth2-proxy/components/istio-external-auth/patches/cm.enable-oauth2-proxy.yaml
  common/oidc-client/oauth2-proxy/components/istio-external-auth/patches/deployment.jwt-refresh-interval.yaml
  common/oidc-client/oauth2-proxy/components/istio-external-auth/requestauthentication.dex-jwt.yaml
  common/oidc-client/oauth2-proxy/components/istio-m2m/README.md
  common/oidc-client/oauth2-proxy/components/istio-m2m/kustomization.yaml
  common/oidc-client/oauth2-proxy/components/istio-m2m/params.yaml
  common/oidc-client/oauth2-proxy/components/istio-m2m/requestauthentication.yaml
  common/oidc-client/oauth2-proxy/overlays/m2m-self-signed/kustomization.yaml
  common/oidc-client/oauth2-proxy/overlays/m2m/README.md
  common/oidc-client/oauth2-proxy/overlays/m2m/component-overwrite-m2m-token-issuer/kustomization.yaml
  common/oidc-client/oauth2-proxy/overlays/m2m/kustomization.yaml
  contrib/kserve/tests/utils.py
  example/kustomization.yaml
  tests/gh-actions/install_cert_manager.sh
  tests/gh-actions/install_istio_with_ext_auth.sh
  tests/gh-actions/install_kind.sh
  tests/gh-actions/install_kubectl.sh
  tests/gh-actions/install_multi_tenancy.sh
  tests/gh-actions/install_pipelines.sh
Labels: lgtm, approved, size/XXL

#2627 Update kserve manifests from v0.11.2
  README.md
  contrib/kserve/kserve/kserve-runtimes.yaml
  contrib/kserve/kserve/kserve.yaml
  contrib/kserve/kserve/kserve_kubeflow.yaml
  tests/gh-actions/install_cert_manager.sh
Labels: size/M
