Repository kubeflow/manifests, pull requests merged in 2024-08, with the labels that each got.

#2827 disable the broken dex login test for now or fix it
  .github/workflows/dex_test.yaml
Labels: lgtm, approved, size/XS

#2825 fix issue with linting of YAML files
  .github/workflows/linting_bash_python_yaml_files.yaml
Labels: lgtm, approved, size/XS

#2834 Expose Ray and Seldon to example kustomization.yaml file
  example/kustomization.yaml
Labels: lgtm, approved, size/S

#2830 fix dex-login-test
  .github/workflows/dex_test.yaml
  tests/gh-actions/deploy-dex-login-environment/kustomization.yaml
  tests/gh-actions/test_dex_login.py
Labels: lgtm, approved, size/M

#2819 Added tests to tests/gh-actions to enable baseline and restricted PSS
  .github/workflows/pss_test.yaml
  contrib/security/PSS/static/baseline/kustomization.yaml
  contrib/security/PSS/static/baseline/patches/auth-labels.yaml
  contrib/security/PSS/static/baseline/patches/istio-system-labels.yaml
  contrib/security/PSS/static/restricted/kustomization.yaml
  contrib/security/PSS/static/restricted/patches/auth-labels.yaml
  contrib/security/PSS/static/restricted/patches/istio-system-labels.yaml
  tests/gh-actions/enable_baseline_PSS.sh
  tests/gh-actions/enable_restricted_PSS.sh
Labels: lgtm, approved, size/M

#2838 Added changes to pss_test.yaml workflow
  .github/workflows/pss_test.yaml
Labels: lgtm, approved, size/S

#2836 Added securityContext profiles for deployments failing PSS restricted level
  contrib/security/PSS/patches/cache-server.yaml
  contrib/security/PSS/patches/cluster-local-gateway.yaml
  contrib/security/PSS/patches/dex.yaml
  contrib/security/PSS/patches/kfam.yaml
  contrib/security/PSS/patches/kubeflow-pipelines-profile-controller.yaml
  contrib/security/PSS/patches/manager.yaml
  contrib/security/PSS/patches/metadata-envoy-deployment.yaml
  contrib/security/PSS/patches/metadata-grpc-deployment.yaml
  contrib/security/PSS/patches/metadata-writer.yaml
  contrib/security/PSS/patches/minio.yaml
  contrib/security/PSS/patches/ml-pipeline-persistenceagent.yaml
  contrib/security/PSS/patches/ml-pipeline-scheduledworkflow.yaml
  contrib/security/PSS/patches/ml-pipeline-ui.yaml
  contrib/security/PSS/patches/ml-pipeline-viewer-crd.yaml
  contrib/security/PSS/patches/ml-pipeline-visualizationserver.yaml
  contrib/security/PSS/patches/ml-pipeline.yaml
  contrib/security/PSS/patches/mysql.yaml
  contrib/security/PSS/patches/oauth2-proxy.yaml
Labels: lgtm, approved, size/L

#2845 Refactor .github/workflows/pss_test.yaml
  .github/workflows/pss_test.yaml
Labels: lgtm, approved, size/S

#2805 Consolidate Kubeflow tests
  .github/workflows/admission_webhook_test.yaml
  .github/workflows/bentoml_test.yaml
  .github/workflows/centraldashboard_test.yaml
  .github/workflows/dex_test.yaml
  .github/workflows/jupyter_web_application_test.yaml
  .github/workflows/katib_test.yaml
  .github/workflows/kserve_cni_test.yaml
  .github/workflows/kserve_m2m_test.yaml
  .github/workflows/kserve_test.yaml
  .github/workflows/metacontroller_test.yaml
  .github/workflows/model_registry_test.yaml
  .github/workflows/notebook_controller_m2m_test.yaml
  .github/workflows/notebook_controller_test.yaml
  .github/workflows/pipeline_run_from_notebook.yaml
  .github/workflows/pipeline_test.yaml
  .github/workflows/profiles_test.yaml
  .github/workflows/pss_test.yaml
  .github/workflows/ray_test.yaml
  .github/workflows/seldon_test.yaml
  .github/workflows/tensorboard_controller_test.yaml
  .github/workflows/tensorboards_web_application_test.yaml
  .github/workflows/training_operator_test.yaml
  .github/workflows/volumes_web_application_test.yaml
  tests/gh-actions/install_KinD_create_KinD_cluster_install_kustomize.sh
  tests/gh-actions/install_istio_with_ext_auth.sh
  tests/gh-actions/install_kind.sh
  tests/gh-actions/kind-cluster.yaml
Labels: lgtm, approved, size/L

#2854 re-enable more parts of the dex test
  .github/workflows/dex_test.yaml
  tests/gh-actions/deploy-dex-login-environment/kustomization.yaml
  tests/gh-actions/test_dex_login.py
Labels: lgtm, approved, size/M

#2853 Synchronize kubeflow kubeflow manifests v1.9.0
  apps/jupyter/jupyter-web-app/upstream/base/configs/spawner_ui_config.yaml
  hack/synchronize-kubeflow-manifests.sh
Labels: lgtm, approved, size/M

#2859 add kubeflow installation guide to issue report
  .github/ISSUE_TEMPLATE/issue-report.yml
Labels: lgtm, approved, size/L

#2860 Adjust the Trivy scanning workflow to upload artifacts
  .github/workflows/trivy.yaml
Labels: lgtm, approved, size/S

#2863 update PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: lgtm, approved, size/XS

#2856 cve: fix Double-count in "All Images" for CVE image scan report
  hack/trivy_scan.py
Labels: lgtm, approved, size/M

#2862 fix: wrong diagram path for kubeflow auth .
  common/oauth2-proxy/README.md
Labels: lgtm, approved, size/XS

#2861 Consolidate Kubeflow Manifest tests
  .github/workflows/katib_test.yaml
  .github/workflows/pipeline_run_from_notebook.yaml
Labels: lgtm, approved, size/XS
