Repository kubeflow/manifests, pull requests merged in 2024-06, with the labels that each got.

#2724 add Model Registry networkpolicy
  common/networkpolicies/base/kustomization.yaml
  common/networkpolicies/base/model-registry.yaml
Labels: lgtm, approved, size/M

#2737 Sync kubeflow model registry manifests v0.2.1-alpha
  .github/workflows/model_registry_test.yaml
  README.md
  apps/model-registry/upstream/OWNERS
  apps/model-registry/upstream/base/model-registry-deployment.yaml
  apps/model-registry/upstream/base/model-registry-service.yaml
  apps/model-registry/upstream/options/istio/virtual-service.yaml
  apps/model-registry/upstream/overlays/db/kustomization.yaml
  apps/model-registry/upstream/overlays/db/patches/model-registry-deployment.yaml
  apps/model-registry/upstream/overlays/postgres/kustomization.yaml
  apps/model-registry/upstream/overlays/postgres/patches/model-registry-deployment.yaml
  hack/sync-model-registry-manifests.sh
Labels: lgtm, approved, size/M

#2740 Update kubeflow/kubeflow manifests from v1.9.0-rc.0
  README.md
  apps/admission-webhook/upstream/base/kustomization.yaml
  apps/centraldashboard/upstream/base/configmap.yaml
  apps/centraldashboard/upstream/base/deployment.yaml
  apps/centraldashboard/upstream/base/kustomization.yaml
  apps/centraldashboard/upstream/overlays/istio/kustomization.yaml
  apps/centraldashboard/upstream/overlays/istio/virtual-service.yaml
  apps/centraldashboard/upstream/overlays/kserve/kustomization.yaml
  apps/centraldashboard/upstream/overlays/kserve/patches/configmap.yaml
  apps/jupyter/jupyter-web-app/upstream/base/configs/spawner_ui_config.yaml
  apps/jupyter/jupyter-web-app/upstream/base/kustomization.yaml
  apps/jupyter/notebook-controller/upstream/base/kustomization.yaml
  apps/jupyter/notebook-controller/upstream/crd/kustomization.yaml
  apps/jupyter/notebook-controller/upstream/crd/patches/validation_patches.yaml
  apps/jupyter/notebook-controller/upstream/manager/manager.yaml
  apps/jupyter/notebook-controller/upstream/manager/params.env
  apps/profiles/upstream/base/kustomization.yaml
  apps/profiles/upstream/manager/kustomization.yaml
  apps/profiles/upstream/overlays/kubeflow/kustomization.yaml
  apps/profiles/upstream/samples/_v1beta1_profile.yaml
  apps/pvcviewer-controller/upstream/base/kustomization.yaml
  apps/pvcviewer-controller/upstream/crd/bases/kubeflow.org_pvcviewers.yaml
  apps/tensorboard/tensorboard-controller/upstream/base/kustomization.yaml
  apps/tensorboard/tensorboards-web-app/upstream/base/kustomization.yaml
  apps/tensorboard/tensorboards-web-app/upstream/base/params.env
  apps/volumes-web-app/upstream/base/deployment.yaml
  apps/volumes-web-app/upstream/base/kustomization.yaml
  apps/volumes-web-app/upstream/base/viewer-spec.yaml
Labels: lgtm, approved, size/XXL

#2749 Fix requested changes in pr issue templates
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/issue-report.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: lgtm, approved, size/S

#2751 Sync kserve manifests 0.13.0
  README.md
  contrib/kserve/kserve/kserve-cluster-resources.yaml
  contrib/kserve/kserve/kserve.yaml
  contrib/kserve/kserve/kserve_kubeflow.yaml
  hack/sync-kserve-kserve-manifests.sh
Labels: lgtm, approved, size/XXL

#2752 fix: update /models/ to /kserve-endpoints/ for kserve models web app …
  apps/centraldashboard/upstream/overlays/kserve/patches/configmap.yaml
Labels: lgtm, approved, size/XS

#2677 Remove 2 extra spaces
  example/kustomization.yaml
Labels: lgtm, approved, size/XS

#2667 Make the kubeflow-m2m-oidc-configurator a CronJob
  .github/workflows/kserve_m2m_test.yaml
  .github/workflows/notebook_controller_m2m_test.yaml
  .github/workflows/pipeline_test.yaml
  common/oidc-client/oauth2-proxy/components/configure-self-signed-kubernetes-oidc-issuer/cronjob.kubeflow-m2m-oidc-configurator.yaml
  common/oidc-client/oauth2-proxy/components/configure-self-signed-kubernetes-oidc-issuer/job.configure-kubernetes-oidc-issuer-jwks-in-requestauthentication.yaml
  common/oidc-client/oauth2-proxy/components/configure-self-signed-kubernetes-oidc-issuer/kustomization.yaml
  common/oidc-client/oauth2-proxy/components/configure-self-signed-kubernetes-oidc-issuer/rbac.yaml
  common/oidc-client/oauth2-proxy/components/configure-self-signed-kubernetes-oidc-issuer/script.sh
  tests/gh-actions/install_istio_with_ext_auth.sh
  tests/gh-actions/install_knative-cni.sh
  tests/gh-actions/install_knative.sh
  tests/gh-actions/install_kserve.sh
  tests/gh-actions/install_pipelines.sh
  tests/gh-actions/wait_for_kubeflow_m2m_oidc_configurator.sh
Labels: lgtm, approved, size/L

#2756 Update kubeflow/katib manifests from v0.17.0-rc.1
  apps/katib/upstream/components/controller/trial-templates.yaml
  apps/katib/upstream/installs/katib-cert-manager/katib-config.yaml
  apps/katib/upstream/installs/katib-cert-manager/kustomization.yaml
  apps/katib/upstream/installs/katib-external-db/katib-config.yaml
  apps/katib/upstream/installs/katib-external-db/kustomization.yaml
  apps/katib/upstream/installs/katib-leader-election/katib-config.yaml
  apps/katib/upstream/installs/katib-openshift/katib-config.yaml
  apps/katib/upstream/installs/katib-openshift/kustomization.yaml
  apps/katib/upstream/installs/katib-standalone-postgres/katib-config.yaml
  apps/katib/upstream/installs/katib-standalone-postgres/kustomization.yaml
  apps/katib/upstream/installs/katib-standalone/katib-config.yaml
  apps/katib/upstream/installs/katib-standalone/kustomization.yaml
  apps/katib/upstream/installs/katib-with-kubeflow/kustomization.yaml
Labels: lgtm, approved, size/L

#2759 set CNCF slack channel in README file
  README.md
Labels: lgtm, approved, size/XS

#2758 Convert trivy_scan.sh into python
  .github/workflows/trivy.yaml
  hack/table_generate_for_security_results.py
  hack/trivy_scan.py
  hack/trivy_scan.sh
  image_lists/.gitkeep
Labels: lgtm, approved, size/XL

#2757 Added PSS to contrib/baseline and contrib/restricted as kustomize components
  contrib/security/PSS/static/baseline/kustomization.yaml
  contrib/security/PSS/static/baseline/patches/istio-labels.yaml
  contrib/security/PSS/static/baseline/patches/kubeflow-labels.yaml
  contrib/security/PSS/static/restricted/kustomization.yaml
  contrib/security/PSS/static/restricted/patches/istio-labels.yaml
  contrib/security/PSS/static/restricted/patches/kubeflow-labels.yaml
  example/kustomization.yaml
Labels: lgtm, approved, size/M

#2753 authorize requests to ml-pipeline endpoint if contains any trusted principals
  .github/workflows/pipeline_run_from_notebook.yaml
  apps/pipeline/upstream/base/installs/multi-user/istio-authorization-config.yaml
  tests/gh-actions/kf-objects/notebook.test.kubeflow-user-example.com.yaml
  tests/gh-actions/kf-objects/poddefaults.access-ml-pipeline.kubeflow-user-example-com.yaml
  tests/gh-actions/run_and_wait_kubeflow_pipeline.py
Labels: lgtm, approved, size/L

#2769 Synchronize kubeflow training operator manifests from v1.8.0-rc.1
  README.md
  apps/training-operator/upstream/base/crds/kubeflow.org_mpijobs.yaml
  apps/training-operator/upstream/base/crds/kubeflow.org_mxjobs.yaml
  apps/training-operator/upstream/base/crds/kubeflow.org_paddlejobs.yaml
  apps/training-operator/upstream/base/crds/kubeflow.org_pytorchjobs.yaml
  apps/training-operator/upstream/base/crds/kubeflow.org_tfjobs.yaml
  apps/training-operator/upstream/base/crds/kubeflow.org_xgboostjobs.yaml
  apps/training-operator/upstream/overlays/kubeflow/kustomization.yaml
  apps/training-operator/upstream/overlays/standalone/kustomization.yaml
  hack/sync-training-operator-manifests.sh
Labels: lgtm, approved, size/S

#2764 Improve the trivy CVE scanning output
  .github/workflows/trivy.yaml
  hack/trivy_scan.py
  image_lists/.gitkeep
Labels: lgtm, approved, size/M

#2748 proposal: Uniform way for handling JWTs
  proposals/20240606-jwt-handling.md
Labels: lgtm, approved, size/L
