Repository kubeflow/manifests, pull requests merged in 2024-05, with the labels that each got.

#2668 Reorder oauth2-proxy manifests so that namespace is first
  common/oidc-client/oauth2-proxy/base/kustomization.yaml
Labels: lgtm, approved, size/XS

#2670 Split istio-external-auth into two components
  common/istio-1-17/istio-install/overlays/oauth2-proxy/kustomization.yaml
  common/istio-cni-1-17/istio-install/overlays/oauth2-proxy/kustomization.yaml
  common/oidc-client/oauth2-proxy/components/istio-external-auth-patches/README.md
  common/oidc-client/oauth2-proxy/components/istio-external-auth-patches/kustomization.yaml
  common/oidc-client/oauth2-proxy/components/istio-external-auth-patches/patches/cm.enable-oauth2-proxy.yaml
  common/oidc-client/oauth2-proxy/components/istio-external-auth-patches/patches/deployment.jwt-refresh-interval.yaml
  common/oidc-client/oauth2-proxy/components/istio-external-auth/kustomization.yaml
  common/oidc-client/oauth2-proxy/overlays/m2m-self-signed/kustomization.yaml
  common/oidc-client/oauth2-proxy/overlays/m2m/kustomization.yaml
Labels: lgtm, approved, size/S

#2699 Update kubeflow/training-operator manifests from v1.8.0-rc.0
  README.md
  apps/training-operator/upstream/base/crds/kubeflow.org_mpijobs.yaml
  apps/training-operator/upstream/base/crds/kubeflow.org_mxjobs.yaml
  apps/training-operator/upstream/base/crds/kubeflow.org_paddlejobs.yaml
  apps/training-operator/upstream/base/crds/kubeflow.org_pytorchjobs.yaml
  apps/training-operator/upstream/base/crds/kubeflow.org_tfjobs.yaml
  apps/training-operator/upstream/base/crds/kubeflow.org_xgboostjobs.yaml
  apps/training-operator/upstream/base/deployment.yaml
  apps/training-operator/upstream/base/kustomization.yaml
  apps/training-operator/upstream/base/rbac/role.yaml
  apps/training-operator/upstream/base/service.yaml
  apps/training-operator/upstream/base/webhook/kustomization.yaml
  apps/training-operator/upstream/base/webhook/kustomizeconfig.yaml
  apps/training-operator/upstream/base/webhook/manifests.yaml
  apps/training-operator/upstream/base/webhook/patch.yaml
  apps/training-operator/upstream/overlays/kubeflow/kubeflow-training-roles.yaml
  apps/training-operator/upstream/overlays/kubeflow/kustomization.yaml
  apps/training-operator/upstream/overlays/standalone/kustomization.yaml
  hack/sync-training-operator-manifests.sh
Labels: lgtm, approved, size/XXL

#2697 Update kubeflow/model-registry manifests from v0.2.0-alpha
  .github/workflows/model_registry_test.yaml
  README.md
  apps/model-registry/upstream/OWNERS
  apps/model-registry/upstream/README.md
  apps/model-registry/upstream/base/kustomization.yaml
  apps/model-registry/upstream/base/model-registry-configmap.yaml
  apps/model-registry/upstream/base/model-registry-deployment.yaml
  apps/model-registry/upstream/base/model-registry-sa.yaml
  apps/model-registry/upstream/base/model-registry-service.yaml
  apps/model-registry/upstream/options/istio/destination-rule.yaml
  apps/model-registry/upstream/options/istio/istio-authorization-policy.yaml
  apps/model-registry/upstream/options/istio/kustomization.yaml
  apps/model-registry/upstream/options/istio/virtual-service.yaml
  apps/model-registry/upstream/overlays/db/kustomization.yaml
  apps/model-registry/upstream/overlays/db/model-registry-db-deployment.yaml
  apps/model-registry/upstream/overlays/db/model-registry-db-pvc.yaml
  apps/model-registry/upstream/overlays/db/model-registry-db-service.yaml
  apps/model-registry/upstream/overlays/db/params.env
  apps/model-registry/upstream/overlays/db/patches/model-registry-deployment.yaml
  apps/model-registry/upstream/overlays/db/secrets.env
  apps/model-registry/upstream/overlays/postgres/kustomization.yaml
  apps/model-registry/upstream/overlays/postgres/model-registry-db-deployment.yaml
  apps/model-registry/upstream/overlays/postgres/model-registry-db-pvc.yaml
  apps/model-registry/upstream/overlays/postgres/model-registry-db-service.yaml
  apps/model-registry/upstream/overlays/postgres/params.env
  apps/model-registry/upstream/overlays/postgres/patches/model-registry-deployment.yaml
  apps/model-registry/upstream/overlays/postgres/secrets.env
  hack/sync-model-registry-manifests.sh
Labels: lgtm, approved, size/XL

#2702 Fix kserve upgrade script and update kserve diagram
  contrib/kserve/Makefile
  contrib/kserve/README.md
  contrib/kserve/UPGRADE.md
  contrib/kserve/assets/kserve_new.png
  contrib/kserve/tests/requirements.txt
Labels: lgtm, approved, size/M

#2703 update cert-manager to 1.14.5
  common/cert-manager/README.md
  common/cert-manager/cert-manager/base/cert-manager.yaml
Labels: lgtm, approved, size/XL

#2704 Upgrade bentoml to 1.2.28 and 1.1.21
  contrib/bentoml/Makefile
  contrib/bentoml/bentoml-yatai-stack/bases/yatai-deployment/resources.yaml
  contrib/bentoml/bentoml-yatai-stack/bases/yatai-image-builder/resources.yaml
  contrib/bentoml/test.sh
Labels: lgtm, approved, size/XXL

#2707 update readme
  README.md
Labels: lgtm, approved, size/S

#2710 Upgrade dex to 2.39.1
  common/dex/base/deployment.yaml
Labels: lgtm, approved, size/XS

#2709 Upgrade knative to v1.12.4
  .github/workflows/kserve_cni_test.yaml
  README.md
  common/knative/README.md
  common/knative/knative-eventing-post-install-jobs/base/eventing-post-install.yaml
  common/knative/knative-eventing/base/upstream/eventing-core.yaml
  common/knative/knative-eventing/base/upstream/in-memory-channel.yaml
  common/knative/knative-eventing/base/upstream/mt-channel-broker.yaml
  common/knative/knative-serving-post-install-jobs/base/serving-post-install-jobs.yaml
  common/knative/knative-serving/base/upstream/net-istio.yaml
  common/knative/knative-serving/base/upstream/serving-core.yaml
  hack/sync-knative-manifests.sh
Labels: lgtm, approved, size/XXL

#2708 Creating Issue templates
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/issue-report.yml
Labels: lgtm, approved, size/M

#2716 Kubernetes 1.29
  README.md
  tests/gh-actions/kind-cluster.yaml
Labels: lgtm, approved, size/L

#2717 Upgrade guide
  README.md
Labels: lgtm, approved, size/S

#2722 Create PR template
  .github/PULL_REQUEST_TEMPLATE.md
  .github/pull_request_template.md
Labels: lgtm, approved, size/M

#2726 Changed the checkbox style
  .github/PULL_REQUEST_TEMPLATE.md
Labels: lgtm, approved, size/S

#2719 Update seldon manifests from v1.18.1
  contrib/seldon/Makefile
  contrib/seldon/seldon-core-operator/base/resources.yaml
  hack/sync-seldon-manifests.sh
Labels: lgtm, approved, size/L

#2732 update ray to 2.23 and kuberay to 1.1.1
  .github/workflows/ray_test.yaml
  contrib/ray/Makefile
  contrib/ray/README.md
  contrib/ray/kuberay-operator/base/aggregated-roles.yaml
  contrib/ray/kuberay-operator/base/kustomization.yaml
  contrib/ray/kuberay-operator/base/resources.yaml
  contrib/ray/kuberay-operator/overlays/kubeflow/kustomization.yaml
  contrib/ray/kuberay-operator/overlays/standalone/kustomization.yaml
  contrib/ray/kuberay-operator/overlays/standalone/namespace.yaml
  contrib/ray/raycluster_example.yaml
  contrib/ray/test.sh
Labels: lgtm, approved, size/XXL

#2733 Change extract_images.sh to include Model Registry
  hack/extract_images.sh
Labels: lgtm, approved, size/XS
