Repository kubeflow/manifests, pull requests merged in 2024-10, with the labels that each got.

#2826 Add seaweedfs to contrib
  .github/workflows/pipeline_swfs_test.yaml
  contrib/seaweedfs/OWNERS
  contrib/seaweedfs/README.md
  contrib/seaweedfs/UPDGRADE.md
  contrib/seaweedfs/base/kustomization.yaml
  contrib/seaweedfs/base/seadweedfs-networkpolicy.yaml
  contrib/seaweedfs/base/seaweedfs-deployment.yaml
  contrib/seaweedfs/base/seaweedfs-pvc.yaml
  contrib/seaweedfs/base/seaweedfs-service.yaml
  contrib/seaweedfs/istio/istio-authorization-policy.yaml
  contrib/seaweedfs/istio/kustomization.yaml
  contrib/seaweedfs/test.sh
Labels: lgtm, approved, size/L, ok-to-test

#2886 Synchronize kubeflow kubeflow manifests v1.9.1
  README.md
  apps/admission-webhook/upstream/base/kustomization.yaml
  apps/centraldashboard/upstream/base/kustomization.yaml
  apps/jupyter/jupyter-web-app/upstream/base/configs/spawner_ui_config.yaml
  apps/jupyter/jupyter-web-app/upstream/base/kustomization.yaml
  apps/jupyter/notebook-controller/upstream/base/kustomization.yaml
  apps/profiles/upstream/base/kustomization.yaml
  apps/profiles/upstream/overlays/kubeflow/kustomization.yaml
  apps/pvcviewer-controller/upstream/base/kustomization.yaml
  apps/tensorboard/tensorboard-controller/upstream/base/kustomization.yaml
  apps/tensorboard/tensorboards-web-app/upstream/base/kustomization.yaml
  apps/volumes-web-app/upstream/base/kustomization.yaml
  contrib/ray/README.md
  hack/synchronize-istio-cni-manifests.sh
  hack/synchronize-istio-manifests.sh
  hack/synchronize-katib-manifests.sh
  hack/synchronize-knative-manifests.sh
  hack/synchronize-kserve-kserve-manifests.sh
  hack/synchronize-kserve-web-app-manifests.sh
  hack/synchronize-kubeflow-manifests.sh
  hack/synchronize-model-registry-manifests.sh
  hack/synchronize-seldon-manifests.sh
  hack/synchronize-training-operator-manifests.sh
  hack/trivy_scan.py
  tests/gh-actions/kf-objects/notebook.test.kubeflow-user-example.com.yaml
Labels: lgtm, approved, size/M

#2894 fix: expand spark rbac to include scheduledsparkapplication
  contrib/spark/spark-operator/base/aggregated-roles.yaml
Labels: lgtm, approved, size/XS

#2896 Running command in README errors, upstream folder does not exist
  README.md
Labels: lgtm, approved, size/XS

#2884 feat: add doc to describe use oauth2proxy directly.
  README.md
  common/oauth2-proxy/README.md
  common/oauth2-proxy/components/oauth2-flow.svg
Labels: lgtm, approved, size/L, ok-to-test

#2898 Synchronize kubeflow/kubeflow manifests v1.9.2
  README.md
  apps/admission-webhook/upstream/base/kustomization.yaml
  apps/centraldashboard/upstream/base/deployment.yaml
  apps/centraldashboard/upstream/base/kustomization.yaml
  apps/jupyter/jupyter-web-app/upstream/base/configs/spawner_ui_config.yaml
  apps/jupyter/jupyter-web-app/upstream/base/kustomization.yaml
  apps/jupyter/notebook-controller/upstream/base/kustomization.yaml
  apps/profiles/upstream/base/kustomization.yaml
  apps/profiles/upstream/overlays/kubeflow/kustomization.yaml
  apps/pvcviewer-controller/upstream/base/kustomization.yaml
  apps/tensorboard/tensorboard-controller/upstream/base/kustomization.yaml
  apps/tensorboard/tensorboards-web-app/upstream/base/kustomization.yaml
  apps/volumes-web-app/upstream/base/kustomization.yaml
  hack/synchronize-kubeflow-manifests.sh
Labels: lgtm, approved, size/M

#2897 Synchronize kubeflow model registry manifests v0.2.9
  README.md
  apps/model-registry/upstream/base/kustomization.yaml
  hack/synchronize-model-registry-manifests.sh
Labels: lgtm, approved, size/S
