Repository kubeflow/manifests, pull requests merged in 2024-09, with the labels that each got.

#2873 Updating master README.md for Install individual components
  README.md
Labels: lgtm, approved, size/S

#2872 Update kubeflow/pipelines manifests from 2.3.0
  README.md
  apps/pipeline/upstream/README.md
  apps/pipeline/upstream/base/cache-deployer/kustomization.yaml
  apps/pipeline/upstream/base/cache/kustomization.yaml
  apps/pipeline/upstream/base/installs/generic/pipeline-install-config.yaml
  apps/pipeline/upstream/base/installs/multi-user/view-edit-cluster-roles.yaml
  apps/pipeline/upstream/base/metadata/base/kustomization.yaml
  apps/pipeline/upstream/base/pipeline/kustomization.yaml
  apps/pipeline/upstream/base/pipeline/metadata-writer/kustomization.yaml
  apps/pipeline/upstream/base/pipeline/ml-pipeline-ui-deployment.yaml
  apps/pipeline/upstream/env/aws/README.md
  apps/pipeline/upstream/env/gcp/inverse-proxy/kustomization.yaml
  apps/pipeline/upstream/env/platform-agnostic-multi-user-legacy/kustomization.yaml
  apps/pipeline/upstream/env/platform-agnostic-multi-user/kustomization.yaml
  apps/pipeline/upstream/hack/presubmit.sh
  apps/pipeline/upstream/sample/README.md
  apps/pipeline/upstream/sample/kustomization.yaml
  apps/pipeline/upstream/third-party/argo/base/workflow-controller-configmap-patch.yaml
  apps/pipeline/upstream/third-party/argo/base/workflow-controller-deployment-patch.yaml
  apps/pipeline/upstream/third-party/argo/upstream/manifests/Kptfile
  apps/pipeline/upstream/third-party/argo/upstream/manifests/namespace-install/kustomization.yaml
  apps/pipeline/upstream/third-party/argo/upstream/manifests/quick-start/base/kustomization.yaml
  apps/pipeline/upstream/third-party/argo/upstream/manifests/quick-start/minimal/kustomization.yaml
  apps/pipeline/upstream/third-party/argo/upstream/manifests/quick-start/mysql/kustomization.yaml
  apps/pipeline/upstream/third-party/argo/upstream/manifests/quick-start/postgres/kustomization.yaml
  apps/pipeline/upstream/third-party/argo/upstream/manifests/quick-start/sso/kustomization.yaml
  hack/synchronize-pipelines-manifests.sh
Labels: lgtm, approved, size/L

#2878 Synchronize kserve manifests v0.13.1
  contrib/kserve/kserve/kserve-cluster-resources.yaml
  contrib/kserve/kserve/kserve.yaml
  contrib/kserve/kserve/kserve_kubeflow.yaml
  hack/synchronize-kserve-kserve-manifests.sh
Labels: lgtm, approved, size/M

#2879 Synchronize kubeflow training operator manifests v1.8.1
  README.md
  apps/training-operator/upstream/overlays/kubeflow/kustomization.yaml
  apps/training-operator/upstream/overlays/standalone/kustomization.yaml
  hack/synchronize-training-operator-manifests.sh
Labels: lgtm, approved, size/XS

#2880 Synchronize kubeflow model registry manifests v0.2.5 alpha
  README.md
  apps/model-registry/upstream/README.md
  hack/synchronize-model-registry-manifests.sh
Labels: lgtm, approved, size/XS

#2847 Enable istio support for ray
  .github/workflows/ray_test.yaml
  contrib/ray/Makefile
  contrib/ray/README.md
  contrib/ray/kuberay-operator/overlays/standalone/kustomization.yaml
  contrib/ray/kuberay-operator/overlays/standalone/namespace.yaml
  contrib/ray/raycluster_example.yaml
  contrib/ray/test.sh
Labels: lgtm, approved, size/L
