Repository kubeflow/manifests, pull requests merged in 2024-07, with the labels that each got.

#2781 Update kubeflow/kubeflow manifests from v1.9.0-rc.1
  README.md
  apps/admission-webhook/upstream/base/kustomization.yaml
  apps/centraldashboard/upstream/base/kustomization.yaml
  apps/jupyter/jupyter-web-app/upstream/base/configs/spawner_ui_config.yaml
  apps/jupyter/jupyter-web-app/upstream/base/kustomization.yaml
  apps/jupyter/notebook-controller/upstream/base/kustomization.yaml
  apps/profiles/upstream/base/kustomization.yaml
  apps/profiles/upstream/overlays/kubeflow/kustomization.yaml
  apps/pvcviewer-controller/upstream/base/kustomization.yaml
  apps/tensorboard/tensorboard-controller/upstream/base/kustomization.yaml
  apps/tensorboard/tensorboards-web-app/upstream/base/kustomization.yaml
  apps/volumes-web-app/upstream/base/kustomization.yaml
  hack/synchronize-kubeflow-manifests.sh
  tests/gh-actions/kf-objects/notebook.test.kubeflow-user-example.com.yaml
  tests/gh-actions/run_and_wait_kubeflow_pipeline.py
Labels: lgtm, approved, size/L

#2768 Patch further static namespaces with PSS labels
  contrib/security/PSS/static/baseline/kustomization.yaml
  contrib/security/PSS/static/baseline/patches/cert-manager-labels.yaml
  contrib/security/PSS/static/baseline/patches/dex-labels.yaml
  contrib/security/PSS/static/baseline/patches/oauth2-proxy-labels.yaml
  contrib/security/PSS/static/restricted/kustomization.yaml
  contrib/security/PSS/static/restricted/patches/cert-manager-labels.yaml
  contrib/security/PSS/static/restricted/patches/dex-labels.yaml
  contrib/security/PSS/static/restricted/patches/oauth2-proxy-labels.yaml
Labels: lgtm, approved, size/M

#2782 Added Daemonset to istio-cni and fixed the script
  common/istio-cni-1-22/istio-install/base/install.yaml
  hack/synchronize-istio-cni-manifests.sh
Labels: lgtm, approved, size/L

#2786 networkpolicy for training operator
  common/networkpolicies/base/kustomization.yaml
  common/networkpolicies/base/training-operator-webhook.yaml
Labels: lgtm, approved, size/S

#2791 Update kubeflow/kubeflow manifests from 1.9.0-rc.2
  README.md
  apps/admission-webhook/upstream/base/kustomization.yaml
  apps/centraldashboard/upstream/base/kustomization.yaml
  apps/jupyter/jupyter-web-app/upstream/base/kustomization.yaml
  apps/jupyter/notebook-controller/upstream/base/kustomization.yaml
  apps/profiles/upstream/base/kustomization.yaml
  apps/profiles/upstream/overlays/kubeflow/kustomization.yaml
  apps/pvcviewer-controller/upstream/base/kustomization.yaml
  apps/tensorboard/tensorboard-controller/upstream/base/kustomization.yaml
  apps/tensorboard/tensorboards-web-app/upstream/base/kustomization.yaml
  apps/volumes-web-app/upstream/base/kustomization.yaml
  hack/synchronize-kubeflow-manifests.sh
Labels: lgtm, approved, size/M

#2792 Remove --kubeconfig mycluster.yaml and use KUBECONFIG instead of moving files
  README.md
Labels: lgtm, approved, size/XS

#2774 Introduce proper formatting on python ,bash and yaml files
  .github/workflows/bash_formatter.yaml
  .github/workflows/python_formatter.yaml
  .github/workflows/yaml_formatter.yaml
  .shellcheckrc
  .yamllint.yaml
  contrib/kserve/tests/test_sklearn.py
  hack/synchronize-istio-cni-manifests.sh
  hack/synchronize-istio-manifests.sh
  hack/synchronize-kserve-web-app-manifests.sh
  hack/trivy_scan.py
  run_yamllint.sh
  tests/gh-actions/kf-objects/test_pipeline.py
  tests/gh-actions/runasnonroot.sh
Labels: lgtm, approved, size/XL

#2793 Simplify the pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: lgtm, approved, size/S

#2785 Document the CVE scanning process
  README.md
  documents/KustomizeBestPractices.md
Labels: lgtm, approved, size/L

#2799 Documented about how to change default password in README.md
  README.md
Labels: lgtm, approved, size/M

#2801 Update kubeflow/katib manifests from v0.17.0
  apps/katib/upstream/components/controller/trial-templates.yaml
  apps/katib/upstream/installs/katib-cert-manager/katib-config.yaml
  apps/katib/upstream/installs/katib-cert-manager/kustomization.yaml
  apps/katib/upstream/installs/katib-external-db/katib-config.yaml
  apps/katib/upstream/installs/katib-external-db/kustomization.yaml
  apps/katib/upstream/installs/katib-leader-election/katib-config.yaml
  apps/katib/upstream/installs/katib-openshift/katib-config.yaml
  apps/katib/upstream/installs/katib-openshift/kustomization.yaml
  apps/katib/upstream/installs/katib-standalone-postgres/katib-config.yaml
  apps/katib/upstream/installs/katib-standalone-postgres/kustomization.yaml
  apps/katib/upstream/installs/katib-standalone/katib-config.yaml
  apps/katib/upstream/installs/katib-standalone/kustomization.yaml
  apps/katib/upstream/installs/katib-with-kubeflow/kustomization.yaml
Labels: lgtm, approved, size/L

#2802 Update kubeflow/training-operator manifests from v1.8.0
  README.md
  apps/training-operator/upstream/overlays/kubeflow/kustomization.yaml
  apps/training-operator/upstream/overlays/standalone/kustomization.yaml
Labels: lgtm, approved, size/XS

#2806 Synchronize training operator and katib manifests fixes
  README.md
  hack/synchronize-katib-manifests.sh
  hack/synchronize-training-operator-manifests.sh
Labels: lgtm, approved, size/S

#2807 Update kubeflow/kubeflow manifests from v1.9.0
  README.md
  apps/admission-webhook/upstream/base/kustomization.yaml
  apps/centraldashboard/upstream/base/kustomization.yaml
  apps/jupyter/jupyter-web-app/upstream/base/kustomization.yaml
  apps/jupyter/notebook-controller/upstream/base/kustomization.yaml
  apps/profiles/upstream/base/kustomization.yaml
  apps/profiles/upstream/overlays/kubeflow/kustomization.yaml
  apps/pvcviewer-controller/upstream/base/kustomization.yaml
  apps/tensorboard/tensorboard-controller/upstream/base/kustomization.yaml
  apps/tensorboard/tensorboards-web-app/upstream/base/kustomization.yaml
  apps/volumes-web-app/upstream/base/kustomization.yaml
  hack/synchronize-kubeflow-manifests.sh
Labels: lgtm, approved, size/M

#2808 Update kserve models web application manifests from 0.13.0
  README.md
  hack/synchronize-kserve-web-app-manifests.sh
Labels: lgtm, approved, size/XS

#2803 Proper message display when no bash, python and YAML files changed in the PR
  .github/workflows/bash_formatter.yaml
  .github/workflows/linting_bash_python_yaml_files.yaml
  .github/workflows/python_formatter.yaml
  .github/workflows/yaml_formatter.yaml
  README.md
Labels: lgtm, approved, size/L

#2788 Deprecate optional Knative Eventing components
  example/kustomization.yaml
Labels: lgtm, approved, size/XS

#2787 Added PSS profile seccompProfile to pods of istio
  common/istio-1-22/istio-install/base/kustomization.yaml
  common/istio-1-22/istio-install/base/patches/seccomp-istio-ingressgateway.yaml
  common/istio-1-22/istio-install/base/patches/seccomp-istiod.yaml
  common/istio-cni-1-22/istio-install/base/kustomization.yaml
  common/istio-cni-1-22/istio-install/base/patches/seccomp-istio-ingressgateway.yaml
  common/istio-cni-1-22/istio-install/base/patches/seccomp-istiod.yaml
  contrib/security/PSS/static/baseline/kustomization.yaml
Labels: lgtm, approved, size/M

#2778 PSS labels for the profile controller
  contrib/security/PSS/dynamic/baseline/kustomization.yaml
  contrib/security/PSS/dynamic/baseline/namespace-labels.yaml
  contrib/security/PSS/dynamic/restricted/kustomization.yaml
  contrib/security/PSS/dynamic/restricted/namespace-labels.yaml
  contrib/security/PSS/static/restricted/kustomization.yaml
  example/kustomization.yaml
Labels: lgtm, approved, size/M

#2818 Typographical changes
  .github/workflows/kserve_m2m_test.yaml
  .github/workflows/model_registry_test.yaml
  .github/workflows/notebook_controller_m2m_test.yaml
  .github/workflows/pipeline_run_from_notebook.yaml
  .github/workflows/pipeline_test.yaml
Labels: lgtm, approved, size/S

#2779 Training operator CICD improvements
  .github/workflows/linting_bash_python_yaml_files.yaml
  .github/workflows/model_registry_test.yaml
  .github/workflows/train_operator_test.yaml
  .github/workflows/training_operator_test.yaml
  common/networkpolicies/base/training-operator-webhook.yaml
  tests/gh-actions/install_multi_tenancy.sh
  tests/gh-actions/install_training_operator.sh
  tests/gh-actions/kf-objects/notebook.test.kubeflow-user-example.com.yaml
  tests/gh-actions/kf-objects/tfjob.yaml
  tests/gh-actions/kf-objects/training_operator_job.yaml
Labels: lgtm, approved, size/L

#2810 Document how to change the default username for dex
  README.md
Labels: lgtm, approved, size/S

#2821 change ray version and enable auto scaling
  contrib/ray/raycluster_example.yaml
Labels: lgtm, approved, size/S

#2823 fix issue of trying to linting deleted files in PR
  .github/workflows/linting_bash_python_yaml_files.yaml
Labels: lgtm, approved, size/L
