Repository kubeflow/manifests, pull requests merged in 2024-03, with the labels that each got.

#2634 Add steps to install Kubeflow on kind
  README.md
Labels: lgtm, approved, size/M

#2633 Update kserve manifests from v0.11.2 (#2627) and synchronize from the 1.8 branch
  README.md
  contrib/kserve/kserve/kserve-runtimes.yaml
  contrib/kserve/kserve/kserve.yaml
  contrib/kserve/kserve/kserve_kubeflow.yaml
  contrib/kserve/kserve/kustomization.yaml
  tests/gh-actions/install_kserve.sh
Labels: approved, size/XXL

#2637 Update to Kind 1.27 and fix the integration tests
  .github/workflows/pipeline_kind_test.yaml
  tests/gh-actions/kf-objects/katib_test.yaml
  tests/gh-actions/kind-cluster-1-24.yaml
  tests/gh-actions/kind-cluster-1-26.yaml
  tests/gh-actions/kind-cluster.yaml
Labels: approved, size/L

#2636 Backup ~/.kube/config before the replacement
  README.md
Labels: size/XS

#2640 Remove outdated versions of Kubernetes
  .github/workflows/bentoml_kind_test.yaml
  .github/workflows/seldon_kind_test.yaml
  README.md
  tests/gh-actions/kind-cluster-1-26.yaml
Labels: size/M

#2643 update kind to 1.28
  tests/gh-actions/kind-cluster.yaml
Labels: lgtm, approved, size/XS

#2644 chore: remove repetitive words
  README.md
  common/knative/README.md
Labels: lgtm, approved, size/XS

#2654 kustomize 5.2.1
  .github/pull_request_template.md
  README.md
  go.mod
  tests/e2e/README.md
  tests/gh-actions/install_kustomize.sh
Labels: lgtm, approved, size/S
