Repository kubeflow/manifests, pull requests merged in 2024-01, with the labels that each got.

#2588 Fix #2229 - dex-passwords in common/dex/base
  common/dex/base/dex-passwords.yaml
  common/dex/base/kustomization.yaml
Labels: lgtm, approved, size/XS

#2586 Fixes dex for kustomize 5
  common/dex/overlays/istio/kustomization.yaml
Labels: lgtm, approved, size/M

#2590 Improve dex kustomizations readability
  common/dex/base/kustomization.yaml
  common/dex/overlays/istio/kustomization.yaml
Labels: lgtm, approved, size/S

#2329 Update 20220926-contrib-component-guidelines.md
  proposals/20220926-contrib-component-guidelines.md
Labels: lgtm, approved, size/XS

#2595 Fix image name ($VOLUME_VIEWER_IMAGE) produced by hack/extract_images.sh
  hack/extract_images.sh
Labels: lgtm, approved, size/XS

#2578 removed namespace from kubeflow cluster issuer
  common/cert-manager/kubeflow-issuer/base/kustomization.yaml
Labels: lgtm, approved, size/XS

#2596 Decomission dex overlays for github and ldap
  common/dex/overlays/github/config-map.yaml
  common/dex/overlays/github/kustomization.yaml
  common/dex/overlays/github/params.env
  common/dex/overlays/github/params.yaml
  common/dex/overlays/github/virtual-service.yaml
  common/dex/overlays/ldap/config-map.yaml
  common/dex/overlays/ldap/deployment.yaml
  common/dex/overlays/ldap/kustomization.yaml
  common/dex/overlays/ldap/params.env
  common/dex/overlays/ldap/params.yaml
Labels: lgtm, approved, size/L

#2546 Add tests for rootless containers
  tests/README.md
  tests/e2e/README.md
  tests/e2e/mnist.py
  tests/e2e/runasnonroot.sh
  tests/e2e/runner.sh
  tests/e2e/utils/kserve.py
Labels: lgtm, size/L
