Repository kubeflow/manifests, pull requests merged in 2025-05, with the labels that each got.

#3126 Synchronize training operator manifests v1.9.2
  README.md
  apps/training-operator/upstream/base/deployment.yaml
  apps/training-operator/upstream/overlays/kubeflow/kustomization.yaml
  apps/training-operator/upstream/overlays/standalone/kustomization.yaml
  scripts/synchronize-training-operator-manifests.sh
Labels: lgtm, approved, size/S

#3125 fix: make again script runnable on Mac OSX
  scripts/library.sh
Labels: lgtm, approved, size/XS

#3127 Add KFP V1 Pipeline Test to CI Workflow
  .github/workflows/full_kubeflow_integration_test.yaml
  .github/workflows/pipeline_test.yaml
  tests/gh-actions/kserve/requirements.txt
  tests/gh-actions/test_pipeline_v1.py
Labels: lgtm, approved, size/M

#3122 Update kubeflow/model-registry manifests from v0.2.17
  README.md
  apps/model-registry/upstream/base/kustomization.yaml
  apps/model-registry/upstream/base/model-registry-configmap.yaml
  apps/model-registry/upstream/base/model-registry-deployment.yaml
  apps/model-registry/upstream/options/controller/default/kustomization.yaml
  apps/model-registry/upstream/options/controller/default/manager_metrics_patch.yaml
  apps/model-registry/upstream/options/controller/default/metrics_service.yaml
  apps/model-registry/upstream/options/controller/manager/kustomization.yaml
  apps/model-registry/upstream/options/controller/manager/manager.yaml
  apps/model-registry/upstream/options/controller/network-policy/allow-metrics-traffic.yaml
  apps/model-registry/upstream/options/controller/network-policy/kustomization.yaml
  apps/model-registry/upstream/options/controller/overlays/base/kustomization.yaml
  apps/model-registry/upstream/options/controller/overlays/base/params.env
  apps/model-registry/upstream/options/controller/overlays/base/replacements.yaml
  apps/model-registry/upstream/options/controller/prometheus/kustomization.yaml
  apps/model-registry/upstream/options/controller/prometheus/monitor.yaml
  apps/model-registry/upstream/options/controller/rbac/kustomization.yaml
  apps/model-registry/upstream/options/controller/rbac/leader_election_role.yaml
  apps/model-registry/upstream/options/controller/rbac/leader_election_role_binding.yaml
  apps/model-registry/upstream/options/controller/rbac/metrics_auth_role.yaml
  apps/model-registry/upstream/options/controller/rbac/metrics_auth_role_binding.yaml
  apps/model-registry/upstream/options/controller/rbac/metrics_reader_role.yaml
  apps/model-registry/upstream/options/controller/rbac/role.yaml
  apps/model-registry/upstream/options/controller/rbac/role_binding.yaml
  apps/model-registry/upstream/options/controller/rbac/service_account.yaml
  apps/model-registry/upstream/options/csi/clusterstoragecontainer.yaml
  apps/model-registry/upstream/options/csi/kustomization.yaml
  apps/model-registry/upstream/options/ui/base/kustomization.yaml
  apps/model-registry/upstream/options/ui/base/model-registry-ui-deployment.yaml
  apps/model-registry/upstream/overlays/db/patches/model-registry-deployment.yaml
Labels: lgtm, approved, size/XL

#3128 Use istio cni in pipelines gha
  .github/workflows/pipeline_run_from_notebook.yaml
  .github/workflows/pipeline_test.yaml
Labels: lgtm, approved, size/XS

#3131 Enable Spark Operator with UI by default
  README.md
  example/kustomization.yaml
Labels: lgtm, approved, size/S

#3129 Updated the V2 pipeline test to be more robust
  .github/workflows/full_kubeflow_integration_test.yaml
  .github/workflows/pipeline_test.yaml
  tests/gh-actions/test_pipeline.py
  tests/gh-actions/test_pipeline_v2.py
Labels: lgtm, approved, size/L

#3132 Apply pss labels from diectly PSS enable scripts
  common/knative/knative-serving/base/kustomization.yaml
  tests/gh-actions/enable_baseline_PSS.sh
  tests/gh-actions/enable_restricted_PSS.sh
Labels: lgtm, approved, size/M

#3134 istio namespace missing
  common/istio-1-24/istio-install/base/gateway.yaml
  common/istio-cni-1-24/istio-install/base/gateway.yaml
  common/istio-cni-1-24/istio-install/base/kustomization.yaml
Labels: lgtm, approved, size/XS

#3136 The test_pipeline.py has been changed to test_pipeline_v2.py
  .github/workflows/pipeline_swfs_test.yaml
Labels: lgtm, approved, size/S

#3138 Adding OpenSSF Best Practices and build status
  README.md
Labels: lgtm, approved, size/XS

#3137 Update kubeflow/model-registry manifests from v0.2.18
  .github/workflows/full_kubeflow_integration_test.yaml
  .github/workflows/model_registry_test.yaml
  README.md
  apps/model-registry/upstream/README.md
  apps/model-registry/upstream/base/kustomization.yaml
  apps/model-registry/upstream/base/model-registry-deployment.yaml
  apps/model-registry/upstream/options/csi/kustomization.yaml
  apps/model-registry/upstream/options/istio/kustomization.yaml
  apps/model-registry/upstream/options/ui/base/kustomization.yaml
  apps/model-registry/upstream/overlays/db/kustomization.yaml
  apps/model-registry/upstream/overlays/db/patches/model-registry-deployment.yaml
  apps/model-registry/upstream/overlays/postgres/kustomization.yaml
  apps/model-registry/upstream/overlays/postgres/patches/model-registry-deployment.yaml
Labels: lgtm, approved, size/L

#3135 Switch to Istio CNI by default
  .github/workflows/admission_webhook_test.yaml
  .github/workflows/jupyter_web_application_test.yaml
  .github/workflows/model_registry_test.yaml
  .github/workflows/notebook_controller_test.yaml
  .github/workflows/pipeline_swfs_test.yaml
  .github/workflows/profiles_test.yaml
  .github/workflows/ray_test.yaml
  .github/workflows/spark_test.yaml
  .github/workflows/tensorboard_controller_test.yaml
  .github/workflows/tensorboards_web_application_test.yaml
  README.md
  common/istio-cni-1-24/istio-install/overlays/gke/gke-cni-patch.yaml
  common/istio-cni-1-24/istio-install/overlays/gke/kustomization.yaml
  example/kustomization.yaml
Labels: lgtm, approved, size/M

#3130 Remove static PSS files and apply security labels directly in enable PSS scripts
  common/cert-manager/base/kustomization.yaml
  common/cert-manager/base/namespace-patch.yaml
  common/dex/base/namespace.yaml
  common/istio-1-24/istio-namespace/base/namespace.yaml
  common/istio-cni-1-24/istio-namespace/base/namespace.yaml
  common/knative/knative-serving/base/patches/namespace-injection.yaml
  common/kubeflow-namespace/base/namespace.yaml
  common/oauth2-proxy/base/namespace.yaml
  experimental/security/PSS/static/baseline/kustomization.yaml
  experimental/security/PSS/static/baseline/patches/auth-labels.yaml
  experimental/security/PSS/static/baseline/patches/cert-manager-labels.yaml
  experimental/security/PSS/static/baseline/patches/istio-system-labels.yaml
  experimental/security/PSS/static/baseline/patches/knative-serving-labels.yaml
  experimental/security/PSS/static/baseline/patches/kubeflow-labels.yaml
  experimental/security/PSS/static/baseline/patches/oauth2-proxy-labels.yaml
  experimental/security/PSS/static/restricted/kustomization.yaml
  experimental/security/PSS/static/restricted/patches/auth-labels.yaml
  experimental/security/PSS/static/restricted/patches/istio-system-labels.yaml
  experimental/security/PSS/static/restricted/patches/knative-serving-labels.yaml
  experimental/security/PSS/static/restricted/patches/kubeflow-labels.yaml
  experimental/security/PSS/static/restricted/patches/oauth2-proxy-labels.yaml
Labels: lgtm, approved, size/L
