Repository kubeflow/manifests, pull requests merged in 2025-08, with the labels that each got.

#3211 Synchronize kubeflow pipelines manifests 2.14.0
  .github/workflows/full_kubeflow_integration_test.yaml
  .github/workflows/pipeline_swfs_test.yaml
  .github/workflows/pipeline_test.yaml
  README.md
  applications/pipeline/upstream/third-party/argo/base/workflow-controller-deployment-patch.yaml
  applications/pipeline/upstream/third-party/argo/upstream/manifests/base/workflow-controller/workflow-controller-deployment.yaml
  scripts/synchronize-pipelines-manifests.sh
Labels: lgtm, approved, size/M

#3181 Synchronize trainer manifests 2.0
  .github/workflows/full_kubeflow_integration_test.yaml
  .github/workflows/istio_validation.yaml
  .github/workflows/trainer_test.yaml
  README.md
  applications/trainer/overlays/kustomization.yaml
  applications/trainer/upstream/base/crds/kustomization.yaml
  applications/trainer/upstream/base/crds/trainer.kubeflow.org_clustertrainingruntimes.yaml
  applications/trainer/upstream/base/crds/trainer.kubeflow.org_trainingruntimes.yaml
  applications/trainer/upstream/base/crds/trainer.kubeflow.org_trainjobs.yaml
  applications/trainer/upstream/base/manager/kustomization.yaml
  applications/trainer/upstream/base/manager/manager.yaml
  applications/trainer/upstream/base/rbac/kustomization.yaml
  applications/trainer/upstream/base/rbac/role.yaml
  applications/trainer/upstream/base/rbac/role_binding.yaml
  applications/trainer/upstream/base/rbac/service_account.yaml
  applications/trainer/upstream/base/runtimes/deepspeed_distributed.yaml
  applications/trainer/upstream/base/runtimes/kustomization.yaml
  applications/trainer/upstream/base/runtimes/mlx_distributed.yaml
  applications/trainer/upstream/base/runtimes/mpi_distributed.yaml
  applications/trainer/upstream/base/runtimes/torch_distributed.yaml
  applications/trainer/upstream/base/runtimes/torchtune/kustomization.yaml
  applications/trainer/upstream/base/runtimes/torchtune/llama3_2/llama3_2_1B.yaml
  applications/trainer/upstream/base/runtimes/torchtune/llama3_2/llama3_2_3B.yaml
  applications/trainer/upstream/base/webhook/kustomization.yaml
  applications/trainer/upstream/base/webhook/kustomizeconfig.yaml
  applications/trainer/upstream/base/webhook/manifests.yaml
  applications/trainer/upstream/base/webhook/patch.yaml
  applications/trainer/upstream/overlays/kubeflow-platform/kubeflow-trainer-roles.yaml
  applications/trainer/upstream/overlays/kubeflow-platform/kustomization.yaml
  applications/trainer/upstream/overlays/kubeflow-platform/patches/remove-namespace.yaml
  applications/trainer/upstream/overlays/kubeflow-platform/role_binding.yaml
  applications/trainer/upstream/overlays/manager/kustomization.yaml
  applications/trainer/upstream/overlays/manager/namespace.yaml
  applications/trainer/upstream/overlays/runtimes/kustomization.yaml
  applications/trainer/upstream/third-party/jobset/kustomization.yaml
  applications/trainer/upstream/third-party/jobset/patches/jobset_remove_namespace.yaml
  common/istio/profile.yaml
  common/kubeflow-namespace/base/namespace.yaml
  common/networkpolicies/base/default-allow-same-namespace-kubeflow-system.yaml
  common/networkpolicies/base/jobset-webhook-kubeflow-system.yaml
  common/networkpolicies/base/kustomization.yaml
  common/networkpolicies/base/trainer-webhook-kubeflow-system.yaml
  example/kustomization.yaml
  scripts/synchronize-trainer-manifests.sh
  tests/PSS_baseline_enable.sh
  tests/PSS_restricted_enable.sh
  tests/istio_dummy_deployment.yaml
  tests/kubeflow_profile_install.sh
  tests/metrics-server_resource_table.py
  tests/trainer_install.sh
  tests/trainer_job.yaml
  tests/trainer_test.sh
Labels: lgtm, approved, size/XXL, ok-to-test

#3218 Update trivy_scan.py
  tests/trivy_install.sh
  tests/trivy_scan.py
Labels: lgtm, approved, size/XS

#3199 TrainJob support to Katib Trial Templates
  applications/katib/upstream/components/controller/rbac.yaml
  experimental/helm/charts/katib/templates/controller/rbac.yaml
Labels: lgtm, approved, size/S, ok-to-test

#3206 Limit Istio Sidecar Scope to reduce memory usage
  .github/workflows/admission_webhook_test.yaml
  .github/workflows/centraldashboard_test.yaml
  .github/workflows/dex_oauth2-proxy_test.yaml
  .github/workflows/jupyter_web_application_test.yaml
  .github/workflows/katib-helm-kustomize-comparison.yaml
  .github/workflows/kserve-models-web-app-comparison.yml
  .github/workflows/kserve_jwt_authentication_test.yaml
  .github/workflows/kserve_secure_test.yaml
  .github/workflows/kserve_test.yaml
  .github/workflows/pipeline_run_from_notebook.yaml
  .github/workflows/pipeline_swfs_test.yaml
  .github/workflows/pipeline_test.yaml
  .github/workflows/profiles_test.yaml
  .github/workflows/ray_test.yaml
  .github/workflows/spark_test.yaml
  .github/workflows/tensorboard_controller_test.yaml
  .github/workflows/tensorboards_web_application_test.yaml
  common/istio/istio-install/base/kustomization.yaml
  common/istio/istio-install/base/sidecar-prune-egress.yaml
  tests/istio-cni_install.sh
Labels: lgtm, approved, size/L

#3221 Update kserve_test.yaml
  .github/workflows/kserve_test.yaml
Labels: lgtm, approved, size/M

#3229 Update cluster-roles.yaml
  common/istio/kubeflow-istio-resources/base/cluster-roles.yaml
Labels: lgtm, approved, size/XS

#3228 Deny All Network Policies for the namespaces knative-serving oauth2-proxy cert-manager istio-system auth
  common/networkpolicies/base/cert-manager-webhook.yaml
  common/networkpolicies/base/default-allow-same-namespace-auth.yaml
  common/networkpolicies/base/default-allow-same-namespace-cert-manager.yaml
  common/networkpolicies/base/default-allow-same-namespace-istio-system.yaml
  common/networkpolicies/base/default-allow-same-namespace-knative-serving.yaml
  common/networkpolicies/base/default-allow-same-namespace-oauth2-proxy.yaml
  common/networkpolicies/base/kustomization.yaml
Labels: lgtm, approved, size/M
