Repository kubeflow/manifests, pull requests merged in 2025-02, with the labels that each got.

#2971 fix: update kind config
  README.md
  tests/gh-actions/install_KinD_create_KinD_cluster_install_kustomize.sh
Labels: lgtm, approved, size/XS

#2972 Refactor: Extract pipeline_test.py into a shared file for reuse across workflows
  .github/workflows/pipeline_swfs_test.yaml
  .github/workflows/pipeline_test.yaml
  .yamllint.yaml
  tests/gh-actions/pipeline_test.py
Labels: lgtm, approved, size/L

#2977 Update oauth2-proxy README.md
  common/oauth2-proxy/README.md
Labels: lgtm, approved, size/M

#2979 Synchronize kubeflow training operator manifests 778cd72
  README.md
  apps/training-operator/upstream/overlays/kubeflow/kubeflow-training-roles.yaml
  hack/synchronize-training-operator-manifests.sh
Labels: lgtm, approved, size/XS

#2976 Fix raycluster Readme
  common/networkpolicies/README.md
  common/oauth2-proxy/README.md
  contrib/ray/README.md
  contrib/ray/kuberay-operator/base/kustomization.yaml
Labels: lgtm, approved, size/M

#2973 Update kubeflow/model-registry manifests from 5d8ed91
  .github/workflows/model_registry_test.yaml
  apps/model-registry/upstream/README.md
  apps/model-registry/upstream/base/kustomization.yaml
  apps/model-registry/upstream/options/csi/kustomization.yaml
  apps/model-registry/upstream/options/ui/base/kustomization.yaml
  apps/model-registry/upstream/options/ui/base/model-registry-ui-deployment.yaml
  apps/model-registry/upstream/options/ui/base/model-registry-ui-role.yaml
  apps/model-registry/upstream/options/ui/base/model-registry-ui-service-account.yaml
  apps/model-registry/upstream/options/ui/base/model-registry-ui-service.yaml
  apps/model-registry/upstream/options/ui/overlays/integrated/kustomization.yaml
  apps/model-registry/upstream/options/ui/overlays/integrated/model-registry-ui-deployment.yaml
  apps/model-registry/upstream/options/ui/overlays/istio/authorization-policy-ui.yaml
  apps/model-registry/upstream/options/ui/overlays/istio/destination-rule-ui.yaml
  apps/model-registry/upstream/options/ui/overlays/istio/kustomization.yaml
  apps/model-registry/upstream/options/ui/overlays/istio/model-registry-ui-service.yaml
  apps/model-registry/upstream/options/ui/overlays/istio/virtual-service.yaml
  apps/model-registry/upstream/options/ui/overlays/standalone/kubeflow-dashboard-rbac.yaml
  apps/model-registry/upstream/options/ui/overlays/standalone/kustomization.yaml
  apps/model-registry/upstream/options/ui/overlays/standalone/model-registry-ui-deployment.yaml
  apps/model-registry/upstream/overlays/db/kustomization.yaml
  apps/model-registry/upstream/overlays/db/model-registry-db-deployment.yaml
  hack/synchronize-model-registry-manifests.sh
Labels: lgtm, approved, size/L

#2987 Improve documentation and CI/CD
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/issue-report.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/linting_bash_python_yaml_files.yaml
  .github/workflows/pss_test.yaml
  .github/workflows/ray_test.yaml
  .github/workflows/spark_test.yaml
  .github/workflows/tensorboard_controller_test.yaml
  .github/workflows/tensorboards_web_application_test.yaml
  .github/workflows/triage_issues.yaml
  .github/workflows/trivy.yaml
  .github/workflows/volumes_web_application_test.yaml
  .yamllint.yaml
  README.md
  run_yamllint.sh
Labels: lgtm, approved, size/L

#2989 Add model registry ui network policy
  common/networkpolicies/base/kustomization.yaml
  common/networkpolicies/base/model-registry-ui.yaml
Labels: lgtm, approved, size/S

#2992 fix warnings after kustomize build in contrib
  contrib/kserve/models-web-app/base/kustomization.yaml
  contrib/kserve/models-web-app/overlays/kubeflow/kustomization.yaml
Labels: lgtm, approved, size/M

#2993 Synchronize kubeflow katib manifests v0.18.0 rc.0
  README.md
  apps/katib/upstream/components/controller/controller.yaml
  apps/katib/upstream/components/controller/rbac.yaml
  apps/katib/upstream/components/controller/trial-templates.yaml
  apps/katib/upstream/components/webhook/webhooks.yaml
  apps/katib/upstream/installs/katib-cert-manager/katib-config.yaml
  apps/katib/upstream/installs/katib-cert-manager/kustomization.yaml
  apps/katib/upstream/installs/katib-external-db/katib-config.yaml
  apps/katib/upstream/installs/katib-external-db/kustomization.yaml
  apps/katib/upstream/installs/katib-leader-election/katib-config.yaml
  apps/katib/upstream/installs/katib-openshift/katib-config.yaml
  apps/katib/upstream/installs/katib-openshift/kustomization.yaml
  apps/katib/upstream/installs/katib-standalone-postgres/katib-config.yaml
  apps/katib/upstream/installs/katib-standalone-postgres/kustomization.yaml
  apps/katib/upstream/installs/katib-standalone/katib-config.yaml
  apps/katib/upstream/installs/katib-standalone/kustomization.yaml
  apps/katib/upstream/installs/katib-with-kubeflow/kustomization.yaml
  hack/synchronize-katib-manifests.sh
Labels: lgtm, approved, size/L

#2995 Synchronize kubeflow kubeflow manifests v1.10.0 rc.0
  README.md
  apps/admission-webhook/upstream/base/kustomization.yaml
  apps/centraldashboard/upstream/base/deployment.yaml
  apps/centraldashboard/upstream/base/kustomization.yaml
  apps/centraldashboard/upstream/base/params.env
  apps/jupyter/jupyter-web-app/upstream/base/configs/spawner_ui_config.yaml
  apps/jupyter/jupyter-web-app/upstream/base/deployment.yaml
  apps/jupyter/jupyter-web-app/upstream/base/kustomization.yaml
  apps/jupyter/jupyter-web-app/upstream/base/params.env
  apps/jupyter/notebook-controller/upstream/base/kustomization.yaml
  apps/jupyter/notebook-controller/upstream/default/manager_auth_proxy_patch.yaml
  apps/profiles/upstream/base/kustomization.yaml
  apps/profiles/upstream/default/manager_auth_proxy_patch.yaml
  apps/profiles/upstream/overlays/kubeflow/kustomization.yaml
  apps/pvcviewer-controller/upstream/base/kustomization.yaml
  apps/pvcviewer-controller/upstream/default/manager_auth_proxy_patch.yaml
  apps/tensorboard/tensorboard-controller/upstream/base/kustomization.yaml
  apps/tensorboard/tensorboard-controller/upstream/default/manager_auth_proxy_patch.yaml
  apps/tensorboard/tensorboards-web-app/upstream/base/deployment.yaml
  apps/tensorboard/tensorboards-web-app/upstream/base/kustomization.yaml
  apps/tensorboard/tensorboards-web-app/upstream/base/params.env
  apps/volumes-web-app/upstream/base/deployment.yaml
  apps/volumes-web-app/upstream/base/kustomization.yaml
  apps/volumes-web-app/upstream/base/params.env
  hack/synchronize-kubeflow-manifests.sh
Labels: lgtm, approved, size/L

#2998 Synchronize kubeflow model registry manifests v0.2.14
  README.md
  apps/model-registry/upstream/README.md
  apps/model-registry/upstream/base/kustomization.yaml
  apps/model-registry/upstream/base/model-registry-deployment.yaml
  apps/model-registry/upstream/options/csi/kustomization.yaml
  apps/model-registry/upstream/options/ui/base/kustomization.yaml
  apps/model-registry/upstream/options/ui/base/model-registry-ui-deployment.yaml
  apps/model-registry/upstream/options/ui/overlays/istio/kustomization.yaml
  apps/model-registry/upstream/overlays/db/model-registry-db-deployment.yaml
  apps/model-registry/upstream/overlays/postgres/kustomization.yaml
  apps/model-registry/upstream/overlays/postgres/model-registry-db-deployment.yaml
  apps/model-registry/upstream/overlays/postgres/patches/model-registry-deployment.yaml
  hack/synchronize-model-registry-manifests.sh
Labels: lgtm, approved, size/L

#3003 Synchronize kserve web app manifests v0.14.0 rc.0
  README.md
  contrib/kserve/models-web-app/base/kustomization.yaml
  hack/synchronize-kserve-web-app-manifests.sh
Labels: lgtm, approved, size/S

#3001 feat: Add pre-commit hooks for automated code quality checks
  .pre-commit-config.yaml
  contrib/spark/test.sh
  tests/gh-actions/install_knative-cni.sh
  tests/gh-actions/install_knative.sh
Labels: lgtm, approved, size/M

#3008 Synchronize kubeflow kubeflow manifests v1.10.0 rc.1
  README.md
  apps/admission-webhook/upstream/base/kustomization.yaml
  apps/centraldashboard/upstream/base/kustomization.yaml
  apps/jupyter/jupyter-web-app/upstream/base/configs/spawner_ui_config.yaml
  apps/jupyter/jupyter-web-app/upstream/base/kustomization.yaml
  apps/jupyter/notebook-controller/upstream/base/kustomization.yaml
  apps/profiles/upstream/base/kustomization.yaml
  apps/profiles/upstream/base/patches/manager.yaml
  apps/profiles/upstream/overlays/kubeflow/kustomization.yaml
  apps/profiles/upstream/overlays/kubeflow/patches/kfam.yaml
  apps/pvcviewer-controller/upstream/base/kustomization.yaml
  apps/tensorboard/tensorboard-controller/upstream/base/kustomization.yaml
  apps/tensorboard/tensorboards-web-app/upstream/base/kustomization.yaml
  apps/volumes-web-app/upstream/base/kustomization.yaml
  contrib/ray/README.md
  hack/synchronize-kubeflow-manifests.sh
  tests/gh-actions/kf-objects/notebook.test.kubeflow-user-example.com.yaml
Labels: lgtm, approved, size/M

#3000 Add Model Registry UI Integration Test
  .github/workflows/model_registry_test.yaml
Labels: lgtm, approved, size/M

#2986 chore: Removing PSS patches
  apps/pipeline/upstream/third-party/metacontroller/base/crd.yaml
  common/oauth2-proxy/components/cluster-jwks-proxy/cluster-jwks-proxy.yaml
  contrib/security/PSS/patches/cache-server.yaml
  contrib/security/PSS/patches/metacontroller.yaml
  contrib/security/PSS/patches/metadata-envoy-deployment.yaml
  contrib/security/PSS/patches/metadata-grpc-deployment.yaml
  contrib/security/PSS/patches/metadata-writer.yaml
  contrib/security/PSS/patches/minio.yaml
  contrib/security/PSS/patches/ml-pipeline-persistenceagent.yaml
  contrib/security/PSS/patches/ml-pipeline-scheduledworkflow.yaml
  contrib/security/PSS/patches/ml-pipeline-ui.yaml
  contrib/security/PSS/patches/ml-pipeline-viewer-crd.yaml
  contrib/security/PSS/patches/ml-pipeline-visualizationserver.yaml
  contrib/security/PSS/patches/ml-pipeline.yaml
  contrib/security/PSS/patches/mysql.yaml
  contrib/security/PSS/patches/workflow-controller.yaml
Labels: lgtm, approved, size/L

#3009 Add a section for pre-commit in README.md
  README.md
Labels: lgtm, approved, size/M

#2988 Upgrading metacontroller to v4.11.22
  apps/pipeline/upstream/base/installs/multi-user/pipelines-profile-controller/decorator-controller.yaml
  apps/pipeline/upstream/base/installs/multi-user/pipelines-profile-controller/kustomization.yaml
  apps/pipeline/upstream/base/installs/multi-user/pipelines-profile-controller/sync.py
  apps/pipeline/upstream/third-party/metacontroller/base/cluster-role.yaml
  apps/pipeline/upstream/third-party/metacontroller/base/crd.yaml
  apps/pipeline/upstream/third-party/metacontroller/base/stateful-set.yaml
Labels: lgtm, approved, size/L

#3012 docs: Add guide for Dex and Keycloak
  README.md
  common/dex/README.md
Labels: lgtm, approved, size/L

#3021 Update common/knative manifests to v1.16.2/v1.16.4.
  README.md
  common/knative/README.md
  common/knative/knative-eventing-post-install-jobs/base/eventing-post-install.yaml
  common/knative/knative-eventing/base/upstream/eventing-core.yaml
  common/knative/knative-eventing/base/upstream/in-memory-channel.yaml
  common/knative/knative-eventing/base/upstream/mt-channel-broker.yaml
  common/knative/knative-serving-post-install-jobs/base/serving-post-install-jobs.yaml
  common/knative/knative-serving/base/upstream/serving-core.yaml
  hack/synchronize-knative-manifests.sh
Labels: lgtm, approved, size/L

#3019 Pipelines MySQL volume permissions fix
  apps/pipeline/upstream/third-party/mysql/base/mysql-deployment.yaml
Labels: lgtm, approved, size/S

#2994 docs: Add information about KEP process
  proposals/README.md
Labels: lgtm, approved, size/S
