Repository kubeflow/manifests, pull requests merged in 2025-07, with the labels that each got.

#3182 Simplified the metrics
  .github/workflows/full_kubeflow_integration_test.yaml
  README.md
  scripts/generate_resource_table.py
  tests/metrics-server_resource_table.py
Labels: lgtm, approved, size/XL

#3187 security and contributors.md
  CONTRIBUTING.md
  README.md
  SECURITY.md
Labels: lgtm, approved, size/M

#3188 Live PVC storage
  README.md
  tests/metrics-server_resource_table.py
Labels: lgtm, approved, size/M

#3050 Fix PSS restricted warnings for kubeflow components
  .github/workflows/full_kubeflow_integration_test.yaml
  applications/admission-webhook/upstream/base/deployment.yaml
  applications/centraldashboard/upstream/base/deployment.yaml
  applications/jupyter/jupyter-web-app/upstream/base/deployment.yaml
  applications/jupyter/notebook-controller/upstream/manager/manager.yaml
  applications/katib/upstream/components/controller/controller.yaml
  applications/katib/upstream/components/db-manager/db-manager.yaml
  applications/katib/upstream/components/mysql/mysql.yaml
  applications/katib/upstream/components/ui/ui.yaml
  applications/kserve/kserve/kserve_kubeflow.yaml
  applications/pipeline/upstream/third-party/argo/upstream/manifests/base/workflow-controller/workflow-controller-deployment.yaml
  applications/profiles/upstream/overlays/kubeflow/patches/kfam.yaml
  applications/tensorboard/tensorboard-controller/upstream/default/manager_auth_proxy_patch.yaml
  applications/tensorboard/tensorboard-controller/upstream/manager/manager.yaml
  applications/tensorboard/tensorboards-web-app/upstream/base/deployment.yaml
  applications/training-operator/upstream/base/deployment.yaml
  applications/volumes-web-app/upstream/base/deployment.yaml
  common/istio/cluster-local-gateway/base/kustomization.yaml
  common/istio/cluster-local-gateway/base/patches/seccomp-cluster-local-gateway.yaml
  tests/PSS_restricted_enable.sh
  tests/runasnonroot.sh
Labels: lgtm, approved, size/L

#3168 Helm Charts Katib
  .github/workflows/katib-helm-kustomize-comparison.yaml
  experimental/helm/charts/katib/.helmignore
  experimental/helm/charts/katib/Chart.yaml
  experimental/helm/charts/katib/README.md
  experimental/helm/charts/katib/ci/values-cert-manager.yaml
  experimental/helm/charts/katib/ci/values-enterprise.yaml
  experimental/helm/charts/katib/ci/values-external-db.yaml
  experimental/helm/charts/katib/ci/values-kubeflow.yaml
  experimental/helm/charts/katib/ci/values-leader-election.yaml
  experimental/helm/charts/katib/ci/values-openshift.yaml
  experimental/helm/charts/katib/ci/values-postgres.yaml
  experimental/helm/charts/katib/ci/values-production.yaml
  experimental/helm/charts/katib/ci/values-standalone.yaml
  experimental/helm/charts/katib/crds/experiment.yaml
  experimental/helm/charts/katib/crds/suggestion.yaml
  experimental/helm/charts/katib/crds/trial.yaml
  experimental/helm/charts/katib/templates/_helpers.tpl
  experimental/helm/charts/katib/templates/autoscaling/hpa.yaml
  experimental/helm/charts/katib/templates/config/configmap.yaml
  experimental/helm/charts/katib/templates/controller/deployment.yaml
  experimental/helm/charts/katib/templates/controller/leader-election-rbac.yaml
  experimental/helm/charts/katib/templates/controller/rbac.yaml
  experimental/helm/charts/katib/templates/controller/service.yaml
  experimental/helm/charts/katib/templates/controller/serviceaccount.yaml
  experimental/helm/charts/katib/templates/controller/trial-templates-configmap.yaml
  experimental/helm/charts/katib/templates/database/mysql-deployment.yaml
  experimental/helm/charts/katib/templates/database/mysql-pvc.yaml
  experimental/helm/charts/katib/templates/database/mysql-service.yaml
  experimental/helm/charts/katib/templates/database/postgres-deployment.yaml
  experimental/helm/charts/katib/templates/database/postgres-pvc.yaml
  experimental/helm/charts/katib/templates/database/postgres-service.yaml
  experimental/helm/charts/katib/templates/database/secret.yaml
  experimental/helm/charts/katib/templates/db-manager/deployment.yaml
  experimental/helm/charts/katib/templates/db-manager/service.yaml
  experimental/helm/charts/katib/templates/istio/authorization-policy.yaml
  experimental/helm/charts/katib/templates/istio/virtual-service.yaml
  experimental/helm/charts/katib/templates/monitoring/servicemonitor.yaml
  experimental/helm/charts/katib/templates/namespace/namespace.yaml
  experimental/helm/charts/katib/templates/rbac/kubeflow-roles.yaml
  experimental/helm/charts/katib/templates/security/network-policy.yaml
  experimental/helm/charts/katib/templates/security/pod-disruption-budget.yaml
  experimental/helm/charts/katib/templates/ui/deployment.yaml
  experimental/helm/charts/katib/templates/ui/rbac.yaml
  experimental/helm/charts/katib/templates/ui/service.yaml
  experimental/helm/charts/katib/templates/ui/serviceaccount.yaml
  experimental/helm/charts/katib/templates/webhook/certificate.yaml
  experimental/helm/charts/katib/templates/webhook/mutating-webhook.yaml
  experimental/helm/charts/katib/templates/webhook/validating-webhook.yaml
  experimental/helm/charts/katib/values.yaml
  tests/compare_all_scenarios.sh
  tests/compare_helm_kustomize.sh
  tests/compare_manifests.py
Labels: lgtm, approved, size/XXL

#3189 Switch to large oracle runners
  .github/workflows/full_kubeflow_integration_test.yaml
  tests/training_operator_test.sh
Labels: lgtm, approved, size/XS

#3194 Update oauth2 proxy manifests v7.10.0
  README.md
  common/oauth2-proxy/base/deployment.yaml
  common/oauth2-proxy/base/kustomization.yaml
  scripts/synchronize-oauth2-proxy-manifests.sh
Labels: lgtm, approved, size/M

#3180 kserve enforce authentication
  .github/workflows/full_kubeflow_integration_test.yaml
  .github/workflows/kserve_jwt_authentication_test.yaml
  .github/workflows/kserve_secure_test.yaml
  .github/workflows/kserve_test.yaml
  .gitignore
  common/istio/cluster-local-gateway/overlays/m2m-auth/README.md
  common/istio/cluster-local-gateway/overlays/m2m-auth/cluster-local-gateway-authorizationpolicy-deny.yaml
  common/istio/cluster-local-gateway/overlays/m2m-auth/cluster-local-gateway-authorizationpolicy-patch.yaml
  common/istio/cluster-local-gateway/overlays/m2m-auth/cluster-local-gateway-requestauthentication.yaml
  common/istio/cluster-local-gateway/overlays/m2m-auth/kustomization.yaml
  tests/knative_authentication_test.sh
  tests/knative_install.sh
  tests/kserve/kserve-external-access.yaml
  tests/kserve_complete_authentication_test.sh
  tests/kserve_jwt_authentication_test.sh
  tests/kserve_setup_external_access.sh
  tests/kserve_test.sh
Labels: lgtm, approved, size/XL

#3202 Update test.sh
  .github/workflows/model_registry_test.yaml
  experimental/ray/test.sh
Labels: lgtm, approved, size/S
