Repository kubeflow/manifests, pull requests merged in 2025-04, with the labels that each got.

#3079 fix: Fixes issue where service account tokens fail with: "Jwt issuer is not configured" error.
  common/oauth2-proxy/overlays/m2m-dex-and-kind/kustomization.yaml
Labels: lgtm, approved, size/S

#3084 Fix: Added example.com in knative serving patch, to solve 404 error
  apps/kserve/tests/test_sklearn.py
  common/knative/knative-serving/overlays/gateways/kustomization.yaml
  common/knative/knative-serving/overlays/gateways/patches/config-domain.yaml
Labels: lgtm, approved, size/S

#3092 Updated the gha workflows to use new install_katib, made changes as s…
  .github/workflows/full_kubeflow_integration_test.yaml
  .github/workflows/katib_test.yaml
  tests/gh-actions/install_central_dashboard.sh
  tests/gh-actions/install_katib.sh
  tests/gh-actions/install_knative-cni.sh
Labels: lgtm, approved, size/M

#3087 Update kubeflow/model-registry manifests from v0.2.16
  README.md
  apps/model-registry/upstream/README.md
  apps/model-registry/upstream/base/kustomization.yaml
  apps/model-registry/upstream/options/csi/kustomization.yaml
  apps/model-registry/upstream/options/ui/base/kustomization.yaml
  apps/model-registry/upstream/options/ui/base/model-registry-ui-deployment.yaml
Labels: lgtm, approved, size/L

#3086 Removed KServe DNS patches from GitHub Actions tests
  .github/workflows/kserve_m2m_test.yaml
  apps/kserve/tests/utils.py
  tests/gh-actions/install_knative-cni.sh
  tests/gh-actions/install_knative.sh
Labels: lgtm, approved, size/S

#3082 Fix: flaky Dex login test by improving authentication flow handling
  .github/workflows/dex_oauth2-proxy_test.yaml
  tests/gh-actions/test_dex_login.py
Labels: lgtm, approved, size/L

#3096 fix: disable GHA in forked repo
  .github/workflows/full_kubeflow_integration_test.yaml
  .github/workflows/manifests_example_test.yaml
  .github/workflows/stale.yaml
  .github/workflows/trivy.yaml
Labels: lgtm, approved, size/XS

#3097 Synchronize kserve web appplication manifests v0.14.0
  README.md
  apps/kserve/models-web-app/base/deployment.yaml
  apps/kserve/models-web-app/base/kustomization.yaml
  scripts/synchronize-kserve-web-application-manifests.sh
Labels: lgtm, approved, size/M

#3093 improve the tests with real KF profile namespaces
  .github/workflows/full_kubeflow_integration_test.yaml
  .github/workflows/katib_test.yaml
  .github/workflows/training_operator_test.yaml
  .github/workflows/volumes_web_application_test.yaml
  tests/gh-actions/install_training_operator.sh
  tests/gh-actions/install_volumes_web_application.sh
  tests/gh-actions/kf-objects/katib_test.yaml
  tests/gh-actions/kf-objects/kserve_test.yaml
  tests/gh-actions/port_forward_gateway.sh
  tests/gh-actions/test_training_operator.sh
  tests/gh-actions/test_volumes_web_application.sh
Labels: lgtm, approved, size/L

#3099 Improving gha's to make them consistent
  .github/workflows/admission_webhook_test.yaml
  .github/workflows/centraldashboard_test.yaml
  .github/workflows/dex_oauth2-proxy_test.yaml
  .github/workflows/full_kubeflow_integration_test.yaml
  .github/workflows/jupyter_web_application_test.yaml
  .github/workflows/katib_test.yaml
  .github/workflows/kserve_test.yaml
  .github/workflows/model_registry_test.yaml
  .github/workflows/notebook_controller_m2m_test.yaml
  .github/workflows/notebook_controller_test.yaml
  .github/workflows/pipeline_run_from_notebook.yaml
  .github/workflows/pipeline_swfs_test.yaml
  .github/workflows/pipeline_test.yaml
  .github/workflows/profiles_test.yaml
  .github/workflows/ray_test.yaml
  .github/workflows/spark_test.yaml
  .github/workflows/tensorboard_controller_test.yaml
  .github/workflows/tensorboards_web_application_test.yaml
  .github/workflows/training_operator_test.yaml
  .github/workflows/volumes_web_application_test.yaml
Labels: lgtm, approved, size/L, ok-to-test

#3103 Fixed the cert manager readiness for kserve
  tests/gh-actions/install_kserve.sh
Labels: lgtm, approved, size/XS

#3101 Synchronize kserve manifests v0.15.0 and update tests
  .github/workflows/full_kubeflow_integration_test.yaml
  .github/workflows/kserve_test.yaml
  .github/workflows/model_registry_test.yaml
  .github/workflows/pipeline_swfs_test.yaml
  .github/workflows/pipeline_test.yaml
  README.md
  apps/kserve/kserve/kserve-cluster-resources.yaml
  apps/kserve/kserve/kserve.yaml
  apps/kserve/kserve/kserve_kubeflow.yaml
  scripts/synchronize-kserve-kserve-manifests.sh
  tests/gh-actions/install_istio.sh
  tests/gh-actions/install_knative-cni.sh
  tests/gh-actions/install_knative.sh
  tests/gh-actions/install_kserve.sh
  tests/gh-actions/kf-objects/notebook.test.kubeflow-user-example.com.yaml
Labels: lgtm, approved, size/XXL

#3108 Fix PSS warning for cluster-local-gateway
  common/istio-1-24/cluster-local-gateway/base/cluster-local-gateway.yaml
  common/istio-cni-1-24/cluster-local-gateway/base/cluster-local-gateway.yaml
Labels: lgtm, approved, size/XS

#3106 Enforce failure on PSS baseline test violations
  apps/kserve/kserve/kustomization.yaml
  tests/gh-actions/enable_baseline_PSS.sh
  tests/gh-actions/enable_restricted_PSS.sh
  tests/gh-actions/install_kserve.sh
Labels: lgtm, approved, size/M

#3116 ci: remove `triage_issues` action
  .github/workflows/triage_issues.yaml
Labels: lgtm, approved, size/S

#3051 Integrate profiles with seaweedfs
  .github/workflows/pipeline_swfs_test.yaml
  experimental/seaweedfs/base/kustomization.yaml
  experimental/seaweedfs/base/minio-service-patch.yaml
  experimental/seaweedfs/base/pipeline-profile-controller/deployment.yaml
  experimental/seaweedfs/base/pipeline-profile-controller/sync.py
  experimental/seaweedfs/base/seaweedfs/kustomization.yaml
  experimental/seaweedfs/base/seaweedfs/seaweedfs-create-admin-user-job.yaml
  experimental/seaweedfs/base/seaweedfs/seaweedfs-deployment.yaml
  experimental/seaweedfs/base/seaweedfs/seaweedfs-networkpolicy.yaml
  experimental/seaweedfs/base/seaweedfs/seaweedfs-pvc.yaml
  experimental/seaweedfs/base/seaweedfs/seaweedfs-service-account.yaml
  experimental/seaweedfs/base/seaweedfs/seaweedfs-service.yaml
  experimental/seaweedfs/istio/istio-authorization-policy.yaml
  tests/gh-actions/install_pipelines_swfs.sh
Labels: lgtm, approved, size/XL

#3118 Fix knative-serving PSS warnings
  apps/kserve/kserve/kustomization.yaml
  common/knative/knative-serving/base/kustomization.yaml
  common/knative/knative-serving/base/patches/seccomp.yaml
Labels: lgtm, approved, size/M

#3115 Making the synchronize scripts consistent
  scripts/lib.sh
  scripts/synchronize-istio-cni-manifests.sh
  scripts/synchronize-istio-manifests.sh
  scripts/synchronize-katib-manifests.sh
  scripts/synchronize-knative-manifests.sh
  scripts/synchronize-kserve-kserve-manifests.sh
  scripts/synchronize-kserve-web-application-manifests.sh
  scripts/synchronize-kubeflow-manifests.sh
  scripts/synchronize-model-registry-manifests.sh
  scripts/synchronize-pipelines-manifests.sh
  scripts/synchronize-spark-operator-manifests.sh
  scripts/synchronize-training-operator-manifests.sh
  scripts/template.sh
Labels: lgtm, approved, size/XXL

#3123 Update README.md
  common/oauth2-proxy/README.md
Labels: lgtm, approved, size/XS

#3120 refactor: move KServe tests from apps to tests/gh-actions
  .github/workflows/full_kubeflow_integration_test.yaml
  .github/workflows/kserve_test.yaml
  tests/gh-actions/install_katib.sh
  tests/gh-actions/kserve/data/iris_input.json
  tests/gh-actions/kserve/requirements.txt
  tests/gh-actions/kserve/test_sklearn.py
  tests/gh-actions/kserve/utils.py
  tests/gh-actions/test_kserve.sh
Labels: lgtm, approved, size/L
