Repository kubeflow/manifests, pull requests merged in 2025-06, with the labels that each got.

#3149 Correct Dex's issuer in README config example
  README.md
Labels: lgtm, approved, size/XS

#3155 test: Kserve test fail reason
  tests/kserve_test.sh
Labels: lgtm, approved, size/XS

#3147 Modernize logger interface
  tests/kserve/utils.py
Labels: lgtm, approved, size/XS

#3157 Move dynamic PSS baseline patch to `apps/profiles/`
  apps/profiles/pss/kustomization.yaml
  apps/profiles/pss/namespace-labels.yaml
  example/kustomization.yaml
  tests/multi_tenancy_install.sh
Labels: lgtm, approved, size/S

#3159 Update trivy_scan.py
  tests/trivy_install.sh
  tests/trivy_scan.py
Labels: lgtm, approved, size/XS

#3148 KServe Path-Based Routing Implementation
  tests/kserve_test.sh
Labels: lgtm, approved, size/L

#3160 Add swfs test to full_kubeflow_integration_test.yaml
  .github/workflows/full_kubeflow_integration_test.yaml
Labels: lgtm, approved, size/S

#3170 fix pipeline application command
  README.md
Labels: lgtm, approved, size/XS

#3091 feat: check resource usage in `full_kubeflow_integration_test` and add section of resource utilization of each component in README
  .github/workflows/full_kubeflow_integration_test.yaml
  README.md
  scripts/generate_resource_table.py
  tests/metrics-server_install.sh
Labels: lgtm, approved, size/XL
