Repository kubeflow/manifests, pull requests merged in 2025-03, with the labels that each got.

#3029 Update kubeflow/pipelines manifests from 2.4.1
  README.md
  apps/pipeline/upstream/base/cache-deployer/kustomization.yaml
  apps/pipeline/upstream/base/cache/kustomization.yaml
  apps/pipeline/upstream/base/installs/generic/pipeline-install-config.yaml
  apps/pipeline/upstream/base/installs/multi-user/pipelines-profile-controller/decorator-controller.yaml
  apps/pipeline/upstream/base/metadata/base/kustomization.yaml
  apps/pipeline/upstream/base/pipeline/kustomization.yaml
  apps/pipeline/upstream/base/pipeline/metadata-writer/kustomization.yaml
  apps/pipeline/upstream/env/gcp/inverse-proxy/kustomization.yaml
  apps/pipeline/upstream/third-party/metacontroller/base/kustomization.yaml
  hack/synchronize-pipelines-manifests.sh
Labels: lgtm, approved, size/M

#3026 Test PSS baseline/restricted for Notebooks, Katib and Kserve
  .github/workflows/katib_test.yaml
  .github/workflows/kserve_test.yaml
  .github/workflows/notebook_controller_test.yaml
  experimental/security/PSS/patches/cluster-jwks-proxy.yaml
  experimental/security/PSS/patches/kfam.yaml
  experimental/security/PSS/patches/manager.yaml
  experimental/security/PSS/static/baseline/kustomization.yaml
  experimental/security/PSS/static/baseline/patches/auth-labels.yaml
  experimental/security/PSS/static/restricted/kustomization.yaml
  experimental/security/PSS/static/restricted/patches/auth-labels.yaml
Labels: lgtm, approved, size/L

#3030 Update README.md
  README.md
Labels: lgtm, approved, size/S

#3032 Update README.md
  README.md
Labels: lgtm, approved, size/S

#3034 Update README.md
  README.md
Labels: lgtm, approved, size/L

#3014 Dummy PR for integration tests
  apps/pipeline/upstream/base/installs/multi-user/pipelines-profile-controller/deployment.yaml
Labels: lgtm, approved, size/S

#3022 Migrate Istio images from DockerHub to GCR
  .yamllint.yaml
  README.md
  common/istio-1-24/README.md
  common/istio-1-24/cluster-local-gateway/base/cluster-local-gateway.yaml
  common/istio-1-24/istio-crds/base/crd.yaml
  common/istio-1-24/istio-install/base/install.yaml
  common/istio-1-24/istio-install/base/istio-ingressgateway-deployment.yaml
  common/istio-1-24/istio-install/base/kustomization.yaml
  common/istio-1-24/profile.yaml
  common/istio-cni-1-24/README.md
  common/istio-cni-1-24/cluster-local-gateway/base/cluster-local-gateway.yaml
  common/istio-cni-1-24/istio-crds/base/crd.yaml
  common/istio-cni-1-24/istio-install/base/install.yaml
  common/istio-cni-1-24/istio-install/base/istio-ingressgateway-deployment.yaml
  common/istio-cni-1-24/istio-install/base/kustomization.yaml
  common/istio-cni-1-24/profile.yaml
  hack/synchronize-istio-cni-manifests.sh
  hack/synchronize-istio-manifests.sh
Labels: lgtm, approved, size/XXL

#3039 istio: generate istio-ingressgateway
  .github/workflows/pipeline_test.yaml
  common/istio-1-24/cluster-local-gateway/base/cluster-local-gateway.yaml
  common/istio-1-24/istio-install/base/install.yaml
  common/istio-1-24/istio-install/base/istio-ingressgateway-deployment.yaml
  common/istio-1-24/istio-install/base/istio-ingressgateway-service.yaml
  common/istio-1-24/istio-install/base/kustomization.yaml
  common/istio-1-24/profile-overlay.yaml
  common/istio-1-24/profile.yaml
  common/istio-cni-1-24/cluster-local-gateway/base/cluster-local-gateway.yaml
  common/istio-cni-1-24/istio-install/base/install.yaml
  common/istio-cni-1-24/istio-install/base/istio-ingressgateway-deployment.yaml
  common/istio-cni-1-24/istio-install/base/istio-ingressgateway-service.yaml
  common/istio-cni-1-24/istio-install/base/kustomization.yaml
  common/istio-cni-1-24/profile-overlay.yaml
  common/istio-cni-1-24/profile.yaml
Labels: lgtm, approved, size/XXL

#3042 PSS baseline / restricted also for Notebooks, Katib, Kserve and istio-ingressgateway
  .github/workflows/dex_oauth2-proxy_test.yaml
  .github/workflows/dex_test.yaml
  .github/workflows/kserve_test.yaml
  .github/workflows/pipeline_run_from_notebook.yaml
  .github/workflows/pipeline_test.yaml
  common/istio-1-24/istio-install/base/install.yaml
  common/istio-1-24/profile.yaml
  common/istio-cni-1-24/istio-install/base/install.yaml
  common/istio-cni-1-24/profile.yaml
  experimental/security/PSS/static/baseline/kustomization.yaml
  experimental/security/PSS/static/baseline/patches/auth-labels.yaml
  experimental/security/PSS/static/restricted/kustomization.yaml
  experimental/security/PSS/static/restricted/patches/auth-labels.yaml
Labels: lgtm, approved, size/L

#3043 Cleanup istio
  .github/workflows/admission_webhook_test.yaml
  .github/workflows/centraldashboard_test.yaml
  .github/workflows/jupyter_web_application_test.yaml
  .github/workflows/katib_test.yaml
  .github/workflows/kserve_cni_test.yaml
  .github/workflows/kserve_m2m_test.yaml
  .github/workflows/kserve_test.yaml
  .github/workflows/ray_test.yaml
  .github/workflows/spark_test.yaml
  .github/workflows/training_operator_test.yaml
  common/istio-1-24/kubeflow-istio-resources/base/cluster-roles.yaml
  common/istio-cni-1-24/kubeflow-istio-resources/base/cluster-roles.yaml
  common/istio/OWNERS
  common/istio/add-anonymous-user-filter/base/envoy-filter.yaml
  common/istio/add-anonymous-user-filter/base/kustomization.yaml
Labels: lgtm, approved, size/M

#3045 fix(pipeline): minio filesystem permission access error
  apps/pipeline/upstream/third-party/minio/base/minio-deployment.yaml
Labels: lgtm, approved, size/XS, ok-to-test

#3046 restructuring
  .github/workflows/trivy.yaml
  .gitignore
  scripts/synchronize-istio-cni-manifests.sh
  scripts/synchronize-istio-manifests.sh
  scripts/synchronize-katib-manifests.sh
  scripts/synchronize-knative-manifests.sh
  scripts/synchronize-kserve-kserve-manifests.sh
  scripts/synchronize-kserve-web-app-manifests.sh
  scripts/synchronize-kubeflow-manifests.sh
  scripts/synchronize-model-registry-manifests.sh
  scripts/synchronize-pipelines-manifests.sh
  scripts/synchronize-training-operator-manifests.sh
  scripts/trivy_scan.py
  tests/gh-actions/install_kustomize.sh
  tests/gh-actions/install_trivy.sh
  tests/gh-actions/trivy_scan.py
Labels: lgtm, approved, size/L

#3049 istio proxy version 1.24.3
  common/istio-1-24/istio-install/base/install.yaml
  common/istio-cni-1-24/istio-install/base/install.yaml
Labels: lgtm, approved, size/XS

#3053 Update kubeflow/model-registry manifests from v0.2.15
  README.md
  apps/model-registry/upstream/base/kustomization.yaml
  apps/model-registry/upstream/options/csi/kustomization.yaml
  apps/model-registry/upstream/options/ui/base/kustomization.yaml
  apps/model-registry/upstream/options/ui/base/model-registry-ui-deployment.yaml
Labels: lgtm, approved, size/S

#3048 Add synchronization script for Spark Operator manifests
  .github/workflows/spark_test.yaml
  apps/spark/Makefile
  apps/spark/README.md
  apps/spark/UPGRADE.md
  apps/spark/test.sh
  scripts/synchronize-spark-operator-manifests.sh
  tests/gh-actions/spark_install.sh
  tests/gh-actions/spark_test.sh
Labels: lgtm, approved, size/L, ok-to-test

#3058 Synchronize kubeflow kubeflow manifests v1.10.0 rc.2
  README.md
  apps/admission-webhook/upstream/base/deployment.yaml
  apps/admission-webhook/upstream/base/kustomization.yaml
  apps/centraldashboard/upstream/base/deployment.yaml
  apps/centraldashboard/upstream/base/kustomization.yaml
  apps/jupyter/jupyter-web-app/upstream/base/configs/spawner_ui_config.yaml
  apps/jupyter/jupyter-web-app/upstream/base/deployment.yaml
  apps/jupyter/jupyter-web-app/upstream/base/kustomization.yaml
  apps/jupyter/notebook-controller/upstream/base/kustomization.yaml
  apps/jupyter/notebook-controller/upstream/manager/manager.yaml
  apps/jupyter/notebook-controller/upstream/samples/_v1_notebook.yaml
  apps/jupyter/notebook-controller/upstream/samples/_v1alpha1_notebook.yaml
  apps/jupyter/notebook-controller/upstream/samples/_v1beta1_notebook.yaml
  apps/profiles/upstream/base/kustomization.yaml
  apps/profiles/upstream/manager/manager.yaml
  apps/profiles/upstream/overlays/kubeflow/kustomization.yaml
  apps/profiles/upstream/overlays/kubeflow/patches/kfam.yaml
  apps/pvcviewer-controller/upstream/base/kustomization.yaml
  apps/pvcviewer-controller/upstream/manager/manager.yaml
  apps/tensorboard/tensorboard-controller/upstream/base/kustomization.yaml
  apps/tensorboard/tensorboard-controller/upstream/manager/manager.yaml
  apps/tensorboard/tensorboards-web-app/upstream/base/deployment.yaml
  apps/tensorboard/tensorboards-web-app/upstream/base/kustomization.yaml
  apps/volumes-web-app/upstream/base/deployment.yaml
  apps/volumes-web-app/upstream/base/kustomization.yaml
  scripts/synchronize-istio-cni-manifests.sh
  scripts/synchronize-istio-manifests.sh
  scripts/synchronize-katib-manifests.sh
  scripts/synchronize-knative-manifests.sh
  scripts/synchronize-kserve-kserve-manifests.sh
  scripts/synchronize-kserve-web-app-manifests.sh
  scripts/synchronize-kubeflow-manifests.sh
  scripts/synchronize-model-registry-manifests.sh
  scripts/synchronize-pipelines-manifests.sh
  scripts/synchronize-spark-operator-manifests.sh
  scripts/synchronize-training-operator-manifests.sh
  tests/gh-actions/kf-objects/notebook.test.kubeflow-user-example.com.yaml
Labels: lgtm, approved, size/XXL

#3059 Update Kind and test Kubernetes 1.29-1.32
  README.md
  tests/gh-actions/install_KinD_create_KinD_cluster_install_kustomize.sh
Labels: lgtm, approved, size/S

#3060 Update README.md with air gap hints
  README.md
Labels: lgtm, approved, size/S

#3064 Update trivy_scan.py
  .gitattributes
  tests/gh-actions/trivy_scan.py
Labels: lgtm, approved, size/M

#3066 Update kubeflow/model-registry manifests from v0.2.15.3
  README.md
  apps/model-registry/upstream/base/kustomization.yaml
  apps/model-registry/upstream/base/model-registry-deployment.yaml
  apps/model-registry/upstream/options/csi/clusterstoragecontainer.yaml
  apps/model-registry/upstream/options/csi/kustomization.yaml
  apps/model-registry/upstream/options/ui/base/kustomization.yaml
  apps/model-registry/upstream/overlays/db/model-registry-db-deployment.yaml
  apps/model-registry/upstream/overlays/postgres/model-registry-db-deployment.yaml
Labels: lgtm, approved, size/S

#3063 Formatted code block to the experimental/ray README
  experimental/ray/README.md
Labels: lgtm, approved, size/M

#3067 test: fix name, debug hooks
  .github/workflows/model_registry_test.yaml
Labels: lgtm, approved, size/S

#3068 Synchronize kubeflow training operator manifests v1.9.1
  README.md
  apps/training-operator/upstream/overlays/kubeflow/kustomization.yaml
  apps/training-operator/upstream/overlays/standalone/kustomization.yaml
  scripts/synchronize-training-operator-manifests.sh
Labels: lgtm, approved, size/S

#3069 Synchronize kubeflow katib manifests v0.18.0
  README.md
  apps/katib/upstream/components/controller/controller.yaml
  apps/katib/upstream/components/controller/trial-templates.yaml
  apps/katib/upstream/components/db-manager/db-manager.yaml
  apps/katib/upstream/components/ui/ui.yaml
  apps/katib/upstream/installs/katib-cert-manager/katib-config.yaml
  apps/katib/upstream/installs/katib-cert-manager/kustomization.yaml
  apps/katib/upstream/installs/katib-external-db/katib-config.yaml
  apps/katib/upstream/installs/katib-external-db/kustomization.yaml
  apps/katib/upstream/installs/katib-leader-election/katib-config.yaml
  apps/katib/upstream/installs/katib-openshift/katib-config.yaml
  apps/katib/upstream/installs/katib-openshift/kustomization.yaml
  apps/katib/upstream/installs/katib-standalone-postgres/katib-config.yaml
  apps/katib/upstream/installs/katib-standalone-postgres/kustomization.yaml
  apps/katib/upstream/installs/katib-standalone/katib-config.yaml
  apps/katib/upstream/installs/katib-standalone/kustomization.yaml
  apps/katib/upstream/installs/katib-with-kubeflow/kustomization.yaml
  scripts/synchronize-katib-manifests.sh
Labels: lgtm, approved, size/L

#3056 Document secure Kserve authentication via automated tests
  .github/workflows/centraldashboard_test.yaml
  .github/workflows/dex_oauth2-proxy_test.yaml
  .github/workflows/kserve_m2m_test.yaml
  apps/kserve/tests/requirements.txt
  apps/kserve/tests/utils.py
  common/istio-1-24/cluster-local-gateway/base/gateway-authorizationpolicy.yaml
  common/istio-cni-1-24/cluster-local-gateway/base/gateway-authorizationpolicy.yaml
  tests/gh-actions/deploy-dex-login-environment/kustomization.yaml
Labels: lgtm, approved, size/L

#3071 Synchronize kubeflow kubeflow manifests v1.10.0
  README.md
  apps/admission-webhook/upstream/base/kustomization.yaml
  apps/centraldashboard/upstream/base/kustomization.yaml
  apps/jupyter/jupyter-web-app/upstream/base/configs/spawner_ui_config.yaml
  apps/jupyter/jupyter-web-app/upstream/base/kustomization.yaml
  apps/jupyter/notebook-controller/upstream/base/kustomization.yaml
  apps/profiles/upstream/base/kustomization.yaml
  apps/profiles/upstream/overlays/kubeflow/kustomization.yaml
  apps/pvcviewer-controller/upstream/base/kustomization.yaml
  apps/tensorboard/tensorboard-controller/upstream/base/kustomization.yaml
  apps/tensorboard/tensorboards-web-app/upstream/base/kustomization.yaml
  apps/volumes-web-app/upstream/base/kustomization.yaml
  scripts/synchronize-kubeflow-manifests.sh
Labels: lgtm, approved, size/M

#3072 Fix: Revert OAuth2 authentication policy for cluster-local-gateway
  common/istio-1-24/cluster-local-gateway/base/gateway-authorizationpolicy.yaml
  common/istio-cni-1-24/cluster-local-gateway/base/gateway-authorizationpolicy.yaml
Labels: lgtm, approved, size/S

#3074 Update README.md for the 1.10 release
  README.md
Labels: lgtm, approved, size/XS

#3076 Fix: kubectl wait condition case from ready to Ready
  .github/workflows/dex_oauth2-proxy_test.yaml
  README.md
  experimental/ray/test.sh
  tests/gh-actions/install_cert_manager.sh
  tests/gh-actions/install_oauth2-proxy.sh
Labels: lgtm, approved, size/S

#3070 Add comprehensive Kubeflow integration test GitHub Actions workflow
  .github/workflows/full_kubeflow_integration_test.yaml
Labels: lgtm, approved, size/L, ok-to-test
